---
author: "Joshua Born"
#bibliography: "../bibliographies/abortion-underreporting-on-the-national-survey-of-family-growth.bib"
#csl: "../bibliographies/chicago-author-date.csl"
date: 2024-03-17
draft: true
include-before: |
  ## Table of Contents
output:
  blogdown::html_page:
    number_sections: false
    toc: true
summary: "Put summary sentence here."
tags: ["book, article, or podcast review", "first-person"]
title: "Book Review: The Identity Trap"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  cache = FALSE
)
```


## Introduction

If you have been working in corporate America over the past ten or fifteen years, you have more than likely noticed a distinct change in work culture. It was once polite to keep politics out of the workplace, a kind of unwritten rule in order to avoid vitriolic conflict and keep the peace long enough to do what all of us who are not independently wealthy must do, i.e., make a living.

Now the new work culture is one in which we get email blasts from our C-level corporate overlords pontificating their social commentary in real-time on the news cycle. As part of our paid vocations, we are often required to attend classes in an identity politics ideology of the Ibram X. Kendi and Robin DiAngelo variety under the label of "diversity, equity, and inclusion."

If you have noticed this, you may have wondered, "How did this all happen? And how so suddenly?"

_The Identity Trap: A Story of Ideas and Power in Our Time,_  written by Yascha Mounk -- a Johns Hopkins University professor of international affairs best known for his critique of populism in _The People vs. Democracy_ -- is one of the better answers I have discovered to these questions.

_The Identity Trap_ tries to do three different things:

1. to give a history of ideas that would later form the basis for the modern "identity synthesis," as the author calls it,
2. to give a story as to how the identity synthesis went from obscure academic circles to taking over our work culture, and
3. to argue against the identity synthesis in favor of a philosophical liberalism that values free speech, desegregation, and nondiscrimination.


## A History of Ideas

The foundational ideas that the _The Identity Trap_ covers include

* the postmodernist rejection of the grand narrative and fascination with the power structures of "discourses" attributed to Michel Foucault,
* the criticism of "Orientalist" discourse attributed to Edward Said, 
* the tactic of "strategic essentialism" attributed to Gayatri Chakravorty Spivak,
* the invention of critical race theory by Derrick Bell,
* and the popularization of concepts of "intersectionality" attributed to Bell's disciple Kimberlé Crenshaw.

These are just the ideas covered in Part I of _The Identity Trap_ entitled "The Origins of the Identity Synthesis." In addition, covered in later chapters are the standpoint epistemology of feminist philosophers Donna Haraway and Sandra Harding and the concept of "cultural appropriation" popularized by thinkers such as Stuart Hall and Robert S. Nelson.

I have written about [essentialism](/essentialism.html) and [Kwame Anthony Appiah's critique of "cultural appropriation" as a concept](/kwame-anthony-appiahs-criticism-of-cultural-appropriation-criticism.html) previously, so I was already familiar with a few of these concepts. However, two things struck me about the history of ideas sketched out in _The Identity Trap._ The first is just how much critical race theory is the rejection of the program of the civil rights movement. The second is that while many of these ideas now manifest themselves as fallacies passed around social media to the detriment of society, some began as plausible if not good ideas in the minds' of their original thinkers.


### Derrick Bell and the Origins of Critical Race Theory

I remember one day, after critical race theory became salient in the news cycle, while spending time in an airport waiting for my flight to depart I decided to do a web search of "critical race theory" to see what the fuss was about. The only thing I remember is that I could not actually make out _what it actually was._ Instead I found a word salad of jargon claiming to explain critical race theory. (This game of making a theory inexplicable seems to be a feature of certain kinds of academics, such as anti-positivist sociologists and legal theorists, and critical race theory is a legal theory derived from the anti-positivist Frankfurt school of sociology.)

Yascha Mounk did a better job of explaining critical race theory in a few pages in his book _The Identity Trap_ than all the word salad articles I read on my ill-fated enterprise in the airport. He does so by way of a biographical sketch of its founder Derrick Bell.

The biographical sketch begins with a brief encounter that a young Derrick Bell had with the great civil rights lawyer William H. Hastie, in which Bell expressed a desire to continue Hastie's work and Hastie gave Bell a polite brush off, asserting that the work of civil rights movement was mostly finished. The sketch continues with Bell's young life, law school, time in the Air Force, and arrival to his aspirational job of being a lawyer for the National Association for the Advancement of Colored People (NAACP). 

Bell once wanted to follow in Hastie's footsteps, but it was during his time as an NAACP lawyer that Bell appears to have turned against the civil rights movement. He grew frustrated with what he perceived to be an absolute and ideological commitment to desegregation, even in cases when desegregation was not benefiting Black schoolchildren.

Frustrated, Bell left active litigation and became an academic, learned the anti-positivist "critical theory" jargon popular in academia, and converted his frustration with the civil rights movement into a radical disapproval of the civil rights movement. He concluded that the civil rights movement had been a sham only allowed because it benefited White Americans to allow it, that the civil rights movement had done nothing to advance the status of Black Americans, and that racism was a permanent and unchanging part of American society. Thus, the aims of the civil rights movement, such as desegregation and colorblindness, were in the older Bell's views actually tools of racist oppression.


### When Good (or At Least Plausible) Ideas Go Bad

The evolution of Derrick Bell's thinking is an example of a phenomenon I encountered a few times in my reading of _The Identity Trap._ I find most of the ideas of modern day identity politics (or "identity synthesis" to use Mounk's phrase) to be either counterproductive or themselves outright wrong, as does Yascha Mounk, but it is a testament to Mounk's veracity and scruples as a scholar that I found myself to be sympathetic to these ideas when reading his telling of the their origins.

The history of ideas in _The Identity Trap_ is not a screed of misrepresentation, hyperbole, and defamation unleashed against one's political opponents, as too often is the case with other works, but a sincere attempt to understand where ideas prominent in society today once came from and to grapple with what motivated those who first conceived of them. 

There were specific historical cases in which desegregating schools was, at least in the short-term, worse for Black children than simply improving the schools they were already going to. One can imagine having to travel each and every day, back and forth, long distances to an historically White school, encountering some White teachers who do not actually you there, and having to deal with the bigotry that comes from those encounters. Thus, one can see why the alternative of improving your local historically Black school might be a better option for you, even if that means continuing the "separate but equal" mantra of the Jim Crow era. It is, of course, a large leap to go from these specific cases to the rejection of desegregation _as a matter of principle_ or to the conclusion that the _entire_ civil rights movement is fraudulent -- and fraudulent _forever._


#### Standpoint Epistemology Corrupted

A more striking example of ideas going bad occurs with the transition from standpoint epistemology[^epistemology] to what Yascha Mounk calls "standpoint theory." Aficionados of identity politics will sometimes make the assertion that men cannot possibly understand what women experience, that White Americans cannot understand what Black Americans experience, that straight people cannot understand what queer people experience, etc. etc. This is typically cited as a kind of "standpoint epistemology." However, this is not at all what the idea of standpoint epistemology actually proposed.

[^epistemology]: Epistemology is a theory of knowledge, i.e., what constitutes knowledge and how one can determine what one actually knows.

Standpoint epistemology is a theory from feminist philosophy that does _not_ make the claim that men cannot possibly understand what women experience. Rather, it first separates out two kinds of knowledge: propositional knowledge versus experiential knowledge. Propositional knowledge consists the sort that you can read in a book. Experiential knowledge, on the other hand, is knowledge you gather from your direct experiences. Neither kind of knowledge is entirely better than the other. They both have advantages and disadvantages. What is important for standpoint epistemology is that they are _different_ paths to knowledge.

Standpoint epistemology then notes that in an entirely patriarchal society in which only men participate in public life, and the domestic sphere is the exclusive domain of women, there is a knowledge gap between those who possess experiential knowledge of activities such as child-rearing, who are entirely women, and those who make public policy that affects child-rearing, who are entirely men. Standpoint epistemology admits that men in this scenario can gain _propositional_ knowledge of child-rearing, but that they will miss all the subtleties and details that come from _experiential_ knowledge of raising children.

This is actually a very good point, and it likely explains, at least in part, why human societies have often been so cruel by way of indifference paid to the plight of children. It is similar to the tragedy of war in which generals are briefed with report after report of the battlefield, but are nonetheless out of touch with what is actually going on among the common soldiers who have their boots on the ground.

Note that standpoint epistemology makes no claim that there are identity groups across which people cannot possibly understand each other. If anything, it makes the opposite claim, namely, that any given person only has the experiential knowledge that has come from that person's actual experiences. Thus, a single father and a single mother, under standpoint epistemology, both have experiential knowledge of raising a child as a single parent and likely have much that they can understand about each others' experiences because they have had a lot of experiences in common. A woman who has never raised a child does not magically get the same experiential knowledge of the single mother just because she is in the same identity group. Experiences do not map one-to-one on to identity categories.

Furthermore, even if experiences did map one-to-one on to identity categories, standpoint epistemology never denied that human beings are capable of propositional knowledge. Even if we will never be a Black schoolchild in the United States during desegregation, we can read the words of those who did experience desegregation, use our powers of language, abstraction, and cognitive empathy, and understand why some Black Americans came to the conclusion that they were better off without desegregation. This is not by virtue of my membership in an identity group, but by virtue of my possession of a functioning human brain that is not that of a sociopath.


## How Did We Get Here?

While the history of ideas that led to the modern day identity synthesis is perhaps the strongest part of _The Identity Trap,_ there have been many ideas passed around the ivory tower of academia that simply remain there, not permeating into the popular culture. Therefore, the next task that Yascha Mounk sets out to accomplish in _The Identity Trap_ is to give an accounting of how this loosely associated set of ideas that would become the identity synthesis went from academic obscurity to corporate policy.

Yascha Mounk gives a plausible story, some of which involves the usual suspects. No doubt those who have grown up with social media such as Tumblr and TikTok have experienced new ways of exchanging ideas which in turn have likely affected what ideas (or misrepresentation of ideas) they have encountered during their formative years. _The Identity Trap_ devotes all of its fifth chapter to this phenomenon.

_The Identity Trap_ goes on to observe that this younger generation that grew up with social media have gone on to university and to professional life, making demands on school administrators and employers in ways that previous generations did not, successfully using the power of social media campaigns to get their way. Yascha Mounk calls this the "short march through the institutions" and devotes the sixth chapter of his book to it.

These aspects of Yascha Mounk's story of the ascendancy of the identity synthesis are a bit obvious and likely uncontroversial. The next two parts of his accounting are more provocative.

The first is that large swaths of Americans made their core defining political identity their opposition to Donald Trump's campaign for President of the United States in 2015. When Donald Trump did win the Presidency, many of these individuals became apoplectic and took on a _raison d'etre_ to "get Trump," to borrow the title of a book by Alan Dershowitz. However, while it is beyond the actual ability of the vast majority of Americans to "get Trump," as it were, it _is_ within the ability of many Americans to "get Bill, who works in the cubicle down the hallway from me."

Thus, Yascha Mounk proposes that one aspect of the popularity of the identity synthesis is its ability to be used to attack those around us, and because the "get Trump" crowd in the wake of the 2016 election has redirected its attacks from Donald Trump to more obtainable and nearby targets, there is a demand for such attacking ability.

_The Identity Trap_ goes on to note that this weaponization of the identity synthesis in its current form is one of its defining characteristics by quoting liberally from Ibram X. Kendi's book _How to Be an Antiracist._ "Antiracism" as defined therein takes a decidedly "you are either with us or against us" attitude. Firstly, Ibram X. Kendi takes "racist" not in the meaning that us common folk know and recognize in definitions such as "pertaining to prejudice based on racial categorization, which is in turn based on skin color, etc."

Instead, _How to Be an Antiracist_ defines "racist" as anything (and anyone) who is not "antiracist," asserting explicitly that the predicate "not racist" should no longer be valid. "Antiracist" in turn is defined (mostly) as having an overriding preoccupation with eliminating disparities in average outcomes between racial categories. Most people do not go about their lives preoccupied with eliminating disparities in average outcomes between racial categories. Thus, taken literally, _How to Be an Antiracist_ defines the vast majority of people in the world as "racist."

This is a powerful form of defamation because "racist" rightfully comes with it a lot of social stigma, given the history of the United States and, indeed, the world. Many people are understandably averse to the prospect of being branded "racist." Thus, those who are predisposed to attack others -- whether because of Trump derangement syndrome or some other reason -- would find a lot of utility in the modern day identity synthesis as told by Ibram X. Kendi and others.


## Outline

* Chapter 1: Michel Foucault, rejection of the grand narrative, obsession with "discourses"
* Chapter 2: Edward Said, criticism of "Orientalism"; Gayatri Chakravotry Spivak, strategic essentialism
* Chapter 3: Derek Bell, rejection of civil rights movement and invention of critical race theory, Kimberlee Crenshaw, intersectionality
* Chapter 5: Internet and social media, Tumblr/TikTok generation
* Chapter 6: short march
* Chapter 7: Trump derangement syndrome redirected to person next cubicle over, Ibram X. Kendi's everybody is either racist or antiracist
* Chapter 8: Standpoint epistemology mutated into standpoint theory
* Chapter 9: cultural appropriation
* Chapter 10: free speech
* Chapter 11: desegregation vs. "progressive separatism" 
* Chapter 12: race-neutral vs. disparatism
* Chapter 13: meritocracy vs. "structural" -isms
* Chapter 14 and 15: arguments for (philosophical, not leftist) liberal democracy
* Chapter 16: recommendations (including for corporate CEOs)



## Citations

::: {#refs}
:::

## Footnote
