---
author: "Joshua Born"
#bibliography: "../bibliographies/identity-trap.bibtex"
#csl: "../bibliographies/chicago-author-date.csl"
date: 2024-09-04
draft: true 
include-before: |
  ## Table of Contents
output:
  blogdown::html_page:
    number_sections: false
    toc: true
summary: "These weights can be used for analysis of unintended pregnancies in the United States, such as of contraceptive efficacy and failure."
tags: ["analysis", "reproductive responsibility", "induced abortion", "NSFG", "third-person"]
title: "National Survey of Family Growth Weights Adjusted for Abortion Under-Reporting"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  cache = FALSE
)
```


## Abortion Under-Reporting on the National Survey of Family Growth

The [National Survey of Family Growth (NSFG)](https://www.cdc.gov/nchs/nsfg/index.htm) is the premiere fertility survey of the United States. It began in 1973, and since its inception has been designed and administered by the National Center for Health Statistics, which is now an agency within the U.S. Department of Health and Human Services' Centers for Disease Control and Prevention.

However, there is a known issue with the NSFG data that affects any analyses involving counts of pregnancies generally and counts of unintended pregnancies especially. Less than half of pregnancies ending in induced abortion have been reported by respondents to the NSFG.

The Appendix 2 "Topic-Specific Notes" to the User's Guide of the 2017-2019 NSFG states:

> Abortions have always been under-reported in the NSFG and virtually all other demographic surveys. This has been determined by comparing NSFG weighted estimates of abortions with external data from abortion providers....
>
> For the 2017-2019 NSFG, comparing pregnancies ending in abortion reported in 2012-2016 with the number of abortions in the Guttmacher Abortion Provider Census shows that approximately 38% of pregnancies ending in abortion were reported in the NSFG....
>
> Therefore, as in previous surveys, the NSFG staff advises NSFG data users that, generally speaking, NSFG data on abortion should not be used for substantive research focused on the determinants or consequences of abortion. The NSFG abortion data can be used for:
>
> 1. methodological studies of factors affecting abortion reporting.
> 2. studies of contraceptive efficacy, but only after the data are adjusted for the under-reporting of abortion.

This issue has been known for some time,[^attempt] and it appears to be due to some number of respondents simply not reporting their pregnancies that ended in induced abortion. The Public Use Data Tape Documentation for Cycle 3 (1982) of the NSFG states:

> As in the past in surveys of this kind, abortions were underreported by NSFG respondents. The number of induced abortions in the 5 years before the survey represents about 47 percent of the number reported during 1977-1981 by the Alan Guttmacher Institute...
>
> With due allowance for samping variability, estimates of numbers of live births and of miscarriages and stillbirths correspond fairly well to information from other data sources. It appears that, rather than misreporting pregnancy outcomes, the majority of the underreporting is the result of women not reporting at all the pregnancies that ended in abortions.

[^attempt]: An attempt has been made to address this issue by introducing a self-administered portion of the survey, but this did not ameliorate the issue. The User's Guide for Cycle 5 (1995) of the NSFG states:

    > In an effort to diminish the extent of under-reporting, abortion data in the 1995 NSFG were obtained through interviewer-administered questions (CAPI) as well as self-administered questions (Audio-CASI).... This ... yielded an estimate of 3,294,000 abortions for 1991-94, the most recent period for which comparable data are available...
    >
    > This figure represents about 54 percent of the number reported for that period by the Alan Guttmacher Institute (AGI)... The number of abortions reported in the 5 years prior to the 1988 NSFG was only 41 percent of the number reported by AGI. Thus the reporting of abortions appears to be more complete in Cycle 5 than in Cycle 4 of the NSFG. This increase in reporting may be attributable to the use of incentives and Audio-CASI in 1995, but despite these methodological innovations, there still remains a large degree of under-reporting of abortion.
    

As a result of this, any analyses involving counts of pregnancies -- especially unintended pregnancies -- based on unadjusted NSFG data would be flawed. For instance, analysis of contraceptive efficacy based on unadjusted NSFG data would underestimate contraceptive failure due to the under-counting of pregnancies resulting from contraceptive failure that ended in induced abortion.

Such analyses have been done in the past, and they have attempted to compensate for the abortion under-reporting in the NSFG data by using back-of-the-envelope arithmetic adjustments. While such approaches are plausible, they have the disadvantage of limiting what statistical methodologies can be used in the analysis to just those that are amenable to such adjustments.


## Weights to Compensate for Abortion Under-Reporting

Herein are provided survey weights for NSFG public use data files that have been adjusted to compensate for abortion under-reporting. Incorporating the adjustments for abortion under-reporting into the survey weights has the advantage that once these adjusted weights are used, all of the full range of statistical methodologies available in the analysis of surveys can be used, and they can be used without any back-of-the-envelope arithmetic adjustments.

For instance, using these adjusted weights, regression analysis can be done with unintended pregnancy as one of the model variables simply by using the `svyglm` function of the `survey` package in the R statistical programming language or by using the `SURVEYREG` or `SURVEYLOGISTIC` procedures of the SAS statistical programming language.

The weight adjustments were made using a modified form of _post-stratification,_ which is a technique in which survey weights are adjusted such that estimates match totals retrieved from an external source. The weights included with the public-use data files of the NSFG have already been post-stratified in order to make the estimates of population counts based on the NSFG data match external population counts from the U.S. Census Bureau and others.

The adjusted survey weights were produced by performing additional post-stratifications using the technique of _raking,_ in which multiple post-stratifications can be done simultaneously.


### Post-Stratification Dimensions

The post-stratifications performed on the weights for each survey given this treatment were:

1. a repeat of the post-stratification already done in preparing the public-use data files, which were based on number of women in the United States of reproductive age in demographic categories such as age, race and/or ethnicity, sex, marital status, and parity,[^parity]
2. for a given analysis period preceding the survey, the number of live births in each year by respondent's age at end of pregnancy, and
3. for the same analysis period preceding the survey, the number of induced abortions in the entirety of the analysis period by respondent's age at end of pregnancy.

[^parity]: "Parity" in this context refers to the number of live births that a given respondent has had.


### Post-Stratification Targets

The targets for post-stratifications based on population counts of demographic categories were replicated from the NSFG data sets themselves, based on documentation of each NSFG survey's weighting procedures.

Targets for post-stratification of live births by age per year were taken from the [National Vital Statistics Service](https://www.cdc.gov/nchs/nvss/index.htm)'s natality data. For 1995 and after, these came by way of the [CDC WONDER](https://wonder.cdc.gov/natality.html) system. For years before 1995, these came from data files prepared by the [National Bureau of Economic Research](https://www.nber.org/research/data/vital-statistics-natality-birth-data).[^rationale-for-births]:

[^rationale-for-births]: The NSFG [already estimates live births well](/abortion-underreporting-on-the-national-survey-of-family-growth-in-two-plots.html#two-plots-live-births-versus-induced-abortions). The inclusion of post-stratifications to live births has several advantages.
  1. It maintains and improves the accuracy of the estimates of live births per year.
  2. It reduces the variance of estimates of pregnancies per year.
  Both these compensate for any loss of accuracy or increase in estimator variance due to weight inflation to adjust for abortion under-reporting.

Targets for post-stratification of induced abortions by age per analysis period were taken from a [data set created by Guttmacher Institute personnel](https://osf.io/kthnf/) based on total counts from the Guttmacher Institute's Abortion Provider Census with age distributions inferred from Abortion Surveillance Reports of the Centers for Disease Control and Prevention. Post-stratifications to number of induced abortions were done for the entirety of each survey's analysis period rather than by year like live births due to insufficient numbers of respondents reporting abortions to divide up respondents by year.


### Analysis Periods

Adjusted survey weights are provided for Cycle 3 (1982) of the NSFG through the 2015-2019 NSFG. No attempt was made to produce adjusted weights for Cycle 1 or Cycle 2 of the NSFG, as these cycles only interviewed women who had ever been married, and so are not useful for estimating the counts of all pregnancies in the United States. The 2011-2019 versions of the NSFG public-use data files, which were released in two-year chunks, were combined into two four-year data sets in order to make the sample sizes similar to earlier surveys.[^why-not-combine]

[^why-not-combine]: Additionally, the 2015-2019 NSFG expanded its target population to women from ages 15 to 49 from women ages 15 to 44, so combining the 2015-2019 with data from 2011-2015 would result in losing the over-44 respondents from the 2011-2015 data.

The analysis periods for each survey were hand-selected in order to give the most accurate estimates that would give complete coverage for all years from 1974 to 2014, and this is summarized in the table below.

| Analysis Period(s)   | Survey         |
|----------------------|----------------|
| 1974-1979            | Cycle 3 (1982) |
| 1980-1985            | Cycle 4 (1985) |
| 1986-1990, 1991-1994 | Cycle 5 (1995) |
| 1995-2001            | Cycle 6 (2002) |
| 2002-2005            | 2006-2010      |
| 2006-2010            | 2011-2015      |
| 2011-2014            | 2015-2019      |

The analysis period of Cycle 5 of the NSFG is particularly long, and so was divided into two separate analysis periods. 

When using the adjusted weights, estimates of the number of births in each year of a survey's analysis period and estimates of the number of induced abortions in the entirety of each survey's analysis period should match external counts.[^multiple-abortions]

[^multiple-abortions]: There are many respondents to the NSFG who report multiple induced abortions during a survey's analysis period. One of the ways that typical post-stratification was modified specifically for the abortion post-stratification was to handle these multiplicative factors.

In addition to applying adjustments to the weight of each respondent reporting an abortion in a survey's analysis period, weight adjustments were applied to any respondent reporting an abortion _after_ the analysis period, based on the adjustment done for respondents reporting abortions during the analysis period. This was done so that the contraceptive use calendar, which includes many respondent-months that occur after a survey's analysis period, could be used for analysis. This is a departure from how post-stratification is typically done.


### Replicate Weight Schemes

This and other departures from typical post-stratification necessitated the use of replicate weights. Any adjustments made to the main survey weights were also performed upon all replicate weights, which ensures that estimation error can be calculated by statistical software.

The public use data file for Cycle 4 (1985) of the NSFG is distributed with replicate weights. Replicate weights for other surveys were calculated before raking post-stratification was done. What replicate weight scheme was used depended on the structure of strata and clusters in the public use data files, and this summarized in the table below.

| Survey         | Replicate Weight Scheme             |
|----------------|-------------------------------------|
| Cycle 3 (1982) | Balanced Repeated Replication (BRR) |
| Cycle 4 (1985) | Balanced Repeated Replication (BRR) |
| Cycle 5 (1995) | Jackknife                           |
| Cycle 6 (2002) | Balanced Repeated Replication (BRR) |
| 2006-2010      | Jackknife                           |
| 2011-2015      | Jackknife                           |
| 2015-2019      | Jackknife                           |


### Data Files Containing Adjusted Weights

The NSFG web site includes example programs for reading NSFG public use data files in the SAS, SPSS, and Stata programming languages. Because of the diversity of potential environments for their use, the adjusted NSFG weights are distributed below in comma separated values (CSV) files, which should be readable in any programming environment.

* [Cycle 3 (1982)](/weights/NSFG_1982_1983_cycle_3_weights.csv)
* [Cycle 4 (1985)](/weights/NSFG_1985_1987_cycle_4_weights.csv)
* [Cycle 5 (1995)](/weights/NSFG_1995_cycle_5_weights.csv)
* [Cycle 6 (2002)](/weights/NSFG_2002_2003_cycle_6_weights.csv)
* [2006-2010](/weights/NSFG_2006_2010_weights.csv)
* [2011-2015](/weights/NSFG_2011_2015_weights.csv)
* [2015-2019](/weights/NSFG_2015_2019_weights.csv)

Each file contains a column for the `CASEID` of each female respondent in the data set,[^male] a column `FULL_SAMPLE_WGT` that contains the main survey weight for the respondent, and multiple columns beginning with `REP_WGT_` and ending with a number that contain the replicate weights for each respondent.

[^male]: Starting with the Cycle 6 (2002) of the NSFG, male respondents were surveyed. However, male respondents are given a separate survey questionnaire that does not contain a contraceptive use calendar. No attempt was made to derive weights adjusted for abortion under-reporting for male respondents.

These replicate weights can be used with either the female respondent files or the pregnancies files of the NSFG public use data files. Examples are below.
 
 
## Remaining to Do

* Rscales
* Example programs for using the replicate weights in SAS and R
* Citations
    * Of tables
    * To papers\document


## Footnotes
