---
author: "Joshua Born"
bibliography: "../bibliographies/professional-class-cultural-hegemony.bib"
csl: "../bibliographies/chicago-author-date.csl"
date: 2024-07-10
draft: true
implicit-figures: true
include-before: |
  ## Table of Contents
output:
  blogdown::html_page:
    number_sections: false
    toc: true
    toc_depth: 5
summary: "Summary sentence here"
tags: ["editorial", "first-person"]
title: 'Professional Class Cultural Hegemony'
---


## Introduction

The United States of America is a heavily polarized, partisan place. However, as I described in my [review](/myth-of-left-and-right.html) of _The Myth of Left and Right_ by Hyrum and Verlan Lewis [-@lewis_myth_2023], I do not believe the left-right spectrum has any utility as a description of socio-political viewpoints in the United States. Therefore, the left-right spectrum does not explain this partisan polarization.

This raises the question of how to understand the polarization that characterizes American politics. I discovered what I believe to be the best answer to this question a couple of years ago when listening to [episode 40 of season 3 of _Conversations with Coleman_](https://pca.st/1l7zid0r) in which Coleman Hughes interviewed David Sacks.

Coleman Hughes is a columnist, podcaster, and book author who comments on race politics in the United States, and David Sacks is an entrepreneur in the software industry who was the founding CEO of PayPal. However, the explanation of political polarization discussed on the podcast ultimately came from neither David Sacks nor Coleman Hughes, but from the work of Ruy Teixeira, which they discussed.

Ruy Texeira is a political scientist and co-author of _The Emerging Democratic Majority_ in 2002 and of _Where Have All the Democrats Gone?_ in 2023. The former 2002 book predicted that the Democratic Party would soon have a national voting majority. This did not happen, which led to the latter 2023 book and his ongoing political science work.

The phenomenon that explains polarization in the United States is that of _cultural hegemony._ This cultural hegemony emerges out of the university system in the United States, and is predicated on the institutional dominance of the professional class.


## Voter Polarization between the Professional Class and the Working Class

Ruy Texeira uses the label "professional class" for those in the United States who have a four-year degree from a university and uses the label "working class" for those who do not. By this definition, the United States is a majority working class country, with about two-thirds of the United States categorized as working class.

According to the work of Texeira, the biggest polarization in the United States in party preference and in viewpoints on numerous issues occurs between professional class voters and working class voters.

Texeira's explanation for the lack of emergence of a clear national majority voting for Democrats as predicted in his 2002 book is that working class voters are leaving the Democratic Party, despite the Democratic Party being the twentieth century "home" for working class voters.

There are probably many explanations for this phenomenon. For instance, Democrats in the 1990s moved away from New Deal and Great Society economic policies in favor of "neo-liberal" economic policies that favored free trade. A prominent example of this is the public dissatisfaction, especially among working class voters, with the bipartisan support for the North American Free Trade Agreement (NAFTA), which led to third-party candidate Ross Perot becoming a serious contender in 1996 for the election of President of the United States.

However, one the more enduring reasons Democrats have lost much of the working class vote is that the party caters heavily to the interests, cultural values, and biases of the professional class, either neglecting the viewpoints of the working class or expressing outright contempt toward working class voters. This is an ongoing theme of Texeira's blog [_The Liberal Patriot_](https://substack.com/@theliberalpatriot).


## The University as the Origin of the Cultural Hegemony

The cultural hegemony we experience in the United States has its origin in the university system. American universities are very hierarchical and elitist. There is a glut of individuals who hold PhDs, and very few jobs for them in academia. Graduate students and post-doctoral fellows gravitate to the most highly ranked universities out of necessity in order to advance their careers. Most professors even at more lowly ranked universities come from the most highly ranked universities in some way. Thus, there is a scramble among academics to get names like "Harvard" or "Yale" or "UC Berkeley" on their _curricula vitae._

Therefore, whatever culture is prominent at elite universities trickles down throughout the university system as personnel radiate out from elite universities throughout the rest of the university system.

Furthermore, almost all the institutional leadership positions in the United States, whether in Fortune 500 companies or government, are occupied by members of the professional class, i.e., by people who have at least four-year university degrees. Thus, almost all positions of leadership in the United States are occupied by people who have been indoctrinated, for four years if not more, in the cultural biases that come down from a select few on high.

This phenomenon is exacerbated by a positive feedback loop created by the job of journalist becoming a professional class occupation instead of a working class occupation. The information the public receives via mass media is filtered and framed according to the biases of a culture that ultimately comes from a few prestigious people.


## Cultural Hegemony Explains Polarization in the United States

As David Sacks discussed during his _Conversations with Coleman_ interview:

> It's all the college graduates who control the institutions because you do need these credentials and degrees. And I think this is fundamentally what is creating all of the sense of stress and fracture in our society -- is that the professional class runs all the institutions, including the colleges, for their benefit and in accordance with their ideology. And it is not the same ideology as the majority of the country. And that sets up a democracy that is unsustainable somehow. And it sets up this -- I think this fundamentally is the battle line of what's going on in our society. 

The most dramatic polarization we see in the United States is between the professional class and the working class, and this is because the professional class has more exposure to the cultural hegemony, while the working class has less exposure to the cultural hegemony. Furthermore, the working class outnumbers the professional class, but the professional class wields more power than the working class, which in a democracy sows discord.

The working class might poll more "conservative" on a social issue, depending on how the pollsters frame the issue and what (ultimately arbitrary) definition of "conservative" is being used. The professional class might poll more "left-wing" than the working class on an issue, based an fleeting and arbitrary characterizations of the left-right spectrum. But all of these labels miss the point that the schism itself is caused by the phenomenon of professional class cultural hegemony.

If the views of the pseudo-aristocracy that runs the Ivy League and the _New York Times_ were "right-wing" or "conservative," then this schism in American society would still exist, but with a reversing of the labels; there would be a more "right-wing" or "conservative" hegemony compared with a more "left-wing" or "progressive" rest of the country. The source of the polarization itself is the amount of exposure to the cultural hegemony people receive and the amount of power they have in society by virtue of institutional leadership and economic wealth.


## Divisions within the Professional Class

People are motivated to expose themselves to the cultural hegemony because people with four-year university degrees tend to have better economic outcomes than those who do not. As David Sacks discussed:

> And so the fundamental _quid pro quo_ of our civilization is that if you want the economic and social advancement that a college degree brings you, you have to submit to voluntary re-education for four years, maybe longer. And I tend to think that so many of our political divides are essentially downstream of this problem. 

Even though a lot of people are motivated by the socio-economic structures of our society to _expose_ themselves to the cultural hegemony, the degree to which individuals _acquiesce_ to the hegemony varies. Coleman Hughes is an _alumnus_ of Columbia University, and David Sacks is an _alumnus_ of Stanford University, so they both have direct exposure to the cultural hegemony, but they both have rebelled against it in some way. As David Sacks discussed:

> Now, I do think that there are different reactions that people have to this phenomenon. I tend to think there's three types of students or student reactions to this.
> 
> So I tend to think that the first is that you can rebel against it. I tend to think that maybe 1% of the students do this and then -- and those people tend to become either founders, which is why I can stay in business having the views I have, or they tend to become kind of more conservative or independent media personalities.
>
> I think the vast majority are kind of go along to get along. They let this ideology wash over them. They're more interested in professional advancement. And so they're not super ideological, but they're kind of predisposed to accepting the sort of the dominant ideology of the professional class. I'd say that's probably about 80% of the students. 
> 
> And then I think the other 19% are true believers. And then they go on and staff, they tend to do the professional class jobs that don't pay very well.
> 
> So I think the sort of go along to get along types go work at McKinsey and Goldman Sachs, and the true believers go staff the nonprofits and the activist groups and the Democratic Party and the foundations and, and the media -- you know, they go on to, sort of, mainstream media jobs.

Using David Sacks' terminology, there is a minority of _true believers_ in the cultural hegemony, an even smaller minority of overt _rebels_ against the cultural hegemony, and a vast majority of _go-alongs_ who give lukewarm agreement to the cultural hegemony so that they can reap the economic benefits of a university degree.

The rebels have already been lost to the cultural hegemony, but there is still a tension in this phenomenon in which the minority of true believers must keep the many more go-alongs in line.


## Hegemonic Tactics for Policing the Professional Class

Because of this tension within the professional class, it is not enough for the true believers in the cultural hegemony to let things be. The hegemony would not be hegemonic if it simply participated in the marketplace of ideas, appealing to each individual's sense of reason in order to persuade someone to choose the hegemony's preferred viewpoint as one of many possible viewpoints. Instead, the cultural hegemony uses tactics to stifle discourse and shut down the marketplace of ideas.


### Deplatforming 

Probably one the most profound methods of the cultural hegemony is the deplatforming of alternative viewpoints. If the people dominated by the cultural hegemony are simply not exposed to viewpoints other than those of the cultural hegemony, then they are much less likely to deviate from that orthodoxy.

This can manifest itself in two ways, one more public and one more subtle. The first, more public way is through the efforts to "cancel" public figures who deviate from the orthodoxy of the cultural hegemony. Incidentally, Coleman Hughes, less than a year after this podcast was published, was himself the object of an attempted cancellation.

Like a lot of commentary professionals, Coleman Hughes did a [TED talk](https://colemanhughes.substack.com/p/why-is-ted-scared-of-color-blindness). His talk expressed the opinion that one should not judge others based on their race, either in personal life or public policy. The talk would be singled out by an "employee resource group" entitled "Black\@TED" as upsetting, leading to much back and forth between Hughes and the executives at TED.

TED would go on to release Hughes' talk, but with the condition that Hughes would also have to release another video debating his viewpoint with someone who disagreed with his opinion. [In the end](https://colemanhughes.substack.com/p/my-last-word-on-ted), it appears that TED released, but did not promote Coleman Hughes' talk, leading to far fewer views than a TED talk typically receives.

Numerous articles have discussed this "cancel culture" phenomena, leading to many takes on just how prominent it is in our society. This is beyond the scope of this article. However, I will point out that these cancellations are just one aspect of the much larger phenomenon of cultural hegemony. Indeed, public cancellation is not even the most prolific form of deplatforming done by the cultural hegemony.

The second, more subtle, and much more profound way that deplatforming occurs is in the selection process of admissions, hiring, and promotion. This, like a lot of aspects of the cultural hegemony, has begun in academia.

As Peter Berkowitz, himself a long-time academic, discussed in a [recent talk](https://www.aei.org/events/why-do-american-universities-lean-so-far-to-the-left/), there had been an unwritten rule for decades at many academic departments across the country that the few graduate student spots they had available were reserved for those who subscribed to political ideologies they favor. This could be gleaned from personal statements, interviews, or participation in activist groups on an applicant's _curriculum vitae._ While this likely originated in more socio-politcally oriented fields such as sociology or political science, it has spread even to fields like biology.

What has happened since the rise in prominence of "diversity, equity, and inclusion (DEI)" initiatives in admissions and hiring, is that these unwritten rules have now become written down and more public. While many who approve of DEI initiatives do so out of honorable motives and a desire for those that face prejudice to be treated fairly, these DEI initiatives give true believers in the cultural hegemony an opportunity to abuse their power to promote those who share their viewpoints and hinder those who differ from their viewpoints from advancing in society.

For instance, someone who advocates "race conscious" public policy that discriminates on race in a "diversity statement" might have their application passed on to the next phase of the review process, whereas if someone like Coleman Hughes were to apply to graduate school and write in his "diversity statement" that he believed we should not discriminate on race in public policy, then his application can be discarded before the next phase of the process.

Thus, DEI initiatives can be a way to entrench political biases in admissions, hiring, and promotion decisions. In order to be considered for admissions, hiring, or promotion, the cultural hegemony's true believers can police applicants by way of their "diversity statements" to make sure they have the "correct" viewpoints. 

Regardless if someone thinks that race-neutral or race-discriminatory public policies are the best approach, people like Coleman Hughes should not be excluded from academia or from the discourse at large. Excluding such viewpoints impoverishes the entirety of the discourse, and we are all worse off for this deplatforming.


### Misrepresentation and Defamation

Once viewpoints that deviate from the orthodoxy favored by the cultural hegemony are deplatformed, the proponents of the cultural hegemony are left to explain why people disagree with the hegemony's orthodoxy at all. It is in this void that another hegemonic tactic is deployed: the misrepresentation of alternative viewpoints in order to make them unappealing. 

This recalls a humorous anecdote from my days as an undergraduate university student in which I was asked, "Do you support Communism?" When I replied in the negative, I was immediately told, "Then go tell poor people you want them to starve!"[^holodomor]

[^holodomor]: In light of the Holodomor, in which millions of people were starved to death in a man-made famine in the Soviet Union in the period from 1932-1933, this was a very tasteless choice of defamatory accusation.

While this is an obviously facile example of a viewpoint being misrepresented, it illustrates well the technique of misrepresentation. If people did believe my lack of support of Communism was due to my desire for "poor people to starve," then people would be less inclined to deviate from Communism, which for many decades was the cultural hegemony of eastern Europe and other areas.

Because of the prominence of [identity politics](/identity-trap.html) in the United States, many if not most of these misrepresentations of alternative viewpoints involve some invocation of "racist," "misogynistic," "homophobic," "transphobic," etc. Thus, misrepresentation of alternative viewpoints and defamation of the people who hold them are typically intertwined.

Coleman Hughes spoke about the ubiquity of people being called "racist" during his time at university:

> And so I was definitely in that 1% that rebelled when I was at Columbia. I tried writing for the student newspaper, but it was so absolutely captured by students with far left ideology that, you know, I could hardly write a sentence without them trying to fact check me on a book they'd never read.
> 
> And so I, you know, at some point gave up and just started -- I had a hunger to not just say things I was supposed to say to get along. And I also had -- I think what my friend Kmele Foster calls "the melanin force field," which is, you know, the fact -- the fact of the matter is as a -- as a black person, a lot of the people critiquing me on campus were white. And in their mind that gave them less standing to critique me if I did have contrarian views and in some way made it easier for me socially to actually be honest about what I thought, I think relatively, because I couldn't really be called a "racist," which was just a ubiquitous slur hurled at people.

Many people in the United States today rightfully try to avoid racist viewpoints. Misrepresenting viewpoints alternative to the ones advanced by the cultural hegemony as "racist," etc., thus discourages individuals from considering the alternative viewpoints. If people who are dominated by the cultural hegemony have never encountered an actual good faith exposition of an alternative viewpoint due to deplatforming, then this kind of misrepresentation is that much more effective at keeping those dominated by the cultural hegemony away from the viewpoint.


### Fear and Self-Censorship

In addition to the removal of individuals that occurs through public cancellations or through ideological bias in admissions, hiring, and promotion, there is a silencing effect on individuals who remain. For every one person who is fired for expressing viewpoints unpopular with the cultural hegemony, there are many more who see this occur and are scared into self-censorship. As David Sacks said:

> And a lot of it has to do with the cancellation tactics that they're willing to use -- the way that they will smear anybody who disagrees with their agenda. If you're part of that, again, that 80, 90% of the herd, you just don't want to stick your neck out. And there's just no upside for you in challenging the untruths and being called -- being accused of something. So this is a huge part of the dynamic.

As is typical with the cultural hegemony, this phenomenon begins at the university and spreads outward into the rest of society, as reported by the Foundation for Individual Rights and Expression (FIRE). Their most recent report on free speech on campus found that "just over a quarter of students (26%) reported that they feel pressure to avoid discussing controversial topics in their classes," and that "at least a quarter of students said they self-censor 'fairly often' or 'very often' during conversations with other students, with professors, and during classroom discussions (25%, 27%, and 28%, respectively.)" [@fire_2024] 

The situation is even worse for professors. A 2022 survey found that "roughly one-third (34%) of faculty said they often feel they can not express their opinions on a subject because of how students, colleagues, or the administration would respond," and that "the percentages of faculty who said they were very or extremely likely to self-censor in different contexts ranged from 25% (in academic publications) to 45% (on social media)." [@fire_2022]

While it is still a minority of students and faculty on campus who outright self-censor for fear of reprisals, majorities of both students and faculty at least worry about repercussions to their speech. "More than half of students (56%) expressed worry about damaging their reputation because of someone misunderstanding what they have said or done,"  [@fire_2024] and "more than half of faculty (52%) reported being worried about losing their jobs or reputation because someone misunderstands something they have said or done, takes it out of context, or posts something from their past online." [@fire_2022]


## The False Left-Right Binary Spectrum

As discussed in _The Myth of Left and Right,_ a binary spectrum -- whether it is framed as "left-wing" versus "right-wing" or "liberal" versus "conservative" -- fails as a description of socio-political _viewpoints,_ for many reasons, not the least of which is the fact that what has been considered "left-wing" or "right-wing" in the United States has changed from decade to decade and will likely change considerably in the future.

However, the left-right labeling [does explain certain _people_](when-left-wing-and-right-wing-are-and-arent-substantive-criticism.html) who adhere themselves to partisan conformity, even if they are adhering to a fad that is transient, ephemeral, and unnecessary. This is true of partisan conformists whether they identify themselves as "left-wing" or "right-wing."

Taking a more social view, the phenomenon of professional class cultural hegemony partly explains the emergence of this partisan conformity in the first place, but for only one of the (currently) popular versions of the left-right spectrum.

The original popular use of the left-right spectrum in the United States was over whether someone supported the New Deal, with "left" denoting degree of support for the New Deal and "right" denoting degree someone rejected the New Deal. This has little to do with the professional class cultural hegemony. Indeed, regardless of whether someone thought it the best way forward, the New Deal was largely targeted at the concerns of the working class.

Today, however, "left-wing" is sometimes used to denote the degree of conformity someone has to to a set of _cultural_ norms such as identity politics, abortion liberation ideology, and the banning of firearms. These are (currently) the norms fashionable among the cultural hegemons, i.e., administrators of elite universities and billionaires who own media outlets.

For this one -- and only this one -- specific use of "left-wing," the term "left-wing" is synonymous with domination by the professional class cultural hegemony. The degree to which someone is either a true believer using hegemonic tactics to promote these viewpoints or a go-along acquiescing to these viewpoints can be a measure of how "left-wing" someone is, but only for this limited definition of "left-wing."

Where does this leave the corresponding term "right-wing?" More generally, what kind of left-right spectrum does this specific definition of "left-wing" lead to?

It does _not_ lead to a left-right spectrum, at least not a binary one. Under this definition, there is a specific culture -- the one promoted by people who have an outsized impact on American society -- and then there are _all the other ones._ "Right-wing" under this specific definition is a catch-all for all the people who do not conform to the professional class cultural hegemony. Under this specific definition, "right-wing" is just dissent.

Instead of a linear spectrum with "left-wing" on one side and "right-wing" on the other, this definition leads to a star-burst pattern, with "left-wing" constituting an area of conformity to the cultural hegemony in the the middle of the pattern, and many lines away from this middle, each representing one of the many ways an individual can disagree with the cultural hegemony.

![
[Image](https://pixabay.com/vectors/fireworks-explosion-burst-circle-8240036/?utm_source=link-attribution&utm_medium=referral&utm_campaign=image&utm_content=8240036)
by
[Gordon Johnson](https://pixabay.com/users/gdj-1086657/?utm_source=link-attribution&utm_medium=referral&utm_campaign=image&utm_content=8240036)
from
[Pixabay](https://pixabay.com//?utm_source=link-attribution&utm_medium=referral&utm_campaign=image&utm_content=8240036).
](/images/starburst-pattern.png){alt="A circular pattern with whitespace at the center and many black lines radiating away from the center"}

Thus, even under this definition, the binary left-right spectrum makes no sense, and I do not recommend using the concepts of "left-wing" and "right-wing" even with this limited definition.

However, this star-burst model does help explain what is going on when people dominated by the cultural hegemony use terms like "right-wing," "conservative," "alt right," or "far right." People dominated by the cultural hegemony, be they true believers or go-alongs, have been prejudiced away from viewpoints that deviate from the cultural hegemony. These terms induce a knee-jerk reaction to avoid serious consideration of alternative viewpoints and to default back to conformity to the cultural hegemony.

Renowned economist Melissa Kearney relates an anecdote illustrating this phenomenon in which she received push back against her work:

> I thought about a conversation I had recently had with a different economist in a different setting who reacted negatively when I mentioned the importance of family structure to children's outcomes. He bristled, suggesting to me that I sounded "socially conservative," in a way that implied "not academically serious." I countered, "You are always talking about the things you are doing for your kids and how much time their activities take up in your life. Why would you be offended by the suggestion that maybe other kids would also benefit from having the involvement of two parents, and in particular a father, in their lives?" [@kearney_2023]

This knee-jerk aversion to viewpoints outside the cultural hegemony is expanded to other phrases in addition to "conservative" or "right-wing" by use of the concept of a "dog whistle." Some people dominated by the cultural hegemony espouse the belief that there are certain special codes in "right-wing" circles, which are called "dog whistles," that "right-wing" speakers use to communicate their alleged evildoing to other "right-wing" listeners in ways that sound innocent to the uninitiated.

These special codes are called "dog whistles" because much as dogs can hear the sounds made by special whistles that human beings cannot, the common person does not understand these alleged special codes, but both the "right-wing" audience and the special "left-wing" critics can. As expected, most of these special codes are construed to mean "racism," "misogyny," "homophobia," "transphobia," etc.

This is a level of paranoia and conspiracy thinking that poisons any possibility of engagement in the public discourse necessary to sustain a self-governing society. When people are metaphorically going through all the books in the library to cross out "Western civilization" and pencil in "White supremacy," there is no more room for rational thought. 

To be sure, there is _some_ amount of racism, sexism, etc., in human civilization, and this prejudice[^literal] explains _some_ of the viewpoints held by _some_ people. We can be sure that it is not the case that 0% of viewpoints in the world can be attributed to bigotry. But we can also be sure that it is not the case that 100% of viewpoints that deviate from the cultural hegemony can be attributed to bigotry, though that is what some would like us to believe. 

[^literal]: It should be pointed out that when many academics use words like "racism" or "sexism," they are not using the common dictionary definitions of these words which define them as a kind of prejudice. Rather, they are used with highly specialized meanings that differ from the common usage and do _not_ mean prejudice. For the sake of brevity, I have just used the common dictionary definitions here.

What is much more likely is that three or four of the rays out of center of the star-burst pattern are the rays of racism, sexism, etc., and that -- given the great diversity and wealth of human experience, thinking, and values -- all of the other rays represent ways of thinking and feeling that deviate from the thoughts and feelings of the Western, educated, industrialized, and rich people who are the hegemons of culture in the United States.


## Bullet List

* Cultural Hegemony of Abortion Liberation Ideology
  * Coleman Hughes and David Sacks don't see the hegemony of the abortion lobby because this was a successful hegemony 50 years ago
  * FIRE data on abortion being the most difficult topic to discuss among college students
  * My naivete about this explains the bad decisions I made in trying to pursue research career
  * Explains how United States is 50/50 on abortion, but academia is more like 99/1 and that 1% is currently being cancelled
  * While views on abortion have been near 50/50 split, only one side of this split has been able to completely override the other in terms of political dominance and in research opportunities
  * When there was less sorting on views on abortion between the two parties, Democrats had to moderate their abortion platform, which means I grew up in an era when the cultural hegemony around abortion was less obvious
  

## Conclusion

I did not realize how pervasive the professional class cultural hegemony phenomenon was until I heard it explained in so many words. I, like many, have my own anecdotes of encounters with the phenomenon.

I once was romantically involved with a woman who was an _alumna_ of Princeton University.[^university] ...

[^university]: For context, I myself graduated from an "elite" university, but one whose "elite" status comes primarily from its engineering school. It currently has an "above average" speech rating from FIRE. It was a common observation made at the university that students did not seem to care about politics or religion. The running joke was that this was because we were too busy with the massive amounts of homework we had. This was only slightly facetious.


## Citations

::: {#refs}
:::


## Footnotes
