---
author: "Joshua Born"
date: 2023-04-09
draft: true
include-before: |
  ## Table of Contents
output:
  blogdown::html_page:
    number_sections: false
    toc: true
    toc_depth: 5
summary: '[OPENING SENTENCE]'
tags: ["editorial", "fallacies", "first-person"]
title: 'Why Are Political People So Stupid?'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE
)
```

## Introduction

There is nothing intrinsically wrong about thinking about public policy. While it is true that politics is just one aspect of human civilization and not the only way to address a social issue you care about, there are many social issues that will inevitably lead someone who genuinely cares about them to think about politics.

If people are motivated to enter the realm of politics in this way, you would expect them to be on their best behavior, using the fullest abilities of their understanding to address an issue that earnestly concerns them.

This has led me often to wonder, why is so much of the stupidity we encounter, both in person and online, _political?_

There are many ways in which someone could become an enthusiastic outlet for stupidity. There are conspiracy theorists, religious fanatics, _et al._ However, in my anecdotal experience, the most common trait I have noticed about outspokenly stupid people I have encountered is that they are political.

The converse is not necessarily true; certainly, not all people who concern themselves with politics are stupid, and I do not mean "political" as in "political science." I have heard nuanced and thoughtful people give insightful analyses of politics.

However, I have also observed otherwise intelligent people, when consumed by politics, froth at the mouth and unleash a tirade of ignorance and, often, hatefulness.

This has led me to wonder, what are the characteristics of the _practice_ of political engagement that are so inimical to the practice of truthfulness and so conducive to stupidity and hatefulness? In the sequel, I summarize my observations categorized into three broad practices commonly associated with political engagement and which I believe to be flawed: partisanship, following the news cycle, and debate.


## Partisanship

Whether it is called "partisanship," "tribalism," "factionalism," or another name, perhaps the most obvious characteristic of political practice is the phenomenon of people sorting themselves into groups, deriving their sense of identity from an affiliation with a group, and exhibiting hostility to other groups.


## Groupthink Bias

This partisanship creates subsections of a society that are not representative of the larger population. A consequence of this is _groupthink bias._

Groupthink bias occurs when one viewpoint about a given issue becomes most salient within a group, and conformists in the group react to this by vehemently agreeing with the salient viewpoint, further reinforcing it. This creates a positive feedback loop until only one viewpoint dominates the group, and no rival viewpoints are expressed.

The salient viewpoint might be the viewpoint of the majority within the group, but this is not necessarily the case. All that is required is that a viewpoint become the most conspicuous within the group and be reified by those who are perceived as leaders and influencers of the group. (Such leaders are often actually being led, rather than leading.) Those who hold alternative viewpoint, regardless of whether they are a minority or silent majority, are then cowed into obsequence.

Groupthink bias leads to a lack of viewpoint diversity. Lack of exposure to a diversity of viewpoints in turn leads to stupidity in at least two ways.

The first way is agreement with a groupthink's viewpoint merely by default. This occurs when the sum of the beliefs and value judgements in a person's mind gives such a person a proclivity for some _other_ viewpoint besides the groupthink's viewpoint. However, those trapped in groupthink bias are unable to adopt the other viewpoint out of simple ignorance and so instead adopt the groupthink's viewpoint. Those who agree with a groupthink's viewpoint in this way are in an unstable position and will often find themselves arguing against their own values or beliefs.

The second way that lack of exposure to a diversity of viewpoints leads to stupidity is in depriving individuals of the opportunity to really understand their own viewpoints. A viewpoint in isolation is rarely well understood. It is only in the challenge of encountering other viewpoints and understanding the nuances of how our own viewpoint agrees and disagrees with other views that we truly understand what our own viewpoints actually are. When left unchallenged by criticism, our viewpoints are liable to lazy and not well thought out.


### Narratives

* Harari's idea of mythology.
* When walking around with a hammer, everything looks like a nail.
* Real understanding of social issues is does not resolve into an easy ongoing story.


### Spitefulness

* Hatred of the out-group becomes a motive unto itself.
* A talking point being _other_ is sufficient reason to disagree with it.


### Misrepresentation of Out-group Viewpoints

* Out-group viewpoints are routinely misrepresented.
* This can be facilitated by generic thinking and demagoguery.


## Following the News

There has been more attention to the issue of biased news sources in the United States. But why is paying attention to the news a good thing in the first place? The news consists of anecdotes and unrepresentative samples. Thus, it makes people less informed because they think they are informed when they are not.

* Fallacy of celebrated cases. Kahneman's availability heuristic.
* Anecdotes generally
* Media selection bias
* Browse not search. Short attention span means no detailed knowledge of a social issue.
* Lack of historical context.

## Debate

* Motivated reasoning
  * Lawyer-mode versus scientist-mode
  * Selection bias again
* Nothing to "win," but it does mean you are not listening


## Conclusion



