---
title: "Love and Other Supposed Counterexamples"
date: 2016-12-25
tags: ["evolution", "love"]
bibliography: "../bibliographies/love-and-other-supposed-counterexamples.json"
csl: "../bibliographies/apa.csl"
link-citations: true
---

Love is often pontificated upon as one of the more mystical and undefinable aspects of human nature. However, it is one of the more obvious effects of evolution by natural selection upon behavior and is readily explicable using the framework articulated here.


## Human Nature and Varieties of Love

Much confusion comes from the word "love" being used for multiple duties in the English, whereas in other languages there are several words for the various phenomena all labeled "love." Others who have contemplated love have started by untangling this mess, listing out all the various kinds of love and noting their similarities and differences. For our purposes, however, we can embrace this equivocation.

Whom do you love?

Your children? Your romantic partner? Your parents? Your siblings? Your extended family? Your good friend you can always rely on during trials and tribulations?

As we learned in our [meditation on human nature](four-teloi-of-human-nature.html), we inherit tendencies toward the pursuit of Four _Teloi_. The first two _teloi_ are survival and reproduction. These _teloi_ are a direct result of having evolved via natural selection. The most common answers to the question, "Whom do you love?" are precisely those individuals whom loving increases our chances of surviving and reproducing.


### Reproductive Advantage

In previous generations, those who had a strong love for their children were more likely to persist through the great demands of time, energy, and material resources &ndash; not to mention emotional stress &ndash; that offspring place upon their parents. Therefore they were more likely to raise their offspring to reproductive maturity successfully, and we are more likely to inherit their traits.

In previous generations, those who fell in love with a romantic partner were more likely to have recurring social interaction with said partner, which in turn led to greater opportunity for fertilizing offspring. Therefore they were more likely to procreate, and we are more likely to inherit their traits.

These two kinds of love increased the chances our ancestors would have been successful at reproducing. Inasmuch as they are influenced by genetic inheritance, natural selection has promoted these kinds of love.


### Survival Advantage

Historically childhood is a time when an organism is most vulnerable and at greatest chance for untimely death. Because of the aforementioned parental love, the most likely individuals to take care of children were their parents. In previous generations, the love of children for their parents would cause them to seek out their parents and thus be better able to receive care and protection. Therefore they were more likely to survive to reproductive maturity, and we are more likely to inherit their traits.

In previous generations, those who loved family and friends that in turn also loved family and friends created a mutual benefit network. Anyone who fell ill and required care in this mutual benefit network would have received care from the other healthy members of the network. Therefore they were more likely to survive, and we are more likely to inherit their traits.

These two kinds of love increased the chances our ancestors would survive. Inasmuch as they have a genetic component, natural selection has promoted these kinds of love.


### Kin Selection

Love for family has an extra adaptive benefit under natural selection since relatives share much of their genome and are more likely to have alleles in common. Because natural selection operates at the genetic level, one loving one's family has not just the selective advantage that comes from a mutual support network that might one day care for oneself, but also the selective advantage of taking care of one's own alleles carried around in others. As far as natural selection is concerned, this is a form of extended self-care. This partly explains why we can observe familial love, on average, less frequent amongst distant relatives and increasing the more closely related two individuals are.


### Et Cetera

While the preceding covers the most commonly experienced kinds of love, it does so using only two of the Four _Teloi._ Other kinds of love are readily explicable in terms of the remaining two _teloi._ This includes love of country (cf. the _telos_ of tribalism) and love of prophets, spirits, or gods (cf. the _telos_ of mythology).


## Supposed Counterexamples

We can imagine how the protests might come pouring in. Some might protest they love another human so much they have been willing to sacrifice themselves, even risking their own lives, for the benefit of the other. Some might protest they love their pets, yet their pets on the balance sheet of life are a cost with no benefit other than the joy they bring. Surely this contradicts the proposition that love is an adaptation under natural selection that promotes survival and reproduction.

Before we address these protests directly, we first must dispel a common confusion about natural selection that that goes something like, "It is claimed that trait _A_ evolved because of selective function _X_, but here are examples of trait _A_ being used to do _Y_ and _Z_ instead. Therefore _A_ did not evolve because of selective function _X."_

Human behavior is rife with many such examples. Eating is something that evolved in our ancestors so that they could survive, but for many humans today eating can be something done for pleasure to the excess of what is needed for survival or even to the detriment of the their long-term health. Sexual intercourse is something that evolved in our ancestors so that they could reproduce, but many humans today engage in sexual intercourse for pleasure and take measures with the expressed purpose of avoiding procreation. However, the use of behaviors for something other than or even contrary to their selective function does not contradict that they were promoted by natural selection because of their selective function.

For one, natural selection promotes traits that result in a _net increase_ in genetic propagation. Consider an allele that causes the majority of organisms that possess it to live twice as long, but that causes the minority of organisms that possess it to die before reaching sexual maturity. This allele could very well be promoted by natural selection, depending on the circumstances of the organisms in question. This is an extreme version of the phenomenon of antagonistic pleiotropy.

One of the more infamous examples of this phenomenon affecting humans is that of sickle-cell trait, which has both the maladaptive effect of putting the children of those with the trait at risk of sickle-cell disease and the adaptive effect of conferring those with the trait some protection against malaria. [@allison] In areas where malaria is a great health risk, sickle-cell trait results in a net selective advantage and so has propagated. In areas where malaria is less of a threat, sickle-cell trait results in a net selective disadvantage and so is uncommon.

Furthermore, natural selection promotes traits that increased the propagation of their alleles in _ancestral_ organisms. It is not at all inconsistent for an inherited trait to have once been adaptive, but now to have lost its adaptive function or even to be maladaptive.

One of the more notable examples of this is an hypothesis regarding human predilection for sweets. The consumption of sweetened drinks in modern, industrialized societies has been implicated in the prevalence of type 2 diabetes and metabolic syndrome. [@malik] Thus we might judge such a predilection to be maladaptive. However, we can imagine our pre-industrialized ancestors living in times of greater physical labor and less readily available nutrition benefitting from such a predilection, since sweetness often denotes nutritionally rich foods helpful to those engaged in physical exertion while undernourished.

Returning to the protests regarding love, yes, a select few individuals might sacrifice their lives for the love of another, but that is a very small loss of genetic propagation when compared with the increase that comes from association with individuals that live in love and support of one another. This would be an example of a net selective advantage in a state of antagonistic pleiotropy.

While pets now serve a largely luxury role in industrialized society, they are descended from domesticated animals that once served important practical functions to their humans. This would be an example of a trait being adaptive in ancestral organisms, even if they are not now.

These are only two concrete supposed counterexamples to the proposition that love is a part of human nature that is a direct result of evolution by natural selection. There are likely many, many more. The vast majority can be answered in the manner articulated here: natural selection explains large trends in how organisms evolve, and not every single instance of a trait will be used for the selective function that promoted the trait, including love. 


## Magnitude of Love in Humans

One thing that can be said of human love, while it may not be [metaphysical](metaphysics-spirituality-and-religion.html) and unexplainable, we have reason to believe it is more intense in humans than in other species of animals. This can be seen if we focus on the sort of love parents have for their children. As previously stated, this kind of love is likely the result of selective pressure compensating for the great demands that offspring place on their parents.

If parental love indeed compensates for the challenge of childrearing, it is greater in humans than in other animals because of the greater amount of effort humans must put into raising their children compared with other species. One of the features that differentiates primates from other mammals is the increased parental investment primates must make in their offspring, and one of the features that differentiates humans from other primates is again the increased parental investment that humans must make in their children. [@larsen] Thus humans represent an extreme case in the amount of care their offspring require. Thus humans may very well represent an extreme case in the magnitude of love we feel.


## Inline Citations

