baseurl = "https://fecundity.blog/"
languageCode = "en-us"
title = "Fecundity"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
uglyURLS = true
disableKinds = ["taxonomyTerm"]

[permalinks]
    post = "/:slug/"

[Taxonomies]
  tags = "tags"

[params]
    description = "Writings about contraception, critical thinking, and other things"
