baseURL = "https://fecundity.blog/"
languageCode = "en-us"
title = "Fecundity"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", ".md$"]
uglyURLS = true
disableKinds = ["taxonomyTerm"]

[permalinks]
  post = "/:slug/"

[Taxonomies]
  tags = "tags"

[params]
  subtitle = "Independent, evidence-based inquiry"
  description = "A blog containing independent thinking, criticism of fallacies, and evidenced-based inquiry into contraception, alloparenting, and abortion."

[mediaTypes]
[mediaTypes."application/atom+xml"]
  suffixes = ["xml"]

[outputFormats.Atom]
  mediaType = "application/atom+xml"
  baseName = "feed"
  isPlainText = false

[outputs]
  home = ["HTML", "Atom"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
