baseurl = "https://fecundity.blog/"
languageCode = "en-us"
title = "Fecundity Blog"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
uglyURLS = true

[permalinks]
    post = "/:slug/"

[Taxonomies]
  tags = "tags"

[params]
    description = "Writings about contraception, critical thinking, and other things"
