baseurl = "https://fecundity.blog/"
languageCode = "en-us"
title = "Fecundity Blog"
theme = "hugo-lithium"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
uglyURLS = true

[permalinks]
    post = "/:slug/"

[params]
    description = "Writings about contraception, critical thinking, and other things"
