baseURL = "https://fecundity.blog/"
languageCode = "en-us"
title = "Fecundity"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
uglyURLS = true
disableKinds = ["taxonomyTerm"]

[permalinks]
  post = "/:slug/"

[Taxonomies]
  tags = "tags"

[params]
  subtitle = "Writings about contraception, critical thinking, and other things"

[mediaTypes]
[mediaTypes."application/atom+xml"]
  suffixes = ["xml"]

[outputFormats.Atom]
  mediaType = "application/atom+xml"
  baseName = "feed"
  isPlainText = false

[outputs]
  home = ["HTML", "Atom"]
