---
author: "Joshua Born"
bibliography: "../bibliographies/abortion-advocacy-is-a-conservative-position.bib"
csl: "../bibliographies/chicago-author-date.csl"
date: 2023-01-14
draft: true
include-before: |
  ## Table of Contents
output:
  blogdown::html_page:
    number_sections: false
    toc: true
    toc_depth: 5
summary: "SUMMARY GOES HERE"
tags: ["opinion", "reproductive responsibility", "first-person"]
title: 'Abortion Advocacy is a Conservative Position'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE
)
```


Different people have radically different judgments about the practice of killing human fetuses or embryos as a method of fertility control, which is euphemistically described in the medical literature as "induced abortion of pregnancy" and as just "abortion" in the vernacular. Some have great compunction about this practice. Others are positively disposed to this practice. Among those positively disposed to the practice, some might judge it to be merely morally neutral, while some judge it to be morally good.

For the latter, the particulars of this judged moral goodness varies considerably by social context. In the United States, those who judge killing fetuses and embryos for fertility control as a moral good typically subscribe to some version of abortion-as-women's-liberation ideology, which is unsurprising given the prominence of "freedom" in the political mythology of the United States. However, in China, the goodness of abortion for fertility control is more likely to be construed as part of the duty of a family to act for the greater benefit of society at large, rather than individual freedom. [@nie2005behind]

Among those who judge abortion to be morally good, some have incorporated it into a core part of their socio-political outlook and might be called "abortion advocates" or, as was done in a previous article, "abortion enthusiasts." This article contends that enthusiasm for abortion is fundamentally a conservative position. This is done not to misrepresent or defame abortion advocates, but to highlight an important dynamic that those who _do_ have compunction about the killing of fetuses and embryos must reckon with in their worldviews.

First of all, it should be noted that by "conservative" is not meant the definitions of "conservative" used to refer to right-wing politics in contrast to left-wing politics, such as "of or constituting a political party professing the principles of conservatism." [-@noauthor_conservative_nodate, 1b] Rather, by "conservative" is meant such definitions as "tending or disposed to maintain existing views, conditions, or institutions" [@noauthor_conservative_nodate, 2a] and which are synonymous with "traditional." The important point is that _abortion advocates need only to preserve the status quo._

This is important for those of us who have compunction about abortion as a method of fertility control to realize because we must frame our strategies with the awareness that we desire a version of human civilization that has not yet existed. In the context of human history, our position is new, tenuous, and radical. In contrast, in a world in which there are 40 million induced abortions every year, the civilization that abortion advocacy desires is basically the world we live in today.

Indeed, the civilization that abortion advocacy desires is basically the civilization that we have had for thousands of years. Killing fetuses is at least as old as the bronze age, when Hippocrates thought to include a proscription against administering pessaries for the purpose of inducing abortion in his famous oath. (This was likely done not out of moral concern for killing the fetus, but rather out concern for the side effects of the poisons used as pessaries on the mother. Hippocrates lived at time when infanticide was a legal and common practice, so he was likely inured to homicide as a method of fertility control.)

* Roman Catholic church didn't start to care about fetuses until the 18th century
* Abortion was common in the United States when it was mostly illegal as a method of fertility control
* Abortion occurs in places where it is illegal today by inventing medical treatments like "menstrual regulation"



## Citations

::: {#refs}
:::

