---
author: "Joshua Born"
bibliography: "../bibliographies/approval-of-abortion-is-conservative.bib"
csl: "../bibliographies/chicago-author-date.csl"
date: 2023-01-14
draft: true
include-before: |
  ## Table of Contents
output:
  blogdown::html_page:
    number_sections: false
    toc: true
    toc_depth: 5
summary: "SUMMARY GOES HERE"
tags: ["opinion", "history", "reproductive responsibility", "abortion", "third-person"]
title: 'Approval of Abortion is Conservative'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE
)
```


## Introduction

Different people have radically different judgments about the practice of killing human fetuses or embryos as a method of fertility control, which is euphemistically described in the medical literature as "induced abortion of pregnancy" and in the vernacular as just "abortion." For instance,

* Discuss Gallup poll here

Among those who approve of this practice, how the approval is framed varies considerably by social context. In the United States, those who judge killing fetuses and embryos for fertility control as a moral good typically subscribe to some version of abortion-as-women's-liberation ideology, which is unsurprising given the prominence of "freedom" in the political mythology of the United States. However, in China, approval of abortion for fertility control is more likely to be construed as part of the duty of a family to act for the greater benefit of society at large, rather than individual freedom. [@nie_behind_2005]


Regardless of particular social context and ideology for the approval, this article contends that approval of abortion as a method of fertility control is a conservative position.


## Definition of "Conservative" Used

First of all, it should be noted that by "conservative" is not meant the definition of "conservative" used to refer to right-wing politics in contrast to left-wing politics, such as "of or constituting a political party professing the principles of conservatism." [-@noauthor_conservative_nodate, 1b] Rather, by "conservative" is meant such definitions as "tending or disposed to maintain existing views, conditions, or institutions." [@noauthor_conservative_nodate, 2a] Approval of abortion is conservative precisely because it is a viewpoint disposed to preserve the _status quo._


## Brief History of Views on Induced Abortion

The use of induced abortion of pregnancy as a method of fertility control is not new.

### Abortion in Ancient Greco-Roman Society

The ancient Greek[^eurocentric] physician Hippocrates who lived during the classical period (5th to 4th centuries B.C.E.) wrote of a story in his treatise _On the Nature of the Child:_

[^eurocentric]: This section focuses on European history and Greco-Roman history in particular. This is not because social phenomena occurring in a European context deserve primacy of consideration, but because there is an abundance scholarship available to someone doing research in the English language regarding European history, whereas studying other social contexts is more challenging and beyond the scope of this article. This article seeks to establish that induced abortion of pregnancy as a method of fertility control is a very old practice, and Greco-Roman scholarship provides a well-documented example.

> A female relative of mine once owned a very valuable singing girl who had relations with men, but who was not to become pregnant lest she lose her value. The singing girl had heard what women say to one another, that when a woman is about to conceive, the seed does not run out of her, but remains inside. She understood what she heard and always paid attention, and when she one time noticed that the seed did not run out of her, she told her mistress, and the case came to me. When I heard (sc. what had happened), I told her to spring up and down so as to kick her heels against her buttocks, and when she had sprung for the seventh time, the seed ran out on to the ground with a noise, and the girl on seeing it gazed at it and was amazed.
>
> How it looked I will recount: it was as if someone had removed the external shell of a raw egg, and the fluid part inside was visible through the internal membrane. Its appearance was somewhat as follows, to say as much as is needed: it was red and roundish; broad, white strands were seen to be present inside the membrane, pressed together with thick, red serum, and around the membrane on the outside there was bloody material. Through the middle of the membrane something narrow came out, which appeared to me to be an umbilical cord, and through this the movement of breath in and out first took place. From this the membrane spread out and completely enclosed the seed. [@hippocrates_nature_2012, 36-37]

The casual way in which Hippocrates relates the killing of a human embryo in order to preserve the value of a slave is indicative of how little compunction he felt at induced abortion for the most pecuniary of motives. It also shows that knowledge of how to induce abortion was being promulgated as early as the Greek classical period.

Indeed, induced abortion was common knowledge throughout the Greco-Roman era. The seminal _De Materia Medica_ of 1st century C.E. pharmacologist-botanist Dioscorides, which was widely read for more than a millennium, notes 66 substances that can be used as an abortifacient.[^list] [@dioscorides_materia_2000] Soranus, writing in the 1st or 2nd century C.E., describes procedures for inducing abortion in his _Gynecology,_ including some procedures that use substances described by Dioscorides. [@soranus_gynecology_1991, 66-68] Given its prevalence in widely promulgated texts of the Greco-Roman era, knowledge of how to induce abortion of pregnancy was relatively accessible.

[^list]: The 66 abortifacients described in _De Materia Medica_ are are _kardamomon_ (p. 6), _kinamomon_ (pp. 18-19), _balsamon_ (pp. 23-24), _aspalathos_ (pp. 24-25), _sampsuchinon_ (pp. 55-56), _bdellion_ (pp. 82-83), _kedros mikra_ (pp. 102-103), _daphne_ (p. 106), _leuke_ (p. 109), _katoros orchis_ (p. 193), _oisupon_ (p. 212), _pitua_ (p. 213), _apopatos_ (pp. 222-223), _erebinthos_ (p. 244), _thermos emeros_ (p. 255), _sion to en odasin_ (p. 280), _kardamon_ (p. 312), _thlaspi_ (p. 315), _piper_ (pp. 316-319), _strouthion_ (p. 323), _kuklaminos_ (pp. 323-324), _drakontion meca_ (pp. 327-328), _drakontion mikron_ (pp. 328-331), _kissos_ (pp. 351-352), _gentiane_ (p. 367), _aristolochia klematitis_ (pp. 368-371), _kentaurion makron_ (p. 372), _kentaurion mikron_ (p. 375), _glechon_ (p. 404), _elelisphakon_ (p. 408), _kalaminthe_ (p. 412), _thmos_ (p. 415), _bakcharis_ (pp. 420-423), _peganon to kepaion_ (pp. 423-427), _panakes herakleion_ (pp. 428-431), _seseli massaleotikon_ (p. 436), _anethon_ (p. 443), _smurnion_ (p. 455), _daukos_ (p. 460), _sagapenon_ (p. 479), _chalbane_ (pp. 480-483), _ammoniakon_ (pp. 483-484), _klinopodion_ (p. 492), _chamaidrus_ (p. 496), _artemisia monoklonos_ (pp. 513-514), _konuza_ (pp. 517-518), _leukoion_ (p. 519), _onosma_ (pp. 523-524), _anthemis_ (pp. 527-528), _eruthrodanon_ (p. 532), _anaguris_ (p. 535), _anchousa_ (p. 567), _mandragoras_ (p. 624), _elleboros_ (pp. 696-699), _elleboros melas_ (pp. 700-703), _elaterion_ (pp. 707-708), _skammonia_ (pp. 726-727), _thumelaia_ (p. 728), _kolokunthis_ (p. 731), _ampelos leuke_ (pp. 733-734), _thelupteris_ (p. 736), _eliotropion mega_ (p. 739), _oinos phthorios enibruon_ (p. 778), _oinos elleborites_ (pp. 779-780), _stupteria_ (pp. 806-807), _theion_ (p. 807).

It is clear that the ancients knew of ways to kill embryos and fetuses _in utero._ It is more difficult to glean what were ancient attitudes toward abortion, however, since there were no nationally representative opinion polls in antiquity.

At least one famous figure, the philosopher Aristotle, endorsed abortion specifically as a method of fertility control. Writing in the 4th century B.C.E., he recommends in his _Politics:_

> As regards whether to expose or nourish what is born, let the law be to nourish nothing that is defective but not to expose anything born, where the arrangement of customs forbids [more than a certain number of children], merely because of numbers. For there should be a limit to the amount of child-getting, but if some couple together and get offspring contrary to this, abortion should be procured before perception and life appear (what is and is not holy will be defined by perception and life). [@simpson_politics_1997, 1335b19]

While Aristotle specifically endorses induced abortion of pregnancy as a method of fertility control, this is only when abortion is induced before "perception and life" appear. This an early example of what might be called "threshold" attitudes toward abortion as a method of fertility control, which hold that killing fetuses or embryos as a method for family planning is acceptable before a certain point in their development, but killing them after this threshold is unacceptable. Such threshold attitudes include those that posit an inflection point such as "sentience," "personhood," etc., occurring _in utero._

Description of Aristotle's views on abortion as a method of fertility control is not to deny that there were a diversity of moral viewpoints on abortion in antiquity, much as the morality of abortion is a controversial subject in modern times. For instance, Soranus in his _Gynecology_ relates how there was much disagreement about induced abortion in his day:

> A contraceptive differs from an abortive, for the first does not let conception take place, while the latter destroys what has been conceived. Let us, therefore, call the one "abortive" _(phthorion)_ and the other "contraceptive" _(atokion)._ And an "expulsive" _(ekbolion)_ some people say is synonymous with an abortive; others, however, say that there is a difference because an expulsive does not mean drugs but shaking and leaping, .... For this reason they say that Hippocrates, although prohibiting abortives, yet in his book "On the Nature of the Child" employs leaping with the heels to the buttocks for the sake of expulsion.
> 
> But a controversy has arisen. For one party banishes abortives, citing the testimony of Hippocrates who says: "I will give to no one an abortive"; moreover, because it is the specific task of medicine to guard and preserve what has been engendered by nature. The other party prescribes abortives, but with discrimination, that is, they do not prescribe them when a person wishes to destroy the embryo because of adultery or out of consideration for youthful beauty; but only to prevent subsequent danger in parturition if the uterus is small and not capable of accommodating the complete development, or if the uterus at its orifice has knobby swellings and fissures, or if some similar difficulty is involved. And they say the same about contraceptives as well, and we too agree with them. And since it is safer to prevent conception from taking place than to destroy the fetus, we shall now first discourse upon such prevention. [@soranus_gynecology_1991, 62-63]

This passage is notable because there is no consideration as to whether it is morally wrong to kill embryos or fetuses _per se._ Even though Soranus understands the difference between contraception and induced abortion and relates the controversies around abortion, most of these disagreements are equally applicable to considerations about contraception. 

Any discussion on whether it is wrong to kill embryos and fetuses like it is wrong to kill infants is absent from Soranus' description because the idea that it was morally wrong to kill infants was not yet widely accepted. Indeed, Aristotle was ahead of his time in recommending that exposure not be used for fertility control, but only used to dispose of "defective" infants. This social context is important for understanding ancient attitudes toward induced abortion.


### Legal Right to Infanticide in Greco-Roman Society

Throughout the ancient Greco-Roman era, infanticide was seen as a legal right. By the time of the Roman Empire, this attitude was embedded the _patria potestas_, which stipulated the rights of a patriarch of a household, or _pater familias,_ pertaining to his authority over the household. The _patria potestas_ recognized that the _pater familias_ wielded _jus vitae ac necis_ (literally "the right of life and death") over the children of the household, and could choose to raise, abandon, or outright kill whichever children he pleased. [@obladen_right_2016]

Sometimes decisions to not raise a child took the form of an overt act of killing, such as drowning a newborn in a bucket, but the practice of exposure, in which a neonate was abandoned in a public place, was also common. When exposure was done, the death of the child was likely, but there was always the possibility that someone else would take and raise the child. This is known to have sometimes occurred, since in the later imperial period the legal status of children exposed by one _pater familias_ only to be raised by another became a political issue. [@grubbs_infant_2013]

Regardless of how unwanted children were disposed of, _patria potestas_ and similar laws enshrined the legality of the practice. Proposing that children should be protected from aribtrary death would thus have been considered a strange opinion in antiquity. Therefore, as long as killing infants, either directly or indirectly through abandonment, were accepted practices in human society, it was unlikely that much consideration would be given to the morality of killing fetuses or embryos.

In addition to preventing moral reflection about induced abortion, infanticide and child abandonment may have been a more desirable alternative in antiquity, a time when induced abortion of pregnancy was considered risky for the mother. For instance, Plutarch relates a story about the legendary Spartan lawgiver Lycurgus:

> Polydectes also died soon afterwards, and then, as was generally thought, the kingdom devolved upon Lycurgus; and until his brother’s wife was known to be with child, he was king. But as soon as he learned of this, he declared that the kingdom belonged to her offspring, if it should be male, and himself administered the government only as guardian. Now the guardians of fatherless kings are called _"prodikoi"_ by the Lacedaemonians. 
>  
> Presently, however, the woman made secret overtures to him, proposing to destroy her unborn babe on condition that he would marry her when he was a king of Sparta; and although he detested her character, he did not reject her proposition, but pretended to approve and accept it. He told her, however, that she need not use drugs to produce a miscarriage, thereby injuring her health and endangering her life, for he would see to it himself that as soon as her child was born it should be put out of the way.
> 
> In this manner he managed to bring the woman to her full time, and when he learned that she was in labour, he sent attendants and watchers for her delivery, with orders, if a girl should be born, to hand it over to the women, but if a boy, to bring it to him, no matter what he was doing. [@plutarch_lives_1914, 210-211]

While stories about Lycurgus are semi-mythical and so do not tell us much about attitudes in the 9th century B.C.E. when he is supposed to have lived, this story does reflect on the sensibilities of Plutarch's 1st or 2nd century C.E. audience, who would have been familiar with the attitude that infanticide or child abandonment were safer alternatives to induced abortion.

In the story, due to the rules of royal succession, Lycurgus is more interested in the child if it is a boy than if it is a girl. This highlights the fact that the ancients could use infanticide and child abandonment for more purposes than they could use induced abortion. For instance, a popular use of induced abortion today is sex-selective abortion, which occurs when parents screen the sex of a fetus and have it killed if it is an unwanted sex, typically female. This practice results in unbalanced sex ratios in many countries. [@chao_systematic_2019]

Sex-selective abortion could not be done in antiquity, since a method for reliably determining the sex of a fetus was not available. This could be done with infanticide or child abandonment, however. For instance, the Oxyrhynchus Papyri contain a letter written in Egypt during the Roman era by a gentleman by the name of Hilarion to his wife Alis:

> Hilarion to Alis his sister, hearty greetings, and to my lady Berous, and Apollonarion. Know that at present I am still in Alexandria. Don’t worry if they all come back, and I stay in Alexandria. I ask you, I urge you -- care for the child, and if I soon get pay, I will send it up to you. If perhaps you give birth, then if it is male, let it be; if it is female, throw it out. You told Aphrodisias "Don't forget me." How can I forget you? So I ask you not to worry. [@mckechnie_errant_1999]

In addition to sex selection, infanticide and child abandonment could be used to dispose of children judged to be unhealthy or malformed, whereas those living in antiquity without modern fetal assessment technologies could not use induced abortion for a similar purpose, at least not effectively. Thus, Seneca, writing in the 1st century C.E., reports:

> Unnatural progeny we destroy; we drown even children who at birth are weakly and abnormal. Yet it is not anger, but reason that separates the harmful from the sound. [@seneca_moral_1928, 145]

Therefore, there must have been some in antiquity who saw infanticide and child abandonment as preferable to induced abortion of pregnancy since it was perceived to be safer and could be used for more purposes than just fertility control, such as sex selection and disposing of children deemed unhealthy.


### Criminalization of Infanticide

The enshrinement in _patria potestas_ of the legal right to dispose of unwanted children by infanticide and child abandonment was slowly eroded in the late Roman Empire until infanticide was finally outlawed in 374 C.E. during the overlapping reigns of emperors Valentinian, Valens, and Gratian. A few decades later, the Visigoths sacked Rome, and in time the (western) Roman Empire collapsed, but the _Lex Visigothorum_ also outlawed infanticide. [@obladen_right_2016] 

Despite the proscription of infanticide and child abandonment by some legal codes, the practices persisted. Pope Innocent III, reigning in the 13th century C.E., was so disturbed by the number of infant corpses being retrieved from the Tiber River in Rome by fishermen that he commissioned a foundling home to take in unwanted infants. [@grubbs_infant_2013]

The establishment of foundling homes was a widely used strategy in attempts to remedy infanticide, but to very limited success, as oftentimes foundling homes themselves had such high infant mortality rates that they were perceived to be not much better than exposure, and authorities struggled to institute policies to deal with infanticide well into the 19th and 20th centuries C.E. [@kilday_history_2013]

This inability of the authorities to eliminate infanticide in Europe throughout the late medieval and early modern periods despite the practice being outlawed was paralleled in other parts of the world. Curiously, ameliorating infanticide became a _cause célèbre_ of European missionaries to China, leading to infanticide in East Asia being more well known for a time, despite infanticide being a social problem in Europe during the same time frame, as well. [@mungello_drowning_2008]


### Christian Views on Sexuality

Much as understanding ancient Greco-Roman society's views on induced abortion are complicated by the fact that the killing of infants was viewed as a legal right of patriarchs, understanding views on induced abortion after the spread of Christianity is complicated by the fact that contraception was (and in some cases, still is) viewed as a sin by prominent interpretations of Christianity.

Augustine, who lived during the 4th and 5th centuries C.E., is considered a saint in the Catholic Church, the Eastern Orthodox Church, and the Anglican Communion and was highly influential on early Christianity. Augustinian doctrine exalts chastity and considers any sexual intercourse except for the purpose of procreation to be sinful. This stems from a general attitude of avoiding excess or gluttony. In his treatise _The Good of Marriage,_ Augustine writes:

> Surely we must see that God gives us some goods which are to be sought for their own sake, such as wisdom, health, friendship; others, which are necessary for something else, such as learning, food, drink, sleep, marriage, sexual intercourse. Certain of these are necessary for the sake of wisdom, such as learning; others for the sake of health, such as food and drink and sleep; others for the sake of friendship, such as marriage or intercourse, for from this comes the propagation of the human race in which friendly association is a great good. So, whoever does not use these goods, which are necessary for something else, for the purpose for which they are given does well. As for him for whom they are not necessary, if he does not use them, he does better. [@augustine_treatises_1955, 21-22]

In Augustinian doctrine, while sexual intercourse done for pleasure instead of propagation of the human race is considered sinful, if this occurs between married couples, it is a lesser sin:

> In marriage, intercourse for the purpose of generation has no fault attached to it, but for the purpose of satisfying concupiscence, provided with a spouse, because of the marriage fidelity, it is a venial sin; adultery or fornication, however, is a mortal sin. And so, continence from all intercourse is certainly better than marital intercourse itself which takes place for the sake of begetting children. [@augustine_treatises_1955, 17]

Indeed, according to Augustine, marriage itself makes sexual intercourse done for pleasure rather than procreation pardonable as long as it does not interfere with a couple's pious activities:

> ... it is that sexual intercourse that comes about through incontinence, not for the sake of procreation and at the time with no thought of procreation, that [Paul the Apostle] grants as a pardon. Marriage does not force this type of intercourse to come about, but asks that it be pardoned, provided it is not so great as to encroach on the times that ought to be set aside for prayer ... [@augustine_treatises_1955, 24]

Augustinian injunctions against sexual intercourse are thus intended to encourage piety. However, this doctrine also has the direct implication that _any_ contraceptive methods are inimical to Christian piety, because their expressed purpose is to engage in sexual intercourse without procreation. Therefore, in Augustinian Christianity, contraception is itself a sin. This complicates interpretation of attitudes toward induced abortion of pregnancy.

Any Christian commentator who subscribes to Augustinian attitudes about sexuality will judge induced abortion to be wrong at least in the same way as contraception is judged to be wrong. This is a minor kind of wrong for which punishment is not necessary in Augustinian doctrine, so long as it occurs within marriage.

However, it is also possible that a Christian commentator would judge the killing of embryos and fetuses to be wrong in the way homicide is wrong, similarly to how the practices of infanticide and child abandonment were increasingly judged to be wrong during the same time period early Christianity was developing. This is a much more severe kind of wrong, as both Valentinian-era Roman law and the _Lex Visogothorum_ prescribed capital punishment for those convicted of infanticide.

Furthermore, both kinds of judgement can be occurring in the commentary of Christians who subscribe to Aristotlean threshold attitudes toward induced abortion, which Augustine himself did.

> _If two men are fighting, and they strike a woman who is pregnant, and her child does not emerge deformed, he shall suffer a fine. As much as the woman's husband shall specify, he shall give what is demanded._ (Ex 21:22) It seems to be that this is said as having some meaning rather than as a scripture passage dealing with deeds of this sort. For, if its aim were that a pregnant woman not be struck and forced into a miscarriage, it would not posit two quarreling men, when it could be done by the one man who, when he was fighting with the woman herself, or, even if the were not fighting, nonetheless acted intentionally to harm another man's posterity. But he did not intend the unformed child to be the object of murder, and surely he did not deem what is carried in the womb to be a human being. At this point it is customary to raise a question about the soul, namely, whether what has not been formed can even be understood to possess a soul, and therefore whether this would be murder, because it cannot be said to have been deprived of life if it did not yet have a soul, for [the passage] continues and says, _But if it has been formed, he shall give a life for a life_ (Ex 21:23)....
> 
> Hence, if at the time that was indeed an unformed child, but still in some way possessed of an unformed soul (because the great question about the soul is not to be hurried along with the hastiness of an unconsidered opinion), the law was unwilling to make the case pertain to murder, because it cannot yet be called a living soul in that body which lacks sensation, if such [a soul] has not yet been formed in the flesh and [the flesh] has not yet been endowed with senses. [@augustine_writings_2016, 130-131]

In this passage, Augustine recapitulates almost exactly the Aristolean doctrine regarding prenatal life, such that there is a threshold _in utero_ when offspring are "formed" after which killing an embryo or fetus is homicide, but before which it is not. All that has changed in Augustine's view from Aristotle's view is, in addition to concepts such as sensation and life, the concept of possession of a soul is added.


### Quickening and Abortion in 19th Century Law

Trying to summarize views on induced abortion, contraception, and infanticide throughout the history of Christianity would likely require a book-length treatment and is beyond the scope of this article. However, a basically Aristotlean-Augustinian threshold attitude was popular enough throughout the centuries to become English common law and eventually be codified into laws of the United States.[^gump]

[^gump]: This section's discussion of the history of United States laws pertaining to abortion in the 19th century owes considerably to _Criminal Abortion Laws Across Before the Fourteenth Amendment_ [@gump_criminal_2023].

The threshold that developed in English common law for this purpose was called "quickening." When a pregnant woman first felt movement from the embryo or fetus inside of her, she was said to be "quick with child." This was taken to be the beginning of "perception and life" that Aristotle spoke about so many centuries before, and quickening became the inflection point after which the child was entitled legal protections. 

William Blackstone wrote in the seminal 18th century treatise _Commentaries on the Laws of England:_

> Life is the immediate gift of God, a right inherent by nature in every individual; and it begins in contemplation of law as soon as an infant is able to stir in the mother's womb. For if a woman is quick with child, and by a potion, or otherwise, killeth it in her womb; or if any one beat her, whereby the child dieth in her body, and she is delivered of a dead child; this, though not murder, was by the ancient law homicide or manslaughter. [@blackstone_commentaries_1775, 129]

The United States of America after its creation inherited English common law regarding induced abortion of pregnancy because the several states lacked statute law on the matter. In 1821, Connecticut was the first of the states to enact its own statue regarding induced abortion of pregnancy, and quickening was reaffirmed as the Aristolean-Augustinian threshold for protection of a child:

> Every person who shall, wilfully and maliciously, adminster to, or cause to be administered to, or taken by, any person or persons, any deadly poison, or other noxious and destructive substance, with an intention him, her, or them, thereby to murder, or there to cause or procure miscarriage of any woman, then being quick with child, and shall be thereof duly convicted, shall suffer imprisonment, in newgate prison, during his natural life, or for such other term as the court having cognizance of the offence, shall determine. [@connecticut_public_1824, 96]

Other states followed with similar statutes, also using quickening as an Aristotlean-Augustinian threshold. 

The 19th century, however, was also a time of rapid scientific advance. Karl Ernst von Baer published _Ovi Mammalium et Hominis Genesi_ in 1827 and _Über Entwickelungsgeschichte der Thiere_ in 1828. With greater awareness of the workings of mammalian developmental biology, concepts like quickening were increasingly seen as folk pseudo-knowledge. A select committee report in the Ohio state senate summed up this change in attitude:

> The erroneous opinion has been entertained by the unthinking---and our law has favored the idea---that the life of the foetus commences only with quickening, and hence the conclusion that to destroy the embryo before that period is not child-murder, but only a venial offense. No opinion could be more erroneous. Quickening is generally purely mechanical. The uterus, in consequence of its enlargement, rises from the cavity of the pelvis to that of the abdomen. Hence the sensation of motion.
> 
> The period of quickening is uncertain. Some women are not conscious of foetal motion during the whole period of pregnancy. Others are sensible of it much before the usual time. Physiological researches have demonstrated that it exists in the early stages of utero-gestation, but it is too feeble to be perceived by the mother. The law now is settled, and it has averred, in most pithy and expressive language, that "quick with child is having conceived;" but our statutes have made an unnatural and unscientific distinction. Let it be proclaimed to the world, and let it be impressed upon the conscience of every woman in the land, "that the willful killing of a human being, at any stage of its existence, is murder." [@ohio_journal_1867, 234]

The Ohio senate subcomittee's use of the term "venial" in this context is a rather conspicuous allusion Aristolean-Augustinian doctrine.

Throughout the 18th century, legislatures of the several states of the United States moved away from using quickening as an Aristotlean-Augustinian threshold. Some passed new statutes that simply removed any reference to quickening from the old statute. Maine is notable for having explicitly rejected quickening as a threshold in the text of its new statute:

> Every person, who shall administer to any woman pregnant with child, whether such child be quick or not, any medicine, drug or substance whatever, or shall use or employ any instrument or other means whatever, with intent to destroy such child, and shall thereby destroy such child before its birth, unless the same shall have been done as necessary to preserve the life of the mother, shall be punished by imprisonment in the state prison, not more than five years, or by fine, not exceeding one thousand dollars, and imprisonment in the county jail, not more than one year. [@maine_revised_1840, 686]


### Comstock Laws

While the Aristotlean-Augustinian threshold of quickening was removed from criminal abortion statutes in the 19th century, Augustinian views on sexuality led to statutes prohibiting dissemination of information pertaining to contraception and induced abortion in what would be called the "Comstock laws." A United States Criminal Code bill entitled "An Act for the Suppression of Trade in, and Circulation of, obscene Literature and Articles of immoral Use" passed in 1873 reads:

> _Be it enacted by the Senate and House of Representatives of the United States of America in Congress assembled,_ That whoever, within the District of Columnia or any of the Territories of the United States, or other place within the exclusive jurdisdiction of the United States, ... shall have in his possession, for any such purpose or purposes, any obscene book, pamphlet, paper, writing, advertisement, circular, print, picture, drawing or other representation, figure, or image on or of paper or other material, or any cast, instrument, or other article of an immoral nature, or any drug or medicine, or any article whatever, for the prevention of contraception, or for causing unlawful abortion, ... shall be deemed guilty of a misdemeanor, and, on conviction thereof in any court of the United States having criminal jurisdiction in the District of Columbia, or in any Territory or place within the exclusive jurisdiction of the United States, where such misdemeanor shall have ben committed ; and on conviction theref, he shall be imprisoned at hard labor in the peneitentiary for not less than six months nor more than five years for each offense, or fined not less than one hundred dollars nor more than two thousand dollars, with costs of court. [@sanger_statutes_1873, 598-599]


### Persistence of Abortion into 20th Century

Similarly to how laws criminalizing infanticide did not bring infanticide to an end, induced abortion of pregnancy persisted into the 20th century in the United States as a common occurrence despite it being prohibited. Because it was an underground activity, estimates of how frequently embryos or fetuses were intentionally killed varied wildly. Birth control pioneer Margaret Sanger, speaking in 1918, relates the opinions of the experts she consulted:

> In the very nature of the case, it is impossible to get accurate figures upon the number of abortions performed annually in the United States. It is often said, however, that one in five pregnancies end in abortion. One estimate is that 150,000 occur in the United States each year and that 25,000 women die of the effects of such operations in every twelve months. Dr. William J. Robinson asserts that there are 1,000,000 abortions every year in this country and adds that the estimate is conservative. He quotes Justice John Proctor Clark as saying that there are at least 100,000 in the same length of time in New York City alone.
>
> Dr. Max Hirsch, a famous authority quotes an opinion that there are 2,000,000 abortions in the United States every year!
>
> "I believe" declares Dr. Hirsch, "that I may say without exaggeration that absolutely spontaneous or unprovoked abortions are extremely rare, that a vast majority&mdash;I should estimate it at 80 per cent&mdash;have a criminal origin."
>
> "Our examinations have informed us that the largest number of abortions are performed on married women. This fact brings us to the conclusion that contraceptive measures among the upper classes and the practice of abortion among the lower class, are the real means employed to regulate the number of offspring." [@sanger_birth_1918]

Margaret Sanger lobbied to remove the Comstock laws' prohibitions on contraception with the goal of ending induced abortion as a method of fertility control, a subject given a [full treatment in its own article](/margaret-sanger-on-abortion-in-her-own-words.html). Much as the removal of quickening from criminal abortion laws in the 19th century was a rejection of Aristotlean-Augustinian conceptions of prenatal life, the removal of prohibitions on contraception was the removal of Augustinian doctrine on sexuality from United States obscenity law.


## Induced Abortion is Very Common

Today, there are much more accurate counts of the number of induced abortions occurring every year.

* Chart of abortions in U.S. based on Guttmacher APC numbers
* Lancet paper

![Number of induced abortions of pregnancy in the United States per year, based on the Abortion Provider Census by the Guttmacher Institute.[@maddow-zimet_pregnancies_2022]](/images/Guttmacher_APC_abortion_totals.png){alt="A plot with the number of induced abortions of pregnancy in the United States on the y-axis and the year on the x-axis."}


## Summary

* There has has been a trend toward protecting children from being killed arbitrarily earlier and earlier in their development.
    * Children are property of their father and can be killed arbitrarily
    * Valentinian-era laws forbid infanticide and protect children from birth on
    * Aristotlean-Augustinian attitudes protect fetuses after quickening
    * 19th century rejection of quickening in the wake of modern embryology and obstetrics protects children throughout the entirety of their gestation
* While these efforts were being made by philosophers, theologians, and lawmakers, there was still much killing of children as a form of fertility control. Infanticide and child abandonment persisted for centuries. Abortion was common even after it was criminalized.


## Conservatism of Approval of Abortion

* Very old
* Very common
* Reverses trend


## Conclusion

* There is no golden era to return to. There are just millennia of infanticide, child abandonment, and abortion.
* Deadlock perpetuates abortion. This is particularly relevant when it comes to how to engage with politics, if at all.


## Citations

::: {#refs}
:::


## Footnotes
