---
title: "Category-Based Prejudice"
draft: true
date: 2021-11-19
tags: ["critical thinking", "statistics"]
bibliography: "../bibliographies/category-based-prejudice.bib"
csl: "../bibliographies/chicago-author-date.csl"
link-citations: true
implicit-figures: true
output:
  blogdown::html_page:
    md_extensions: ["+footnotes"]
    toc: true
    toc_depth: 5
include-before: |
  <p>Opening paragraph goes here</p>
  <!--more-->
  ## Table of Contents
---


## Terminology

This article discusses the fallacies associated with judging an individual based on how the individual is categorized. The word "prejudice" can be used to name this practice. However, the word "prejudice" in the English language can be interpreted either too broadly or too narrowly.

For instance, the first definition for "prejudice" in the _American Heritage Dictionary of the English Language_ consists of: "the act or state of holding unreasonable preconceived judgments or convictions." [@pickett_american_2018] This first definition is more broad than how "prejudice" is used in this article; there are many different kinds of prejudice so broadly construed, beyond the specific kind discussed in this article.

The second definition for "prejudice" in the _American Heritage Dictionary of the English Language_ is "irrational suspicion or hatred of a particular social group, such as a race or the adherents of a religion." [@pickett_american_2018] This is similar to how the word "bigotry" is used in contemporary discourse.

This second definition is more narrow than how "prejudice" is used in this article in at least two ways. First, this definition applies specifically to judgments about human beings, whereas the criticisms discussed here apply equally well when reasoning about rocks, single-celled organisms, music, countries, or anything else that can be categorized. Second, this definition construes "prejudice" as referring to judgments that are undesirable, whereas the way "prejudice" is used in this article can refer to judgments about desirable traits, as well.

Because the English language lacks a word with the precise scope desired by this article, the phrase "category-based prejudice" is used.


## Analytical versus Moral Criticism 

The criticisms this article puts forth of category-based prejudice are entirely with regard to the flaws such prejudice imparts on attempts to understand the world. Much can be written about the [moral](/moral-skepticism.html) aspects of category-based prejudice targeting human beings in particular, but writing about the evils of bigotry is not the purpose this article and is instead left to works of social science or history. Instead, this article focuses on criticisms of category-based prejudice as a form of reasoning, regardless of the consequences of such thinking.

Thus, the criticisms articulated here are independent of the moral dimensions of category-based prejudice. This article puts forward the thesis that category-based prejudice is always a flawed way of thinking, even if there does not appear to be anything morally objectionable about it. Indeed, even if one judges an instance of category-based prejudice as morally justified, the fallacies in reasoning discussed in this article persist.


## Abstract Example

* _x_ position
* _y_ position
* shape
* color (continuous or discrete?)
* opacity?
* size?


### Properties of Populations Are Not Properties of Individuals

Example: no individual in a population has the population mean for the response variable. Use a continuous response variable.

Example: no individual in the population has proportions of colors that all shapes in the population do. 


### Categorization Is Arbitrary

Average response variable for one explanatory variable for a given figure is small, but the average response variable for a different explanatory variable is large. Use a continuous response variable.


## Concrete Example: Gender Prejudice in Hiring

In order to illustrate the main flaws with category-based prejudice, this article turns from the abstract to more concrete examples. Suppose that a hiring manager at a company is considering what to look for in the next employee to be hired and is told the next hire should be a woman because the team needs more empathy and women are more empathic. Alternatively, the manager is told to hire a man because the team needs more math ability and men are good at math.

Further suppose in either scenario, the hiring manager has narrowed the search for a new employee to two people, one a woman and one a man. These two prospects seem equally qualified in other respects besides math ability or empathy, and all that remains is to choose between the two prospective employees.


### Direct Measurement

How could such propositions such as whether someone is "good at math" or "more empathic" be evaluated?

Math is a broad subject, and the skill sets for doing arithmetic quickly by hand, for doing university physics problems, or for proving mathematical theorems are all quite different. Those who want more math proficiency are best served to identify exactly what kind of math skills are needed. In so doing, the appropriate test for these math skills might be identified. 

With regard to traits such as empathy, psychologists often spend large amounts of time and effort attempting to devise a test that is reliable (i.e., self-consistent and consistent across various contexts) and valid (i.e., actually measuring what it is supposed to measure). There are various schools of thought and approaches to development of such tests, but overall the goals of these approaches are similar: to devise a method for measuring a psychological property.

What both of these propositions presuppose, then, is that there is some _instrument of measurement_ by which the relevant math skills or empathy traits can be discerned. Otherwise, the propositions are uninformative, pointless speech.

This raises the question: _why not apply the instrument of measurement to the job applicants directly?_

Category-based prejudice involves two steps. The first step is to arrive at more general propositions such as "women are more empathic" or "men are better at math." The second step is to apply the more general proposition to the specific individuals being considered, such as the man and the woman being considered for employment. Invoking knowledge about population attributes when judging individuals thus adds a layer of indirection to the evaluation of specific individuals. 

In the example scenarios, the hiring manager could simply give the two prospective employees the instrument of measurement, determine which is better than the other at empathy or at math, and hire that individual. This can be termed the "direct measurement" approach.

The category-based prejudice approach is inferior to the direct measurement approach in at least three ways:

* arriving at a more general proposition such as "women are more empathic" or "men are better at math" is more costly than directly measuring the individuals being considered,
* applying a more general proposition such as "women are more empathic" or "men are better at math" to the specific individuals is probabilistic at best and thus a weaker conclusion than directly measuring the individuals being considered, and
* the choice of variable used to judge an individual using category-based prejudice is arbitrary, which can lead to ambiguous judgments.



### Additional Cost of Generalization

In order to arrive at a more general conclusion about "men" or "women," several steps need to occur. First, a more precise _target population_ needs to be identified. This might be all the men or women in a certain place and time frame, or perhaps all job applicants to a company. Once the target population is identified, a _sampling frame_ must be devised that can be used to identify each individual in the target population and that allows the target population to be sampled. Once that is accomplished, a _representative sample_ can be selected from the target population. The instrument of measurement can then be applied to each individual in the representative sample, and statistical analysis can done to infer estimates of the relevant values in the target population. Then, the hiring manager would know the relative math abilities or empathy levels of men and women in the population of interest.

This generalization adds additional costs to a judgment: the cost of sampling and the cost of administering the instrument of measurement to every individual in a sample large enough for statistical inference. The exact magnitude of these additional costs vary depending on the details of their circumstances.

In large surveys intended to be nationally representative, the cost of sampling can be the largest cost in the enterprise. When targeting smaller populations, such as the customers of a company, there may be a preexisting records from which it is straightforward to derive a sampling frame, so the cost of sampling would be relatively small. 

The cost of measuring every individual in a representative sample depends, of course, on the sample size. Sample size in turn depends on the variance in the population of the variable of interest, on the minimally detectable difference in the variable that is desired, and on the desired statistical power.[^power]

[^power]: In statistics, "power" has a specific mathematical meaning. It refers to one minus the Type II error rate. The Type II error rate is the probability of failing to reject the null hypothesis when the null hypothesis is indeed false. In statistical inference, drawing a conclusion is framed in terms of rejecting the null hypothesis. Therefore, Type II error rate measures how probable it is for a test to fail to draw a conclusion when a conclusion should have been drawn. Type II error rate can be thought of as the "false negative" rate. The lower the Type II error rate of a statistical test, the more power it has, and the more capable it is at inferring a conclusion.

While the exact amount of these costs might vary, they are costs that are incurred whenever a general conclusion is sought, but not costs incurred in the direct measurement approach.


#### Stereotypes

Of course, in practice category-based prejudice is often done based not on a valid generalization, but on little more than stereotypes stemming from [anecdotes](/anecdotes-are-not-evidence.html) or [selection bias](/selection-bias-and-the-fallacy-of-listing-examples.html). In these cases, there is not additional cost entailed in establishing a more general proposition, because a more general proposition has not actually been established. Thus, using the category-based prejudice approach is not more costly compared to the direct measurement approach when appealing to stereotypes, but these cases are based entirely on fallacies and thus are worthless.


#### Preexisting Studies

It might sometimes be the case that the cost of arriving at a more general proposition such as "women are more empathic" or "men are better at math" is a sunk cost, when such general results have already been established by previous work. These cases do not entail additional cost for the category-based prejudice approach over the direct measurement approach, but the other criticisms described in this article remain.

Furthermore, care must be taken to discern whether the previously established results are indeed applicable. Psychology experiments do not generalize to a larger population when they are based on opportunity samples, such as the samples of 20 or 40 undergraduate student volunteers at the researchers' university often discussed in the psychological literature. Opinion polls done by magazines or web sites that rely on volunteers also do not generalize.[^volunteers]

[^volunteers]: For more discussion of why polls of volunteered responses are unrepresentative, see Chapter 1 of Lohr [-@lohr_sampling_2021].

In studies that do generalize to a larger population, the sampled population of the study might not be the population of interest for the judgment being made. For instance, the hiring manager in the example scenarios is concerned with empathy or math skills in the population of job applicants to a specific company. Results discovered about the math skills of fifth graders in Idaho or the empathy skills of therapists in Massachusetts are likely not relevant for judging job applicants to the company.[^unless] If the sampled population of a study does not contain the population of interest, attempting to apply the study's results to the population of interest is an extrapolation outside the scope of inference of the study, which is fallacious.

[^unless]: The obvious exception would be a company in Massachusetts providing therapy services.


### Weaker Conclusion

Suppose that previous work has established the distribution of empathy scores and math scores in the population of job applicants to the hiring manager's company. If this work is based on sound statistical inference and the sampled population in this research is indeed the population of interest, then the cost of arriving at a more general proposition has already been paid.

However, the conclusion that the hiring manager can reach when applying this information to the two remaining prospective employees is a weaker conclusion than can be reached with the direct measurement approach.

Even if it is the case that the mean empathy score of women is higher than that of men among job applicants or the mean math score of men is higher than that of women among job applicants, this is not directly relevant to the hiring manager's decision. As seen previously, properties of populations are not properties of individuals. What the hiring manager wants to know is whether the specific woman being considered has a higher empathy score than the man being considered or whether the specific man being considered has a higher math score than the women being considered.

What is relevant for the hiring manager's decision is what has come to be called the "probability of superiority." The probability of superiority for the empathy question is the probability that a randomly selected woman from the population of job applicants would have a higher empathy score than a randomly selected man from the population of job applicants. This requires knowledge of the probability density of the two distributions, which the supposition at the beginning of this section assumes is available.[^density]

[^density]: Means are indicators of the central tendency of a distribution, which is just one aspect of the distribution of a variable such as empathy score or math score. Point estimates such as the estimate of a population mean are insufficient to calculate probability of superiority. In order to calculate probability of superiority, one can assume or attempt to establish that the probability density of the variable of interest conforms to some established mathematically defined distributions for which there is a closed form solution for probability of superiority. Alternatively, one could estimate the density empirically, using techniques such as kernel density estimation.

Using this information, the hiring manager could calculate probabilities of superiority, arriving at conclusions such as "a randomly selected woman in the population of job applicants has 68\% chance of having a higher empathy score than a randomly selected man" or "a randomly selected man in the population of job applicants as a 72\% chance of having a higher math score than a randomly selected woman."

If the hiring manager were to use this information to decide between the last two prospective employees, the hiring manager would commit to being wrong 32\% of the time when hiring for empathy based on gender or wrong 28\% of the time when hiring for math ability based on gender.

The given values for the probabilities are just examples, but this nonetheless illustrates why the category-based prejudice approach leads to a weaker conclusion than the direct measurement approach. The conclusion of the category-based prejudice approach is at best probabilistic and so will lead to decisions based on false beliefs for some percentage of the time in the long run.

These weaker, probabilistic conclusion can easily be replaced by stronger, more relevant information by simply applying the instrument of measurement directly to the final two prospective employees that the hiring manager is considering.


#### Individuals Not Randomly Selected

The idea of a randomly selected individual from a population is a useful construct when learning probability theory and statistics. However, in real life scenarios, one rarely ever encounters a randomly selected individual from a population. The final two prospective employees in these example scenarios illustrate this phenomenon.

The prospective employees have applied to this specific job posting and they have gone through a vetting process that may have included interviews and other examinations. They are thus not randomly selected from the population of job applicants. Indeed, if the job posting specifically asked for applicants with empathy skills or with math skills, or if the interviewers were specifically looking for evidence of empathy skills or math skills, there is reason to believe the final two prospective employees might be unusually good in the trait of interest.

Another way of conceiving of this phenomenon is that the true population of interest in these scenarios is not the population of all job applicants to the company, but the population of job applicants to this specific job posting who have made it through all the vetting to become one of the two final prospective employees. This is may be too small of a population to sample for any kind of inference about probability densities.


### Ambiguous Categorization

[...]


## Citations

::: {#refs}
:::


## Footnotes
