---
author: "Joshua Born"
date: 2022-06-03
draft: true
tags: ["book, article, or podcast review", "first-person"]
title: "Discussion about Disagreement on the Rationally Speaking Podcast"
output:
  blogdown::html_page:
    number_sections: false
    toc: true
    toc_depth: 5
include-before: |
  <!--more-->
  ## Table of Contents
---

```{r setup, include=FALSE}
library(here)

i_am('content/discussion-about-disagreement-on-the-rationally-speaking-podcast.Rmd')

knitr::opts_chunk$set(
  echo = FALSE
)
```

* Photos
* Opening paragraph

## Introduction

I stumbled on the [Rationally Speaking Podcast](http://rationallyspeakingpodcast.org/) with Julia Galef in 2020, and it has become my favorite podcast. I discovered it while I was in graduate school, shortly after my mother had died unexpectedly and around the same time that most of us in the United States became shut-ins because of the COVID-19 pandemic. Of course, later throughout this shut-in period, much of the news was dominated by riots and protests.

Ultimately, I disabled all my social media accounts because I had found that the state of discourse on social media was so terrible that all I was doing by even having social media accounts was providing a platform for the most facile social commentary imaginable. By enabling the worst of us, social media de-platforms the kind of discourse I actually value, drowning it out with the din of [slogans](/political-rhetoric-as-shibboleths.html), ideology, and snark.

Rationally Speaking was a ray of sunshine in what was then a dark time for me intellectually. It sounds corny now when reflecting upon it, but I realize I had tacitly stopped believing that there was _any_ thoughtful, nuanced, self-critical discourse out there. Rationally Speaking reminded me that the best parts of the human intellect -- though rarely -- do still show themselves from time to time.

Though I am sure I disagree with host Julia Galef on issues I am passionate about, I still respect her intellectually. Granted, this is because much of the framework of _how_ she thinks and the framework of _how_ I think overlap. She puts into words the sort of questions I would ask, she makes comments and criticisms similar to those I would make, and she frames discussion in ways that I would frame. But more than this, I respect her intellectually despite what disagreement we might have _because she disagrees well._

Indeed, I have said a few times that if I lived in a world of people who disagree as well as Julia Galef, I would be much more open about my views, mostly because I would walk away from a disagreement having become a better thinker, not a worse one.

These days, it seems like the Rationally Speaking Podcast is either on break or finished,[^break] so I have been going through some of the back catalog. Recently, I listened to two episodes back-to-back that were about the very thing that the podcast itself handles so well, i.e., disagreement:

* [Episode 229](http://rationallyspeakingpodcast.org/229-erisology-the-study-of-disagreement-john-nerst/) "Erisology, the study of disagreement (John Nerst)" and
* [Episode 244](http://rationallyspeakingpodcast.org/244-seeing-other-perspectives-with-compassion-stephanie-lepp-buster-benson/) "Seeing other perspectives, with compassion (Stephanie Lepp & Buster Benson)".

[^break]: Apparently, the podcast has taken extended breaks in the past, for instance, when host Julia Galef focused on working on her book.


## Low Resolution Abstraction

Episode 229 of Rationally Speaking consists of an interview with John Nerst, who has coined the neologism of "erisology" to label his studies of disagreement. John Nerst has an engineering degree, but his school's curriculum was unusual in that it had a strong humanities component, which is how he got his interests in broader topics outside of engineering.

The thing that really stuck out for me from this interview is the concept of "low resolution" in disagreement:

> I mean, of course, people disagree about things that have right and wrong answers like math theorems or what's the capital of Spain, which have these ... these questions have real answers. But those aren't really interesting disagreements. They don't cause any sort of chaos, they don't erode the public's fear or damages the public debate or anything like that. They’re very simple. We don't need an elaborate theoretical construction to deal with those.
> 
> In most cases what we're dealing with when we're dealing with a disagreement, people are disagreeing because they each have adopted a very low resolution belief, like something very abstract and general. If somebody believes “the capitalist class is exploiting the workers” and the other person thinks “we must let entrepreneurs create wealth for all of us,” or something like that. Those are very, very abstract beliefs. They don't really get proved or disproved, because none of them map onto reality in any simple way, in a straightforward way. They're more stories than they are beliefs.
> 
> And I think many of the things that people disagree about in the most complicated ways, they are beliefs more of this kind. Very low resolution, very abstracted, more story-like than fact-like. So that's a big misunderstanding, I think.
> 
> When you get beliefs like that, they’re not true or false -- they are typically
kind of true, or kind of valid. True or false doesn't even apply to them
exactly. ...

This does appear to explain many types of disagreement. I would hesitate to call these kinds of things "beliefs," however, because calling them "beliefs" is giving them too much credit. Indeed, John Nerst himself says that these low resolution ideas are "more stories than they are beliefs." Therefore, I have taken to calling this kind of thing "low resolution abstraction."

John Nerst's description of low resolution abstraction sounds like my description of the [fallacy of generic thinking](/fallacy-of-generic-thinking.html). Indeed, the observation that this low resolution abstraction defies truth conditions, i.e., "true or false doesn't even apply to them exactly," is one of my main criticisms of generic thinking.

However, I consider low resolution abstraction to be a superset of generic thinking. Yes, the parts of low resolution abstraction that claim to describe the world are probably generic thinking. For instance, "the capitalist class" is a label that describes millions of people, and the sentence "the capitalist class is exploiting the workers" is basically a generic generalization: it does not quantify how many of the people denoted by "capitalist class" it is applying its predicate to. It therefore comes with all the flaws of generic thinking that make generic thinking worthless to me.

That being said, there is another issue with low resolution abstraction beyond generic thinking: low resolution abstraction mixes descriptive and normative ideas to the point where the person doing the ideating probably is not clear about which parts are descriptive and which parts are normative. When someone says "we must let entrepreneurs create wealth," there is a component that is descriptive, i.e., that entrepreneurship has a certain economic effect described as "creating wealth," and there is a component that is normative, i.e., that "we must let" this happen because it is good.

Similarly, saying "the capitalist class is exploiting the workers" is not just a description of an economic relationship between "the capitalist class" and "the workers." It is as much a normative judgment that any such relationship is _bad,_ as the connotations of "exploiting" in this context allude to.

Thus, when there is disagreement due to conflicts in low resolution abstraction, there is probably mixing of descriptive beliefs and normative sentiments. This should not be surprising because we must do work to separate the two kinds of sentiments ourselves since natural language tends to mix the two, as I described in my article on [moral skepticism](/moral-skepticism.html).

Therefore, there are (at least) two ways in which "true or false doesn't even apply to" low resolution abstraction:

* low resolution abstraction lacks truth conditions when the part of it that is descriptive consists of generic thinking, and
* low resolution abstraction lacks truth conditions when it mixes normative sentiments with descriptive beliefs for the part of it that is normative, since normative sentiments themselves lack truth conditions.


### In Poor Survey Questions

In the interview, John Nerst expressed a frustration, which I have as well, at survey questions that are too low resolution:

> I'm often very disappointed in how surveys are done, and the sort of questions that they have. Because as I said before, our beliefs are often very low-res, and survey questions are often extremely low-res. It's often the fact that I'm thinking, "What does this even mean?"

This is something I experienced when reading _[The Hidden Tribes of America](https://hiddentribes.us/),_ a report on a survey which attempts to explore the phenomenon of binary partisan polarization. This is a subject that is very near and dear to my heart. For instance, the (not so subtle) subtext of my article on [Margaret Sanger's views on abortion](/margaret-sanger-on-abortion-in-her-own-words.html) is a prolonged criticism of binary polarization.

However, while I liked the intent and some of the broader conclusions of _Hidden Tribes,_ I was frustrated that most of the survey questions were so low resolution that they were basically meaningless to me.[^other] For instance, the report makes much of that both "82 percent of Americans agree that hate speech is a problem in America today, but 80 percent also believe that political correctness has gone too far." _Hidden Tribes_ likes to contrast these results, but both of these propositions are so low resolution that it is anyone's guess what the people who agreed with either proposition were thinking when they agreed.

When _Hidden Tribes_ does formulate a question well, the question is high resolution enough to have actual policy ramifications. For instance,

> ... a full 85 percent also believe that race should not be considered in decisions on college admissions. By contrast, only 40 percent of Progressive Activists believe race should not be considered in college admissions decisions.

In contrast to lower resolution questions, this is perhaps indicative of a genuine split between those categorized as "Progressive Activists" and the rest of the country.

[^other]: I have other criticisms as well. One is just a general (and rightful) skepticism of surveys of [non-probability samples](/how-to-scrutinize-a-statistic.html#sampling). Other criticisms include the amount of junk ornamenting the actual results, such as "profiles" (i.e., stereotypes) of the various categories, quotes from respondents scattered throughout the text of the report, etc.

However, if someone were to ask me whether I agree with either "many people nowadays don't take racism seriously enough" or "many people nowadays are too sensitive about things to do with race," I would not answer the question, responding instead with my criticisms of the question itself.[^criticisms] Indeed, such a question might actually make me angry at how the dumb the question is.

[^criticisms]: The criticisms are exactly what I have articulated here viz a viz generic thinking and mixing of descriptive and normative sentiments.


### Differing Attitudes Toward

John Nerst and I would agree that in low resolution disagreements, people appear to be disagreeing not about the facts of any given matter, but about what ideologies and narratives to which they subscribe. However, we would disagree on how we deal with this.

John Nerst takes a more conciliatory attitude. At the end of his "exploits workers" versus "creates wealth" example, he says:

> ... So we need to understand that proving that you yourself are correct, doesn't mean that the other person is wrong, and vice versa.

Later, he explains further:

> What I think one should do, and what I try to do, is to learn how to look at things in different ways. There is this model here, and it generalizes reality in this way, or compresses reality in this way; and there's this other model that focuses on getting these very different features right. And when you're trying to get different features and describe them accurately, you're going to use a different set of rules, and abstract them in a different way.
> 
> There are many kinds of different belief systems that capture different parts of reality or the human experience, not as well. Some belief systems, they capture some things well and not others, and for other belief systems it's the other way around. So that's why you need to collect so many of them. You really should not have just one.

Thus, John Nerst looks as these low resolution disagreements as two different mental models interacting in a way that is incompatible, and his solution is to accumulate more low resolution abstraction so that he can use whichever mental model is best for the specific job at hand.

Therefore, if both sides took the John Nerst approach to the "exploits workers" versus "creates wealth" disagreement, they would simply absorb each other's mental models as alternatives to the one they are using, then explore what the new mental model is good for.

This also informs John Nerst's approach to survey questions:

> I would like to work on ways to improve how surveys work. Write questions in such a way that you will make it possible for people with different sort of internal abstractions to answer them. And maybe write, "Oh this question does not match the structure of my head, it doesn't fit into anything where I can produce a yes or no answer." Because yeah, you can say if you agree or disagree with an issue, and with a question or a statement, or anything like that -- and sometimes when you do political quizzes, you can also answer, "I think this is very important, or this is not important." That's also a big dimension that people have been ignoring.
> 
> I miss an option that says, "This question does not make sense to me."

Thus, the main issue John Nerst takes with low resolution survey questions is that they might not fit a particular respondent's low resolution abstraction.

I take a decidedly different attitude toward low resolution abstraction. As might be guessed from my attitude toward generic thinking, to me, it is not that having _different_ low resolution abstractions creates a problem, it is that low resolution abstraction is _itself_ the problem. I think we should simply do away with low resolution abstraction, especially when it comes to social issues.

I think it is possible to police your own mind to check against generic thinking, and it is possible to be cognizant of when you are making a descriptive claim versus when you are expressing a normative sentiment. Perhaps this cannot be done with 100\% perfection, but the impossibility of perfection should not be an excuse for contentment with something that is worse.

Furthermore, when I encounter people who do not practice such self-skepticism and instead have debates such as "the capitalist class is exploiting the workers" versus "we must let entrepreneurs create wealth for all of use," I just want them to stop having such a facile debate and start thinking more rigorously. There is nothing about this way of thinking that makes me want to internalize it. My honest assessment is that I simply do not have anything to learn from such low resolution abstraction.


## Productive Disagreement

Episode 244 of Rationally Speaking actually consists of two interviews. I frankly did not find the first interview with Stephanie Lepp, host of the Reckonings Podcast, to be very enlightening. The Reckonings Podcast focuses on particular human-interest type stories, such as a former Neo-Nazi or a reformed sex offender. I also had the suspicion that the podcast was biased in recognizing "reckonings" that were in accord with viewpoints associated with left-wing partisanship, something that Stephanie Lepp herself admitted. For instance, she has had episodes about people who switched from being opposed to induced abortion of pregnancy to being in favor of it, but not the other way around.

On the other hand, the second interview of Episode 244 with Buster Benson, author of _Why Are We Yelling? The Art of Productive Disagreement,_ I did find to be enlightening.


### Redirection to "Win" a Disagreement

In particular, I found Buster Benson's self-criticism over an incident in which he argued with his wife to be insightful. The high-level summary of the incident is that Buster Benson's wife wanted him to contribute more to the parenting of their son. The disagreement began because Buster Benson's wife felt like he was not "willing to pick up the slack" of parenting. However, in the process of arguing over this, the discussion diverged into an argument over whether it was illegal or not to leave their son at home when school was closed.

At first, Julia Galef expressed sympathy for this latter argument, saying:

> But in another sense... it does seem not great to me if someone is arguing something that's literally false, and they don't care that it's literally false. Your wife was wrong about the legal fact of the matter, right? It seems not great for someone to be saying, "It's illegal," when what they really mean is, "I wish you would pick up more of the slack."[^legal]

[^legal]: As an aside, I actually do not consider legal questions to be factual questions. Law itself is a social fiction. It is something made up by legislatures, judges, and juries. Laws are open to a lot of interpretation, and the actual results of any given case can be different based on the lawyers involved and the tactics used. This is in contrast to scientific theories which, while in some sense are also made up by humans, seek to model an external reality and so are bounded by their ability to model the empirical phenomena, rather than the whims of lawyers' maneuvers.

Buster Benson's explanation was refreshingly self-aware:

> ... I forced her into that corner. I brought up the legal aspect, because in my attempt to win, or my attempt to resolve the argument, I introduced this new argument that I could win.
> 
> Then she fell for it, and then I won, but by winning I only proved more so that I was not a good husband.
> 
> So, I think it's my responsibility as well to not necessarily force people to have arguments that I'm advantaged at winning. After the fact we can resolve that, because it wasn't really critical to our lives. Even if it was legal or not legal, it wouldn't really change whether or not we should leave him at home.
> 
> But I have to take responsibility for the fact that I collapsed into something that I was better at winning. I think that's what was hard for me to see until I saw it -- and then I saw it everywhere, that we do this all the time.

If we are motivated to "win" an argument, we might try to redirect discussion into a true-or-false question that we have more knowledge about. However, doing so completely ignores the original disagreement and thus dodges whatever concerns led to the original disagreement.

There are many issues with this practice. I am skeptical of the motives of anyone who goes into a disagreement with a desire to "win" as if the disagreement were a high school debate competition. I am not sure what anyone "wins" in these kind of encounters, but whatever is won is not something that I value.

But beyond this, there is the issue that a lot of disagreement is not due to disagreement over true-or-false questions. Indeed, Buster Benson's wife just wanted him to contribute more as a parent. This is not a descriptive, true-or-false question, but a normative sentiment. Thus, the original disagreement was over a value judgment, and value judgments are subjective evaluations of goodness or badness of a state of affairs.

In disagreements over value judgments, it is not the case that one person is "right" and the other one is "wrong" like when two people have contradictory descriptive beliefs, but it is the case that two people feel differently about the same state of affairs. Before their discussion, Buster Benson was content with the level of parenting he was contributing to the family, and his wife was not content with his contribution.

This is a relatively minor disagreement in value judgments, but a similar phenomenon occurs with much more contentious issues, such as induced abortion of pregnancy, capital punishment, or slaughtering of animals for human consumption.

I occasionally encounter such comments. Sometimes other people respond to moral compunction at the killing of human fetuses as a method of fertility control with whatever developmental biology information they have picked up. Such individuals are the sort who start talking about the neurological capacity to sense pain or perceive the outside world or the viability of fetuses outside a womb, etc.

These are not genuine attempts to provide others with information. Implicit in most of these comments is the proposition that moral sentiments about killing fetuses should _hinge_ or _turn_ on the facts being shared, and unsurprisingly, the way this is framed is such that the information being volunteered leads to the conclusion that killing fetuses is fine. These are attempts to redirect a disagreement that is over value judgments into a disagreement over true-or-false, descriptive beliefs so that person doing the redirection can "win."

As it turns out, my moral sentiments are not contingent on whatever information these other people volunteer to me. (As it so happens, I too took developmental biology in university and got an "A" in the class, so facts about gastrulation or notochords or whatever are things I have heard before.) Indeed, if my moral sentiments were contingent on such things, I would have long ago investigated the relevant information, so these comments are predicated an the assumption that I cannot myself find out information relevant to me.

Perhaps, though, that is the point of this tactic. Those who would volunteer information have the condescension that those who disagree with them in moral sentiments are ignorant, and if everyone would just learn the facts they know, then everyone would agree with their moral sentiments. I suppose this is easier to live with than to face the reality of moral disagreements occurring when different people have the same information.

This attitude, though, is just self-delusional, arrogant stupidity. I am self-aware enough to realize that my moral sentiments, like all value judgments, are just how I feel about matters, and others might feel differently about the same matters, even in light of the same information.

The only thing I really learn from encountering people with such an arrogant attitude that their reaction to a moral disagreement is to start volunteering information is that they are not self-aware enough for discourse on moral disagreement. Thus, I find it prudent to confine such discourse to individuals of the caliber of Julia Galef, Coleman Hughes, Jonathan Haidt, et al.[^guests]

[^guests]: Coleman Hughes and Jonathan Haidt are two individuals who are also exceptional at disagreeing well and who have been interviewed on the Rationally Speaking Podcast.

    I first learned of Coleman Hughes while listening to [Episode 249](http://rationallyspeakingpodcast.org/249-the-case-for-racial-colorblindness-coleman-hughes/) "The case for racial colorblindness" during which he displays a striking amount of self-awareness and intelligence in handling disagreement for someone at such a young age.

    I had read some of Jonathan Haidt's work previously and would recommend it, though I think his work on social intuitionism (which is basically the application of motivated reasoning research and social cognition research to moral psychology)  is more profound than his work on moral foundations (which is an attempt to categorize the various flavors of moral sentiment), and lately he seems to be featuring his moral foundations work. Jonathan Haidt was interviewed on another disagreement-themed episode of Rationally Speaking, [Episode 252](http://rationallyspeakingpodcast.org/252-understanding-moral-disagreements-jonathan-haidt/) "Understanding moral disagreements."


### Anger Loves Company

Another interesting point that came up in the conversation between Julia Galef and Buster Benson had to do with the emotional experience of disagreement. In particular, Buster Benson noted that he realizes sometimes his friends get angry at him for not getting angry when they get angry.

> ... I can come across as smug, I think. Because if I don't get angry at the right times, then it can be like, "Oh, you don't have to get angry? You think you're better than me?" You know, that kind of thing.

Julia Galef found this curious, asking:

> Oh, interesting. Do you mean like, in an argument where the person's angry at you, or they're angry about an issue in the world, they want you to be angry about too?

To this question, Buster Benson answered, "Both." This was surprising to Julia Galef, who said:

> Oh man. That seems really difficult, if a person interprets lack of anger as a sign that you think they're better than them...

When asked by Buster Benson if she has never experienced this, Julia Galef replied:

> I think I just choose people for my life that... I just have various picky, idiosyncratic criteria for the kind of people who I would be close enough to, to get in an argument with.

This struck me as insightful because I had a similar reaction to Julia Galef: this behavior in which someone gets angry at you for not getting angry is frustrating to me to the point where I find it not worth engaging with such people. While this point came up in the context of interpersonal relationships, I found it helpful for understanding why I found all the protesting, both of the left-wing and right-wing varieties, so distasteful.

Indeed, I remember in my youth having my first substantial encounter with a protester. I was going to a local shopping mall, and apparently the Macy's department store employees were on strike and picketing the store. In shopping malls in the United States, department stores are often considered the "anchor stores" of the mall and placed toward the exterior of the shopping mall. I was not going to shop at Macy's, but I was going to stores or restaurants in the interior of the shopping mall. To do so, I had to walk _through_ Macy's to get to the inside of the shopping mall.

Most people just ignored the protesters and walked by without acknowledging the protesters in any way. In my naivety, I thought I might have an intelligent conversation with them. As I walked by, one yelled at me something to the effect of "boycott Macy's!" I remember stopping, turning toward the protester, and saying calmly, "I'm not going to Macy's. I'm just going to the mall on the other side of Macy's." The protester just sneered back at me and turned away, preparing to yell at the next person walking by.

I remember very distinctly standing there for a moment really taken by the stupidity of this person. In retrospect, the protester was not interested in -- and perhaps even capable of having -- an intelligent conversation. This protester was just angry at me at for not sharing in their anger and, indeed, wanted to express this anger to all those who happened to walk by.

This complete inability to communicate or behave like an intelligent life-form is a huge part of why protests are such a non-starter for me.[^riots] In retrospect, I think it is a big part of why I have disconnected from social media, as well: the standards of discourse on social media are around the same impoverished levels of discourse I had with that Macy's protester so many years ago.

[^riots]: Obviously, when protests escalate to riots and people are actually being murdered, harmed in their person, or harmed by having their property destroyed, there are larger issues than this more intellectual concern.

I suppose I am more like Julia Galef and less like Buster Benson. Buster Benson believes that he is "definitely surrounded by people that are not, would not identify as being rational, logical people" and wants to maintain relationships with his friends. Whereas I, like Julia Galef, have "criteria for the kind of people who I would be close enough to, to get in an argument with."


## Conclusion

Both Julia Galef's interviews of John Nerst and of Buster Benson were insightful for me with regard to my attitudes toward disagreement.

John Nerst identified a problem -- low resolution abstraction -- that I also grapple with, but his idea of a solution to the problem is quite different from mine: he would add different kinds of low resolution abstractions to his thinking in order to try viewing things through different paradigms, whereas I try to do away with low resolution abstraction from my thinking as much as possible.

Buster Benson discussed two phenomena that at first might seem opposite. On the one hand, he noted his own redirection of a disagreement toward a different question -- one that was descriptive rather than a value judgment -- in order to "win" the disagreement. This could be viewed as a fallacy of making a disagreement more intellectual and less emotional. On the other hand, he noted his friends' anger at his lack of anger. This could be viewed as a fallacy of making a disagreement less intellectual and more emotional.

However, it is not the case that there is a "correct" amount of intellectual or emotional components of a disagreement and that Buster Benson is striving to find a sweet spot. Disagreement can involve disagreement in value judgments or disagreement in descriptive beliefs, and it is important to recognize when there is disagreement in one or the other or both and to handle them appropriately. Both of Buster Benson's anecdotes illustrate such a failure. Furthermore, they are both indicative of an even more fundamental failing. In both cases, people are operating from a position of naive solipsism, i.e., acting if their own selves were the only things that existed.

When Buster Benson redirected the disagreement about his parental contribution to another disagreement he could "win," he acted as if only his knowledge and, implicitly, only his values were relevant to the disagreement. When the Macy's protester yelled and sneered at all those walking by without stopping to wonder who they were or where they were going, he acted as if only his knowledge and only his values were relevant.

This gets at a fundamental issue that makes disagreement unproductive. Just as it takes two to disagree, it takes two people to disagree _well._ In these kinds of unproductive disagreements, at least one person is not actually cognizant of the other's value judgments or descriptive beliefs. Thus, they are talking past each other. This, compounded by the desire to "win" or to express anger, leads to an inability to communicate.

Perhaps this is what John Nerst is getting at when he tries to internalize additional low resolution abstractions; he is trying to see things from the perspective of the person with whom he is disagreeing. However, I would contend, you do not need the low resolution abstraction to do this. The low resolution abstraction, in my view, is a crutch that people use to avoid discussing their value judgments and descriptive beliefs directly. Oftentimes this crutch comes with it the added expense of fallacies like generic thinking. You can have productive disagreement with someone by skipping the low resolution abstraction and learning about their value judgments and descriptive beliefs.

Hearing others discuss how they have grappled with disagreement on the Rationally Speaking Podcast, interviewed by a host who herself is adept at disagreeing well, has aided me in understanding our tendencies when we disagree badly. Of course, you might disagree.


## Footnotes
