---
title: "The Fallacy of Listing Confirmatory Examples"
draft: true
#date: 2018-11-11
tags: ["fallacies", "third-person"]
#bibliography: "../bibliographies/anecdotes-are-not-evidence.bib"
#csl: "../bibliographies/apa.csl"
link-citations: true
implicit-figures: true
output:
  blogdown::html_page:
    md_extensions: ["+footnotes"]
    toc: true
    toc_depth: 5
include-before: |
  <p></p>
  <!--more-->
  ## Table of Contents
---

## Example Scenario

For instance, suppose there is a fear that a popular cooking appliance, the Acme Z341 electric grill, is a fire hazard. In this case, there is a desire to determine whether there is an association between the use of the Acme Z341 grill and residential fire incidents.

Perhaps suspicion of the Acme Z341 grill stems from testimonials of several recent residential fire victims, who report that they possessed Acme Z341 grills, or perhaps suspicion is cast on the Acme Z341 because of the reports of several firefighters who recall seeing the Acme Z341 grill often present at the scene of recent residential fires.[^anecdotes]

[^anecdotes]: These would be examples of anecdotal evidence.

![
_Firefighters at the scene of a house fire._<br/>
["House fire"](https://www.flickr.com/photos/39195806@N04/5044281763)
by
[Ada Be](https://www.flickr.com/photos/adambelles/)
is licensed under
[CC BY 2.0](https://creativecommons.org/licenses/by/2.0/)
and is not modified.
](/images/house-fire.jpg)

Regardless of the origin of the suspicion, it might seem an obvious course of action to find examples and make a list of cases in which there was a residential fire and in which there was an Acme Z341 grill in the residence.

Suppose that an investigation results in a list of a hundred incidents of residential fires in which Acme Z341 grills were present. Some of the fires on this list were extinguished quickly and resulted in minimal property damage. Some of the fires, however, come with stories of loss of property. Some of the fires on the list might include emotionally heart-wrenching tales of the loss of a loved one.

After going through several dozen examples, one can imagine the audience of such a list glazing over as the examples start to pile up. Such an audience learns of so many fires, so many Acme Z341 grills, that it loses count, and all the examples star to blur together. Only the emotional weight of the sheer number of examples and all the stories of loss would remain. This might be a persuasive experience for many in the audience.

The practice of making a list of examples of confirmatory cases in which two things are alleged to be associated, as the above thought experiment illustrates, can leave a powerful impression. Unfortunately, such a list proves absolutely nothing.

These lists of confirmatory examples are nothing more than extended exercises in confirmation bias. Whenever such a list of examples is produced, no conclusion can be drawn. One learns nothing by assembling such a list. This is a fallacious practice, and it ought to be avoided.


## 2 by 2 Contingency Table

In order to see the fallacy of such a practice, one need first consider the implications of the hypothesis being considered. Returning to the Acme grill example, the hypothesis being investigated is that possession of an Acme Z341 grill increases a household's risk of fire.[^converse]

If that were the case, at the very least, it would be expected that the proportion of homes with an Acme Z341 grill that experience a fire would be greater than the proportion of homes without an Acme Z341 grill that experience a fire.

For instance, if 3.12% of homes that do not have an Acme Z341 grill experience fires in a given time period, then it would be expected that, all other things being equal, _more than_ 3.12% of homes that do have an Acme Z341 grill would experience fires in the same time period, if indeed the Acme Z341 grill were a fire hazard.

[^converse]: It could also be the case that residential fires and possession of an Acme Z341 grill are associated because of the converse relationship: the risk of residential fire explains an increased probability that a household has an Acme Z341 grill. For instance, this could arise if poorer households have an increased risk of fire, and the Acme Z341 is cheaper than other grills and so popular among poorer households. However, for the purposes of this example, any association between the two is framed as possession of the Acme Z341 grill explaining prevelance of residential fires.

There are four unknowns that must become knowns in order to calculate the two proportions. This can be illustrated by creation of a table. This sort of table of counts is often called a "contingency table."

<table>
  <thead>
    <tr class="question-row">
      <th class="blank"></th>
      <th class="blank"></th>
      <th class="column-question" colspan=2>Acme Z341?</th>
    </tr>
    <tr>
      <th class="blank"></th>
      <th class="blank"></th>
      <th class="column-label">Yes</th>
      <th class="column-label">No</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th class="row-question" rowspan=2>Fire?</th>
      <td class="row-label">Yes</td>
      <td class="count">&ge; 100</td>
      <td class="count">&nbsp;</td>
    </tr>
    <tr>
      <td class="row-label">No</td>
      <td class="count">&nbsp;</td>
      <td class="count">&nbsp;</td>
    </tr>
  </tbody>
  <caption><strong>Table 1:</strong> A 2 by 2 contingency table with information from the list of confirmatory examples.</caption>
</table>

The body of the table contains counts of households. The rows separate these counts into households that have experienced a fire and households that have not. The columns separate the counts into households that have Acme Z341 grills and households that do not.

In order to find the proportion of homes with an Acme Z341 grill that experience a fire, one would divide the upper left cell by the sum of the upper row. In order to find the proportion of homes without an Acme Z341 grill that experience a fire, one would divide the lower left cell by the sum of the lower row.

Table 1 is filled in with all the information gleaned from the list of confirmatory examples. The upper left cell contains "&ge; 100" because it is known from the list that there are at least 100 homes with the Acme Z341 grill that had fires, and _that is it._

The emptiness of the contingency table illustrates the emptiness of the information that comes from making a list of confirmatory examples. In this case, it is not known how many households that have an Acme Z341 have not had a fire (upper right cell), so it is not known what proportion of households with Acme Z341 grills experience fires. It also not known how many households without Acme Z341 grills have experienced fires (lower left cell) and have not experienced fires (lower right cell), so it is not known what proportion of households without Acme Z341 grills experience fires.

Thus, there is no way to check if the proportion of residential fires is greater among households with the Acme Z341 grill than among households without it.


## Selection Bias in Sampling




## Falsification Principle

## Citations

::: {#refs}
:::


## Footnotes
