---
draft: true
title: "The Fallacy of Generic Generalization"
date: '`r format(Sys.Date(), "%Y-%m-%d")`'
tags: ["fallacy", "third-person"]
csl: "../bibliographies/apa.csl"
link-citations: true
implicit-figures: true
output:
  blogdown::html_page:
    md_extensions: ["+footnotes"]
    toc: false
    toc_depth: 5
---


A generic generalization is a belief about a population of numerous individuals, but that lacks quantification. Such beliefs are too imprecise to constitute knowledge. However, unlike other fallacies that might lead to patently false beliefs, a generic generalization is too imprecise to be evaluated as either true or false. Thus, generic generalizations constitute a particularly pernicious kind of fallacy.


<!--more-->


## Examples and Definition

> My friend Leslie got an 'A' on the exam.

> Some students got an 'A' on the exam.

> All students got an 'A' on the exam.

> Most students got an 'A' on the exam.

> 70.97% of students got an 'A' on the exam.

> Students got an 'A' on the exam.

> Cagots are dirty liars.


## Why This Is a Fallacy


### The Psychology of Generic Generalization

* Asymmetric interpretation of scope of generic generalizations


## How To Avoid This Fallacy


### In One's Own Thinking

All true beliefs about a population of individuals necessarily describe a distribution.


#### Philosophical Attempts to Rescue the Semantics of Generic Generalizations


### In Others' Thinking


## Inline Citations

::: {#refs}
:::


## Footnotes
