---
title: "Moral Skepticism"
draft: false
date: 2020-12-28
tags: ["worldview", "morality"]
bibliography: "../bibliographies/moral-skepticism.bib"
csl: "../bibliographies/apa.csl"
link-citations: true
implicit-figures: true
output:
  blogdown::html_page:
    md_extensions: ["+footnotes"]
    toc: true
    toc_depth: 5
include-before: |
  <p>Much of moral philosophy construes morality as a search for truths and moral knowledge, and much of everyday moralizing consists of handwringing over "justice," "human rights," etc. This article disabuses morality of these delusions by examining differences between descriptive and normative mental models, leading to the implication that truth and falsity apply to the former, but not the latter. This in turn implies practices for dealing with moral sentiments, including the rejection of moral constructs as fictitious.</p>
  <!--more-->
  ## Table of Contents
---

## Descriptive versus Normative Mental Models

### Truth or Falsity

The words "true" and "false" are symbols, and symbols can be used in a variety of ways. The definition of "truth" used here is different than that used by those who say "speak your truth" to denote things that are subjectively important to someone. Instead, "truth" is used here to describe a relationship between a mental model and the external world.[^external]

[^external]: This article uses the phrase "external world" to denote everything in the cosmos except for the contents of a _specific_ mind.

A mind might have a belief, which is a representation of how the mind perceives the external world. When a belief accurately models the external world, it is a _true_ belief. When a belief and the external world are not in agreement, this is a _false_ belief.[^correspondence]

[^correspondence]: This is a correspondence definition of truth, which is a kind of truth also called _"a posteriori,"_ "synthetic," "contingent", or "matters of fact." There are also coherence definitions of truth, which in philosophical jargon are called _"a priori,"_ "analytic," "necessary," or "relations of ideas." This latter kind of truth comprises things that are true by definition, such as "1 + 1 = 2" or "bachelors are unmarried men." These kinds of true beliefs are _tautologies_, i.e., they refer to the same thing twice. This kind of tautology is only more interesting than more obvious tautologies like "2 = 2" or "bachelors are bachelors" inasmuch as they refer to the same thing with different symbols. This article regards tautologies as not useful for understanding morality because they merely beg the question. For instance, if one were to be questioned as why one felt that murder is wrong, and one replied "because I have defined 'wrong' that way," this would not be informative.

Beliefs are, in practice, rarely true or false in isolation. In order to examine truth or falsity, many interrelated beliefs are examined at once. For instance, if someone believes that a certain backpack weighs approximately 10 kilograms, other beliefs must also be held in order to examine whether this belief about the backpack is true or false. These other beliefs include, for instance, the belief that heavier objects tip a balance lower when placed opposite lighter objects.

Because of this, instead of truth or falsity being discussed as properties of individual beliefs, this inquiry examines truth and falsity as properties of a _mental model_. A mental model includes a particular belief and all the other related beliefs necessary in order to test this belief. This kind of mental model is _descriptive,_ in that it attempts to model how things actually are.

![
_**Figure 1:** Two diagrams illustrating conditions for truth, in which mental models correspond to the external world. The left diagram illustrates an individual who believes that a certain backpack weighs 10 kilograms when it indeed does weigh 10 kilograms, and the right diagram illustrates an individual who believes that the backpack weighs greater than 10 kilograms when it does indeed weigh greater than 10 kilograms._
](/images/two-true-beliefs-2.svg)

![
_**Figure 2:** Two diagrams illustrating conditions for falsity, in which mental models fail to correspond to the external world. The left diagram illustrates an individual who believes that a certain backpack weighs greater than 10 kilograms when it actually weighs 10 kilograms, and the right diagram illustrates an individual who believes that the backpack weighs 10 kilograms when it actually weighs greater than 10 kilograms._
](/images/two-false-beliefs-2.svg)

### Belief Revision

A common definition of knowledge is justified, true belief. Thus, if a mental model is true, and if the mind that has the mental model has a justification for it in the form of evidence, then the mind _knows_ something about the external world.

No mind ever has complete and perfect knowledge of the external world. Therefore, it is prudent for a sound mind to allow for revision of its mental models. Descriptive mental models try to explain and predict phenomena in the external world. However, the explanations and predictions of _false_ mental models are flawed, and a sound mind will always try to amend false mental models in order to make them true.

For instance, mental models illustrated in Figure 2 are flawed. In the first case, an individual might abstain from attempting to carry a backpack that was within the individual's ability to carry. In the second case, an individual might attempt to carry a backpack that is greater than the individual's capacity. On the other hand, the individual in either of the cases illustrated in Figure 1 can make correctly informed decisions about the backpack.

The totality of the external world cannot, in practice, be observed by any given mind. Some specific circumstances of the external world can, however, be partially observed. These observations constitute _empirical evidence._

When a mind encounters empirical evidence that is consistent with a descriptive mental model, then it is prudent for the mental model to persist. _When a mind encounters evidence that contradicts a descriptive mental model, then it is prudent for the mental model to be amended_ in order to better agree with the external world, such as in Figure 3. Thus, empirical evidence prompts the revision of false beliefs to better approximate true beliefs.

![
_**Figure 3:** A diagram illustrating belief revision, in which a mental model is changed to agree with the external world after empirical evidence is observed. The left panel illustrates an individual who believes a backpack weighs 10 kilograms. The middle panel illustrates the same individual has now seen the backpack tip a scale when opposite a 10-kilogram weight. The right panel illustrates the individual now believes the backpack weighs greater than 10 kilograms._
](/images/belief-revision-2.svg)


### Moral Sentiments

Morality can also be construed as a kind of mental model. However, moral sentiments do something other than simply try to represent the external world. Mere modeling of _how things are_ does not constitute morality. For instance, merely believing that there is murder in the world as a matter of fact as in Figure 4 does not constitute a moral sentiment.

![
_**Figure 4:** A diagram illustrating a descriptive rather than normative mental model, in which an individual witnesses a murder in progress and believes there is a murder taking place._
](/images/not-moral-sentiment.svg)

Morality models _how things should be._ Moral sentiments occur when there is a _judgment_ or _prescription_ about the external world. For instance, a moral mental model does not merely believe that there is murder in the world as in Figure 4, but _judges_ murder to be wrong as in Figure 5. Moral mental models are _normative,_ rather than descriptive. They do not have implications that explain or predict phenomena, but instead judge the worth of things (e.g., "murder is bad" or "charity is good"), prescribe certain behavior (e.g., "be kind to one another"), or proscribe behavior (e.g., "do not steal").

![
_**Figure 5:** A diagram illustrating a normative mental model, which, unlike Figure 4, contains a red circle-backslash symbol to represent the additional element of moral disapproval._
](/images/moral-sentiment.svg)


### World Revision

While both true-or-false beliefs and moral sentiments constitute kinds of mental models, an important difference occurs in how these kinds of mental model react to contradiction with observations of the external world. Earlier it was seen that when a descriptive mental model and the external world disagree, it is prudent to amend the mental model to fit the external world. However, with moral sentiments, _when a normative mental model and the external world disagree, the mind tries to amend the external world, not the mental model._

It is contrary to the purpose of morality to have the moral sentiment that murder is wrong, observe an incident of murder, and then conclude, "I guess I was mistaken. Murder is righteous," as in Figure 6. Rather, someone who has the moral sentiment that murder is wrong and who observes an incident of murder is expected to try to prevent the murder, as in Figure 7. One might also censure the act, call the authorities, report the act, or, with a longer view, investigate the root causes of murder in society and attempt to remedy them. In other words, the purpose of a normative mental model is to amend the external world.

Thus, descriptive mental models and normative mental models are diametrically opposed in how they handle contradictory empirical evidence. Such contradictions lead to a change of the mental model in the descriptive case, but lead to attempts to change the external world in the normative case.

![
_**Figure 6:** A diagram illustrating how a normative mental model is_ not _expected to react to contradiction with the external world. The left panel illustrates an individual who disapproves of murder. The middle panel illustrates the same individual witnessing a murder. The right panel illustrates the individual changing moral sentiment from disapproval to approval of murder, as symbolized by inclusion of a check mark._
](/images/nonsensical-moral-revision.svg)

![
_**Figure 7:** A diagram illustrating how a normative mental model_ is _expected to react to contradiction with the external world. The left panel illustrates an individual who disapproves of murder. The middle panel illustrates the same individual witnessing a murder. The right panel illustrates the individual attempting to stop the murder, while the moral sentiment is retained._
](/images/world-revision.svg)


### No Moral Truth

For a worldview that accepts these definitions, it must be concluded that inquiring as to the truth or falsity of moral sentiments _is a mistake_, in the same way it is a mistake even to ask about the color of a taste or the odor of a touch. One is simply asking the wrong kind of question in these cases.

There are no conditions under which a moral sentiment is false, because any disagreement between the external world and a normative mental model is judged to be a fault of the external world, not the mental model. Indeed, this is the very point of moral judgment. Where there is not even an opportunity for falsity, there is neither the possibility of truth. Thus, there are no moral truths.

### No Moral Knowledge

A direct consequence of this and the earlier definition of knowledge as justified, true belief is that there is no such thing as moral knowledge. Moral knowledge is impossible, not due to any limitation of the human condition, but because it is nonsensical to attempt to apply truth and falsity to moral sentiments.

In philosophical jargon, a position that denies the possibility of moral knowledge is termed "moral skepticism."


## Separation of Descriptive and Normative Elements

### Linguistic Mixing

Since true-or-false beliefs and moral sentiments are different and are even in a certain sense opposite, and because true-or-false beliefs and moral sentiments are evaluated in different ways, it is best to distinguish between the two in order to maintain clear thinking. Unfortunately, human beings speak, hear, write, and read natural languages, and natural languages obfuscate attempts to achieve such clarity by often mixing the expression of the two. 

Two individuals can relate the same fact, but one individual might label a faction "terrorists," while the other individual might use the phrase "freedom fighters." Indeed, the two individuals might have the exact same descriptive mental models about what has actually happened. However, the _connotation_ of the language used differs between the two individuals. The connotation of the first includes a disapproving moral sentiment, while the connotation of the second includes an approving moral sentiment.

Such connotations lead to a mixing of true-or-false beliefs and moral sentiments at the level of language. Because of this, and because human beings encounter a lot of language usage in their daily lives, often the first encounter one has with a new true-or-false belief also includes moral sentiments mixed with it, and the first encounter one has with a new moral sentiment also includes true-of-false beliefs mixed with it.

Thus, true-or-false beliefs and moral sentiments do not come partitioned in a neat package, properly separated and labeled. Instead, a sound mind must consciously and deliberately do such partitioning itself in order to maintain clarity in its thinking.


### The Method of Attitudinal Propositions

Doing such a mental partitioning can be facilitated by the realization that moral sentiments can readily be translated into descriptive beliefs _about the normative mental models themselves._ Such a belief can be termed an "attitudinal proposition" because it is a belief about a mind's attitude toward something.

For instance, if an individual named Zhaohui says, "stealing is wrong," then the corresponding attitudinal proposition is "Zhaohui disapproves of stealing" or "Zhaohui is morally opposed to stealing" or "Zhaohui feels that stealing is wrong."

While it makes no sense to attempt to evaluate the truth or falsity of the moral sentiment "stealing is wrong" itself, descriptive mental models _can_ be correct or incorrect _about_ Zhaohui's normative mental model. From the perspective of the more than seven billion human minds on the Earth, Zhaohui's mind is part of their external world.

Such attitudinal propositions make a different kind of claim than the objective statement that "murder is wrong." They make claims about subjective mental states, claims that _are_ true or false, as illustrated by Figure 8 and Figure 9. Thus, while there are no moral truths and no moral knowledge, there can be truths and knowledge about moral sentiments.

![
_**Figure 8:** Two diagrams illustrating true beliefs about attitudinal propositions. The left diagram illustrates an individual (teal icon) who disapproves of raising and slaughtering animals for food, and another individual (orange icon) who has the descriptive belief that this individual indeed disapproves of raising and slaughtering animals for food. The right diagram illustrates an individual (teal icon) who approves of raising and slaughtering animals for food, and another individual (orange icon) who has the descriptive belief that this individual indeed approves of raising and slaughtering animals for food._
](/images/true-attitudinal-propositions.svg)

![
_**Figure 9:** Two diagrams illustrating false beliefs about attitudinal propositions. The left diagram illustrates an individual (teal icon) who disapproves of raising and slaughtering animals for food, but another individual (orange icon) has the descriptive belief that this individual approves of raising and slaughtering animals for food. The right diagram illustrates an individual (teal icon) who approves of raising and slaughtering animals for food, but another individual (orange icon) has the descriptive belief that this individual disapproves of raising and slaughtering animals for food._
](/images/false-attitudinal-propositions.svg)

Mixed statements with both descriptive information and normative connotations can be interpreted as a conjunction between two propositions: one about a state of affairs and another about a mind's attitude toward the state of affairs. For instance, if someone named Chidi says, "the Liberation Front terrorists were defeated in the battle today," this can be interpreted as two propositions: "the Liberation Front faction lost the battle today" and "Chidi disapproves of the Liberation Front." Similarly, if someone named Astrid says, "during the battle today, the Liberation Front was set back in their struggle against oppression," this can be interpreted as "the Liberation Front faction lost the battle today" and "Astrid approves of the Liberation Front."

If social decorum permits, one can make these translations explicitly as part of one's conversation. This has the potential to inform one's interlocutor that one has a worldview that includes moral skepticism. Of course, there are social settings where it may not be prudent to make such translations overtly. In these cases, one can quietly make this sort of translation from moral sentiments to attitudinal propositions in one's own mind.

Regardless of whether done overtly or tacitly, making such translations as a matter of habit rescues a truth from a sort of dialogue that consists of untruths. These habitual translations thus create opportunities to gain new knowledge and make learning experiences out of what, taken at face value, would not be opportunities to learn.


## Moral Constructs

Sometimes moral sentiments are expressed in very literal, self-aware terms, e.g., "I am a vegetarian because I am ethically opposed to raising and harvesting animals for food." However, sometimes moral sentiments are expressed in terms of abstract concepts, such as "justice," "virtue," etc. When they appear in the predicates of statements, these normative _moral constructs_ can readily be translated to descriptive beliefs by the method of attitudinal propositions.

"This war is a just war" can be translated to the belief that the speaker morally approves of the war in question, and "this war is unjust" can be translated to the belief that the speaker morally disapproves of the war. "Practicing birth control is virtuous" can be translated to the belief that the speaker morally approves of birth control, and "using abortion as a method of family limitation is vicious" can be translated to the belief that the speaker [morally disapproves of the use of abortion as a birth control method](/margaret-sanger-on-abortion-in-her-own-words.html).

However, sometimes these moral constructs are used not just in the predicates of statements, but assume an existence of their own, being used as the subject of statements. For instance, the word "good" is understood to mean something that is desirable when predicated of a physically existing subject, but in ancient Greek philosophy it was fashionable to speak about "the Good," as if it were a thing in and of itself, in statements such as "the Good is One." Likewise, today some individuals create theories of justice. For a time, it was fashionable for thinkers to speak of "Nature and Nature's laws" with an uppercase "N."


There are at least three major ways morally skeptical worldviews can interpret moral constructs.

### Noncognitivism

One interpretation notes that not all grammatically correct sentences of natural languages form a meaningful thought. For instance, the sentence "purple ideas sleep furiously" is a grammatically correct sentence of the English language, but it is nonsense and meaningless. Puzzling over such a sentence is a waste of time. Under this interpretation, statements about moral constructs are viewed in a similar light, judging them to be meaningless, in a literal sense. This is ethical _noncognitivism._ [@ayer_language_1946]

This is perhaps the most obvious extension of the earlier interpretation of moral sentiments. Much as it was interpreted to be a mistake to attempt to judge the truth or falsity of moral sentiments, this interpretation believes it a mistake to attempt to judge the truth or falsity of statements about moral constructs.

Statements about moral constructs might still have connotations, even if their denotation is empty because they refer to nothing. When these connotations can be translated using the method of attitudinal propositions, there may be a true-or-false belief to be discovered.

For instance, if someone named Thomas were to say, "Nature and Nature's Law demands the overthrow of the Republic of Freelandia," then this can be translated to "Thomas approves of the overthrow of Freelandia." This can be done without engaging in speculative philosophy about what Nature wants or what Nature's Law is, because ethical noncognitivism judges such statements as meaningless.

Thus, whereas mixed language can be translated into the conjunction of a factual statement and a statement about someone's normative mental model, statements about moral constructs are interpreted as missing the former, factual content and consisting of, at most, just the latter attitudinal proposition. 

### Error Theory

Another interpretation is to take statements about moral constructs at face value and to make existence of a subject a criterion of truth. Under this interpretation, statements such as "all unicorns are white" are interpreted as false because there are not, in fact, any unicorns. Similarly, statements in terms of "justice," "virtue," etc., are _trying_ to describe some feature of the non-mental world.[^non-mental] However, there are no such physically existing things such as justice, virtue, etc., to describe, and all of these sort of statements fail. Therefore, all such statements about moral constructs are false. This is an _error theory_ of morality. [@mackie_ethics_1977]

This kind of an error theory for morality is specific to the _subjects_ of statements. One can have a more general error theory for morality, which would contradict the earlier sections of this article, since a more general error theory would judge moral sentiments to be false, and earlier it was judged a mistake to apply truth or falsity to moral sentiments. However, a more specific error theory in which the existential criterion is applied only to subjects of statements is compatible with the earlier sections of this article.

Under such a more specific error theory, statements such as "murder is wrong" are neither false nor true, since the subject of the statement, i.e., murder, describes something that exists, in this case a physical act. Statements such as "the Good is One" or "justice is more important than facts" are false because their subjects &ndash; i.e., "the Good" and "justice" &ndash; do not denote something that exists in the non-mental world.

[^non-mental]: This article uses the phrase "non-mental world" to denote everything in the cosmos except for the contents of _any_ mind. This is a more restrictive class than what is referred to by "external world" by exactly one mind.

### Useful Fictions

A third interpretation of statements about moral constructs is that they are not to be taken literally, but are _useful fictions,_ like a fable, intended to remind individuals to act in accord with some moral system.

However, while it may be the case that moral constructs _should_ be interpreted as useful fictions, many individuals have, in fact, not interpreted them as such, but instead have taken them literally. Pages and pages of philosophical treatises have been devoted to speculating about "the Good," "virtue," etc. Even today, in contemporary news outlet there is much handwringing about the nature of "justice" or "human rights."

An issue with the useful fictions interpretation is that, while it may make a mind internally consistent, this is largely hidden from the external world. An individual who ironically speaks in terms of "justice" or "human rights" with the understanding that these are useful fictions is not readily distinguishable from someone who literally speaks in terms of "justice" or "human rights" as if they described actual things. This leaves those with useful fiction interpretations either to call out repeatedly that moral constructs are fictional when using them or to maintain secret worldviews indistinguishable from diametrically opposed worldviews.

### Moral Fictions

Regardless if statements about moral constructs are interpreted as neither true nor false, always false, or false but in a way that has utility, the important point that all these morally skeptical interpretations have in common is that statements about moral constructs are not literally true. Thus, such statements about moral constructs are _moral fictions._

#### The Fallacy of Externalization

Statements about moral constructs are fictional because all truths describing morality are describing normative mental models, however indirectly this may be. Value judgements do this indirectly by ascribing goodness or badness to things in the non-mental world, such as the act of murder. Moral constructs take this indirection even further with the invention of abstractions that do not describe anything in the non-mental world, such as justice, virtue, etc.

While all truths about morality describe normative mental models, moral fictions are a tool to create the impression that one is discussing something external to one's own mind. This lie may be termed the "fallacy of externalization."[^fallacy] Moral fictions use the same language used to describe things that have physical existence independent of one's own mind, such as gravity, oxygen, or tectonic shift. The use of such language is a way to pretend that one is describing something _other_ than one's own normative mental model. 

[^fallacy]: This kind of fallacy is different from the fallacies discussed in articles tagged "fallacies" in this blog. The articles tagged "fallacies" discuss mistakes in interpreting evidence, regardless of one's philosophical position. The fallacy of externalization is a fallacy to moral skepticism, but is not a fallacy to moral realism.

#### Delusions of Moral Knowledge

By using the fallacy of externalization, moral fictions create the illusion of being statements made by a descriptive mental model. Descriptive mental models, as has been seen, can be evaluated as true or false and can constitute knowledge. However, it is a mistake to attempt to apply truth or falsity to moral sentiments, and there is no moral knowledge. Thus, moral fictions are a way for a mind to delude itself into believing it has moral knowledge.


## Conflict between Moral Skepticism and Moral Realism

Worldviews that believe moral sentiments can constitute knowledge of the non-mental world are called "moral realism" in the philosophical jargon. Unfortunately, moral realism has been a common if not the most common meta-ethical[^meta-ethics] position in the history of philosophy taught in academic settings, and so one is liable to encounter many moral fictions when perusing published thinking about ethics.

[^meta-ethics]: The terms "meta-ethics" or "meta-morality" are philosophical jargon for that branch of moral philosophy that deals with what morality is, as opposed to those branches of moral philosophy that tackle specific ethical problems or that invent moral systems.

While academic philosophy is notoriously irrelevant to the daily lives of the masses, this is not just a recondite disagreement. In contemporary life, one need not look very far to find those advancing their own pet ideas of what "justice" is. Morally contentious issues such as abortion are often framed in terms of moral fictions such as "personhood" or "human rights."

Worldviews of moral realism and worldviews of moral skepticism are prone to conflict. For instance, a morally realist worldview might view its invention of moral fictions as giving credence to its own morality. It might view its own morality as superior to others because it is "rational," substantiated with argumentation, and supported by logic. A morally realist worldview might look at the morality of a morally skeptical worldview as unsubstantiated, inferior because of its lack of moral fictions, and prone to "emotional arguments."

However, a morally skeptical worldview would view the moral fictions of a morally realist worldview as a self-delusion, not an asset. It would view the claims that a moral system is superior to others as merely begging the question. It would view argumentation supporting a moral system as backwards rationalization of a preconceived conclusion. It would view claims that moral sentiments are supported with logic as impossible, since logic is a calculus of truth conditions, and it is mistaken to apply truth or falsity to moral sentiments. It would view the attempts to disparage moral sentiments as "emotional" as entirely misguided since emotions are a large part of how morality actually works in a human mind, rather than how philosophers speculate it should work in their pointless treatises.

This meta-ethical conflict has large implications in how human beings go about their morality and how their worldviews relate to and understand one another. Unfortunately, there are many individuals who have never gone to the trouble of figuring out their own meta-ethical position. Some of these individuals launch right into moralizing assuming a kind of naive moral realism. It then falls upon those of morally skeptical worldviews to articulate their own meta-ethical positions before a naive moral realist can even understand where they are coming from. Such is a motive for this article.


## Practices of Moral Skepticism

The meta-ethical position articulated herein is not just of speculative interest, but has implications for how to go about the doing of morality, implications that lead to certain practices.

The first practice is, when expressing one's own morality, to do so by referring to one's attitudes directly, such as with statements of the form "I ethically approve of &hellip;" or "I disapprove of &hellip; morally." Since the only true things that can be said about morality are descriptions of a normative mental model, this is the most direct and truest way to express moral sentiments. Furthermore, everyone is the world's foremost expert on the contents of one's own mind, so this is an approach that leads to authoritative information on a subject.

Another practice is, when encountering the moral sentiments of others expressed in a manner not referring directly to their attitudes, to translate these statements into attitudinal propositions. This can be done overtly, when social context allows for it, or silently in one's own mind, when social context does not. This has the benefit of rooting out the linguistic obfuscation of true-or-false beliefs and moral sentiments so that one can use methods for investigating truth or falsity for the former and not mistakenly attempt to use such methods for the latter.

A final practice is to avoid moral constructs entirely. Because they are fictions, nothing true can be said about them, and it is waste of time to engage in speculation about them. It is relatively easy to avoid being the origin of moral fictions, but one is liable to encounter the moral fictions of others. Sometimes there is an attitudinal proposition that can be rescued from others' moral fictions; sometimes not. Either way, this is perhaps the most challenging situation that those of a morally skeptical viewpoint encounter, for the only remedy such a circumstance allows is to explain precisely why one views moral fictions as frivolous and self-delusional.


## Conclusion 

The strains of moral realism popular in the history of philosophy would portray morality as a quest for objective truths and moral knowledge. Moral skepticism as articulated here rejects this approach to morality. While this clarifies what morality is not, it does not identify what morality actually is. 

### Moral Psychology Instead of Moral Philosophy

The worldview articulated here identifies moral sentiments as normative mental models. Thus, it identifies morality as a _psychological construct._ Since moral sentiments of any one person are influenced by those around them, morality is a socio-psychological construct.

At the same time that the meta-ethical position articulated here implies that traditional moral philosophy is not a worthwhile pursuit, it points to moral psychology as a way to truly understand morality. This may seem to have little relevance for anyone outside of academic pursuits. Most individuals lack the time and resources to do psychology (though many at least have the time and resources to study the work of others). 

### Self-Awareness Instead of Self-Delusion

There is also an important implication relevant for all individuals, regardless of vocation. It is that moral enlightenment does not come from discovering supposed moral truths, nor does it come from the vain invention of fictions intended to rationalize one's moral sentiments, but comes from introspection. The best one can do is to _know thyself,_ as the ancient maxim goes.

A critical thinker is compelled to believe what is true and disbelieve what is false. What remains after this is just how one feels. The only enlightenment that can be attained about this remainder is to be _aware_ of how one feels and to abstain from trying to rationalize one's feelings post hoc. Then, one can investigate oneself with the same tools of inquiry &ndash; such as empirical evidence, investigation into causation, etc. &ndash; that one might use to investigate any other fact about the world.

![
_**Figure 10:** A diagram illustrating moral self-awareness._
](/images/self-awareness.svg)


## Further Reading

Ethical noncognitivism was popularized in the English speaking world by Ayer [-@ayer_language_1946]. An error theory for morality is advocated by Mackie [-@mackie_ethics_1977].


## Citations

::: {#refs}
:::


## Footnotes
