---
author: "Joshua Born"
bibliography: "../bibliographies/philosophical-positions-that-make-viewpoints-insufferable.bib"
csl: "../bibliographies/chicago-author-date.csl"
date: 2022-11-13
include-before: |
  ## Table of Contents
output:
  blogdown::html_page:
    number_sections: false
    toc: true
    toc_depth: 5
summary: '[Summary sentence goes here.]'
tags: ["opinion", "philosophy", "first-person"]
title: 'Philosophical Positions that Make Viewpoints Insufferable'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE
)
```

## Introduction

I am fond of the maxim that you should study enough philosophy to know not to study philosophy.


### Useful Part of Philosophy

The rationale behind the positive, "study enough philosophy" part of the maxim is that there are a finite number of ways to view or interpret the world, and given that there have been billions of people, most of the ways to view the world that you encounter in your life are not new. Indeed, the ways you yourself view the world are not entirely original. These ways to view the world are philosophical positions, and everyone has them, whether they are aware of them or not.

The study of philosophy can benefit you by giving you the opportunity to explore and label many of these philosophical positions ahead of time, understand which are your positions, and understand the sticking points you will have with the other philosophical positions you encounter.


### Useless Part of Philosophy

The rationale behind the negative, "know not to study philosophy" part of the maxim is that, even though the exercise of understanding and labeling different positions takes only a few pages, formal philosophy is infamous for comprising treatises that consist of hundreds upon hundreds of pages. 

Typically, such treatises consist of an author espousing a philosophical position and trying to justify something along the lines of "why _my_ philosophical position is the best," and a lot, if not most, of the positions espoused in popular philosophical treatises are very, very flawed. Indeed, perhaps formal philosophy consists mostly of these very flawed positions precisely because they require hundreds of pages to defend. It would be difficult to have enough work to merit a department of philosophy at a university without ponderous, interminable treatises to dissect and discuss.

Thus, once equipped with enough knowledge to identify your own philosophical positions, the philosophical positions of those you encounter, and the differences between, you have gotten what there is of value from the study of philosophy. The rest can be skipped. 


### Differences in Philosophical Positions

This article is an exercise in the useful part of learning about philosophy. I identify four philosophical positions often found in the social commentary I encounter in my life and how differences with my own philosophical positions lead to more fundamental disagreements than the specific matters discussed.

Three things are striking about such incompatibilities in philosophical positions.

The first is that many people are not consciously aware that they even have philosophical positions. This is akin to people who have never traveled the world and encountered other languages besides their native tongue. Such people are easy to spot because they find it incomprehensible that anyone would have a different way of thinking than they.

The second striking feature of disagreement across philosophical positions is that two people who disagree about something _and_ have underlying differences in philosophical positions often cannot understand the disagreement itself. Such situations are akin to two people who speak only different languages: they cannot even understand what the other person is saying. If they had a common language, they would likely still disagree about something, but at least they would be able to understand _how_ they disagree with each other.

The third striking feature is that what philosophical position anyone has is largely independent of what specific opinion anyone has. A moral realist and a moral skeptic can wind up with the same view on capital punishment, or different views; no matter your view on capital punishment, you could be a moral realist or a moral skeptic or have some different metaethical position entirely. Thus, differences in philosophical position cut across the familiar -- and simple-minded -- partisan ideological boundaries that are conspicuous in social commentary.


## Essentialism

Essentialism is the position that behind the phenomena of the world that we observe are hidden essences that are not directly observable, and when categories of individuals exhibit similarities, this is because they share a common essence.

Essentialism is quite old in Western philosophy and versions nof it were espoused in various works by Plato and Aristotle. Ancient versions of essentialism tended toward the metaphysical. However, essentialism comes up again and again today in less metaphysical ways, particularly in social commentary.  Sometimes commentators actually use the word "essence" or its derivatives, as in "AP’s style is now to capitalize Black in a racial, ethnic or cultural sense, conveying an _essential_ and shared sense of history, identity and community..."[^italics] [@daniszewski_ap_2020] Other common language includes "culture," "spirit," or "nature" of a "people," "race," or "nation." Thus, modern essentialism can appeal to either cultural or biological explanations or both.

[^italics]: Italics have been added for emphasis.

The major implication of essentialism is that the way we categorize is either correct or incorrect, and categorization is not arbitrary. A label is correct when all individuals who have the common essence are categorized together and no individuals who lack the essence are included in the category.


### My Contradictory Position: Nominalism

I subscribe to a position that is the explicit rejection of essentialism and labeled "nominalism" by Karl Popper [-@popper_open_2020, Chapter 11]. According to this distinction, essentialism interprets the statement, "A puppy is a young dog," as an answer to the question, "What is the essence of a puppy?" However, nominalism interprets the statement, "A puppy is a young dog," as an answer to the question, "What shall we call a young dog?"

To nominalism, categorizing individuals is a language convention, and [categorization is arbitrary](/category-based-prejudice.html#categorization-is-arbitrary), in a sense.

Of course, language is a social phenomenon, and in order to communicate you must adopt at least some established conventions, which is what the process of learning a language is to a nominalist. Furthermore, it might turn out that some conventions are generally more useful than others, and therefore, the labeling you use might change over time. If enough people do this, this leads to changes in the popular use of language. Similarly, some conventions might be more useful in certain contexts, causing specialized fields to invent their own jargon out of terms of art.

The major implication of nominalism is that there are not correct categorizations and incorrect categorizations, but instead categorization is arbitrary, with some categorization schemes better than others for certain purposes and in certain contexts, but no one true way to categorize.


### Why Essentialism is Insufferable to Me

Essentialists hold opinions that are insufferable to nominalists such as myself because an essentialist who has labeled an individual as a member of a category has done so with the belief that this reflects a great truth. To essentialists, such categorization constitutes knowledge, whereas to nominalists, it is merely a labeling convention.

For nominalists, it is easy to spot essentialists in everyday life. Essentialists are prone to want to engage in such ruminations as whether or not someone is "really gay" or "really Black," whereas nominalists are prone to cringe at such questions. Essentialists are liable to interpret a nominalists' cringing as disagreement with the essentialists' answers to the question of whether someone is "really gay" or "really Black," but nomiminalists are not disagreeing with the validity of the essentialists' answers, but with the validity of the essentialists' question.

Sexual orientation is something that has been handled by the vast tapestry of human cultures that have ever existed in a variety of ways, whereas labeling someone "gay" or not is largely a phenomenon developed in twentieth century, Western, education, industrialized, rich, democratic societies and then exported to the rest of the world. Similarly, categorization of people by their phenotypical appearance such as skin color, etc, is a relatively modern phenomenon that has its origins in the colonialism of the Age of Sail. [@larsen_our_2014, Chapter 4]

Nominalists such as myself would note this as evidence that there is nothing eternal or essential about these labels. Dedicated essentialists might retort that labels are merely imperfect approximations of some underlying essence, such as "gay" genotypes, much like Plato and his Theory of Forms. This could continue _ad nauseum._ However, even to get to this realization, essentialists and nominalists would first have to realize that they are not disagreeing in the particulars of the essentialists' evaluation that someone is "really gay" or "really Black," but actually disagreeing at the more fundamental level of whether this is a valid question. To nominalists, no one is "really gay" or not or "really Black" or not, because no one is "really" anything.

How we categorize fellow human beings is probably the most contentious kind of labeling, which is why this genre of categorization is used as an example, but the essentialism versus nominalism divide extends to all kinds of categorization. Indeed, discussions about whether certain music is "really metal" or "really jazz" have gotten quite contentious.

A particularly insufferable form of essentialism occurs when essentialists do not even realize that they are essentialists. These are the sort of individuals discussed in the introduction who are either not aware their views are contingent on a particular philosophical position or are not aware that others have philosophical positions that differ from their own. This naive essentialism is aggravating because it is prone to presume that nominalists do not "get it." Such naive essentialists are so ignorant that they mistake their own ignorance as the ignorance of others who have consciously considered and rejected essentialism. 


### Independence to Specific Views

The disagreement between essentialist and nominalist philosophical positions does not map one-to-one onto the partisan ideological divides that come and go in human society, but are orthogonal to them. For instance, there is rancor over transgender issues in the United States. Roughly summarized, one viewpoint exists that looks at people who identify as transgender as yet another long-oppressed group to champion and to whom to be an "ally."

Curiously, this "ally" viewpoint can manifest itself both in ways that are very nominalist and very essentialist. On the one hand, someone of this viewpoint might regard gender as something that is explicitly a conventional label, such as discussion of "gender assigned at birth," "gender someone identifies with," or "preferred pronouns." On the other hand, someone of this viewpoint might discuss gender as something that is overtly an essence, with assertions that someone who identifies as a transgender man "is really a man" or someone who identifies as a transgender woman "is really a woman" or that certain pronouns are "the correct pronouns."

Nominalists such as myself would easily interpret the former discussion as intended, and conversation could rapidly move on to more depth into the subject-matter itself. However, when nominalists such as myself encounter the latter sort of discussion, we are liable to reject the assertions, and the more fundamental difference in philosophical positions must be resolved one way or another before productive conversation on the subject-matter itself can ensue.

Even more curiously, viewpoints critical of the "ally" viewpoint can also manifest themselves both in ways that are nominalist and essentialist. Furthemore, essentialist viewpoints critical of the "ally" viewpoint are prone to use language almost exactly like that of the essentialist "ally" viewpoint, but with concepts switched. Such viewpoints might assert that someone who identifies as a transgender man "is really a woman" or someone who identifies as a transgender woman "is really a man" or that certain -- opposite -- pronouns are "the correct pronouns." Thus, what viewpoint someone has on a given issue is related to, but independent of the essentialism versus nominalism divide.


### More Philosophical Positions Than Two

Of course, trying to summarize all the different ways that a human being could interpret categorization and labeling with just the two positions of "essentialism" and of "nominalism" is an oversimplication, as is the case whenever we use a dichotomy. There are likely many ways to interpret categorization that might be similar or entirely different from the ways discussed here. Furthermore, the uses of "essentialism" and "nominalism" in this section are actually quite narrow definitions of the concepts. All of this is done in order to illustrate a very specific point, and this section should not be interpreted as an attempt to define the essence of "essentialism" or the essence of "nominalism."


## Moral Realism

## Epistemological Rationalism

## Credulity




## Citations

::: {#refs}
:::


## Footnotes
