---
bibliography: "../bibliographies/political-rhetoric-as-shibboleths.bib"
csl: "../bibliographies/chicago-author-date.csl"
date: 2020-07-04
implicit-figures: true
link-citations: true
output:
  blogdown::html_page:
    md_extensions: ["+footnotes"]
    toc: false
    toc_depth: 5
summary: "Political rhetoric comprises some of the worst excuses for dialogue known to human civilization. In this article, the concept of a shibboleth, which comes from an example of sectarian conflict in the Hebrew Bible, is used to explain a function of slogans in the context of political rhetoric, and the characteristics of shibboleths that make them inimical to independent, critical thinking &ndash; namely conformity, superficiality, and exclusion of non-binary viewpoints &ndash; are examined."
tags: ["opinion", "third-person"]
title: "Political Rhetoric as Shibboleths"
---

## Introduction

A conversation can reasonably be construed as two or more individuals engaged in at least two activities: communicating their own thoughts and understanding their interlocutor's thoughts. Using this definition, political rhetoric often fails to merit being labeled a "conversation."

Political rhetoric can fail to constitute a genuine conversation in the sense of the latter activity, when one has no genuine interest in even attempting to understand what the other party is communicating.

However, this article examines a different, but also common, failure in the sense of the former activity: political rhetoric often fails to communicate any tangible thoughts because it consists of slogans, catch-phrases, or more generally, superficial ideas commonly passed around by a faction amongst themselves.

It is naive to believe that the purpose of all usage of language is to communicate information. Such is not the purpose of the sort of political rhetoric identified here. Therefore, one cannot be enlightened _by_ this sort of political rhetoric. However, one can be enlightened in how one thinks _about_ political rhetoric.


## Definition of "Shibboleth"

The word "shibboleth" comes to the English language from the Hebrew Bible. In the below passage, a civil war is described between tribes of Israel. The Ephraimites have invaded the territory of the Gileadites, who are led by Jephthah. 

> Then Jephthah gathered all the men of Gilead and fought with Ephraim; and the men of Gilead defeated Ephraim, because they said, "You are fugitives from Ephraim, you Gileadites—--in the heart of Ephraim and Manasseh."^[This passage can be difficult to read because there are two different usages of what is rendered in the English as "fugitives." In this instance, the Ephraimites are calling the Gileadites "fugitives from Ephraim." Ephraim and Manasseh were named after two sons of Joseph and are considered to be two subtribes of the tribe of Joseph. The tribe of Gilead is sometimes itself considered to be a subtribe of the tribe of Manasseh.] Then the Gileadites took the fords of the Jordan against the Ephraimites. Whenever one of the fugitives of Ephraim^[In this case, the passage is using "fugitives of Ephraim" to describe the Ephraimites fleeing their defeat. It is not referring to the Gileadites as in the earlier "fugitives from Ephraim" passage.] said, "Let me go over," the men of Gilead would say to him, "Are you an Ephraimite?" When he said, "No," they said to him, "Then say Shibboleth," and he said, "Sibboleth," for he could not pronounce it right. Then they seized him and killed him at the fords of the Jordan. Forty-two thousand of the Ephraimites fell at that time. [@coogan_new_2010, Judges 12:4-6 NRSV]

According to the passage, the Ephraimites had been defeated by the Gileadites. Not wanting to spare any Ephraimites, the Gileadites blockaded the Jordan River so that no Ephraimites could escape the massacre.

![
_The Jordan River, pictured in 2009, was the site of a massacre of fleeing Ephraimites by Gileadites in ancient times._<br/>
["Jordan River"](https://www.flickr.com/photos/tony709/6107292778/)
by
[Cycling Man](https://www.flickr.com/photos/tony709/)
is licensed under
[CC BY-NC-ND 2.0](https://creativecommons.org/licenses/by-nc-nd/2.0/)
and is not modified.
](/images/jordan-river.jpg)

This led to a problem for the Gileadites blockading the river. How would a Gileadite know if any given person caught crossing the Jordan River were a fleeing Ephraimite or just a Gileadite going about one's business? The solution told by the passage is that the Gileadites blockading the river challenged the river crossers to say a specific word, which was pronounced one way in the Gileadite dialect and another way in the Ephraimite dialect. If a river crosser pronounced it the Gileadite way, the individual would be spared, but if a river crosser pronounced it the Ephraimite way, the individual would be killed.

What was important was not what the word _"shibboleth"_ meant.^[Incidentally, there is some debate among modern scholarship as to what the word did mean.] Indeed, any ancient Hebrew word with a leading _"sh"_ sound might have served the same function. What was important was that the pronunciation of the word could be used as a marker to differentiate members of one tribe from another.

As the concept of shibboleth has evolved in modern English, it has grown beyond just the use of the _pronunciation_ of a word as a tribal marker, encompassing definitions such as

> a word or saying used by adherents of a party, sect, or belief and usually regarded by others as empty of real meaning [@merriam-webster_shibboleth_nodate]

This broadened concept of the shibboleth to include sayings denotes precisely the kind of political rhetoric that is the subject of this article.


## Characteristics of Shibboleths

The modern shibboleths of political rhetoric are slogans used to identify to what political sect, which can be thought of as a tribe, an individual belongs. For instance, in the United States, there are certain shibboleths that are associated with a tribe that might loosely be called "conservatives," and there are other shibboleths that are associated with a tribe that might loosely be called "leftists."^[The use of the word "liberal" is avoided in this article because the term "liberal" is heavily confounded. While it is often used to refer to leftist politics in the United States, "liberal" parties in many other countries are right-wing or center-right parties. Furthermore, even in the United States, "neo-liberal" economic policies and "classical liberal" political philosophies are often associated with right-wing or libertarian positions.]

![
_A sign consisting of nothing but leftist shibboleths, found in front of a house in the author's neighborhood._^[A right-wing version of such a sign would have been included in this article, but the author does not live in an area where these are easily found.]
](/images/left-wing-shibboleths.jpg)


### Conformity

One of the most conspicuous characteristics of shibboleths is that they are expressions of conformity. For instance, consider the above sign. The sign contains eight shibboleths. All of these shibboleths demonstrate affiliation with the leftist political tribe. Is it the case that the individual who posted this sign just happened to independently come to the leftist position on all eight issues, and the individual found someone else who was making signs who also just happened to independently come to the leftist position on all eight issues?

It is more likely the case that, because an individual's sentiments are influenced by the individual's social milieu, both the sign buyer and the sign maker are simply conforming to the same social forces.

Much as the ancient Ephraimites' similar pronunciation of _"shibboleth"_ was due to a common social origin, shibboleths today are expressions of conformity to the same political tribe.


### Superficiality

Another trait of shibboleths is that they are repeated almost word for word by members of a political tribe. In the process of hearing or reading a shibboleth and then regurgitating a nearly identical shibboleth, there is superficiality in at least two ways.

For one, a serious treatment of any issue requires more prolonged thought than can be conveyed in a shibboleth-length unit of language.

Secondly, there is no critical thinking exercised in this phenomenon. Any human being with a robust mind has a viewpoint that will agree in some ways with another viewpoint and disagree in other ways. This is one reason that individuals are apt to express their viewpoints in their own words and to protest against "putting words in my mouth." The phenomenon of repeating shibboleths without modification and without inclusion of criticisms is indicative of a lack of substantive thought.

Much as the function of the ancient _"shibboleth"_ occurred without any regard to the actual meaning of the word, modern day shibboleths can fulfill their function just fine without any meaningful content.


### Exclusion of Non-binary Viewpoints

If it is assumed that each of the eight shibboleths in the pictured sign allude to a logically independent issue,^[If these eight issues are not logically independent, the same thought experiment works by picking any eight logically independent issues arbitrarily.] and that there are at least two possible opinions about each issue, then there are 2<sup>8</sup>&nbsp;=&nbsp;256 possible viewpoints^[Here, by "viewpoint" is meant a unique combination opinions on each of the eight issues. This is actually a minimum bound and likely an underestimate, as there are far more than two possible opinions that any one person could reasonably have about an issue, so there are likely on the order of magnitude of 5<sup>8</sup>&nbsp;=&nbsp;390,625 such viewpoints, if not more.] that any one person could have about these eight issues.

However, the above sign construes a world in which there are not at least 256 different viewpoints, but just two, since each of the leftist shibboleths in it targets a conservative policy position or, perhaps more accurately, a straw-man version of a conservative position.

Much as the ancient _"shibboleth"_ was used in a tribal conflict to identify enemies, so too do modern political factions use shibboleths to identify their enemies. Sometimes this is done directly. For instance, conservatives might notice leftists use certain shibboleths, or leftists might notice conservatives use certain shibboleths.

Identification of enemies can also occur indirectly by construing a kind of sin of omission. This occurs when members of a political tribe proclaim their shibboleths and react with hostility to anyone who does not parrot back a similar shibboleth, in the fashion of "anyone who is not with us is against us." With this second usage, it is not just the viewpoint of the opposing tribe, but _all of the other hundreds if not thousands of viewpoints_ that do not fit neatly into either leftist or conservative tribes, that are identified as _enemies._

Much as the ancient use of _"shibboleth"_ assumed all who attempted to cross the Jordan River were either Gileadite or Ephraimite, the use of shibboleths today reinforces the exclusion of all but a few viewpoints from political discourse.


## Implications for Worldview

These traits of shibboleths make them useful for simple-minded, tribal worldviews that construe the intellectual landscape as a battle between "us" and "them." They serve no use for worldviews that value independent thinking instead of conformity and critical thinking instead of superficiality. Indeed, independent, critically thinking worldviews are the very sort of viewpoints that the use of shibboleths attempts to exclude.

Thus, those who value independent, critical thinking are best served by shunning the use of shibboleths. However, it is unavoidable to encounter _others_ using shibboleths. There is nothing to be gained from trying to learn _from_ such shibboleth usage directly. However, two things can be gleaned _about_ an incident of shibboleth use. The first is that the user of the shibboleth has indirectly proclaimed an association with a certain faction. The second is that the user of the shibboleth has a simplistic worldview characterized by superficiality and conformity.


## Citations

::: {#refs}
:::


## Footnotes
