---
title: "Reality versus Morality"
date: 2017-12-03
tags: ["morality"]
---

Morality is one of the most common features of human thought. It is also a prolific source of fallacies. A conspicuous feature of my worldview is that I enforce a strict separation between my beliefs about reality and my moral sentiments. In this meditation I articulate this separation and my motive for enforcing such a separation.


## The Language of Moral Sentiments

Beliefs about reality are often expressed in declarative sentences. When these statements consist of linking two ideas, often the word "is" and its conjugations are used, as in, for instance, "the Earth was formed approximately 4.6 billion years ago," "Paris is the capital of the United States," or "there will be rain tomorrow."

Moral sentiments sometimes take syntactic forms that differ from this. Sometimes moral sentiments are expressed in prescriptions, which can readily be spotted because they are predicated on words such as "should" or "ought" instead of "is," as in "every child should be given an education" or "criminals ought to be punished for their crimes." 

However, moral sentiments can also take the form of declarative sentences predicated on the word "is." This is noticeable in the case of value judgements, which join a subject to a predicate that includes an adjective declaring the subject’s perceived worth or lack thereof, as in "it is good to help those less fortunate" or "stealing is bad" or, more forcefully, "helping others is right" or "stealing is wrong." (Value judgements are not always moral sentiments. For instance, the sentence "rain on a summer afternoon is beautiful" is a value judgement, but most would consider it an aesthetic judgement, not a moral one.)

Because value judgements can use a similar syntax, they can have a surface appearance similar to beliefs about reality. Compare the two sentences "it is wrong that Paris is the capital of the United States" and "it is wrong for Paris to be betrothed to Juliet against her will." The two sentences have similar structure and even use a few of the same words, but the first asserts a belief about reality, whereas the second makes a value judgement.

This example, though admittedly contrived, serves to illustrate the challenge of discriminating between beliefs about reality and value judgements. This is further complicated by the fact that statements can both be informative and have connotations that express value judgements. Consider a case in which a battle has transpired, and we wish to know who won the battle. One report might say "the rebel terrorists have been driven out of the city. " Another report on the same events might say "the resistance forces have retreated from the city to fight again another day."

The situation becomes even more confusing when we consider what for lack of a better phrase might be called "moral constructs." In moral constructs, the moral sentiments appear neither as verbs such as "should" or "ought," nor as adjectives such as "good" or "bad," but as nouns. "We have come here to seek justice," "tomorrow we fight for freedom," and "you are against our rights" are just a few examples of statements involving moral constructs.

Finally, no accounting of the language of moral sentiments would be complete without acknowledging the existence of what have come to be called "weasel words." These are words that purport to be used to make a claim, but are so vague as to be without any actual substance. Words such as "inappropriate" or "problematic" are oft used weasel words by those who appear to be on the trajectory toward expressing a claim, but fail to. Such deployments of "inappropriate" leave us asking "inappropriate for whom?" or "inappropriate to what end?" Similar uses of "problematic" leave us asking what kind of "problems" the commenter has identified: factual errors or the "problems" of having moral sentiments that differ from one’s own?


## Distinguishing between Beliefs about Reality and Moral Sentiments

The preceding exercise has shown us that there is no reliable way based purely on language syntax and lexical choice to distinguish between a statement reporting a belief about reality and a statement expressing a moral sentiment. Instead we must look at the semantics of the said statements.

First let us compare beliefs about reality with moral sentiments expressed as prescriptions. Inasmuch as it happens to be false, "Paris is the capital of the United States" illustrates that beliefs about reality have the property of being either true or false. This property greatly influences the utility of the belief for us. "There will be rain tomorrow" might be a very useful belief to have if it were true, or it might lead us astray if it were false. We thus have a motive to evaluate its truth or falsity, especially if we have plans for tomorrow that involve outdoor activities. There is also at least one trivial way to determine the truth or falsity of the belief: the belief can be tested experientially by waiting until tomorrow and keeping track of the weather until end of day.

In contrast consider the prescription "you should give me a large sum of money." Our reaction does not seem to be influenced by any putative property of truth or falsity. By what procedure could we even establish the truth or falsity of this sentiment? If we were to wait for some observable event, like we considered doing to evaluate the truth or falsity of "there will be rain tomorrow," we would be waiting for very long time. Indeed we seem to miss the intent of the sentiment entirely were we to try to evaluate its truth or falsity.

"You should give me a large sum of money" does not tell us about an actual state of affairs, but relates to us a _desire_ for a certain state of affairs. Our reaction might be informed by a variety of things, none of which are the supposed truth or falsity of the sentiment. Is the sentiment being expressed by someone engaged in an activity trying to bring about a goal that we ourselves desire, such as someone working for our favorite charity? Is the sentiment being expressed by someone who has us at a disadvantage and is threatening us with violence? Is the sentiment being expressed by a familial relative? Is the familial relative known to have a gambling problem?

Beliefs about reality and prescriptions thus differ in that beliefs about reality purport to tell us about a state of affairs that has existed, exists, or will exist, whereas prescriptions purport to tell us about a state of affairs that the individual making the prescription wants to occur. (It should be noted sometimes predictions about the future in the English also use the words "should" or "ought" and in this way might be confused with prescriptions. For instance "the rain should be done in an hour or two" is a belief about reality, not a prescription, except perhaps for those so foolish to think they can command the weather.)

Moving on to value judgements, the examples "it is good to help those less fortunate" or "stealing is bad" illustrate how the antonyms "good" and "bad" are often used to express moral value judgements. "Good" has come to mean _valuable, desirable, favorable, beneficial,_ whereas "bad" has come to mean _inadequate, unsatisfactory, worthless, unfortunate._ In short, "good" is a word applied to things that are desired, and "bad" is used to apply to the opposite of that which is desired. In this way value judgements contrast with beliefs about reality in the same way that prescriptions do.

The antithetical words "right" and "wrong" sometimes fulfill a similar function. When used in sentiments such as "helping others is right " or "stealing is wrong" they are used synonymously with "good" and "bad," respectively, to make moral value judgements. "Right" can also be used to mean _correct,_ and "wrong" _incorrect._ This is ambiguous between "correct" to mean _factually correct_ or _truthful_ and "correct" to mean _morally correct_ or _good._ This is where the ambiguity between "it is wrong that Paris is the capital of the United States" and "it is wrong for Paris to be betrothed to Juliet against her will" originates. The first sentence asserts that its subordinate clause is false in a factual way, whereas the second does not deny that the circumstances of its subordinate clause are true, but instead indicates the desire that the circumstances differ.

There is a direct correlation between the semantics of prescriptions and those of value judgements. Any prescription of the form _"X_ should _Y"_ has a similar value judgement of the form _"Y_ is good," and vice versa. Any prescription of the form _"X_ should not _Y"_ has a similar value judgement of the form _"Y_ is bad" and vice versa. Thus "every child should be given an education" could be roughly expressed as "it is good for every child to being given an education," and "stealing is bad" could be roughly expressed as "you should not steal." There are differences in expressing moral sentiments as prescriptions or as value judgements, most notably that prescriptions involve an explicit subject who is being told to bring about the desired state of affairs whereas value judgments leave that unstipulated, but the fundamental contrast between beliefs about reality and either way of expressing a moral sentiment is the same. Beliefs about reality purport to tell us about a state of affairs that has existed, exists, or will exist, whereas moral sentiments, expressed as either value judgements or prescriptions, tell us about a state of affairs that the individual expressing the moral sentiment either wants or does not want to exist.

Moral constructs are not amenable to a similar analysis as done with prescriptions and value judgements in the preceding. Rather than analyzing moral constructs in general, we would need to pick a specific theory of a moral construct (e.g., a specific theory of justice) in order to analyze it. This is far beyond the scope of this meditation. However, we can reach a few modest conclusions.

Prescriptions and value judgements are akin to the building blocks of any moral constructs. For instance, a theory of justice usually implies that whatever is "just" is _good_ and that we _should_ try to bring "justice" about. Of course exactly what "justice" is, how to measure it, and how to bring it about varies considerably from theory to theory. It is fair to conclude, however, that what makes a moral construct specifically a _moral_ construct is the stipulation of something that is _good_ or to which we _ought_ to aspire. There may additionally be some beliefs about reality in a moral theory. A theory of justice might include, for instance, the belief that the root cause of poverty is an unequal distribution of the means of production. Thus moral constructs can be thought of as being built out of prescriptions and value judgements, plus optionally some beliefs about reality.

Finally, weasel words can be thought of as similar to sentences predicated on "right" and "wrong," though they are far more vague. Much as "right" and "wrong" can be used either to denote moral correctness or factual correctness and so be used either to create value judgements or beliefs about reality, so too can proclamations of the "inappropriate" or "problematic" properties of things.

Throughout the preceding analysis we have found that while we cannot quickly distinguish between beliefs about reality and moral sentiments based on syntax, there is a rather simple and straightforward way to distinguish between the two based on semantics: beliefs about reality purport to tell us about a state of affairs that has existed, exists, or will exist, whereas moral sentiments describe a state of affairs that someone either wants or does not want to exist. Also beliefs about reality have the property of truth or falsity, which greatly influences their relevance to us, whereas the significance of moral sentiments is evaluated in other ways.


## Beliefs about Reality Do Not Imply Moral Sentiments

Saying something is the case is not tantamount to saying one wants it to be the case. This leads to the first fallacy stemming from failure to differentiate between beliefs about reality and moral sentiments that we shall consider. There are at least two ways this fallacy occurs: as a prolific source of misunderstanding and as a problem so common in moral philosophy that it has been given it a label.


### Falsely Imputing Moral Sentiments upon Others

Implying a moral sentiment from someone else’s belief about reality leads to misunderstanding. Sometimes this is done innocently enough and stems from a genuine misunderstanding. Sometimes this is done maliciously in an attempt to discredit the individual in question. Regardless of why it is done, the practice is fallacious.

We have already seen a potential example of this in our [meditation on human nature](four-teloi-of-human-nature.html) We observed that humans are inclined toward tribalism and mythology. However, this does not imply that we want there to be lots of tribalism and mythology. Rather we ruminated in the aforementioned meditation on the challenge that tribalism and mythology present to enlightenment.

Falling into the trap of being falsely assigned a moral sentiment based on purely factual reporting is something that can easily afflict the more scientifically inclined. Science is ideally an amoral investigation of reality. In science classes, students are taught to avoid making value judgements and to avoid verbiage such as "good" or "bad" in their science writing. This is a laudable restraint imposed for the purpose of pursuing knowledge, but it does leave an opening for others to impute moral sentiments upon one that one simply does not have.

An example of this might occur from the observation that, due to differences in reproductive physiology, there is a selective advantage for placental mammals that live in social groups to have a preference for males to engage in behaviors that involve risk of death or seriously bodily injury, such as intergroup violence. This largely explains why a preference for male warfighters is a human cultural universal. Suppose someone observed this phenomenon, studied this phenomenon, published a long-winded academic paper that discussed all the subtleties of this phenomenon and, in the finest scientific tradition, made no assertions about the goodness or badness of the phenomenon. 

Because it would be an academic paper, the preponderance of the reaction such an individual would receive from the general public would be silence. For the sake of the thought experiment, however, let us imagine that this individual were met with a comment to the effect of "this chauvinist doesn’t want to let women in the military!" We could imagine the academic’s reaction to this comment would be one of genuine perplexity. All this individual would be doing would be reporting on how things got to be a certain way, not expressing a preference for things to be this way.


### The "Is-Ought Problem"

Let us consider a different individual from this academic, an individual who does not just want to understand phenomena, but who is making an argument. Label this individual "Person _A."_ Person _A_ is attempting to persuade someone else, called "Person _B,"_ that women should be not allowed in the military of some imaginary country, called "Country _C."_ Person _A_ uses the exact same facts that were morally neutral to the academic from the previous section.

Person _A_ makes the argument, "A preference for male warfighters appears to be a human cultural universal. Because of this, Country _C_ should have a preference for male warfighters as well, and the best way to realize this preference is to have only men in the military."

Person _B_ could simply reply, "I understand that a preference for male warfighters is a human cultural universal, but I do not want it to be that way. Therefore I want Country _C_ to allow women in its military."

The dialogue between Person _A_ and Person _B_ has thus encountered what is called the "is-ought problem." In the English-speaking world, articulation of the is-ought problem is often attributed to David Hume (1711-76), though it is such a basic idea that it has likely been articulated by many different individuals in many different cultures long before David Hume’s time.

We can imagine the dialogue continuing with Person _A_ arguing, "This human cultural universal did not appear out of thin air. It is likely the result of natural selection that led to a preference for males to fulfill riskier roles, such as intergroup violence. Societies that had this preference in the past would have maintained greater reproductive output than those who did not, which over time led to this preference becoming a cultural universal. Since this has worked in the past, the best thing to do is to continue this practice. The best way to continue this practice is to have a military that is only men."

Person _B_ could reply, "I understand how evolution, both genetic and cultural, works. Societies in the past that have used men preferentially for warfare have had greater reproductive output than those which did not. That might have been important when humans were struggling to keep population levels up, but now in an era of overpopulation, that does not seem very important. I still want Country _C_ to have women in its military."

Note that in this dialogue between Person _A_ and Person _B,_ there is no disagreement in any matters of fact. Person _A_ keeps adding more and more beliefs about reality ("is" statements) into the mix, and Person _B_ readily agrees with them. However, whenever Person _A_ tries to infer a moral sentiment ("ought" statement) from the agreement, Person _B_ disagrees.

In the dialogue, if Person _B_ were to agree with what appears to be implicit premise of Person _A_ – that Country _C_ should structure itself in such a way to maximize its reproductive potential – then this would seem to make Person _B_ more likely to accept Person _A’s_ conclusion. (There would probably be a lot more details to work out in the dialogue, but let us gloss over those for now.) In this way, agreement on an "ought" conclusion seems to _require_ agreement on another "ought" premise, in addition to agreement on a lot of a "is" premises. 

Thus there is nothing compelling someone to agree to an "ought" conclusion, even if said person agrees with all the "is" premises. There is nothing that forces someone to want things to be a certain way just because they are now a certain way, which results in a gap between beliefs about reality and moral sentiments such that one cannot infer the latter from the former.


## Beliefs about Reality Can Inform Moral Sentiments

While beliefs about reality, as we have seen in the preceding, do not imply moral sentiments, they can inform moral sentiments.

Imagine someone, "Person _D,"_ who is asked about another individual, "Person _E."_ Person _D_ reports having a generally approving opinion of Person _E._ Person _D_ recalls Person _E_ always being friendly and kind and thus has no reason to dislike Person _E._ Person _D_ might even call Person _E_ a "good person."

Next imagine that we have very good evidence that Person _E_ has been stealing Person _D’s_ money. We can imagine Person _D’s_ opinion of Person _E_ changing quite dramatically.

The moral sentiments of Person _D,_ in general, did not change. Person _D_ always had a disapproving attitude toward thievery in general and an especially disapproving attitude toward the thievery that victimized Person D in particular. However, the specific moral sentiment of Person _D_ with regard to Person _E_ changed dramatically because new information was learned.

In a previous section we reflected on how the property of truth or falsity is an essential property of beliefs about reality, and the outcomes we experience in response to a belief about reality is greatly influenced by the truth or falsity of the belief. This appears to be very much the case for moral sentiments informed by beliefs about reality as well. Much as the truth or falsity of our belief that it will rain tomorrow might leave us looking either wise or foolish depending on whether it actually does rain, Person _D’s_ disapproval of Person _E’s_ stealing could wind up being regrettable in hindsight if it turns out the Person _E_ did not actually steal Person _D’s_ money. Indeed Person _E_ might become angry about false accusations in this case.

However, let us continue this thought experiment with the assumption that the belief that Person _E_ stole Person _D’s_ money is true. Not only is this belief informing the moral sentiment Person _D_ has toward Person _E,_ it is quite possible for Person _D_ to acquire additional beliefs that would further inform Person _D’s_ moral sentiment toward Person _E._ For instance, imagine that Person _D_ learned that Person _E_ is the primary caretaker for several orphaned children and has been stealing Person _D’s_ money in order to take care of the orphaned children. We can imagine Person _D’s_ moral sentiment toward Person _E_ undergoing further development. It might have started with approval, became some sort of disapproval, and finally moved onto some more complicated sentiment in between.

All of this serves to illustrate that while beliefs about reality alone do not _imply_ moral sentiments, they can change our moral sentiments by providing us with more _information._ To use the shorthand of the preceding section, while "is" beliefs alone cannot imply "ought" sentiments, some combination of "is" beliefs and "ought" sentiments can lead to other "ought" sentiments, and adding additional "is" beliefs to this mixture can sometimes result in different "ought" sentiments. To use the language from an earlier section, how things actually are does not _determine_ how we want things to be, but how things actually are does _influence_ how we want things to be.


## Moral Sentiments Neither Imply nor Inform Beliefs about Reality

In the preceding two sections we examined the ways our beliefs about reality do and do not influence our moral sentiments. We now note that this is entirely a one way street. While beliefs about reality can inform – but not imply – our moral sentiments, our moral sentiments can neither imply nor inform our beliefs about reality. This follows from the fact that none of us have the mythical genie in a lamp granting us wishes, and merely wanting a certain state of affairs to be the case does not actually make it the case. No matter how passionate our "ought" sentiments are, these do not lend truth or falsity to any of our "is" beliefs.


### Reasoning from Goodness or Badness

Despite how self-evident a realization this appears to be, violation of it is an all too common fallacy. One of the more subtle ways this occurs is by reasoning based on whether some entity is "good" or "bad." For instance, if in the preceding thought experiment Person _D_ disregarded evidence that Person _E_ had stolen Person _D’s_ money because Person _E_ is a "good person," this would be an example of attempting to inform beliefs about reality from moral sentiments rather than the other way around. Whether or not Person _E_ did steal Person _D’s_ money is factual question that has a true or false answer regardless of how any of us feel about Person _E._


### Fault and Blame Instead of Cause and Effect

Another way in which we fallaciously attempt to inform our beliefs about reality with our moral sentiments comes from our tendency to assign fault or blame. Understanding cause and effect is one of the more useful ways to increase our knowledge. Armed with learnings about cause and effect, we can take a course of action more likely to lead to some desired outcome. However, discerning cause and effect typically requires much observation, experiment, and review. Assigning fault or blame, on the other hand, is arbitrary. One can blame whatever or whomever one wants, and one can assign fault wherever one wishes. A fallacy occurs when such assignment of fault or blame becomes a substitute for understanding cause and effect because it is an easier alternative.

Because there are many, many necessary conditions required in order for any outcome to take place, the fallacy of substituting fault or blame for cause and effect often takes the form of concentrating on one cause to the exclusion of others. For example, let us consider an individual who is exhibiting obesity, called "Person _F."_ Someone who wishes to blame Person _F_ might fault Person _F’s_ poor exercise habits and say that lack of exercise is "the cause" of Person _F’s_ obesity. Someone who wishes to excuse Person _F_ might fault Person _F’s_ genetic inheritance and say that genetics is "the cause" of Person _F’s_ obesity. In reality neither are "the cause" of Person _F’s_ obesity because there are many causes in the system of physiology that we are calling "Person _F"_ that lead to the emergent property we call "obesity." They are both causes of Person F's obesity. The effect we call "obsesity" can be analyzed from outside the system by looking at Person _F’s_ behavior and habits, or analyzed from within the system by looking at the internal response of adipose tissues to glucagon and insulin. It is not as simple as one thing being "the cause" of Person _F’s_ obesity.

Understanding cause and effect is to beliefs about reality what assigning fault or blame is to moral sentiments, so this is an example of attempting to use moral sentiments to inform beliefs about reality.


## Beliefs about Reality Take Priority over Moral Sentiments

We have seen that beliefs about reality do not imply moral sentiments, that beliefs about reality can inform moral sentiments, and that moral sentiments neither imply, nor inform beliefs about reality. We have arrived at the central conclusion of this meditation: beliefs about reality take priority over moral sentiments.

We can imagine an ideal scenario for arriving at a moral sentiment that occurs chronologically. First, without any regard to whether anything is "good" or "bad," we dispassionately and skeptically learn all the relevant facts of a matter. Then, only after we are satisfied we have learned the relevant facts, we perform an act of reflection on what we value, apply these values to the facts we have learned, and arrive at a moral sentiment. These two steps are best done separately since the first is an act of investigating the outside world and the second is an act of introspection.

Of course this ideal scenario never actually occurs. As we live and grow, we are perpetually acquiring new knowledge, learning that something we previously believed is actually false and disabusing ourselves of the belief, encountering something about which we form a tentative moral sentiment based on our existing knowledge, revising a moral sentiment as we learn more, etc. etc. Our actual experience is not as tidy as our chronological ideal. If we are to seek enlightenment while trying to make sense of ourselves in this messiness, we therefore must remember to enforce the priority of beliefs about reality over moral sentiments in our own minds, for time will not conveniently maintain this priority for us. 

To do otherwise is to inflict upon ourselves a profound and all too common fallacy. This occurs when a combination of moral sentiments and beliefs about reality entail some other moral sentiment that becomes such a part of our worldview that we begin to evaluate beliefs about reality based on whether or not they continue to uphold this moral sentiment.

This is when belief becomes ideology. This is where enlightenment goes to die. This is the anathema of those who value and pursue understanding. Of all the fallacies stemming from morality – and there are many – this is the greatest in its destructive power to an intellect.

To pursue enlightenment, beliefs about reality must be evaluated by whether they are true or false. Whether or not they uphold one’s moral sentiments are irrelevant. The pursuit of enlightenment entails that we are constantly questioning our beliefs, trimming beliefs that turn out to be false and adding new beliefs with the hope that they are true. Thus we can only pursue enlightenment if we do not let our devotion to a moral sentiment transfer to the beliefs about reality that informed it. This necessitates that we enforce the priority of our beliefs about reality over our moral sentiments. To do otherwise is to abandon the pursuit of enlightenment.


## Other Fallacies of Morality

While we have examined here what may be the greatest fallacy that stems from morality, it is not the only one. There are other obstacles to enlightenment that the mere separation of beliefs about reality from moral sentiments is insufficient to protect us from. These shall be examined in subsequent meditations, including on how [moral arguments are self-delusional](moral-arguments-are-self-delusional.html) and on how moral constructs are fictional. Furthermore I would be remiss to point out so many fallacies stemming from morality without a meditation on how to avoid these fallacies.
