---
author: "Joshua Born"
#bibliography: "../bibliographies/approval-of-abortion-is-conservative.bib"
#csl: "../bibliographies/chicago-author-date.csl"
date: 2023-04-02
draft: true
#include-before: |
#  ## Table of Contents
output:
  blogdown::html_page:
    number_sections: false
    toc: false
summary: "[Put summary sentence here.]"
tags: ["editorial", "first-person"]
title: 'Rhetoric about People "Who Look Like Me"'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE
)
```


On several occasions I have encountered writings decrying those who do not understand what it is like to grow up not seeing people who "look like you" in the popular media. It seems to have become routine for entertainers who win awards and who are not categorized as "White" to proclaim how they have paved the way and inspired young people who "look like me." The culture of what has been called "identity politics" has become salient in the United States. 

I will rapidly move past my annoyance at entertainers' exaggerated views of the importance of entertainers to human civilization and their own self-aggrandizing attitudes. However, I will allow myself to ruminate on a much more profound sense of annoyance I feel whenever I encounter these statements. 


## Two Kinds of "Representation"

I am someone who is categorized as "interracial" by the rest of United States society. This is not a unique experience to me, and I do not view this categorization as a part of my core identity. If I were asked to summarize the attributes I find to be most important for someone to understand who I am, being categorized as "interracial" would likely not even make the top ten. However, my "interracial" status is important for understanding my disgust at the "people who look like me" rhetoric. 

I grew up without people who look like me in the popular media. Any experience that race-identifiers -- i.e., those who happily categorize themselves as "White," "Black," "Hispanic," "Asian," "Indigenous," etc. -- might have had leading them to complain about lack of "representation" in popular culture, I experienced even more so.

My experience lacking this kind of representation was multiplied by the fact that people categorized as "interracial" comprise even less of the cast of popular culture than race-identifiers, and those categorized with the same specific combination of racial categories with which I am also categorized comprise even less of the cast of popular culture than this.

Throughout my life, I have struggled for representation, and I have searched in vain for what might be termed "my people." However, I could not care less that I did not grow up seeing people who look like me on television.

Instead, I have struggled to be represented for my ideas, my values, and my desire to contribute to human knowledge. My people are not (necessarily) those who look like me, but those whose worldviews and activities overlap with mine. My people are those who could be my colleagues, rather than my doppelgangers.

I would even welcome a kind of representation in which others at least stop misrepresenting my views. This would require the stupidity that is political partisanship to be attenuated enough for a more intelligent public discourse to emerge. That is a world so far removed from the one in which I live that it seems like a fever dream to write about it in so many words, so I expect tomorrow to once again wake up to a world of hatred and demagoguery. 


## Honesty in Superificiality

There is at least an honesty in the "who look like me" rhetoric. It is quite open in proclaiming just how superficial it is. The concept of a human being described in the "who look like me" rhetoric is based on appearance, and _just_ appearance.

I unironically appreciate this honesty because there are those who have attempted to make the pseudo-genetic nonsense that is racial categorization seem more informative and reclaimable by asserting it to be a proxy for culture. This has always seemed a facile argument to me because [culture is something you learn, do, and teach](/kwame-anthony-appiahs-criticism-of-cultural-appropriation-criticism.html), not a category to which you are assigned in your youth and you use to check boxes on demographic forms.

The "who look like me" rhetoric renounces this duplicity of defending racial identity by conflating it with culture. Instead of defensively trying to evade judgements of superficiality, the "who look like me" rhetoric embraces the true superficiality of racial identity and proudly proclaims the superficiality as [essential](/essentialism.html) to one's core identity.

Instead of trying to dissuade the world of the stereotype that Americans are culturally inept, the "who look like me" rhetoric accepts our cultural ineptitude. By the logic of "who look like me" rhetoric, what is the difference between a German and a Pole or between a Japanese and a Korean, provided, of course, they look similar to each other? The first pairing is "White people" and the second pairing is "Asian people" and that is all you need to know. Knowledge of language, history, or customs is irrelevant. (Indeed, one cannot possibly imagine any history one should be aware of in either of these relations.)

The "who look like me" rhetoric does not hide behind specious intellectual arguments, and so allows a discerning mind to see it for what it is and to judge it for what it is.


## Further Writing

I have always been a square peg in a round hole. I have never found my people. This is due to the nonconformity of my views, not because of my appearance, at least not directly...

Of course, my failure to achieve my kind of representation is not just the fault of the society in which I live, but my fault as well...

I have been in my personal experience a kind of human Rorschach test...


## Citations

::: {#refs}
:::

## Footnotes
