---
title: "Skeptical Metamorality"
draft: true
#date: 2018-11-11
tags: ["worldview", "third-person"]
bibliography: "../bibliographies/skeptical-metamorality.bib"
#csl: "../bibliographies/apa.csl"
link-citations: true
implicit-figures: true
output:
  blogdown::html_page:
    md_extensions: ["+footnotes"]
    toc: false
    toc_depth: 5
include-before: |
  <p></p>
  <!--more-->
---

## Truth or Falsity of Beliefs

The words "true" and "false" are just symbols, and symbols can be used in a variety of ways. The definition of "truth" used here is different than that used by those who are apt to say "speak your truth" to denote things that are subjectively important to someone. Instead, "truth" is used here to describe a relationship between a mental model and the external world.[^external]

[^external]: This article uses the phrase "external world" to denote everything in the cosmos except for the contents of a _specific_ mind.

A mind might have a belief. This is a representation of how the mind perceives the world external to the mind. When a belief accurately models the external world, it is a _true_ belief. When a belief in a mind and the world external to the mind are not in agreement, this is a _false_ belief.[^correspondence]

[^correspondence]: This is a correspondence definition of truth. There are also coherence definitions of truth, which in philosophical jargon are called _"a priori,"_ "analytic," "necessary," or "relations of ideas." This kind of truth comprises things that are true by definition, such as "1 + 1 = 2" or "bachelors are are unmarried men." These kinds of true beliefs are _tautologies_, i.e., they refer to the same thing twice. These kind of tautologies are only more interesting than more obvious tautologies like "2 = 2" or "bachelors are bachelors" in as much as they refer to the same thing with different symbols. This inquiry regards tautologies as not useful for understanding morality because they merely beg the question. For instance, if one were to be questioned as why one felt that stealing is wrong, and one replied "because I have defined 'wrong' that way," this would not add to anyone's understanding.

![
_A diagram illustrating truth conditions in which a mental model corresponds to the external world._<br/>
](/images/image.svg)

Beliefs are, in practice, rarely true or false in isolation. In order to examine truth or falsity, many interrelated beliefs are examined at once. For instance, if someone believes that a certain sack is approximately 20 kilograms in weight, in order to examine that belief, other beliefs that comprise expectations about how heavier objects behave relative to lighter objects and how to measure weight must also be held in order to examine whether the belief about the sack is true or false.

Because of this, instead of truth or falsity being discussed as properties of individual beliefs, this inquiry examines truth and falsity as properties of a _mental model_. A mental model includes a particular belief and all the other related beliefs necessary in order to test this belief. These kind of mental models are _descriptive,_ in that they attempt to model how things actually are.

![
_A diagram illustrating falsity conditions in which a mental model fails to correspond to the external world._<br/>
](/images/image.svg)

## Belief Revision

A common definition of knowledge is justified, true belief. Thus, if a mental model is true, and if the mind that has the mental model is justified in having the mental model, then the mind _knows_ something about the external world.

No mind ever has complete and perfect knowledge of the external world. Therefore, it is prudent for a sound mind to allow for revision of its mental models. Descriptive mental models try to explain and predict phenomena in the external world. However, the explanations and predictions of _false_ descriptive mental models are flawed. Therefore, a sound mind will always try to amend false mental models in order to make them true.

The totality of the external world cannot, in practice, be observed by any given mind. Some specific circumstances of the external world can, however, be partially observed. These observations constitute _empirical evidence._

When a mind encounters evidence that is consistent with the predictions of a descriptive mental model, then it is prudent for the mental model to persist. _When a mind encounters evidence that contradicts a descriptive mental model, then it is prudent for the mental model to be amended,_ in order to better agree with the external world. Thus, empirical evidence prompts the revision of false beliefs to better approximate true beliefs.

![
_A diagram illustrating belief revision, in which the false beliefs of a mental model are changed to be in agreement with the external world after empirical evidence is observed._<br/>
](/images/image.svg)


## Moral Sentiments

Morality can also be construed as a kind of mental model. However, moral sentiments do something other than simply try to represent the external world. Mere modeling of _how things are_ does not constitute morality. For instance, merely believing that there is stealing in the world as a matter of fact does not constitute a moral sentiment. Morality models _how things should be._

![
_A diagram illustrating a mental model that fails to constitute moral sentiments._<br/>
](/images/image.svg)

Moral sentiments occur when there is a _judgment_ or _prescription_ about the external world. For instance, a _moral_ mental model does not merely believe that there is stealing in the world, but judges stealing to be wrong. Moral mental models are _normative,_ rather than descriptive. They do not have implications that explain or predict phenomena, but instead have implications that prescribe certain behavior (e.g., "be kind to one another") and proscribe other behavior (e.g., "do not steal").

More specifically, moral sentiments judge or prescribe the behavior of certain individuals in the external world. Few human beings morally judge the behavior of rocks or the behavior of plants.[^animals] Human beings tend to judge the behavior of other human beings and of themselves. The individuals whose behavior are judged in this way, by any specific mind, are its _moral agents._

[^animals]: Some human beings do judge the behavior of non-human animals, such as in animal trials in medieval Europe or in circumstances in which there is a household pet, while some human beings do not ascribe moral agency to non-human animals, so this is more of a gray area.

![
_A diagram illustrating a moral mental model._<br/>
](/images/image.svg)


## World Revision

While both true-or-false beliefs and moral sentiments constitute kinds of mental models, an important difference occurs in how these mental models react to contradiction with observations of the external world. Earlier it was seen that when a descriptive mental model and the external world are in disagreement, it is prudent to amend the mental model to fit the external world. However, with moral sentiments, _when a normative mental model and the external world are in disagreement, the mind tries to amend the external world, not the mental model._

![
_A diagram illustrating a moral mental model._<br/>
](/images/image.svg)

It is against the spirit of morality to have the moral sentiment that stealing is wrong, observe an incident of stealing, and then conclude, "I guess I was mistaken. Stealing is righteous." Rather, someone who has the moral sentiment that stealing is wrong and who observes an incident of stealing is expected to censure the act, try to prevent the thief from leaving with the stolen item, call the authorities, report the act, or, with a longer view, investigate the root causes of theft in society and attempt to remedy them. In other words, the purpose of a normative mental model is to amend the external world or, at the very least, the actions of moral agents.

![
_A diagram illustrating a moral reaction to the observation of the act of stealing._<br/>
](/images/image.svg)

Thus, descriptive mental models and normative mental models are diametrically opposed in how they handle observations of the external world that contradict the mental model. These contradictions lead to a change of the mental model in the descriptive case, but lead to attempts to change the external world in the normative case.


## No Moral Truth or Moral Knowledge

For a worldview that accepts these definitions of truth, belief, and moral sentiment, it must be concluded that inquiring as to the truth of moral sentiments _is a mistake_, in the same way it is a mistake even to ask about the color of a taste or the odor of a touch. One is simply asking the wrong kind of question in these cases.

There are no conditions under which a moral sentiment is false, because any disagreement between the external world and a normative mental model is judged to be a fault of the external world, not the mental model. Indeed, this is the very point of moral judgment.

Where there is not even an opportunity for falsity, there is neither the possibility of truth. Thus, there are no moral truths. A direct consequence of this and the earlier definition of knowledge is that there is no such thing as moral knowledge. Moral knowledge is impossible, not due to any limitation of the human condition, but because the very concept of moral knowledge is nonsensical.

In philosophical jargon, this position is termed "moral skepticism" because it denies the possibility of moral knowledge.


## Linguistic Mixing

Since true-or-false beliefs and moral sentiments are different and are even in a certain sense opposite, and because true-or-false beliefs and moral sentiments are evaluated in different ways, it is best to distinguish between the the two in order to maintain clear thinking. Unfortunately, human beings speak, hear, write, and read natural languages, and natural languages obfuscate attempts to achieve such clarity by often mixing the expression of the two. 

Two individuals can relate the same facts, but one individual might label a faction "terrorists," while the other individual might use the phrase "freedom fighters." Indeed, the two individuals might have the exact same descriptive mental models about what has actually happened. However, the _connotation_ of the language used differs between the two individuals. The connotation of the first includes a disapproving moral sentiment, while the connotation of the second includes an approving moral sentiment.

Such connotations lead to a mixing of true-or-false beliefs and moral sentiments at the level of language. Because of this, and because human beings encounter a lot of language usage in their daily lives, often the first encounter one has with a new true-or-false belief also includes moral sentiments mixed with it, and the first encounter one has with a new moral sentiment also includes true-of-false beliefs mixed with it.

Thus, true-or-false beliefs and moral sentiments do not come partitioned in a neat package, properly separated and labeled. Instead, a sound mind must consciously and deliberately do such partitioning itself in order to maintain clarity in its thinking.


## The Method of Attitudinal Propositions

Doing such a mental partitioning can be facilitated by the realization that moral sentiments can readily be translated into descriptive beliefs _about the normative mental models themselves._ Such a belief can be termed an "attitudinal proposition" because it is a belief about a mind's attitude toward something.

For instance, if an individual named Zhaohui says, "stealing is wrong," then the corresponding attitudinal proposition is "Zhaohui disapproves of stealing" or "Zhaohui is morally opposed to stealing" or "Zhaohui feels that stealing is wrong."

While it makes no sense to attempt to evaluate the truth or falsity of the moral sentiment "stealing is wrong" itself, descriptive mental models _can_ be correct or incorrect _about_ Zhaohui's normative mental model. From the perspective of the more than seven billion human minds on the Earth, Zhaohui's mind is part of their external world.

![
_A diagram illustrating a true belief about an attitudinal proposition._<br/>
](/images/image.svg)

Such attitudinal propositions make a different kind of claim than the objective statement that "stealing is wrong." They make claims about subjective mental states, claims that are true or false.

![
_A diagram illustrating truth and falsity for attitudinal propositions. The upper left and lower right diagrams illustrate true beliefs about attitudinal propositions. The upper right and lower left diagrams illustrate false beliefs about attitudinal propositions._<br/>
](/images/image.svg)

Thus, while there are no moral truths and no moral knowledge, there can be truths and knowledge about moral sentiments. 

One can quietly make this sort of translation from moral sentiments to attitudinal propositions in one's own mind. Furthermore, doing so as a matter of habit rescues a truth from a sort of dialogue that consists of untruths. These habitual translations thus create an opportunity to gain new knowledge and make a learning experience out of what, taken at face value, would not be an opportunity to learn.


## Moral Constructs

Sometimes moral sentiments are expressed in very literal, self-aware terms, e.g., "I am a vegetarian because I am ethically opposed to eating animals." However, sometimes moral sentiments are expressed in terms of abstract concepts, such as justice, virtue, etc. When they appear in the predicate of statements, these normative _moral constructs_ can readily be translated to descriptive beliefs by the method of attitudinal propositions.

"This is a just war" can be translated to the belief that the speaker morally approves of the war in question, and "this war is unjust" can be translated to the belief that the speaker morally disapproves of the war. "Practicing birth control is virtuous," can be translated to the belief that the speaker morally approves of birth control, and "using abortion as a method of family limitation is vicious" can be translated to the belief that the speaker [morally disapproves of the use of abortion as a birth control method](/margaret-sanger-on-abortion-in-her-own-words.html).

However, sometimes these moral constructs appear not just in the predicates of statements, but assume an existence of their own, appearing as the subject of statements. For instance, the word "good" is understood to mean something that is desirable when predicated of a physically existing subject, but in ancient Greek philosophy it was fashionable to speak about "the Good," as if it were a thing in and of itself. Likewise, today some individuals create elaborate theories of justice, perhaps with an uppercase "J" in "Justice." For a time it was fashionable for European thinkers to speak of "Nature and Nature's laws" with an uppercase "N."

The issue with moral constructs used in this way is that they do not refer to anything, except perhaps to the normative mental models that in exist in someone's mind. Statements such as "the Good is not multiple, but One" are not amenable to the method of attitudinal propositions. It is not clear what the speaker of such a statement approves of or disapproves of.

Furthermore, statements such as these use language in a way that is used to refer to phenomena of the external world that have a physical existence independent of minds, such as gravity, oxygen, or tectonic shift, rather than to refer to normative mental models. This opens the way for the delusion that the subscriber to these moral constructs has discovered something about the non-mental world[^non-mental] and thus has some sort of moral knowledge.

[^non-mental]: This article uses the phrase "non-mental world" to denote everything in the cosmos except for the contents of _any_ mind. This is a more restrictive class than what is referred to by "external world."


### Delusions of Moral Knowledge

However, as has been seen, it is a mistake to attempt to apply the properties of truth or falsity to moral sentiments, and thus there is no moral knowledge.

Worldviews that purport to have moral sentiments that constitute objective knowledge of the external world are called "moral realism" in the philosophical jargon. Unfortunately, moral realism has been one of the most common if not the most common metaethical positions in the history of Western philosophy taught in academic settings, and so one is liable to encounter many moral constructs when perusing published thinking about ethics.

While academic philosophy is notoriously irrelevant to the daily lives of the masses, this is not just a recondite disagreement. To the worldview articulated here, those who use moral constructs in a moral realist way are delusional, and they are delusional in a particularly offensive way. [...]

This is not just a theoretical conflict. In contemporary life one need not look very far to find those pontificating their own pet ideas of what "justice" is. Morally contentious issues such as abortion are often framed in terms of moral constructs such as "personhood." [...]

The fundamental issue is that moral constructs are themselves invented by a normative mental model and so cannot _justify_ the normative mental model. A good example occurs in the distinction between civil rights and so-called "natural rights" or "human rights."


### Interpretations of Statements about Moral Constructs

For morally skeptical worldviews, the issue of how to interpret statements about moral constructs remains. There are at least three major ways.

#### Error Theory

One interpretation is to take statements about moral constructs at face value. Statements about "justice," "virtue," "righteousness," etc, are _trying_ to describe some feature of the world external to minds. However, since there are no features of the nonmental world such as such justice, virtue, righteousness, etc, to describe, all of these sort of statements fail. Therefore, all such statements about moral constructs are false, because they are trying to be descriptive beliefs, and judged by the standards of descriptive mental models, they have no truth. This is an _error theory_ of morality. [@mackie_ethics_1977]

#### Noncognitivism

Another interpretation notes that not all syntactically correct sentences of natural languages form a meaningful thought. For instance, the sentence "purple ideas sleep furiously" is a syntactically correct sentence of the English language, but it is nonsense and meaningless. Puzzling over such a sentence is a waste of time. This interpretation views statements about moral constructs in a similar light, judging them to be meaningless, in a literal sense. (They might still have connotations, even if they refer to nothing.) This is ethical _noncognitivism._ [@ayer_language_1946]

#### Useful Fictions

A third interpretation of statements about moral constructs is that they are fictions, like a fable. Under this interpretation, one might continue to use moral constructs, provided one realizes they are not to be taken literally. Instead, they are _useful fictions_, intended to remind individuals to act in accord with some moral system. However, this is a dubious interpretation, since it requires everyone speaking, listening, writing, and reading about moral constructs to be consciously aware that moral constructs do not actually exist. The worldview articulated here does not recommend this practice, and this interpretation is included only for the sake of completeness.

Whether interpreted as false, meaningless, or fictitious, the important implication of moral skepticism regarding moral constructs is that statements about them do not represent knowledge. Such statements are not true, in the sense of truth defined here, and do not tell us anything about the non-mental world.


## Conclusion

The strain of moral realism popular in the history of Western philosophy would portray morality as a quest for objective truths and moral knowledge. Moral skepticism as articulated here rejects this approach to morality. While this clarifies what morality is not, it does not identify what morality actually is. 

The worldview articulated here identified moral sentiments as normative mental models. Thus, it identifies morality as a psychological construct. Since moral sentiments of any one person are influenced by those around them, morality is a socio-psychological construct.

![
_A diagram illustrating moral self-awareness._<br/>
](/images/image.svg)

At the same time that the metaethical position articulated here implies that traditional moral philosophy is not a worthwhile pursuit, it points to the moral psychology as a way to truly understand morality.

This may seem to have little relevance for anyone outside of academic pursuits. Most individuals lack the time and resources to do psychology (though many at least have the time and resources to study the work of others). 

There is also an important implication relevant for all individuals, regardless of vocation. It is that moral enlightenment does not come from moral truths, nor does it come from the vain invention of abstract moral constructs intended to rationalize sentiments one already has, but comes from introspection. The best one can do is to _know thyself,_ as the ancient maxim goes. [...]



## Citations

::: {#refs}
:::


## Footnotes
