---
author: "Joshua Born"
bibliography: "../bibliographies/they-them-those-people-and-the-fallacy-of-partisan-demagoguery.bib"
csl: "../bibliographies/chicago-author-date.csl"
date: 2022-06-14
include-before: |
  ## Table of Contents
output:
  blogdown::html_page:
    number_sections: false
    toc: true
    toc_depth: 5
summary: 'Characterizations of partisan factions lead to the Straw Man Fallacy and to a kind of No True Scotsman Fallacy, and they empower polarized viewpoints at the expense of independent thinkers.'
tags: ["fallacies", "first-person"]
title: '"They," "Them," "Those People," and the Fallacy of Partisan Demagoguery'
---

```{r setup, include=FALSE}
library(here)

i_am('content/they-them-those-people-and-the-fallacy-of-partisan-demagoguery.Rmd')

knitr::opts_chunk$set(
  echo = FALSE
)
```

## Introduction

In the past, I have written about [fallacies](/tags/fallacies.html) in social criticism that I have largely overcome. For instance, once I became aware of the practice of [listing confirmatory examples](/selection-bias-and-the-fallacy-of-listing-examples.html) of some phenomenon and how this proves nothing about the prevalence of the phenomenon, I have largely stopped doing it. Similarly, [generic thinking](/fallacy-of-generic-thinking.html) is something that I used to consciously do, but once I read about it and reflected upon it, I have mostly purged it from my thinking -- with one major exception. The exception is the description of a "they," "them," or "those people,"  which is the topic of this article. I write this article in the first-person because even though I am aware of the fallacies I am describing herein, I still -- much to my chagrin -- catch myself characterizing "those people."

In the United States, conservatives spend a lot of time and energy talking about leftists,[^leftist] and leftists spend a lot of time and energy talking about conservatives. Unsurprisingly, most of this time and energy is spent describing the other group as bad. A similar sort of phenomenon can be seen in many different times and places across the Earth whenever there is an opportunity for binary sorting into an "us" and a "them." This is the most obvious context in which the fallacies discussed in this article occur.

[^leftist]: The use of the word "liberal" is avoided in this article because the term "liberal" is heavily confounded. While it is often used to refer to leftist politics in the United States, "liberal" parties in many other countries are right-wing or center-right parties. Furthermore, even in the United States, "neo-liberal" economic policies and "classical liberal" political philosophies are often associated with right-wing or libertarian positions.

However, mine is a strange case in that I have become quite habituated to being a perpetual "other." I find myself not at home with conservatives, nor with leftists. I am equally alien among libertarians. While moral compunction about induced abortion of pregnancy as a method of fertility control has motivated my desire to work on contraception, this has left me feeling even less represented. Every now and again I search for organizations that might represent my views on reproductive responsibility, and fail to find any.[^closest]

[^closest]: The closest I have found are small, niche organizations such as [Secular Pro-Life](https://secularprolife.org/). While my worldview has a lot of overlap with the worldviews of such organizations, they are all far too small to fund a social science think tank.

Sure, there are those organizations opposed to abortion as a method of fertility control, but those that frame themselves in religions terms or focus on politics do not represent what I do. On the other hand, there are organizations which study contraception, but all of those I have encountered explicitly advocate for abortion as method of fertility control.[^guttmacher] Thus, while I occasionally write about the [early birth control movement](/margaret-sanger-on-abortion-in-her-own-words.html) and wish I had such a community today, I mostly just do my work by myself.

[^guttmacher]: To be fair, the Alan Guttmacher Institute is the only organization I have encountered that does substantial social science research on contraception.

In short, I do not feel like I have an "us." I therefore find it even more perplexing that I still find myself committing the fallacy of characterizing what "they" do that bothers me, what I think of "them," or my differences with "those people."

Upon reflection, I have realized that these kinds of thoughts are worthless and should be purged from my thinking. Instead, I should stay centered on my own activities and on being productive in them, and consider the thoughts of the specific other individuals I actually encounter in my life, rather than populate my mind with the fallacies I describe in the sequel.

By extension, it is also prudent for me not to waste my time engaging with other people preoccupied with the act of characterizing "them" -- e.g., a conservative complaining about the "liberals" again or a leftist complaining about conservatives for the five thousandth time.

Of course, not _every_ description of "them" is fallacious. However, for me, sentiments expressed about "they," "them," or "those people" now constitute signals for further scrutiny. Whenever I encounter such signals, whether in my own thinking or the thinking of someone else, I stop to scrutinize whether the fallacies I describe in the sequel are being committed. If so, I excise the sentiments as worthless. If I have discovered such fallacies in my own thinking, I stop that line of thought. If I have discovered such fallacies in the thinking of someone else, I stop giving such sentiments further consideration.


## Fallacies

When we engage in demagoguery about "they," "them," or "those people," there is not one specific fallacy we commit. Any particular instance of demagoguery might consist of one or more of the fallacies described below, and perhaps others.


### Straw Man

The "Straw Man Fallacy" refers to the act of refuting a position that has been imagined by the person doing the refuting for the purposes of refuting it. The name "straw man" is many centuries old, and it is not clear what this originally referred to. We might speculate it originally referred to a dummy created for martial training or to an effigy of a person burned in public to express contempt with the person. Regardless of the origins of the name, the Straw Man Fallacy is commonly involved in partisan demagoguery.

![
Anticommunist demonstrator kicks burning effigy of Viet Cong soldier during unruly protest outside Saigon headquarters of International Commission of Control and Supervision in Saigon, Jan. 6, 1975.<br>
["Vietnam War - Fall of Saigon"](https://www.flickr.com/photos/13476480@N07/19413130456)
by
[manhhai](https://www.flickr.com/photos/13476480@N07/)
is licensed under
[CC BY 2.0](https://creativecommons.org/licenses/by/2.0/)
and is not modified.
](/images/effigy.jpg){alt="A banner-waving crowd is gathered around a man who is kicking an effigy burning on the ground."}

Firstly, the Straw Man Fallacy comes up in cases in which we are talking about "they," "them," or "those people," but "they" are not present. Thus, we are referring to some characterization of "them" that we are inventing ourselves. This occurs when someone complains that "those evil socialists want to steal the hard-earned fruits of our labor because they are too lazy to work" or "the evil capitalist class wants to crush our revolution so that they can exploit the workers." When these statements are made when no "evil socialists" or "evil capitalists" are present to hear them, the fallacy allows us to characterize the motives and intent of the referent of "they," since "they" in this case refers to nothing more than an image we construct in our own minds.

Secondly, a more subtle version of the Straw Man Fallacy occurs when we refute not a concern that someone has, but some other argument, and hope that no one notices.

For instance, suppose that we are advocating for a new tariff, and someone criticizes it, saying, "I do not think this tariff is a good idea because it will cause our imports and exports to decrease, and many elements of our economy depend on international trade."

Someone else might reply, "This tariff _is_ a good idea because the new tariff will generate revenue for the government. With this new source of money, the government will not have to look for money elsewhere, such as in raising income taxes. Therefore, the new tariff will not lead to higher income taxes."

This is another instance of the Straw Man Fallacy. The criticism of the tariff was with regard to its possible effects on import and export trade, but the response completely ignored that concern, invented a different concern with regard to income taxation, and refuted this newly invented argument.

Thus, when we are engaged in talking to ourselves or to our own echo chamber about "they," "them," or "those people," this kind of Straw Man Fallacy easily enters into our characterizations, even when we appear to be responding to statements made by whoever "they" are.


### Reverse No True Scotsman

This segues into another fallacy that often occurs when we engage in partisan demagoguery: we _choose_ who "they" are. Therefore, our characterizations of "they," "them," or "those people" are arbitrary. If we want to characterize "them" as bad, we can exclude individuals whom we judge to be doing good things or having good motives and only include people whom we judge to be doing bad things or having bad motives. This is a version of what is typically called the "No True Scotsman Fallacy."

In a prototype of the No True Scotsman Fallacy, an enthusiast of Scottish culture might say, "Scotsmen are brave and never retreat in battle."

Someone else might say, "I was with Adair in the Great War during our retreat, and Adair is a Scotsman."

The fallacy occurs when the enthusiast replies, "well, then, Adair is no _true_ Scotsman."

![
["Old Photograph Scottish Soldiers"](https://www.flickr.com/photos/53986137@N04/5062003373)
by
[Sandy Stevenson](https://www.flickr.com/photos/tourscotland/)
is licensed under
[CC BY-NC-ND 2.0](https://creativecommons.org/licenses/by-nc-nd/2.0/)
and is not modified.
](/images/scottish-soldiers.jpg){alt="Four men in kilts and military uniforms run while carrying machine guns."}

In the No True Scotsman Fallacy, the fact that [categorization is arbitrary](/category-based-prejudice.html#categorization-is-arbitrary) is being exploited to include in a category only those individuals who are exemplars of a virtue you wish to associate with the category.

In the context of partisan demagoguery, the opposite of this is typically done. When we pick and choose undesirable individuals for inclusion in "them," we exploit the fact that categorization is arbitrary to associate individuals who exemplify a vice to associate with "they," "them," or "those people." This might be called a "Reverse No True Scotsman Fallacy."

One of the more conspicuously facile examples of this is what has been called _"reductio ad Hitlerum"_ after the Latin name for the fallacy _reductio ad absurdum._ This occurs when someone attempts to discredit a position because Adolf Hitler, the archetypal evil person of the 20th century, also did something or also held a similar viewpoint. For instance, if you learn that someone is a vegetarian, and you criticize this saying, "you know, Hitler was a vegetarian," then this would be a case of _reductio ad Hitlerum._[^reductio]

[^reductio]: This would only be a case of _reductio ad Hitlerum_ if this were shared as part of an attempt to _discredit_ vegetarians by associating them with Hitler. It is not in and of itself fallacious to share this bit of information as historical trivia.

Whether or not Hitler was a vegetarian has no relevance for the evaluation of someone else who is a vegetarian. However, picking Hitler as an example of what "those people" who are vegetarians are like is a rather fatuous attempt to discredit the character of "them," i.e., vegetarians.[^converse]

[^converse]: Note that the _reductio ad Hitlerum_ fallacy is not applicable to criticisms of warmongering or racial bigotry. We judge Hitler to be bad _because_ he did these things, not the other way around. Indeed, we would still judge warmongering and racial bigotry to be bad regardless of whether Hitler did or did not do them. The _reductio ad Hitlerum_ fallacy reverses this by attempting to infer not that Hitler is bad because of _X,_ but that _X_ is bad because Hitler did it.

The Reverse No True Scotsman Fallacy is slightly more connected to reality than the Straw Man Fallacy. In the Straw Man Fallacy, we ourselves invent the viewpoint that we wish to refute. In the Reverse No True Scotsman Fallacy, we go looking for someone who has a viewpoint that we wish to refute.

There is a lot of gray area between these fallacies. For instance, we could be talking with someone who is making one point, but then find a different point being made by someone else and refute that other point. This is a combination of the Straw Man Fallacy and the Reverse No True Scotsman Fallacy. From the standpoint of the person with whom we are actually having a conversation, this is a Straw Man Fallacy, though from our perspective, it is a Reverse No True Scotsman Fallacy.

To continue the example of vegetarianism, you might encounter someone who practices vegetarianism because of the desire to avoid the slaughtering and mistreatment of animals for the harvesting of meat. If you encountered such a person and brought up an historical figure who practiced vegetarianism for the alleged health benefits of avoiding the consumption of meat, and you proceeded to discuss studies that found no health benefits from a vegetarian diet, then this would be such a combination of the two fallacies.

![
["Vegetarian Meal"](https://www.flickr.com/photos/79721788@N00/13913960918)
by
[David Stanley](https://www.flickr.com/photos/davidstanleytravel/)
is licensed under
[CC BY 2.0](https://creativecommons.org/licenses/by/2.0/)
and is not modified.
](/images/vegetarian-meal.jpg){alt="A top-down view of a round plate that contains a colorful assortment of food."}

Indeed, because there are over 7 billion people on the Earth, the Reverse No True Scotsman Fallacy could, in theory, always be used to support the Straw Man Fallacy, because with so many people out there, it is probable that you could find at least one person who has any viewpoint you could possibly imagine and want to discredit. Thus, in practice, there is overlap between the two fallacies.

The major difference between the two fallacies, however, is in _how_ they are fallacious. In a purely Straw Man Fallacy, you are refuting a position you yourself are inventing, and the act of _inventing the viewpoint_ is itself disingenuous. In the Reverse No True Scotsman Fallacy, someone in the world actually does have the viewpoint you want to refute, so the act of refuting it is not itself disingenuous _per se._ In this latter case, it is only disingenuous for you to attempt to characterize someone else who does not have the viewpoint -- such as the person with whom you are actually having a conversation --  as having the viewpoint by associating the viewpoint with what "they" think.

Thus, the Reverse No True Scotsman Fallacy in the context of partisan demagoguery is a particular kind of [generic thinking](/fallacy-of-generic-thinking.html), and as this case illustrates and as I discussed in my article on generic thinking, one of the reasons generic thinking is fallacious is that it is useful for little other than [prejudice](/category-based-prejudice.html). This is precisely what occurs when a viewpoint is selected in an attempt to characterize what "they" think.


### Empowering Partisan Polarization

The previous two sections discussed reasons for avoiding partisan demagoguery pertaining to the disingenuous aspects of the practice, and intellectual honesty _per se_ is a good reason to reform your thinking. However, there is another concern that convinced me to purge specious characterizations of "they," "them," or "those people" from my thinking: the more you think in terms of partisan factions -- even to criticize them -- the more you empower them. Indeed, I noticed that the more I complained about various factions of "they," "them," or "those people," the more ubiquitous, threatening, and oppressive "they" seemed to me.

One of the important lessons to learn from studies such as _[The Hidden Tribes of America](https://hiddentribes.us/)_ is that polarization has led to relatively small clusters of people in the United States who are more engaged with politics and with social media than the rest of the "exhausted majority" who feel less represented by politics and are less engaged with social media.

It is important to remember, then, that your anecdotal experience with media -- both social media and conventional media -- is _not_ a representative sample of viewpoints in the general population. There is _more_ diversity of viewpoints in the real world than engagement with media would lead you to believe. Even direct conversations with other people might be misleading, if people in the polarized clusters feel more empowered to share their viewpoints than the "exhausted majority." Despite how it seems, "those people" are _not_ ubiquitous.

The realization I had which convinced me to rid myself of partisan characterizations is that in complaining about "they," "them," or "those people," I was inadvertently accepting the framing of binary polarization, even when I was trying to criticize it. I was giving even more representation to those in the polarized clusters -- who are already over-represented -- and less of a platform to the diversity of viewpoints in the "exhausted majority" -- who are already under-represented.

This is a phenomenon that is important for my thinking because, as I described in the introduction, binary political polarization around induced abortion of pregnancy has ruined my ability to find a constituency. This is a topic worthy of a fuller treatment in its own article, but suffice it to say that the two polarized viewpoints -- that of religious conservatism and that of the ideology of abortion as women's liberation -- are not the only two viewpoints available to the human mind. Framing discourse in this way, even when attempting to criticize the polarization, aids the polarized factions in their efforts to crowd out alternative viewpoints.


## Conclusion

Sorting the world into an "us" and a "them" and denigrating "them" is one of the human mind's most base and primitive tendencies, which leads to intellectual flaws like the Straw Man Fallacy and a fallacy of association called the "Reverse No True Scotsman Fallacy" in this article. It is possible, even if you do not feel like you have an "us," to still get caught up in the act of demagoguery about "them," in a misguided attempt to channel disgust about the simpleminded conformists who comprise the factions of partisan polarization.

However, denigrating "they," "them," or "those people" both invites the very same fallacies of the partisan mind into your own thinking and frames discourse in a way that further empowers polarized factions at the expense of independent thinkers.

There is a folk story attributed to Cherokee tradition about a lazy rabbit who at night would sneak to a well belonging to other animals and steal water. [@mooney_james_1992] In order to stop this, the other animals created a wolf effigy made out of tar and placed it next to the well. When the rabbit next came to steal water, it first threatened this tar wolf. Frustrated that the wolf did not respond, the rabbit struck it with its paw, causing the rabbit to get stuck. The rabbit demanded to be let go, but the wolf said nothing, angering the rabbit even more, so the rabbit kicked it. This process continued until the rabbit was completely stuck to the tar wolf.[^rabbit]

[^rabbit]: It is not relevant for the analogy used here, but in most stories the rabbit eventually does get away by fast talking after the other animals come and release the rabbit from its tar trap.

Partisan demagoguery is like that tar wolf. The more you let it anger you and the more you lash out at it, the more caught by it you become. Such is polarization. Had the rabbit simply walked past the tar wolf, it could have had its fill of water from the well and gone on with its life unmolested. Likewise, the only way to avoid the trap of fallacies created by partisan polarization is to be a better person and metaphorically walk past it.


## Citation

::: {#refs}
:::


## Footnotes
