---
author: "Joshua Born"
bibliography: "../bibliographies/top-four-needs-for-future-contraceptive-technology.bib"
csl: "../bibliographies/chicago-author-date.csl"
date: 2022-07-24
draft: false
include-before: |
  ## Table of Contents
output:
  blogdown::html_page:
    number_sections: false
    toc: true
    toc_depth: 5
summary: 'Methods both long-acting and reversible, non-hormonal methods, methods for men, and intrinsically more effective methods are urgent needs for contraception.'
tags: ["opinion", "contraception", "birth control", "third-person"]
title: 'Top Four Needs for Future Contraceptive Technology'
---

```{r setup, include=FALSE}
library(here)

i_am('content/top-four-needs-for-future-contraceptive-technology.Rmd')

knitr::opts_chunk$set(
  echo = FALSE
)
```

## Introduction

With over 80 million unintended pregnancies and over 40 million induced abortions every year worldwide [@sedgh_intended_2014], it is abundantly clear that the current state of contraception is inadequate.

This should not be surprising because human civilization is still in a very primitive stage of its contraceptive practice. Despite the relative affluence and technological development of the United States, many of the [most popular contraceptive methods in the United States](/use-of-contraception-in-the-united-states-2017-2019.html#methods-used) today -- such as the male condom or the practice of _coitus interruptus_ a.k.a. withdrawal -- are so ancient that their origins are forever lost to history or perhaps prehistory. Indeed, contraception itself in the United States [has only been legal for about a century](/margaret-sanger-on-abortion-in-her-own-words.html#who-was-margaret-sanger).

Furthermore, innovation of contraceptive technology has been mostly stagnant since the development progestin and estrogen based methods, which were originally developed in the 1950s. [@eig_birth_2016] Since then, different modalities for administration of such hormones have been developed in addition to the original oral pill modality, such as injectables, implants, or inclusion in intrauterine devices (IUDs). However, aside from the path of delivery of the hormones and the exact chemical analog of the hormones used, all of these modalities work in basically the same way.

Thus, there has not been a truly new method of contraception invented in approximately 60 years.

![
["One item in the 1960's history of Oakland is a package of Ovral birth control pills"](https://www.flickr.com/photos/34464825@N00/6715866381)
by
[benjamin sTone](https://www.flickr.com/photos/34464825@N00/6715866381)
is licensed under
[CC BY-NC-SA 2.0](https://creativecommons.org/licenses/by-nc-sa/2.0/)
and is not modified.
](/images/pills.jpg){alt="A pack of birth control pills decorated with sketches of flowers and a butterfly is placed next to a label identifying it as from June 14, 1971 in a museum display."}

It would therefore be tempting to attribute the aforementioned 80 million unintended pregnancies annually to this deficiency of innovation in contraceptive technology. This attribution is probably accurate, but only partly so. Somewhere between [7.5 to 11.5 million persons in the United States](http://localhost:4321/use-of-contraception-in-the-united-states-2017-2019.html#use-of-contraception-during-most-recent-intercourse) did not use _any_ method of contraception whatsoever when they last engaged in sexual intercourse, despite being at risk for unintended pregnancy.[^inconsistently]

[^inconsistently]: These 7.5 to 11.5 million persons include both those who are not using contraception in the long term and those who _are_ using one or more methods, but are [using contraception inconsistently](/use-of-contraception-in-the-united-states-2017-2019.html#consistency-of-use-of-contraception).

Thus, there are both technological and behavioral origins of the annual 80 million unintended pregnancies. Indeed, there is interplay between the technological and behavioral issues such that it is sometimes not clear where one sort of issue ends and the other begins. Despite this overlap, for the sake of brevity this article focuses on the technological issues with the current state of contraception, and discussion of behavioral issues is saved for a subsequent article.


## Long-Acting, Reversible Methods

One area of potential improvement in contraceptive technology is long-acting, reversible contraception (LARC).

The reason for the "long-acting" adjective in LARC is complicated. Two kinds of estimates have been produced for contraceptive failure rates: estimates for "typical use" and estimates for "perfect use," though this naming scheme is somewhat of a misnomer. "Typical use" refers to estimates calculated from surveys of representative samples of large populations. "Perfect use" estimates are ultimately derived from clinical trials of contraceptive methods.

"Perfect use" estimates were created by James Trussell, a professor of population studies at Princeton University. He read more than a hundred and fifty different academic papers that reported on clinical trials of contraceptive methods, decided which trials were methodologically sound and which trials were questionable, and did some very back-of-the-envelope math to come up with a "best guess" of a failure rate for each method based on the clinical trials he deemed sound. [@trussell_contraceptive_1987; @trussell_contraceptive_2004; @trussell_contraceptive_2011]

Estimates of "perfect use" failure rates are thus hypothetical failure rates that could exist, but are never actually observed in the general population. "Typical use" failure rates, on the other hand, are actually observed in a population, but come with a variety of other issues.

Generally, "typical use" failure rates are much higher than "perfect use" failure rates. One hypothesis that might explain part of this gap is that contraceptive users enrolled in clinical trials from which "perfect use" estimates are derived are better at and more consistent in using contraceptive methods than the general population.

Methods such as condoms require user intervention during every act of intercourse. Birth controls pills require users to take a pill each and every day. If such interventions are not done properly or consistently, the effectiveness of the contraceptive method is greatly decreased. Thus, short-acting contraceptives are very sensitive to user error.

The goal of long-acting contraception is to remove the opportunity for such user error, which would cause "typical use" failure rates to be closer to "perfect use" failure rates, under the hypothesis that user error accounts for some of the gap in failure rates.

Of course, sterilizing operations such as vasectomy or tubal ligation are very long-acting, typically lasting the remainder of a person's reproductive life. They are also much more effective than methods considered reversible.[^considered] However, they are only recommended for those who have reached a point in their lives where they have finished having children. Thus, the reason for the "reversible" adjective in LARC is straightforward: it refers to methods not including sterilizing operations.

[^considered]: The phrase "considered reversible" is used deliberately. Vasectomies, in particular, have been reversed numerous times by vasovasostomy procedures. It is therefore possible to use vasectomy as a kind of LARC, though doing so is "off label."
      
      Sterilizing operations such as vasectomy or tubal ligation are orders of magnitude more effective than contraceptive methods considered reversible. Indeed, while estimating contraceptive failure rates based on the National Survey of Family Growth (NSFG) is an ongoing project of this blog, survey-based estimates for vasectomy or tubal ligation are oftentimes impossible, because samples for nationally representative surveys are prone to report not a single unintended pregnancy among those using sterilizing operations as a method of contraception. Instead, estimates of failure rates for sterilizing operations must necessarily come from larger samples in prospective studies that follow large numbers of individuals who have undergone vasectomies or tubal ligations.

LARCs are typically interpreted to include methods administered by injection, implant, or insertion of an IUD. If these methods are successfully administered, they may last months or years without any need for additional user intervention.

![
["Packet of Norplant Contraceptive Implants, Middlesex, England, 1993"](https://collection.sciencemuseumgroup.org.uk/objects/co96805/packet-of-norplant-contraceptive-implants-middlesex-england-1993-contraceptive-implant)
by
[The Board of Trustees of the Science Museum ](https://collection.sciencemuseumgroup.org.uk/objects/co96805/packet-of-norplant-contraceptive-implants-middlesex-england-1993-contraceptive-implant)
is licensed under
[CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)
and is not modified.
](/images/norplant.jpg){alt="A box of Norplant branded leveonogestrel implants, with a manual placed to its left, and A Guide for Patients and the actual implants placed to the right."}

Even if the working hypothesis behind the rationale for LARC is correct, not all of the differences between "typical use" and "perfect use" failure rate estimates are due to increased user error in "typical use" contexts. In particular, "typical use" failure rate estimates are biased upwards by contraception overreporting, a phenomenon in which respondents to a survey report using contraception even when they are not.[^underreporting]

[^underreporting]: On the other hand, "typical use" failure rate estimates are biased downwards by induced abortion underreporting. Indeed, only about 38\% of pregnancies ending in induced abortion were reported on the 2017-2019 NSFG. [@national_center_for_health_statistics_2017-2019_2020, Appendix 2: Topic-Specific Notes] Not counting these unreported pregnancies would result in contraceptive failure rates that are lower than the true rates. However, analysis based on the NSFG has attempted to compensate for abortion underreporting since the 1980s. [@grady_contraceptive_1986; @jones_contraceptive_1992]

Indeed, in the 2017-2019 National Survey of Family Growth (NSFG), respondents representing somewhere between [3 and 5 million](/use-of-contraception-in-the-united-states-2017-2019.html#any-method-during-past-12-months) people who had previously indicated on the survey they were using contraception in the preceding year, when asked how often they used contraception, replied "none of the time." Thus, it is likely that some of the differences between "typical use" and "perfect use" failure rates are due to measurement error in which respondents are incorrectly counted as using a contraceptive method when they are not.

LARC methods are becoming increasingly popular, and as such users of LARCs will be increasingly sampled in surveys such as the NSFG. One of the more interesting questions to be answered by ongoing work estimating contraceptive failure rates -- including the work done for this blog -- is whether LARC methods do indeed lead to "typical use" failure rates closer to "perfect use" failure rates than other reversible methods.


## Non-Hormonal Methods

Unfortunately, while LARC might represent an improvement over short-acting contraceptive methods, nearly all LARC methods available today are hormonal.[^iud] These hormonal methods deliver some combination of progestin and estrogen analogs, which recreate the hormonal conditions signaling a pregnancy and leverage a natural phenomenon in female physiology that suppresses ovulation.

[^iud]: Copper-bearing IUDs not containing a hormonal component would be the major exception. However, copper-bearing IUDs have a [comparable rate of discontinuation](/use-of-contraception-in-the-united-states-2017-2019.html#discontinuation-due-to-dissatisfaction-1) to hormonal IUDs.

The major issue with hormonal methods is that hormones have many non-specific effects, including side effects that can make hormonal contraceptive methods intolerable to many persons. Indeed, somewhere [between 32\% and 37\%](/use-of-contraception-in-the-united-states-2017-2019.html#discontinuation-due-to-dissatisfaction) of women in the United States who have ever tried birth control pills have discontinued use due to dissatisfaction, and side effects are the most common reason for  dissatisfaction, with [between 59\% to 68\%](/use-of-contraception-in-the-united-states-2017-2019.html#pill-1) of those discontinuing birth control pills citing side effects as a reason for dissatisfaction. This represents somewhere between [9.6 and 13.3 million](/use-of-contraception-in-the-united-states-2017-2019.html#reasons-for-discontinuation-of-pill) women in the United States who have quit birth control pills due to side effects at least once in their lives.

Side effects are an issue that can occur whenever exogenous hormones are administered. Hormones are signaling molecules that travel throughout a circulatory system, interacting with receptors in distant organs, which may themselves increase or decrease hormone production in response, which in turn can cause yet another organ to change its hormone output. Thus, hormones by their very nature lead to broad and cascading effects.

A hormonal method that causes side effects discourages persons from using that specific method. Such experience might also discourage persons from using contraception more generally. This is one area, alluded to in the introduction, in which shortcomings of contraceptive technology and shortcomings of contraceptive behavior interact.

In contrast, non-hormonal methods such as male condoms (6.8\%~9.9\%), withdrawal (5.3\%~8.3\%), and calendar methods (4.1\%~8.2\%) have [much lower rates](/use-of-contraception-in-the-united-states-2017-2019.html#discontinuation-due-to-dissatisfaction) of discontinuation due to dissatisfaction. Unfortunately, they have much lower rates of effectiveness, as well, and none of the reversible, non-hormonal methods with low discontinuation rate are long-acting.[^iud2]

[^iud2]: See above note about copper-bearing IUDs.

Hormonal contraception has been an innovation in contraceptive technology. If hormonal contraception were never developed, the _only_ contraceptive methods available today would be the ancient, less-effective methods. However, hormonal contraception has only been an improvement in contraceptive practice among those who can find a formulation of hormones that their bodies can tolerate. Hormonal contraception can thus be viewed as just the _beginning_ of modern contraception. It represents an easily reached, low-hanging fruit that has been grasped before moving on to fruits both better and more difficult to reach.

Currently, there are some less effective methods that have low discontinuation rates, and there are some more effective methods that have high discontinuation rates. Therefore, a novel method that is both highly effective and less prone to side effects has great potential to improve contraceptive practice. Due to the nature of hormones, such a method would most likely be non-hormonal.


## Methods for Men

If one were to browse a list of the [most popular methods of contraception used in the United States](/use-of-contraception-in-the-united-states-2017-2019.html#methods-used) today, one will find only three methods in which the primary user is male: condom, withdrawal, and vasectomy. Indeed, all of the LARC methods currently available today are usable only by those with female physiology.

There are obvious socio-cultural issues with this situation, as it perpetuates the old-fashioned viewpoint that reproduction is "women's work." However, even from the more limited standpoint of contraceptive practice, a consequence of this situation is that for many men, there are not good options available for contraceptive method.

![
["Condom with latin manual from 1813 Lund University Historical Museum"](https://commons.wikimedia.org/wiki/File:Condom_with_manual_from_1813.jpg)
by
MatthiasKabel
is licensed under the
[GNU Free Documentation License](https://www.gnu.org/licenses/fdl-1.3.html)
and is not modified.
](/images/condom.jpg){alt="A condom from 1813 with a handwritten manual placed behind it."}

The two male methods available today that are reversible -- i.e., condoms and withdrawal -- are not very effective when they are the sole method of contraception used.[^additional] [@sundaram_contraceptive_2017; @kost_estimates_2008] As mentioned previously, vasectomy, though highly effective as a contraceptive method, is not typically marketed as a reversible method.[^vasovasostomy]

[^additional]: Condoms and withdrawal may still be valuable as _additional_ methods of contraception used _simultaneously_ with a more effective method, to make up for the overall poor effectiveness of contraceptive methods available today. Additionally, condoms may be valuable for reducing the risk for sexually transmitted infections.

[^vasovasostomy]: Many vasectomies actually have been reversed by vasovasostomy procedures. See note about methods "considered reversible" above.

Thus, those persons with male physiology who have not reached a point at which they have finished having children are left either to take on the cost and the risk that a vasectomy cannot later be reversed, should the need arise, or are left with just two relatively ineffective contraceptive methods.

Risk for unintended pregnancy necessarily occurs during intercourse between two people, one with male and one with female physiology. As such, the best contraceptive practice occurs when _both_ individuals are full contributors to reproductive responsibility. Much as hormonal side-effects discourage some women from contraceptive use, the lack of male contraceptive options can discourage men from full participation in contraceptive practice. Therefore, innovations in contraceptive technology should include methods that can be used by men, in addition to those used by women.


## More Effective Methods

The previous three sections have gone over phenomena that make contraceptive methods less effective in practice: short-acting methods leave more opportunity for user error, hormonal methods are prone to side-effects discouraging their use, and there are few methods available for men. Even despite these details, there also remains the glaring issue that all the reversible methods today are intrinsically not effective enough.

For instance, between [5.1 to 6.9 million women and between 6.8 to 9.2 million men](/use-of-contraception-in-the-united-states-2017-2019.html#method-used-exclusively-during-past-12-months) in the United States relied on condoms as their exclusive method of contraception during the preceding year. The most recently published estimates based on the NSFG report a first-year "typical use" failure rate for condoms of 12.6\%. [@sundaram_contraceptive_2017] While condoms are especially prone to user error, even the first-year "perfect use" failure rate estimated by back-of-the-envelope math is 2\%. [@trussell_contraceptive_2011]

Thus, assuming that there were similar failure rates when all 5.1 to 6.9 million women relying exclusively on condoms began using condoms, it should be expected that there would be between 640,000 and 870,000 unintended pregnancies among exclusive condom users _just in the first year of their condom use alone._ Even if all of the exclusive condom users used condoms perfectly, there would still be 100,000 to 140,000 unintended pregnancies among exclusive condom users, again, just in the first year of their condom use. Subsequent years would lead to further unintended pregnancies.

The point of this section is not to single out condoms. Use of condoms is better than no use of contraception while at risk for unintended pregnancy, which unfortunately also occurs quite frequently, and in the big picture of effective contraceptive practice, condoms may still have their use. They might be valuable as an additional method of contraception used _simultaneously_ with a more effective method, reducing the risk for sexually transmitted infections while providing a little extra contraceptive effectiveness.

Instead, condoms are used as an example because condoms are the [most common method of contraception in the United States](/use-of-contraception-in-the-united-states-2017-2019.html#among-those-who-have-ever-had-intercourse) in the sense that more women have used condoms as a method of contraception than any other method, and yet this method is woefully inadequate. Similar numbers of unintended pregnancies could be estimated for all reversible methods currently used in the United States, though the numbers would be slightly less bad for hormonal methods.

For instance, birth control pills compose another very popular method of contraception in the United States. Between [6 to 8.3 million women and between 3 to 5 million men](/use-of-contraception-in-the-united-states-2017-2019.html#method-used-exclusively-during-past-12-months) in the United States relied on pills as their exclusive method of contraception during the preceding year. The most recently published estimates based on the NSFG report a first-year "typical use" failure rate for pills of 7.2\%. [@sundaram_contraceptive_2017] The first-year "perfect use" failure rate for pills is estimated to be 0.3\%. [@trussell_contraceptive_2011]

Therefore, assuming no trend in failure rates, it should be expected that there would be between 430,000 and 600,000 unintended pregnancies among exclusive pill users just in the first year of their pill use. Even if all of the exclusive pill users used pills perfectly, there would still be 18,000 to 25,000 unintended pregnancies among exclusive pill users just in the first year of their pill use. Again, subsequent years would lead to further unintended pregnancies. While pills, the most popular modality for hormonal methods, perform somewhat better than condoms, the effect is only marginal.

Therefore, the point of this section is to illustrate that there is a pressing need for methods of contraception that, in addition to addressing issues that make contraceptive methods less effective in practice, are themselves intrinsically more effective.


## Conclusion

When the birth control movement in the United States began more than a century ago, it was conceived in the excitement of the [vision of a future world](/margaret-sanger-on-abortion-in-her-own-words.html) that would evolve beyond phenomenon of unintended pregnancy and the use of abortion as a method of fertility control. At first, there may have been reason for such hope. Prohibitions of dissemination of information about contraception were removed, and when the low-hanging fruit of hormonal contraception was finally brought to market, it proved more effective than the methods that came before.

However, in the decades since then, excitement and innovation has been replaced by complacency and stagnation. As this article demonstrates, the information illustrating the failures of current contraceptive technology and the needs for future contraceptive technology are easily discerned. However, actual innovation in contraceptive technology seems to be much more difficult to achieve.  Subsequent articles will explore why contemporary times are an era of stagnation in contraceptive progress.


## Citations

::: {#refs}
:::


## Footnotes
