---
draft: true
title: "Truth as an Overriding Principle for Belief"
date: '`r format(Sys.Date(), "%Y-%m-%d")`'
tags: ["worldview", "first-person"]
csl: "../bibliographies/apa.csl"
bibliography: "../bibliographies/truth-as-an-overriding-principle-for-beliefs.bib"
link-citations: true
implicit-figures: true
output:
  blogdown::html_page:
    md_extensions: ["+footnotes"]
    toc: false
    toc_depth: 5
---

The lead-in paragraph goes here.

<!--more-->

## Overriding Principle against Arbitrariness of Belief

I hold truth to be a necessary condition of my beliefs. In other words, propositions that are untrue are not eligible to be beliefs of mine. Furthermore, I hold truth to be a sufficient condition for my beliefs. Thus, a proposition being true compels me to believe the proposition.

Therefore, the property of truth constitutes an overriding principle that prevents my beliefs from being arbitrary. One's beliefs are arbitrary when one allows oneself to believe whatever one _wants_ to believe.


## Not "Truth" as in "Speak My Truth"

This is in contrast to the worldviews of those who might say "speak _my_ truth" or "speak _your_ truth." These worldviews seem to use the word "truth" to mean personal conviction. These meanings for the word "truth" are declarations of willfulness and thus endorsements of arbitrariness of belief, not overriding principles that prevent arbitrariness of belief.

It is important to understand that language is just symbols, and that the same symbol can be used for different purposes. Much as the symbol _"x"_ represents one unknown quantity in one math problem and a different unknown quantity in a different math problem, these other uses of "truth" may use the same symbol, but refer to a different property.


## Two Kinds of Truth

In order to define what I mean by "truth," I borrow a dichotomy^[This dichotomy is sometimes called "Hume's Fork" after David Hume (1711 - 1776).] that has been repeatedly used in various forms by thinkers in Western philosophy. This dichotomy separates uses of "truth" into two kinds of truth. There are various pairs of labels for these two kinds of truth depending on the particular thinker and depending on the exact context in which the dichotomy is construed, but all the concepts are related.


### Truth as Coherence

On one side of the dichotomy lies what might be termed "coherence" truth, _"a priori"_ truth, "analytic" truth, or "necessary" truth. This kind of truth includes statements such as:

> Bachelors are unmarried men.

> A podiatrist is a kind of physician.

It includes false statements such as:

> Widows are women who have never married.

> A podiatrist is a kind physician that specializes in conditions of the eye.

> A podiatrist is a kind of duck.

This kind of truth is called "coherence" because the criterion for this kind of truth is simply that the beliefs do not contradict each other and thus form a logically coherent system.


#### Proof by Contradiction

Coherence-truth^[Henceforth, this kind of truth is called "coherence-truth." Propositions possessing this property will also be called "coherence-truths," and the property itself "coherence-true."]  can be established by the method of proof by contradiction.^[Proof by contradiction is sometimes called _"reductio ad absurdum."_] In this method, it is shown that the logical negation of a statement leads to a contradiction within the system, so the original statement must be coherence-true.

For instance, the proposition 

> Widows are women who have married at least once. (1)

can be proved coherence-true by examining the implications of its logical negation:

> Widows are women who have never married. (2)

The definition of "widow" includes "women who have had a husband who has died." The "who have had a husband" part contradicts proposition (2) above. Because proposition (2) leads to a contradiction in the system, it is coherence-false, and its logical negation proposition (1) is coherence-true.


#### Names for Coherence-Truth

Coherence-truths are called _"a priori"_ because they can be determined to be coherence-true _prior_ to acquiring empirical evidence. They are called "analytic" because they can be determined to be coherence-true merely by _analyzing_ the language and ideas used to express them. They are "necessary" because the there is no possible world in which a coherence-truth could even be false, so long as the same definitions are used. In everyday speech, coherence-truths are the sort of things that are labeled with the phrase "by definition."


#### Coherence-Truths as Tautologies

Coherence-truths are tautologies. This means that a coherence-truth simply refers to the same thing twice, once in the subject and once in the predicate of the statement. Propositions that refer to the same thing _and_ use the same language, such as the below, are technically tautologies and coherence-true, though it is unlikely that anyone would find them informative.

> Bachelors are bachelors.

> Unmarried men are unmarried men.

Tautologies are common in everyday language when they use different symbols to refer to the same thing, such as:

> Bachelors are unmarried men.

> Unmarried men are bachelors.


#### Mathematics

Since coherence-truths are tautologies, coherence-truth might seem like a frivolous concept. However, there are propositions such as:

> 1 + 1 = 2

> The sum of the squares of the sides of a right triangle is equal to the square of its hypotenuse.

> Two lines that are parallel never intersect, regardless of how far they are extended.

Mathematics largely consists of coherence-truths, and yet it has been one of the more profound intellectual accomplishments of human civilization. Indeed, if one has encountered a proof by contradiction, it is likely to have been during mathematics instruction. Mathematics heavily relies on equations, which are tautologies, in which the left side of the equation and the right side of the equation refer to the same thing, but with different symbols.


### Truth as Correspondence

On the other side of the dichotomy between two kinds of truth is what might be termed "correspondence" truth, _"a posteriori"_ truth, "synthetic" truth, or "contingent" truth. This kind of truth includes statements such as:

> In the city of Greenville, there are more bachelors than widows. (3)

> The average salary of podiatrists is less than the average salary of plastic surgeons. (4)

Whether a proposition is coherence-true could be established entirely by processes within one's mind, by examining relations between ideas and definitions of symbols used to express them. This second kind of truth, on the other hand, is called "correspondence" because the criterion for this kind of truth is that a belief must accurately describe some fact in the world external to the mind holding the belief.

#### Names for Correspondence-Truth^[Henceforth, this kind of truth is called "correspondence-truth." Other forms are similarly prefixed with "correspondence-."]

Correspondence-truths are called _"a posteriori"_ because they can only be established as correspondence-true _after_ experiencing some empirical evidence. They are called "synthetic" because they _join together_ two different things, rather than being two different ways of describing the same thing. They are "contingent" because they are correspondence-true _only if_ they accurately describe how things are in this world, but one can imagine possible worlds in which they are correspondence-false. Nothing is correspondence-true merely "by definition."


#### Empirical Evidence

Whereas coherence-truths can be established by proofs or arguments, correspondence-truths necessarily require empirical investigation to differentiate them from correspondence-falsehoods.

In order to establish whether proposition (3) is correspondence-true or correspondence-false, one would need to count the total number of bachelors and the total number of widows in the specified city. In order to establish whether proposition (4) is correspondence-true or not, one would first need to stipulate the relevant population, then take a survey of podiatrist salaries and a survey of plastic surgeon salaries from the specified population.

Therefore, correspondence-truth places an emphasis on empirical evidence. Whereas coherence-truth is exemplified by the proofs of pure mathematics, correspondence-truth is characterized by the messiness of empirical science and statistics.


## Two Kinds of Consistency

All the beliefs within a single mind relevant to some subject might be termed a "mental model" of that subject. Both coherence-truth and correspondence-truth have in common that the criterion used to establish truth involves a claim about consistency between a mental model and something. Correspondence-truth makes the claim that a mental model is consistent with the external world. Coherence-truth makes the claim that a mental model is consistent with itself.

Thus, to believe in coherence-truth, one need only believe in the existence of oneself. To believe in correspondence-truth, one needs to believe also that there is an external world independent of one's own mind and that it is possible to be more accurate or less accurate at describing this external world.

Fundamentally, then, coherence-truth would be disappointing as an overriding principle. It only requires that one's beliefs be consistent with themselves, but still allows one to believe whatever one wants. Thus, coherence-truth is not a guard against arbitrary beliefs.


## Axiomatic Systems

Coherence-truth may not _feel_ arbitrary. Doing a mathematical proof, for instance, is not usually described as feeling arbitrary.

Mathematical proofs consist of strict logical entailment.^[Strict logical entailment is sometimes called "deductive logic." "Inductive logic" under this naming scheme would be what we call "statistics" in modern times.] A unit of strict logical entailment is often called an "argument."^[This use is different from the word "argument" used in the context of rhetoric or debate.] Such an argument consists of a conclusion that is derived from one or more premises. In strict logical entailment, the coherence-truth of the argument's conclusion is _forced_ by the coherence-truth of the premises. In other words, it is impossible to accept the premises of the argument as coherence-true without also accepting the conclusion as coherence-true, because doing otherwise would lead to a contradiction.

However, this just moves the question of whether the conclusion of an argument is coherence-true back to the questions of whether the premises of the argument are coherence-true. In a mathematical context, these premises might also be theorems that are themselves established with proofs. These proofs would be arguments that again pass the question of coherence-truth back to their premises. 

This chain of passing the question of coherence-truth back to the premises of yet another argument must stop at some point. Otherwise, this would constitute what is called an "infinite regress." This is usually handled in mathematics by establishing a finite set of axioms. These axioms are the propositions that are just accepted as coherent-true. Unlike theorems, there is no attempt to prove the axioms. Thus, axioms constitute the first premises of all arguments within an axiomatic system; they are the assumptions upon which the entire axiomatic system rests.

The arbitrariness of coherence-truth is the result of the arbitrariness of choosing axioms. One can subscribe to whatever axiomatic system one wants to, as long as none of the axioms of the system contradict each other.


### Non-Euclidean Geometry

As an example, the geometry with which most of us are familiar is called "Euclidean geometry" after Euclid, a Greek mathematician who lived during the reign of Ptolemy I (323–283 BC) in ancient Alexandria. The "Euclidean" in "Euclidean geometry" was unnecessary for more than 2,000 years for lack of any alternatives. 

The axioms of geometry as written by Euclid were divided into what is translated as "postulates" and "common notions." The fifth postulate, translated into modern English, reads:

> That, if a straight line falling on two straight lines makes the interior angles on the same side less than two right angles, the two straight lines, if produced indefinitely, meet on that side on which are the angles less than the two right angles. [@joyce_euclids_2013]

This is sometimes called the "parallel postulate" because it implies that parallel lines never intersect. 

Over the past few centuries, there has been widespread acceptance in the mathematical community of systems of non-Euclidean geometry, which are similar to Euclidean geometry except that the fifth postulate is removed. This has the consequence that, in these systems, parallel lines do not have properties that we think of parallel lines as having intuitively.

These systems of non-Euclidean geometry are just as coherence-true as Euclidean geometry. Depending on the application, one can use whichever system of geometry is appropriate. Thus, there is an arbitrariness in what constitutes coherence-truth, even for a system that has been a widespread standard for more than two millennia.

Furthermore, non-Euclidean systems, particularly hyperbolic^[In hyperbolic geometry, for any point _P_ not on a line _L_, there are an infinitive number of lines that can be drawn through _P_ that do not intersect _L_. This is different than in Euclidean geometry, where there is only one line that can be drawn through any point _P_ that does not intersect _L_, which is _the_ one and only parallel line to _L_.] ones, are useful to physicists investigating special relativity. Thus, not only are there alternative axiomatic systems for geometry, but it is not obvious which axiomatic system best models spacetime, or indeed if any one of them is _the_ one and only best.


## Less Rigorous Arguments

These criticisms of arguments and of coherence-truth are applicable to fields other than mathematics, as well. Mathematics, however, is the most rigorous kind of argumentation. Thus, the situation for other forms of argumentation is even worse.

All forms of argumentation suffer from the phenomenon in which arguments merely pass the burden of judging the alleged of truth of the conclusion to the alleged truth of the premises of an argument. However, rarely does argumentation outside of mathematics have the strict logical entailment that is a feature of mathematical proofs, so even if one were to accept the premises of their arguments, the conclusions would remain dubious.

Furthermore, rarely do arguments outside of mathematics reach the level of axiomatic system. Thus, most arguments are vulnerable to an infinite regress. In practice, however, lines of argumentation eventually stop, revealing first premises, and one could just arbitrarily reject the first premises to reject the whole line of argumentation. 


## Conclusion

Because of these concerns, when I assert that truth is an overriding principle for my beliefs, this applies exclusively to correspondence-truth, not coherence-truth. Unless otherwise specified, "truth" in this blog refers to correspondence-truth.

The implications for my worldview are that I do not value argumentation and logic very much, but I do value empirical inquiry and statistical analysis quite heavily. Indeed, I can assert without hyperbole that I regard the investigation of empirical evidence as the highest calling of the human mind.


## Citations

::: {#refs}
:::


## Footnotes
