---
draft: true
title: "Two Kinds of Truth"
date: '`r format(Sys.Date(), "%Y-%m-%d")`'
tags: ["worldview", "first-person"]
csl: "../bibliographies/apa.csl"
link-citations: true
implicit-figures: true
output:
  blogdown::html_page:
    md_extensions: ["+footnotes"]
    toc: false
    toc_depth: 5
---

This is where the lead-in paragraph goes.

<!--more-->

* truth and falsity as an overriding principle for beliefs
* Hume's fork
  * coherence, a priori, analytic
    * true "by definition"
    * tautologies
  * correspondence, a posterior, synthetic
* Both coherence-truth and correspondence-truth make a claim about a mental model being consistent with something. Coherence-truth claims that a mental model is consistent with itself. Correspondence truth claims that a mental model is consistent with the external world.
* My overriding principle only applies to correspondence-truth. Coherence-truths are "true" only in as much as someone subscribes to some system, e.g., such as an axiomatic system in mathematics, 
* The root of all fallacies discussed here is that they allow for an arbitrariness of beliefs. Arbitrariness of belief is a root fallacy precisely because it allows beliefs to be inconsistent with the external world. This is why this overriding principle is important.


## Footnotes
