LIBNAME NSFG '/home/u43676684/NSFG/Library';

PROC FORMAT CNTLOUT=NSFG.FemPregFormats_2002;

VALUE AGECON 
 0-1999 = "UNDER 20 YEARS"
 2000-2499 = "20-24 YEARS"
 2500-2999 = "25-29 YEARS"
 3000-4499 = "30-44 YEARS"
 ;
VALUE AGEENDF 
 5-19 = "UNDER 20 YEARS"
 20-24 = "20-24 YEARS"
 25-29 = "25-29 YEARS"
 30-44 = "30-44 YEARS"
 ;
VALUE AGEPRG 
 . = "INAPPLICABLE"
 0-1999 = "UNDER 20 YEARS"
 2000-2499 = "20-24 YEARS"
 2500-2999 = "25-29 YEARS"
 3000-4499 = "30-44 YEARS"

 ;
VALUE AGEQTNUR 
 . = "INAPPLICABLE"
 0 = "LESS THAN 1 MONTH OLD"
 1 = "1 MONTH OLD"
 2 = "2 MONTHS OLD"
 3 = "3 MONTHS OLD"
 4-6 = "4-6 MONTHS OLD"
 7-12 = "7-12 MONTHS OLD"
 13-24 = "13-24 MONTHS OLD"
 25-95 = "25 MONTHS OR OLDER"
 ;
VALUE AGERFF 
 15 = "15 YEARS"
 16 = "16 YEARS"
 17 = "17 YEARS"
 18 = "18 YEARS"
 19 = "19 YEARS"
 20 = "20 YEARS"
 21 = "21 YEARS"
 22 = "22 YEARS"
 23 = "23 YEARS"
 24 = "24 YEARS"
 25 = "25 YEARS"
 26 = "26 YEARS"
 27 = "27 YEARS"
 28 = "28 YEARS"
 29 = "29 YEARS"
 30 = "30 YEARS"
 31 = "31 YEARS"
 32 = "32 YEARS"
 33 = "33 YEARS"
 34 = "34 YEARS"
 35 = "35 YEARS"
 36 = "36 YEARS"
 37 = "37 YEARS"
 38 = "38 YEARS"
 39 = "39 YEARS"
 40 = "40 YEARS"
 41 = "41 YEARS"
 42 = "42 YEARS"
 43 = "43 YEARS"
 44 = "44 YEARS"
;
VALUE BFEEDWKS 
 . = "INAPPLICABLE"
 0 = "LESS THAN 1 WEEK"
 1-52 = "1 TO 52 WEEKS"
 53-993 = "53 WEEKS OR LONGER"
 994 = "STILL BREASTFEEDING THIS CHILD"
 ;
VALUE BIRTHORD 
 . = "INAPPLICABLE"
 01 = "1ST BIRTH"
 02 = "2ND BIRTH"
 03 = "3RD BIRTH"
 04 = "4TH BIRTH"
 05 = "5TH BIRTH"
 06 = "6TH BIRTH"
 07 = "7TH BIRTH"
 08 = "8TH BIRTH"
 09 = "9TH BIRTH"
 10 = "10TH BIRTH"
 ;
VALUE BPABDS 
 . = "INAPPLICABLE"
 0 = "NEITHER BPA NOR BDS"
 1 = "BPA"
 2 = "BDS"
 ;
VALUE CMFMT 
 301-1164 = "BEFORE 1997"
 1165-1239 = "JANUARY 1997 OR LATER"
 ;
VALUE CMINTVWF 
 1225-1239 = "JAN 2002 - MAR 2003"
 ;
VALUE DATECON 
 301-1164 = "BEFORE 1997"
 1165-1239 = "JANUARY 1997 OR LATER"
 ;
VALUE DATEND 
 . = "INAPPLICABLE"
 301-1164 = "BEFORE 1997"
 1165-1239 = "JANUARY 1997 OR LATER"
 ;
VALUE EDUCAT2F 
 9 = "9TH GRADE OR LESS"
 10 = "10TH GRADE"
 11 = "11TH GRADE"
 12 = "12TH GRADE"
 13 = "1 YEAR OF COLLEGE/GRAD SCHOOL"
 14 = "2 YEARS OF COLLEGE/GRAD SCHOOL"
 15 = "3 YEARS OF COLLEGE/GRAD SCHOOL"
 16 = "4 YEARS OF COLLEGE/GRAD SCHOOL"
 17 = "5 YEARS OF COLLEGE/GRAD SCHOOL"
 18 = "6 YEARS OF COLLEGE/GRAD SCHOOL"
 19 = "7+ YEARS OF COLLEGE/GRAD SCHOOL"
 ;
VALUE FEELINGF 
 1 = "VERY UNHAPPY"
 2 = "2"
 3 = "3"
 4 = "4"
 5 = "5"
 6 = "6"
 7 = "7"
 8 = "8"
 9 = "9"
 10 = "VERY HAPPY"
 ;
VALUE FLGDKMOF 
 . = "INAPPLICABLE"
 0 = "EXACT MONTH & YEAR REPORTED"
 1 = "SEASON REPORTED FOR MONTH"
 2 = "MONTH REPORTED AS DK/RF"
 7 = "NOT ASCERTAINED"
 ;
VALUE FMARCON 
 1 = "MARRIED"
 2 = "DIVORCED"
 3 = "WIDOWED"
 4 = "SEPARATED"
 5 = "NEVER MARRIED"
 ;
VALUE FMARITAL 
 1 = "MARRIED"
 2 = "WIDOWED"
 3 = "DIVORCED"
 4 = "SEPARATED"
 5 = "NEVER MARRIED"
 ;
VALUE FMAROUT 
 . = "INAPPLICABLE"
 1 = "MARRIED"
 2 = "DIVORCED"
 3 = "WIDOWED"
 4 = "SEPARATED"
 5 = "NEVER MARRIED"
 ;
VALUE FRSTEATD 
 . = "INAPPLICABLE"
 0 = "LESS THAN 1 MONTH"
 1 = "1 MONTH"
 2 = "2 MONTHS"
 3 = "3 MONTHS"
 4 = "4 MONTHS"
 5 = "5 MONTHS"
 6 = "6 MONTHS"
 7-95 = "7 OR MORE MONTHS"
 ;
VALUE HAGEENDF 
 LOW-19= "UNDER 20 YEARS"
 20-24 = "20-24 YEARS"
 25-29 = "25-29 YEARS"
 30-44 = "30-44 YEARS"
 45-95 = "45 YEARS OR OLDER"
 ;
VALUE HIEDUC2F 
 5 = "9TH GRADE OR LESS"
 6 = "10TH GRADE"
 7 = "11TH GRADE"
 8 = "12TH GRADE, NO DIPLOMA (NOR GED)"
 9 = "HIGH SCHOOL GRADUATE (DIPLOMA OR GED)"
 10 = "SOME COLLEGE BUT NO DEGREE"
 11 = "ASSOCIATE DEGREE IN COLLEGE/UNIVERSITY"
 12 = "BACHELOR'S DEGREE"
 13 = "MASTER'S DEGREE"
 14 = "DOCTORATE DEGREE"
 15 = "PROFESSIONAL DEGREE"
 ;
VALUE HISPANIC 
 1 = "YES"
 2 = "NO"
 ;
VALUE HISPRACE 
 1 = "HISPANIC"
 2 = "NON-HISPANIC WHITE"
 3 = "NON-HISPANIC BLACK"
 4 = "NON-HISPANIC OTHER"
 ;
VALUE HOWPRGF 
 0-50 = "0-50"
 ;
VALUE IMPFLAG 
 0 = "QUESTIONNAIRE DATA (NOT IMPUTED)"
 1 = "MULTIPLE REGRESSION IMPUTATION"
 2 = "LOGICAL IMPUTATION"
 ;
VALUE INSURANC 
 1 = "NOT COVERED BY ANY HEALTH INSURANCE"
 2 = "COVERED BY A PRIVATE HEALTH INSURANCE PLAN ONLY"
 3 = "COVERED BY MEDICAID (MENTIONED AT ALL)"
 4 = "COVERED BY PUBLIC/GOVERNMENT/STATE/MILITARY HEALTH CARE (MENTIONED AT ALL)"
 ;
VALUE KNEWPREG 
 . = "INAPPLICABLE"
 0-13 = "13 WEEKS OR LESS"
 14-26 = "14-26 WEEKS"
 27-50 = "27 WEEKS OR LONGER"
 ;
VALUE LABOR2FR 
 1 = "WORKING FULL-TIME"
 2 = "WORKING PART-TIME"
 3 = "WORKING-TEMP ILL/ETC"
 4 = "WORKING-MATERNITY OR FAMILY LEAVE"
 5 = "NOT WORKING BUT LOOKING FOR WORK"
 6 = "SCHOOL"
 7 = "KEEPING HOUSE"
 8 = "CARING FOR FAMILY"
 9 = "OTHER"
 ;
VALUE LBFMT 
 0-5 = "UNDER 6 POUNDS"
 6 = "6 POUNDS"
 7 = "7 POUNDS"
 8 = "8 POUNDS"
 9-95 = "9 POUNDS OR MORE"
 ;
VALUE LBW 
 . = "INAPPLICABLE"
 1 = "YES, LOW BIRTH WEIGHT"
 ;
VALUE LEARNPRG 
 . = "INAPPLICABLE"
 0-13 = "13 WEEKS OR LESS"
 14-50 = "14 weeks or later"
 ;
VALUE MATERNLV 
 . = "INAPPLICABLE"
 0 = "NOT EMPLOYED DURING THIS PREGNANCY"
 1 = "TOOK MATERNITY LEAVE FROM JOB HELD DURING THIS PREGNANCY"
 2 = "DID NOT TAKE -- NOT NEEDED DUE TO JOB SCHEDULE OR SELF-EMPLOYMENT"
 3 = "DID NOT TAKE -- NOT OFFERED OR ALLOWED BY EMPLOYER"
 ;
VALUE MATWEEKS 
 . = "INAPPLICABLE"
 0-13 = "13 WEEKS OR LESS"
 14-95 = "14 WEEKS OR LONGER"
 ;
VALUE METRO 
 1 = "MSA, CENTRAL CITY"
 2 = "MSA, OTHER"
 3 = "NOT MSA"
 ;
VALUE MOSFMT 
 0-12 = "0-12 MONTHS"
 97 = "NOT ASCERTAINED"
 ;
VALUE NBRNALIV 
 . = "INAPPLICABLE"
 1 = "1 BABY"
 2 = "2 BABIES"
 3-6 = "3 OR MORE BABIES"
 ;
VALUE NUMFMT 
 0-994 = "0-994"
 ;
VALUE NUMPREGF 
 01 = "1 PREGNANCY"
 02 = "2 PREGNANCIES"
 03 = "3 PREGNANCIES"
 04 = "4 PREGNANCIES"
 05 = "5 PREGNANCIES"
 06 = "6 PREGNANCIES"
 07-95 = "7 OR MORE PREGNANCIES"
 ;
VALUE OLDWANTP 
 1 = "LATER, OVERDUE"
 2 = "RIGHT TIME"
 3 = "TOO SOON, MISTIMED"
 4 = "DIDN'T CARE, INDIFFERENT"
 5 = "UNWANTED"
 6 = "DON'T KNOW, NOT SURE"
 ;
VALUE OLDWANTR 
 1 = "LATER, OVERDUE"
 2 = "RIGHT TIME"
 3 = "TOO SOON, MISTIMED"
 4 = "DIDN'T CARE, INDIFFERENT"
 5 = "UNWANTED"
 6 = "DON'T KNOW, NOT SURE"
 ;
VALUE OUTCOME 
 1 = "LIVE BIRTH"
 2 = "INDUCED ABORTION"
 3 = "STILLBIRTH"
 4 = "MISCARRIAGE"
 5 = "ECTOPIC PREGNANCY"
 6 = "CURRENT PREGNANCY"
 ;
VALUE OZFMT 
 0-15 = "0-15 OUNCES"
 ;
VALUE PARITY 
 0 = "0 BABIES"
 1 = "1 BABY"
 2 = "2 BABIES"
 3 = "3 BABIES"
 4 = "4 BABIES"
 5-95 = "5 OR MORE BIRTHS"
 ;
VALUE PAYDELIV 
 . = "INAPPLICABLE"
 1 = "OWN INCOME ONLY"
 2 = "INSURANCE ONLY"
 3 = "OWN INCOME & INSURANCE ONLY"
 4 = "MEDICAID/GOVT ASSISTANCE MENTIONED AT ALL"
 ;
VALUE PMARPREG 
 . = "INAPPLICABLE"
 1 = "YES"
 ;
VALUE PNCAREWK 
 . = "INAPPLICABLE"
 0-13 = "13 WEEKS OR LESS"
 14-50 = "14 WEEKS OR LATER"
 95 = "NO PRENATAL CARE FOR THIS PREGNANCY"
 ;
VALUE POVERTYF 
 000-099 = "0-99 PERCENT OF POVERTY LEVEL"
 100-199 = "100-199 PERCENT OF POVERTY LEVEL"
 200-299 = "200-299 PERCENT OF POVERTY LEVEL"
 300-399 = "300-399 PERCENT OF POVERTY LEVEL"
 400-499 = "400-499 PERCENT OF POVERTY LEVEL"
 500 = "500 PERCENT OF POVERTY LEVEL OR GREATER"
 ;
VALUE PREGORDR 
 01 = "1ST PREGNANCY"
 02 = "2ND PREGNANCY"
 03 = "3RD PREGNANCY"
 04 = "4TH PREGNANCY"
 05 = "5TH PREGNANCY"
 06 = "6TH PREGNANCY"
 07 = "7TH PREGNANCY"
 08 = "8TH PREGNANCY"
 09 = "9TH PREGNANCY"
 10 = "10TH PREGNANCY"
 11 = "11TH PREGNANCY"
 12 = "12TH PREGNANCY"
 13 = "13TH PREGNANCY"
 14 = "14TH PREGNANCY"
 15 = "15TH PREGNANCY"
 16 = "16TH PREGNANCY"
 17 = "17TH PREGNANCY"
 18 = "18TH PREGNANCY"
 19 = "19TH PREGNANCY"
 ;
VALUE PRGLNGTH 
 0-13 = "13 WEEKS OR LESS"
 14-26 = "14-26 WEEKS"
 27-50 = "27 WEEKS OR LONGER"
 ;
VALUE PRGOUTF 
 1 = "LIVE BIRTH"
 2 = "PREGNANCY LOSS OR ABORTION"
 3 = "CURRENT PREGNANCY"
 ;
VALUE PUBASSIS 
 . = "INAPPLICABLE"
 1 = "YES (R RECEIVED PUBLIC ASSISTANCE IN 2001)"
 2 = "NO (R DID NOT RECEIVE PUBLIC ASSISTANCE IN 2001)"
 ;
VALUE RACE 
 1 = "BLACK"
 2 = "WHITE"
 3 = "OTHER"
 ;
VALUE RELIGION 
 1 = "NO RELIGION"
 2 = "CATHOLIC"
 3 = "PROTESTANT"
 4 = "OTHER RELIGIONS"
 ;
VALUE RMARITAL 
 1 = "CURRENTLY MARRIED"
 2 = "NOT MARRIED BUT LIVING WITH OPP SEX PARTNER"
 3 = "WIDOWED"
 4 = "DIVORCED"
 5 = "SEPARATED FOR REASONS OF MARITAL DISCORD"
 6 = "NEVER BEEN MARRIED"
 ;
VALUE RMAROUT 
 . = "INAPPLICABLE"
 1 = "MARRIED"
 2 = "DIVORCED"
 3 = "WIDOWED"
 4 = "SEPARATED"
 5 = "COHABITING"
 6 = "NEVER MARRIED, NOT COHABITING"
 ;
VALUE SCALEF 
 0 = "0"
 1 = "1"
 2 = "2"
 3 = "3"
 4 = "4"
 5 = "5"
 6 = "6"
 7 = "7"
 8 = "8"
 9 = "9"
 10 = "10"
 ;
VALUE TE_10F 
 1 = "MALE"
 2 = "FEMALE"
 ;
VALUE TE_14F 
 1 = "WEEKS"
 2 = "MONTHS"
 ;
VALUE TE_15F 
 1 = "FIRST TRIMESTER"
 2 = "SECOND TRIMESTER"
 3 = "THIRD TRIMESTER"
 ;
VALUE TE_160F 
 1 = "NO METHOD USED"
 2 = "OFFICE USE ONLY"
 3 = "BIRTH CONTROL PILLS"
 4 = "CONDOM"
 5 = "PARTNER S VASECTOMY"
 6 = "STERILIZING OPERATION/TUBAL LIGATION"
 7 = "WITHDRAWAL, PULLING OUT"
 8 = "DEPO-PROVERA, INJECTABLES (SHOT)"
 9 = "NORPLANT (TM) IMPLANTS"
 10 = "RHYTHM OR SAFE PERIOD BY CALENDAR"
 11 = "SAFE PERIOD BY TEMPERATURE OR CERVICAL MUCUS TEST, NATURAL FAMILY PLANNING"
 12 = "DIAPHRAGM"
 13 = "FEMALE CONDOM, VAGINAL POUCH"
 14 = "FOAM"
 15 = "JELLY OR CREAM"
 16 = "CERVICAL CAP"
 17 = "SUPPOSITORY, INSERT"
 18 = "TODAY (TM) SPONGE"
 19 = "IUD, COIL, OR LOOP"
 20 = "'MORNING AFTER' PILLS OR EMERGENCY CONTRACEPTION"
 21 = "OTHER METHOD"
 22 = "RESPONDENT WAS STERILE"
 23 = "RESPONDENT'S PARTNER WAS STERILE"
 24 = "LUNELLE INJECTABLE (MONTHLY SHOT)"
 25 = "CONTRACEPTIVE PATCH"
 ;
VALUE TE_161F 
 1 = "YES"
 5 = "NO"
 ;
VALUE TE_162F 
 1 = "PROBABLY YES"
 5 = "PROBABLY NOT"
 6 = "DIDN'T CARE"
 ;
VALUE TE_163F 
 1 = "CORRECT"
 2 = "INCORRECT"
 ;
VALUE TE_164F 
 1 = "YES"
 5 = "NO"
 7 = "DIDN'T CARE"
 ;
VALUE TE_165F 
 1 = "TOO SOON"
 2 = "RIGHT TIME"
 3 = "LATER"
 4 = "DIDN'T CARE"
 ;
VALUE TE_166F 
 1 = "MONTHS"
 2 = "YEARS"
 ;
VALUE TE_167F 
 1 = "DEFINITELY YES"
 2 = "PROBABLY YES"
 3 = "PROBABLY NO"
 4 = "DEFINITELY NO"
 ;
VALUE TE_168F 
 1 = "YOUR BIRTH CONTROL METHOD FAILED"
 2 = "YOU DID NOT USE YOUR BIRTH CONTROL METHOD PROPERLY"
 3 = "RESPONDENT WASN'T USING A METHOD"
 ;
VALUE TE_169F 
 1 = "YOU DID NOT EXPECT TO HAVE SEX"
 2 = "YOU DID NOT THINK YOU COULD GET PREGNANT"
 3 = "YOU DIDN T REALLY MIND IF YOU GOT PREGNANT"
 4 = "YOU WERE WORRIED ABOUT THE SIDE EFFECTS OF BIRTH CONTROL"
 5 = "YOUR MALE PARTNER DID NOT WANT YOU TO USE A BIRTH CONTROL METHOD"
 6 = "YOUR MALE PARTNER DID NOT WANT TO USE A BIRTH CONTROL METHOD"
 7 = "RESPONDENT WAS USING A METHOD"
 ;
VALUE TE_231F 
 1 = "DURING THE PREGNANCY"
 2 = "AFTER THE (PREGNANCY ENDED/BABY WAS BORN)"
 ;
VALUE TE_2F 
 1 = "YES"
 5 = "NO"
 ;
VALUE TE_45F 
 1 = "MISCARRIAGE"
 2 = "STILLBIRTH"
 3 = "ABORTION"
 4 = "ECTOPIC OR TUBAL"
 5 = "LIVE BIRTH BY CESAREAN SECTION"
 6 = "LIVE BIRTH BY VAGINAL DELIVERY"
 ;
VALUE TE_46F 
 1 = "LESS THAN 6 MONTHS"
 2 = "6 MONTHS OR MORE"
 ;
VALUE TE_47F 
 1 = "LESS THAN 3 MONTHS"
 2 = "3 MONTHS OR MORE, BUT LESS THAN 6 MONTHS"
 3 = "6 MONTHS OR MORE"
 ;
VALUE TE_49F 
 1 = "5 1/2 POUNDS OR MORE"
 2 = "LESS THAN 5 1/2 POUNDS"
 ;
VALUE TE_50F 
 1 = "IN A HOSPITAL"
 2 = "IN A BIRTHING CENTER"
 3 = "IN YOUR HOME"
 4 = "SOME OTHER PLACE"
 ;
VALUE TE_51F 
 1 = "INSURANCE"
 2 = "CO-PAYMENT OR OUT-OF-POCKET PAYMENT"
 3 = "MEDICAID"
 4 = "NO PAYMENT REQUIRED"
 5 = "SOME OTHER WAY"
 ;
VALUE TE_53F 
 1 = "LESS THAN 3 MONTHS"
 2 = "MORE THAN 3 MONTHS"
 ;
VALUE TE_54F 
 0 = "NONE"
 1 = "ABOUT ONE CIGARETTE A DAY OR LESS"
 2 = "JUST A FEW CIGARETTES A DAY (2-4)"
 3 = "ABOUT HALF A PACK A DAY (5-14)"
 4 = "ABOUT A PACK A DAY (15-24)"
 5 = "ABOUT 1 1/2 PACKS A DAY (25-34)"
 6 = "ABOUT 2 PACKS A DAY (35-44)"
 7 = "MORE THAN 2 PACKS A DAY (45 OR MORE)"
 ;
VALUE TE_55F 
 1 = "ABOUT ONE CIGARETTE A DAY OR LESS"
 2 = "JUST A FEW CIGARETTES A DAY (2-4)"
 3 = "ABOUT HALF A PACK A DAY (5-14)"
 4 = "ABOUT A PACK A DAY (15-24)"
 5 = "ABOUT 1 1/2 PACKS A DAY (25-34)"
 6 = "ABOUT 2 PACKS A DAY (35-44)"
 7 = "MORE THAN 2 PACKS A DAY (45 OR MORE)"
 ;
VALUE TE_56F 
 1 = "LESS THAN 3 MONTHS"
 2 = "AT LEAST 3 MONTHS BUT LESS THAN 6 MONTHS"
 3 = "6 OR MORE MONTHS"
 ;
VALUE TE_57F 
 1 = "YES"
 5 = "NO"
 6 = "R VOLUNTEERED SHE WORKED DURING PREGNANCY, BUT QUIT JOB BEFORE DELIVERY"
 ;
VALUE TE_58F 
 1 = "DID NOT NEED TO TAKE MATERNITY LEAVE"
 2 = "WERE NOT OFFERED OR ALLOWED TO TAKE MATERNITY LEAVE"
 3 = "SOME OTHER REASON"
 ;
VALUE TE_59F 
 1 = "4 WEEKS OR LESS"
 2 = "LONGER THAN 4 WEEKS"
 ;
VALUE TE_60F 
 1 = "WITH BIOLOGICAL FATHER"
 2 = "WITH OTHER RELATIVES"
 3 = "WITH ADOPTIVE FAMILY"
 4 = "AWAY AT SCHOOL/COLLEGE"
 5 = "LIVING ON OWN"
 6 = "OTHER"
 ;
VALUE TE_61F 
 1 = "MONTHS"
 2 = "WEEKS"
 3 = "DAYS"
 ;
VALUE TOOSOONF 
 1-100 = "1-100"
 ;
VALUE WANTPART 
 1 = "LATER, OVERDUE"
 2 = "RIGHT TIME"
 3 = "TOO SOON, MISTIMED"
 4 = "DIDN'T CARE, INDIFFERENT"
 5 = "UNWANTED"
 6 = "DON'T KNOW, NOT SURE"
 ;
VALUE WANTRESP 
 1 = "LATER, OVERDUE"
 2 = "RIGHT TIME"
 3 = "TOO SOON, MISTIMED"
 4 = "DIDN'T CARE, INDIFFERENT"
 5 = "UNWANTED"
 6 = "DON'T KNOW, NOT SURE"
 ;
VALUE WKSFMT 
 0-50 = "0-50 WEEKS"
 ;
VALUE YEARFMT 
 1950-2003 = "1950-2003"
 ;
VALUE YESNO 
 1 = "YES"
 2 = "NO"
 ;
RUN;


/*****************************/
/* SAS DATA STEP BEGINS HERE */
/*****************************/

DATA NSFG.FemPregData_2002;
INFILE "/home/u43676684/NSFG/Data/2002FemPreg.dat" LRECL=447;
INPUT
   CASEID $ 1-12            PREGORDR  13-14          HOWPREG_N  15-16      
   HOWPREG_P  17            MOSCURRP  18             NOWPRGDK  19          
   PREGEND1  20             PREGEND2  21             NBRNALIV  22          
   MULTBRTH  23             CMOTPREG  24-27          PRGOUTCOME  28        
   CMPRGEND  29-32          FLGDKMO1  33             CMPRGBEG  34-37       
   AGEATEND  38-39          HPAGEEND  40-41          GESTASUN_M  42-43     
   GESTASUN_W  44-45        WKSGEST  46-47           MOSGEST  48-49        
   DK1GEST  50              DK2GEST  51              DK3GEST  52           
   BPA_BDSCHECK1  53        BPA_BDSCHECK2  54        BPA_BDSCHECK3  55     
   BABYSEX  56              BIRTHWGT_LB  57-58       BIRTHWGT_OZ  59-60    
   LOBTHWGT  61             BABYSEX2  62             BIRTHWGT_LB2  63-64   
   BIRTHWGT_OZ2  65-66      LOBTHWGT2  67            BABYSEX3  68          
   BIRTHWGT_LB3  69-70      BIRTHWGT_OZ3  71-72      LOBTHWGT3  73         
   CMBABDOB  74-77          KIDAGE  78-81            HPAGELB  82-83        
   BIRTHPLC  84             PAYBIRTH1  85            PAYBIRTH2  86         
   PAYBIRTH3  87            KNEWPREG  88-89          TRIMESTR  90          
   LTRIMEST  91             PRIORSMK  92             POSTSMKS  93          
   NPOSTSMK  94             GETPRENA  95             BGNPRENA  96-97       
   PNCTRIM  98              LPNCTRI  99              WORKPREG  100         
   WORKBORN  101            DIDWORK  102             MATWEEKS  103-104     
   WEEKSDK  105             MATLEAVE  106-107        MATCHFOUND  108       
   LIVEHERE  109            ALIVENOW  110            CMKIDIED  111-114     
   CMKIDLFT  115-118        LASTAGE  119-121         WHERENOW  122         
   LEGAGREE  123            PARENEND  124            ANYNURSE  125         
   FEDSOLID  126            FRSTEATD_N  127-129      FRSTEATD_P  130       
   FRSTEATD  131-133        QUITNURS  134            AGEQTNUR_N  135-137   
   AGEQTNUR_P  138          AGEQTNUR  139-141        MatchFound2  142      
   LIVEHERE2  143           ALIVENOW2  144           CMKIDIED2  145-148    
   CMKIDLFT2  149-152       LASTAGE2  153-155        WHERENOW2  156        
   LEGAGREE2  157           PARENEND2  158           ANYNURSE2  159        
   FEDSOLID2  160           FRSTEATD_N2  161-162     FRSTEATD_P2  163      
   FRSTEATD2  164-165       QUITNURS2  166           AGEQTNUR_N2  167-168  
   AGEQTNUR_P2  169         AGEQTNUR2  170-171       MatchFound3  172      
   LIVEHERE3  173           ALIVENOW3  174           CMKIDIED3  175-178    
   CMKIDLFT3  179-182       LASTAGE3  183-185        WHERENOW3  186        
   LEGAGREE3  187           PARENEND3  188           ANYNURSE3  189        
   FEDSOLID3  190           FRSTEATD_N3  191         FRSTEATD_P3  192      
   FRSTEATD3  193           QUITNURS3  194           AGEQTNUR_N3  195      
   AGEQTNUR_P3  196         AGEQTNUR3  197           CMLASTLB  198-201     
   CMFSTPRG  202-205        CMLSTPRG  206-209        CMINTSTR  210-213     
   CMINTFIN  214-217        CMINTSTROP  218-221      CMINTFINOP  222-225   
   CMINTSTRCR  226-229      CMINTFINCR  230-233      EVUSEINT  234         
   STOPDUSE  235            WHYSTOPD  236            WHATMETH01  237-238   
   WHATMETH02  239-240      WHATMETH03  241-242      WHATMETH04  243-244   
   RESNOUSE  245            WANTBOLD  246            PROBBABE  247         
   CNFRMNO  248             WANTBLD2  249            TIMINGOK  250         
   TOOSOON_N  251-253       TOOSOON_P  254           WTHPART1  255         
   WTHPART2  256            FEELINPG  257-258        HPWNOLD  259          
   TIMOKHP  260             COHPBEG  261             COHPEND  262          
   TELLFATH  263            WHENTELL  264            TRYSCALE  265-266     
   WANTSCAL  267-268        WHYPRG1  269             WHYPRG2  270          
   WHYNOUSE1  271           WHYNOUSE2  272           WHYNOUSE3  273        
   ANYUSINT  274            PRGLNGTH  275-276        OUTCOME  277          
   BIRTHORD  278-279        DATEND  280-283          AGEPREG  284-287      
   DATECON  288-291         AGECON  292-295          FMAROUT5  296         
   PMARPREG  297            RMAROUT6  298            FMARCON5  299         
   LEARNPRG  300-301        PNCAREWK  302-303        PAYDELIV  304         
   LBW1  305                BFEEDWKS  306-308        MATERNLV  309         
   OLDWANTR  310            OLDWANTP  311            WANTRESP  312         
   WANTPART  313            CMBIRTH  314-317         AGER  318-319         
   agescrn  320-321         FMARITAL  322            RMARITAL  323         
   EDUCAT  324-325          HIEDUC  326-327          RACE  328             
   HISPANIC  329            HISPRACE  330            RCURPREG  331         
   PREGNUM  332-333         PARITY  334-335          INSURANC  336         
   PUBASSIS  337            POVERTY  338-340         LABORFOR  341         
   RELIGION  342            METRO  343               BRNOUT  344           
   YRSTRUS  345-348         PRGLNGTH_I  349          OUTCOME_I  350        
   BIRTHORD_I  351          DATEND_I  352            AGEPREG_I  353        
   DATECON_I  354           AGECON_I  355            FMAROUT5_I  356       
   PMARPREG_I  357          RMAROUT6_I  358          FMARCON5_I  359       
   LEARNPRG_I  360          PNCAREWK_I  361          PAYDELIV_I  362       
   LBW1_I  363              BFEEDWKS_I  364          MATERNLV_I  365       
   OLDWANTR_I  366          OLDWANTP_I  367          WANTRESP_I  368       
   WANTPART_I  369          AGER_I  370              FMARITAL_I  371       
   RMARITAL_I  372          EDUCAT_I  373            HIEDUC_I  374         
   RACE_I  375              HISPANIC_I  376          HISPRACE_I  377       
   RCURPREG_I  378          PREGNUM_I  379           PARITY_I  380         
   INSURANC_I  381          PUBASSIS_I  382          POVERTY_I  383        
   LABORFOR_I  384          RELIGION_I  385          METRO_I  386          
   BASEWGT  387-404         ADJ_MOD_BASEWGT  405-422   FINALWGT  423-440     
   SECU_P  441              SEST  442-443            CMINTVW  444-447 ;    



/* VARIABLE LABEL STATEMENT - NSFG PREGNANCY FILE */

LABEL
 /*
 *************
 * SECTION B *
 *************
 */
    CASEID          = "RESPONDENT ID NUMBER"
    PREGORDR        = "PREGNANCY ORDER (NUMBER)"
    HOWPREG_N       = "BB-2 # OF WEEKS OR MONTHS CURRENTLY PREGNANT"
    HOWPREG_P       = "BB-2 CURRENT PREGNANCY LENGTH REPORTED IN MONTHS OR WEEKS"
    MOSCURRP        = "NUMBER OF MONTHS CURRENTLY PREGNANT"
    NOWPRGDK        = "BB-3 WHICH TRIMESTER -- CURRENT PREGNANCY"
    PREGEND1        = "BC-1 HOW PREGNANCY ENDED - 1ST MENTION"
    PREGEND2        = "BC-1 HOW PREGNANCY ENDED - 2ND MENTION"
    NBRNALIV        = "BC-2 NUMBER OF BABIES BORN ALIVE FROM THIS PREGNANCY"
    MULTBRTH        = "BC-3 WAS THIS A MULTIPLE BIRTH"
    CMOTPREG        = "CM FOR PREGNANCY END DATE (IF NONLIVEBIRTH)"
    PRGOUTCOME      = "OUTCOME OF PREGNANCY (BASED ON PRIORITY ORDERING)"
    CMPRGEND        = "CM FOR PREGNANCY END DATE (REGARDLESS OF OUTCOME)"
    FLGDKMO1        = "FLAG INDICATING SEASON/DK/RF FOR BC-4A DATPRGEN_M"
    CMPRGBEG        = "CM FOR PREGNANCY START DATE"
    AGEATEND        = "BC-4B R'S AGE AT PREGNANCY'S END DATE"
    HPAGEEND        = "BC-4C FATHER'S AGE AT PREGNANCY'S END DATE"
    GESTASUN_M      = "BC-5 GESTATIONAL LENGTH OF PREGNANCY IN MONTHS"
    GESTASUN_W      = "BC-5 GESTATIONAL LENGTH OF PREGNANCY IN WEEKS"
    WKSGEST         = "GESTATIONAL LENGTH OF COMPLETED PREGNANCY (IN WEEKS)"
    MOSGEST         = "GESTATIONAL LENGTH OF COMPLETED PREGNANCY (IN MONTHS)"
    DK1GEST         = "BC-6 DK FOLLOWUP FOR GESTATIONAL LENGTH OF A STILLBIRTH"
    DK2GEST         = "BC-7 DK FOLLOWUP FOR GESTATIONAL LENGTH OF A LIVEBIRTH"
    DK3GEST         = "BC-8 DK FOLLOWUP FOR GESTATIONAL LENGTH OF A MISCARR/ABOR/ECTOP"
    BPA_BDSCHECK1   = "WHETHER 1ST LIVEBORN BABY FROM THIS PREGNANCY WAS BPA OR BDS"
    BPA_BDSCHECK2   = "WHETHER 2ND LIVEBORN BABY FROM THIS PREGNANCY WAS BPA OR BDS"
    BPA_BDSCHECK3   = "WHETHER 3RD LIVEBORN BABY FROM THIS PREGNANCY WAS BPA OR BDS"
    BABYSEX         = "BD-2 SEX OF 1ST LIVEBORN BABY FROM THIS PREGNANCY"
    BIRTHWGT_LB     = "BD-3 BIRTHWEIGHT IN POUNDS - 1ST BABY FROM THIS PREGNANCY"
    BIRTHWGT_OZ     = "BD-3 BIRTHWEIGHT IN OUNCES - 1ST BABY FROM THIS PREGNANCY"
    LOBTHWGT        = "BD-4 IS BABY LOW BIRTHWEIGHT- 1ST BABY FROM THIS PREGNANCY"
    BABYSEX2        = "BD-2 SEX OF 2ND LIVEBORN BABY FROM THIS PREGNANCY"
    BIRTHWGT_LB2    = "BD-3 BIRTHWEIGHT IN POUNDS - 2ND BABY FROM THIS PREGNANCY"
    BIRTHWGT_OZ2    = "BD-3 BIRTHWEIGHT IN OUNCES - 2ND BABY FROM THIS PREGNANCY"
    LOBTHWGT2       = "BD-4 IS BABY LOW BIRTHWEIGHT- 2ND BABY FROM THIS PREGNANCY"
    BABYSEX3        = "BD-2 SEX OF 3RD LIVEBORN BABY FROM THIS PREGNANCY"
    BIRTHWGT_LB3    = "BD-3 BIRTHWEIGHT IN POUNDS - 3RD BABY FROM THIS PREGNANCY"
    BIRTHWGT_OZ3    = "BD-3 BIRTHWEIGHT IN OUNCES - 3RD BABY FROM THIS PREGNANCY"
    LOBTHWGT3       = "BD-4 IS BABY LOW BIRTHWEIGHT- 3RD BABY FROM THIS PREGNANCY"
    CMBABDOB        = "CM FOR BABY'S OR BABIES' DATE OF BIRTH (DELIVERY DATE)"
    KIDAGE          = "CURRENT AGE (IN MOS) OF R'S CHILD(REN) FROM THIS PREGNANCY"
    HPAGELB         = "BD-6 FATHER'S AGE AT TIME OF CHILD(REN) S BIRTH"
    BIRTHPLC        = "BD-7 PLACE WHERE R GAVE BIRTH"
    PAYBIRTH1       = "BD-8 PAYMENT FOR DELIVERY - 1ST MENTION"
    PAYBIRTH2       = "BD-8 PAYMENT FOR DELIVERY - 2ND MENTION"
    PAYBIRTH3       = "BD-8 PAYMENT FOR DELIVERY - 3RD MENTION"
    KNEWPREG        = "BE-1 WEEKS PREGNANT WHEN R LEARNED SHE WAS PREGNANT"
    TRIMESTR        = "BE-2A DK FOLLOWUP FOR KNEWPREG WHEN GESTATION >= 6 MOS"
    LTRIMEST        = "BE-2B DK FOLLOWUP FOR KNEWPREG WHEN GESTATION < 6 MOS"
    PRIORSMK        = "BE-3 AMOUNT R'SMOKED IN 6 MOS BEFORE R KNEW SHE WAS PREGNANT"
    POSTSMKS        = "BE-4 R'SMOKED AT ALL AFTER R KNEW SHE WAS PREGNANT"
    NPOSTSMK        = "BE-5 AMOUNT R'SMOKED DURING PREGNANCY AFTER R KNEW SHE WAS PREG"
    GETPRENA        = "BE-6 ANY PRENATAL CARE FOR THIS PREGNANCY"
    BGNPRENA        = "BE-7 WEEKS PREGNANT AT FIRST PRENATAL CARE VISIT"
    PNCTRIM         = "BE-8A DK FOLLOWUP FOR BGNPRENA WHEN GESTATION >= 6 MOS"
    LPNCTRI         = "BE-8B DK FOLLOWUP FOR BGNPRENA WHEN GESTATION < 6 MOS"
    WORKPREG        = "BF-1 R WORKED AT ALL DURING THIS PREGNANCY"
    WORKBORN        = "BF-2 MATERNITY LEAVE TAKEN FOR THIS PREGNANCY"
    DIDWORK         = "BF-3 WHY NO MATERNITY LEAVE WAS TAKEN FOR THIS PREGNANCY"
    MATWEEKS        = "BF-4 WEEKS OF MATERNITY LEAVE TAKEN FOR THIS PREGNANCY"
    WEEKSDK         = "BF-5 DK FOLLOWUP - WAS MATERNITY LEAVE <=4 OR > 4 WEEKS"
    MATLEAVE        = "BF-6 WEEKS OF PAID MATERNITY LEAVE FOR THIS PREGNANCY"
    MATCHFOUND      = "CHECK ON WHETHER CHILD MATCHES BIO CHILD IN HH ROSTER - 1ST"
    LIVEHERE        = "BG-1 WHETHER CHILD LIVES WITH R - 1ST FROM THIS PREGNANCY"
    ALIVENOW        = "BG-2 WHETHER CHILD IS STILL ALIVE - 1ST FROM THIS PREGNANCY"
    CMKIDIED        = "CM FOR CHLD'S DATE OF DEATH - 1ST FROM THIS PREGNANCY"
    CMKIDLFT        = "CM FOR DATE CHILD STOPPED LIVING W/R - 1ST FROM THIS PREGNANCY"
    LASTAGE         = "AGE (IN MOS) WHEN CHILD LAST LIVED W/R-1ST FROM THIS PREGNANCY"
    WHERENOW        = "BG-5 WHERE CHILD LIVES NOW - 1ST FROM THIS PREGNANCY"
    LEGAGREE        = "BG-6 LEGAL AGREEMENT FOR WHERE CHILD LIVES - 1ST FROM THIS PREG"
    PARENEND        = "BG-7 IS R STILL LEGAL MOTHER OF CHILD - 1ST FROM THIS PREGNANCY"
    ANYNURSE        = "BH-1 WHETHER R BREASTFED THIS CHILD AT ALL - 1ST FROM THIS PREG"
    FEDSOLID        = "BH-2 HAS R BEGUN SUPPLEMENTATION FOR CHILD - 1ST FROM THIS PREG"
    FRSTEATD_N      = "BH-3 AGE (MOS/WKS/DAY) WHEN 1ST SUPPLEMENTED - 1ST FROM THIS PREG"
    FRSTEATD_P      = "BH-3 UNITS (MOS/WKS/DAYS) FOR FRSTEATD_N - 1ST FROM THIS PREG"
    FRSTEATD        = "AGE (IN MOS) WHEN 1ST SUPPLEMENTED - 1ST FROM THIS PREG"
    QUITNURS        = "BH-4 HAS R'STOPPED BREASTFEEDING CHILD - 1ST FROM THIS PREG"
    AGEQTNUR_N      = "BH-5 AGE (MOS/WKS/DAY) WHEN STOPPED BREASTFEEDING - 1ST FROM THIS PREG"
    AGEQTNUR_P      = "BH-5 UNITS (MOS/WKS/DAYS) FOR AGEQTNUR_N - 1ST FROM THIS PREG"
    AGEQTNUR        = "AGE (IN MOS) WHEN R'STOPPED NURSING CHILD - 1ST FROM THIS PREG"
    MATCHFOUND2     = "CHECK ON WHETHER CHILD MATCHES BIO CHILD IN HH ROSTER - 2ND"
    LIVEHERE2       = "BG-1 WHETHER CHILD LIVES WITH R - 2ND FROM THIS PREGNANCY"
    ALIVENOW2       = "BG-2 WHETHER CHILD IS STILL ALIVE - 2ND FROM THIS PREGNANCY"
    CMKIDIED2       = "CM FOR CHLD'S DATE OF DEATH - 2ND FROM THIS PREGNANCY"
    CMKIDLFT2       = "CM FOR DATE CHILD STOPPED LIVING W/R - 2ND FROM THIS PREGNANCY"
    LASTAGE2        = "AGE (IN MOS) WHEN CHILD LAST LIVED W/R - 2ND FROM THIS PREGNANCY"
    WHERENOW2       = "BG-5 WHERE CHILD LIVES NOW - 2ND FROM THIS PREGNANCY"
    LEGAGREE2       = "BG-6 LEGAL AGREEMENT FOR WHERE CHILD LIVES - 2ND FROM THIS PREG"
    PARENEND2       = "BG-7 IS R STILL LEGAL MOTHER OF CHILD - 2ND FROM THIS PREGNANCY"
    ANYNURSE2       = "BH-1 WHETHER R BREASTFED THIS CHILD AT ALL - 2ND FROM THIS PREG"
    FEDSOLID2       = "BH-2 HAS R BEGUN SUPPLEMENTATION FOR CHILD - 2ND FROM THIS PREG"
    FRSTEATD_N2     = "BH-3 AGE (MOS/WKS/DAY) WHEN 1ST SUPPLEMENTED - 2ND FROM THIS PREG"
    FRSTEATD_P2     = "BH-3 UNITS (MOS/WKS/DAYS) FOR FRSTEATD_N - 2ND FROM THIS PREG"
    FRSTEATD2       = "AGE (IN MOS) WHEN 1ST SUPPLEMENTED - 2ND FROM THIS PREG"
    QUITNURS2       = "BH-4 HAS R'STOPPED BREASTFEEDING CHILD - 2ND FROM THIS PREG"
    AGEQTNUR_N2     = "BH-5 AGE (MOS/WKS/DAY) WHEN STOPPED BREASTFEEDING - 2ND FROM THIS PREG"
    AGEQTNUR_P2     = "BH-5 UNITS (MOS/WKS/DAYS) FOR AGEQTNUR_N - 2ND FROM THIS PREG"
    AGEQTNUR2       = "AGE (IN MOS) WHEN R'STOPPED NURSING CHILD - 2ND FROM THIS PREG"
    MATCHFOUND3     = "CHECK ON WHETHER CHILD MATCHES BIO CHILD IN HH ROSTER - 3RD"
    LIVEHERE3       = "BG-1 WHETHER CHILD LIVES WITH R - 3RD FROM THIS PREGNANCY"
    ALIVENOW3       = "BG-2 WHETHER CHILD IS STILL ALIVE - 3RD FROM THIS PREGNANCY"
    CMKIDIED3       = "CM FOR CHLD'S DATE OF DEATH - 3RD FROM THIS PREGNANCY"
    CMKIDLFT3       = "CM FOR DATE CHILD STOPPED LIVING W/R - 3RD FROM THIS PREGNANCY"
    LASTAGE3        = "AGE (IN MOS) WHEN CHILD LAST LIVED W/R - 3RD FROM THIS PREGNANCY"
    WHERENOW3       = "BG-5 WHERE CHILD LIVES NOW - 3RD FROM THIS PREGNANCY"
    LEGAGREE3       = "BG-6 LEGAL AGREEMENT FOR WHERE CHILD LIVES - 3RD FROM THIS PREG"
    PARENEND3       = "BG-7 IS R STILL LEGAL MOTHER OF CHILD - 3RD FROM THIS PREGNANCY"
    ANYNURSE3       = "BH-1 WHETHER R BREASTFED THIS CHILD AT ALL - 3RD FROM THIS PREG"
    FEDSOLID3       = "BH-2 HAS R BEGUN SUPPLEMENTATION FOR CHILD - 3RD FROM THIS PREG"
    FRSTEATD_N3     = "BH-3 AGE (MOS/WKS/DAY) WHEN 1ST SUPPLEMENTED - 3RD FROM THIS PREG"
    FRSTEATD_P3     = "BH-3 UNITS (MOS/WKS/DAYS) FOR FRSTEATD_N - 3RD FROM THIS PREG"
    FRSTEATD3       = "AGE (IN MOS) WHEN 1ST SUPPLEMENTED - 3RD FROM THIS PREG"
    QUITNURS3       = "BH-4 HAS R'STOPPED BREASTFEEDING CHILD - 3RD FROM THIS PREG"
    AGEQTNUR_N3     = "BH-5 AGE (MOS/WKS/DAY) WHEN STOPPED BREASTFEEDING - 3RD FROM THIS PREG"
    AGEQTNUR_P3     = "BH-5 UNITS (MOS/WKS/DAYS) FOR AGEQTNUR_N - 3RD FROM THIS PREG"
    AGEQTNUR3       = "AGE (IN MOS) WHEN R'STOPPED NURSING CHILD - 3RD FROM THIS PREG"
    CMLASTLB        = "CM FOR R'S MOST RECENT LIVE BIRTH"
    CMFSTPRG        = "CM FOR R'S FIRST COMPLETED PREGNANCY"
    CMLSTPRG        = "CM FOR R'S MOST RECENT COMPLETED PREGNANCY"

 /*
 *************
 * SECTION E *
 *************
 */
    CMINTSTR        = "CM FOR DATE OF BEGINNING OF PREGNANCY INTERVAL"
    CMINTFIN        = "CM FOR DATE OF END OF PREGNANCY INTERVAL"
    CMINTSTROP      = "OPEN INTERVAL: CM OF DATE OF BEGINNING"
    CMINTFINOP      = "OPEN INTERVAL: CM OF DATE OF END (MON OF INTERVIEW)"
    CMINTSTRCR      = "CURRENTLY PREGNANT: CM OF DATE OF BEGINNING OF INTERVAL"
    CMINTFINCR      = "CURRENTLY PREGNANT: CM OF DATE OF END OF INTERVAL (MON OF INTERVIEW)"
    EVUSEINT        = "EG-1 USE ANY METHOD IN PREGNANCY INTERVAL?"
    STOPDUSE        = "EG-2 BEFORE YOU BECAME PREG, STOP USING ALL METHODS?"
    WHYSTOPD        = "EG-3 STOP USING METHODS BEFORE PREG BECAUSE WANTED PREG?"
    WHATMETH01      = "EG-4 METHOD(S) USING WHEN BECAME PREG - 1ST MENTION"
    WHATMETH02      = "EG-4 METHOD(S) USING WHEN BECAME PREG - 2ND MENTION"
    WHATMETH03      = "EG-4 METHOD(S) USING WHEN BECAME PREG - 3RD MENTION"
    WHATMETH04      = "EG-4 METHOD(S) USING WHEN BECAME PREG - 4TH MENTION"
    RESNOUSE        = "EG-5 REASON NOT USING/HAD STOPPED USING METHOD BEC. WANTED PREG?"
    WANTBOLD        = "EG-6 RIGHT BEF PREG, WANT TO HAVE BABY AT ANY TIME IN FUTURE?"
    PROBBABE        = "EG-7 PROBABLY WANT BABY AT ANY TIME OR NOT?"
    CNFRMNO         = "EG-8 VERIFY DIDN'T WANT BABY AT ANY TIME IN FUTURE"
    WANTBLD2        = "EG-9 RIGHT BEFORE PREG, WANT TO HAVE BABY AT ANY TIME IN FUTURE? (2ND ASKING)"
    TIMINGOK        = "EG-10 BECOME PREG TOO SOON, RIGHT TIME, OR LATER THAN YOU WANTED?"
    TOOSOON_N       = "EG-11 HOW MUCH SOONER THAN WANTED BECAME PREG (MONTHS OR YEARS)"
    TOOSOON_P       = "EG-11 CHOOSE MONS OR YRS FOR HOW MUCH SOONER BECAME PREG THAN WANTED"
    WTHPART1        = "EG-12A RIGHT BEFORE PREG, WANT TO HAVE BABY WITH THAT PARTNER?"
    WTHPART2        = "EG-12B RIGHT BEF. PREG, THINK MIGHT EVER WANT TO HAVE BABY W/THAT PARTNER?"
    FEELINPG        = "EG-13 HAPPINESS TO BE PREG. SCALE (1-10)"
    HPWNOLD         = "EG-16 RIGHT BEF PREG, DID THE FATHER WANT R TO HAVE BABY AT ANY TIME IN FUTURE?"
    TIMOKHP         = "EG-17 R BECAME PREG SOONER, RIGHT TIME, OR LATER THAN FATHER OF PREG WANTED"
    COHPBEG         = "EG-18A WAS R LIVING W/FATHER OF PREG AT BEGINNING OF PREG"
    COHPEND         = "EG-18B WAS R LIVING W/FATHER OF PREG WHEN PREG ENDED/BABY WAS BORN"
    TELLFATH        = "EG-19 DID R TELL FATHER OF PREG THAT SHE WAS PREGNANT"
    WHENTELL        = "EG-20 WHEN DID R TELL FATHER OF PREG ABOUT PREGNANCY: DURING OR AFTER?"
    TRYSCALE        = "EG-21 HOW HARD TRYING TO GET/AVOID PREGNANCY (0-10)"
    WANTSCAL        = "EG-22 HOW MUCH WANTED TO GET/AVOID PREGNANCY (0-10)"
    WHYPRG1         = "EG-23 (UNINTENDED PREG): METHOD FAIL OR R WASN T USING PROPERLY-1ST MENTION"
    WHYPRG2         = "EG-23 (UNINTENDED PREG): METHOD FAIL OR R WASN T USING PROPERLY-2ND MENTION"
    WHYNOUSE1       = "EG-24 (UNINTENDED PREG) REASON DIDN'T USE METHOD - 1ST MENTION"
    WHYNOUSE2       = "EG-24 (UNINTENDED PREG) REASON DIDN'T USE METHOD - 2ND MENTION"
    WHYNOUSE3       = "EG-24 (UNINTENDED PREG) REASON DIDN'T USE METHOD - 3RD MENTION"
    ANYUSINT        = "ANY METHOD USE IN PREGNANCY INTERVAL"

 /* PREGNANCY RECODE IMPUTATION FLAGS */
    PRGLNGTH        = "DURATION OF COMPLETED PREGNANCY IN WEEKS"
    OUTCOME         = "PREGNANCY OUTCOME"
    BIRTHORD        = "BIRTH ORDER"
    DATEND          = "CM DATE PREGNANCY ENDED"
    AGEPREG         = "AGE AT PREGNANCY OUTCOME"
    DATECON         = "CM DATE OF CONCEPTION"
    AGECON          = "AGE AT TIME OF CONCEPTION"
    FMAROUT5        = "FORMAL MARITAL STATUS AT PREGNANCY OUTCOME"
    PMARPREG        = "WHETHER PREGNANCY ENDED BEFORE R'S 1ST MARRIAGE (PREMARITALLY)"
    RMAROUT6        = "INFORMAL MARITAL STATUS AT PREGNANCY OUTCOME - 6 CATEGORIES"
    FMARCON5        = "FORMAL MARITAL STATUS AT CONCEPTION - 5 CATEGORIES"
    LEARNPRG        = "NUMBER OF WEEKS PREGNANT WHEN R LEARNED SHE WAS PREGNANT"
    PNCAREWK        = "NUMBER OF WEEKS PREGNANT AT FIRST PRENATAL CARE"
    PAYDELIV        = "PAYMENT FOR DELIVERY"
    LBW1            = "LOW BIRTHWEIGHT - BABY 1"
    BFEEDWKS        = "DURATION OF BREASTFEEDING IN WEEKS"
    MATERNLV        = "USE OF MATERNITY LEAVE"
    OLDWANTR        = "WANTEDNESS OF PREGNANCY - RESPONDENT - CYCLE 4 VERSION"
    OLDWANTP        = "WANTEDNESS OF PREG - R'S PARTNER (FATHER OF PREGNANCY) - CYCLE 4 VERSION"
    WANTRESP        = "WANTEDNESS OF PREGNANCY - RESPONDENT - CYCLE 5 VERSION"
    WANTPART        = "WANTEDNESS OF PREG - R'S PARTNER (FATHER OF PREGNANCY) - CYCLE 5 VERSION"
    CMBIRTH         = "CENTURY MONTH OF R'S BIRTH"
    AGER            = "AGE AT INTERVIEW"
    AGESCRN         = "R'S AGE AT SCREENER"
    FMARITAL        = "FORMAL MARITAL STATUS"
    RMARITAL        = "INFORMAL MARITAL STATUS"
    EDUCAT          = "EDUCATION (COMPLETED YEARS OF SCHOOLING)"
    HIEDUC          = "HIGHEST COMPLETED YEAR OF SCHOOL OR DEGREE"
    RACE            = "RACE"
    HISPANIC        = "HISPANIC ORIGIN"
    HISPRACE        = "RACE AND HISPANIC ORIGIN"
    RCURPREG        = "PREGNANT AT TIME OF INTERVIEW"
    PREGNUM         = "CAPI-BASED TOTAL NUMBER OF PREGNANCIES"
    PARITY          = "TOTAL NUMBER OF LIVE BIRTHS"
    INSURANC        = "HEALTH INSURANCE COVERAGE STATUS"
    PUBASSIS        = "WHETHER R RECEIVED PUBLIC ASSISTANCE IN 2001"
    POVERTY         = "POVERTY LEVEL INCOME"
    LABORFOR        = "LABOR FORCE STATUS"
    RELIGION        = "CURRENT RELIGIOUS AFFILIATION"
    METRO           = "PLACE OF RESIDENCE (METROPOLITAN / NONMETROPOLITAN)"
    BRNOUT          = "IB-8 R BORN OUTSIDE OF US"
    YRSTRUS         = "YEAR R CAME TO THE UNITED STATES"

 /* PREGNANCY RECODE IMPUTATION FLAGS */
    PRGLNGTH_I      = "PRGLNGTH IMPUTATION FLAG"
    OUTCOME_I       = "OUTCOME IMPUTATION FLAG"
    BIRTHORD_I      = "BIRTHORD IMPUTATION FLAG"
    DATEND_I        = "DATEND IMPUTATION FLAG"
    AGEPREG_I       = "AGEPREG IMPUTATION FLAG"
    DATECON_I       = "DATECON IMPUTATION FLAG"
    AGECON_I        = "AGECON IMPUTATION FLAG"
    FMAROUT5_I      = "FMAROUT5 IMPUTATION FLAG"
    PMARPREG_I      = "PMARPREG IMPUTATION FLAG"
    RMAROUT6_I      = "RMAROUT6 IMPUTATION FLAG"
    FMARCON5_I      = "FMARCON5 IMPUTATION FLAG"
    LEARNPRG_I      = "LEARNPRG IMPUTATION FLAG"
    PNCAREWK_I      = "PNCAREWK IMPUTATION FLAG"
    PAYDELIV_I      = "PAYDELIV IMPUTATION FLAG"
    LBW1_I          = "LBW1 IMPUTATION FLAG"
    BFEEDWKS_I      = "BFEEDWKS IMPUTATION FLAG"
    MATERNLV_I      = "MATERNLV IMPUTATION FLAG"
    OLDWANTR_I      = "OLDWANTR IMPUTATION FLAG"
    OLDWANTP_I      = "OLDWANTP IMPUTATION FLAG"
    WANTRESP_I      = "WANTRESP IMPUTATION FLAG"
    WANTPART_I      = "WANTPART IMPUTATION FLAG"
    AGER_I          = "AGER IMPUTATION FLAG"
    FMARITAL_I      = "FMARITAL IMPUTATION FLAG"
    RMARITAL_I      = "RMARITAL IMPUTATION FLAG"
    EDUCAT_I        = "EDUCAT IMPUTATION FLAG"
    HIEDUC_I        = "HIEDUC IMPUTATION FLAG"
    RACE_I          = "RACE IMPUTATION FLAG"
    HISPANIC_I      = "HISPANIC IMPUTATION FLAG"
    HISPRACE_I      = "HISPRACE IMPUTATION FLAG"
    RCURPREG_I      = "RCURPREG IMPUTATION FLAG"
    PREGNUM_I       = "PREGNUM IMPUTATION FLAG"
    PARITY_I        = "PARITY IMPUTATION FLAG"
    INSURANC_I      = "INSURANC IMPUTATION FLAG"
    PUBASSIS_I      = "PUBASSIS IMPUTATION FLAG"
    POVERTY_I       = "POVERTY IMPUTATION FLAG"
    LABORFOR_I      = "LABORFOR IMPUTATION FLAG"
    RELIGION_I      = "RELIGION IMPUTATION FLAG"
    METRO_I         = "METRO IMPUTATION FLAG"

 /* WEIGHTS, RELATED VARIABLES AND DATE OF INTERVIEW */ 
    BASEWGT         = "BASE WEIGHT"
    ADJ_MOD_BASEWGT = "ADJUSTED MODIFIED BASE WEIGHT"
    FINALWGT        = "FINAL POST-STRATIFIED AND ADJUSTED WEIGHT"
    SECU_P          = "SCRAMBLED VERSION OF THE SAMPLING ERROR COMPUTATIONAL UNIT"
    SEST            = "SCRAMBLED VERSION OF THE STRATUM"
    CMINTVW         = "CENTURY MONTH OF INTERVIEW DATE"
    ;



/* FORMAT STATEMENT BEGINS HERE */

FORMAT
    PREGORDR      PREGORDR. 
    HOWPREG_N     HOWPRGF.  
    HOWPREG_P     TE_14F.   
    MOSCURRP      MOSFMT.   
    NOWPRGDK      TE_15F.   
    PREGEND1      TE_45F.   
    PREGEND2      TE_45F.   
    NBRNALIV      NBRNALIV. 
    MULTBRTH      TE_2F.    
    CMOTPREG      CMFMT.    
    PRGOUTCOME    PRGOUTF.  
    CMPRGEND      CMFMT.    
    FLGDKMO1      FLGDKMOF. 
    CMPRGBEG      CMFMT.    
    AGEATEND      AGEENDF.  
    HPAGEEND      HAGEENDF. 
    GESTASUN_M    MOSFMT.   
    GESTASUN_W    WKSFMT.   
    WKSGEST       WKSFMT.   
    MOSGEST       MOSFMT.   
    DK1GEST       TE_46F.   
    DK2GEST       TE_2F.    
    DK3GEST       TE_47F.   
    BPA_BDSCHECK1 BPABDS.   
    BPA_BDSCHECK2 BPABDS.   
    BPA_BDSCHECK3 BPABDS.   
    BABYSEX       TE_10F.   
    BIRTHWGT_LB   LBFMT.    
    BIRTHWGT_OZ   OZFMT.    
    LOBTHWGT      TE_49F.   
    BABYSEX2      TE_10F.   
    BIRTHWGT_LB2  LBFMT.    
    BIRTHWGT_OZ2  OZFMT.    
    LOBTHWGT2     TE_49F.   
    BABYSEX3      TE_10F.   
    BIRTHWGT_LB3  LBFMT.    
    BIRTHWGT_OZ3  OZFMT.    
    LOBTHWGT3     TE_49F.   
    CMBABDOB      CMFMT.    
    KIDAGE        NUMFMT.   
    HPAGELB       HAGEENDF. 
    BIRTHPLC      TE_50F.   
    PAYBIRTH1     TE_51F.   
    PAYBIRTH2     TE_51F.   
    PAYBIRTH3     TE_51F.   
    KNEWPREG      KNEWPREG. 
    TRIMESTR      TE_56F.   
    LTRIMEST      TE_53F.   
    PRIORSMK      TE_54F.   
    POSTSMKS      TE_2F.    
    NPOSTSMK      TE_55F.   
    GETPRENA      TE_2F.    
    BGNPRENA      KNEWPREG. 
    PNCTRIM       TE_56F.   
    LPNCTRI       TE_53F.   
    WORKPREG      TE_57F.   
    WORKBORN      TE_2F.    
    DIDWORK       TE_58F.   
    MATWEEKS      MATWEEKS. 
    WEEKSDK       TE_59F.   
    MATLEAVE      MATWEEKS. 
    MATCHFOUND    TE_2F.    
    LIVEHERE      TE_2F.    
    ALIVENOW      TE_2F.    
    CMKIDIED      CMFMT.    
    CMKIDLFT      CMFMT.    
    LASTAGE       NUMFMT.   
    WHERENOW      TE_60F.   
    LEGAGREE      TE_2F.    
    PARENEND      TE_2F.    
    ANYNURSE      TE_2F.    
    FEDSOLID      TE_2F.    
    FRSTEATD_N    NUMFMT.   
    FRSTEATD_P    TE_61F.   
    FRSTEATD      FRSTEATD. 
    QUITNURS      TE_2F.    
    AGEQTNUR_N    NUMFMT.   
    AGEQTNUR_P    TE_61F.   
    AGEQTNUR      AGEQTNUR. 
    MatchFound2   TE_2F.    
    LIVEHERE2     TE_2F.    
    ALIVENOW2     TE_2F.    
    CMKIDIED2     CMFMT.    
    CMKIDLFT2     CMFMT.    
    LASTAGE2      NUMFMT.   
    WHERENOW2     TE_60F.   
    LEGAGREE2     TE_2F.    
    PARENEND2     TE_2F.    
    ANYNURSE2     TE_2F.    
    FEDSOLID2     TE_2F.    
    FRSTEATD_N2   NUMFMT.   
    FRSTEATD_P2   TE_61F.   
    FRSTEATD2     FRSTEATD. 
    QUITNURS2     TE_2F.    
    AGEQTNUR_N2   NUMFMT.   
    AGEQTNUR_P2   TE_61F.   
    AGEQTNUR2     AGEQTNUR. 
    MatchFound3   TE_2F.    
    LIVEHERE3     TE_2F.    
    ALIVENOW3     TE_2F.    
    CMKIDIED3     CMFMT.    
    CMKIDLFT3     CMFMT.    
    LASTAGE3      NUMFMT.   
    WHERENOW3     TE_60F.   
    LEGAGREE3     TE_2F.    
    PARENEND3     TE_2F.    
    ANYNURSE3     TE_2F.    
    FEDSOLID3     TE_2F.    
    FRSTEATD_N3   NUMFMT.   
    FRSTEATD_P3   TE_61F.   
    FRSTEATD3     FRSTEATD. 
    QUITNURS3     TE_2F.    
    AGEQTNUR_N3   NUMFMT.   
    AGEQTNUR_P3   TE_61F.   
    AGEQTNUR3     AGEQTNUR. 
    CMLASTLB      CMFMT.    
    CMFSTPRG      CMFMT.    
    CMLSTPRG      CMFMT.    
    CMINTSTR      CMFMT.    
    CMINTFIN      CMFMT.    
    CMINTSTROP    CMFMT.    
    CMINTFINOP    CMFMT.    
    CMINTSTRCR    CMFMT.    
    CMINTFINCR    CMFMT.    
    EVUSEINT      TE_2F.    
    STOPDUSE      TE_2F.    
    WHYSTOPD      TE_2F.    
    WHATMETH01    TE_160F.  
    WHATMETH02    TE_160F.  
    WHATMETH03    TE_160F.  
    WHATMETH04    TE_160F.  
    RESNOUSE      TE_2F.    
    WANTBOLD      TE_161F.  
    PROBBABE      TE_162F.  
    CNFRMNO       TE_163F.  
    WANTBLD2      TE_164F.  
    TIMINGOK      TE_165F.  
    TOOSOON_N     TOOSOONF. 
    TOOSOON_P     TE_166F.  
    WTHPART1      TE_167F.  
    WTHPART2      TE_167F.  
    FEELINPG      FEELINGF. 
    HPWNOLD       TE_161F.  
    TIMOKHP       TE_165F.  
    COHPBEG       TE_2F.    
    COHPEND       TE_2F.    
    TELLFATH      TE_2F.    
    WHENTELL      TE_231F.  
    TRYSCALE      SCALEF.   
    WANTSCAL      SCALEF.   
    WHYPRG1       TE_168F.  
    WHYPRG2       TE_168F.  
    WHYNOUSE1     TE_169F.  
    WHYNOUSE2     TE_169F.  
    WHYNOUSE3     TE_169F.  
    ANYUSINT      TE_2F.    
    PRGLNGTH      PRGLNGTH. 
    OUTCOME       OUTCOME.  
    BIRTHORD      BIRTHORD. 
    DATEND        DATEND.   
    AGEPREG       AGEPRG.   
    DATECON       DATECON.  
    AGECON        AGECON.   
    FMAROUT5      FMAROUT.  
    PMARPREG      PMARPREG. 
    RMAROUT6      RMAROUT.  
    FMARCON5      FMARCON.  
    LEARNPRG      LEARNPRG. 
    PNCAREWK      PNCAREWK. 
    PAYDELIV      PAYDELIV. 
    LBW1          LBW.      
    BFEEDWKS      BFEEDWKS. 
    MATERNLV      MATERNLV. 
    OLDWANTR      OLDWANTR. 
    OLDWANTP      OLDWANTP. 
    WANTRESP      WANTRESP. 
    WANTPART      WANTPART. 
    CMBIRTH       CMFMT.    
    AGER          AGERFF.   
    agescrn       AGERFF.   
    FMARITAL      FMARITAL. 
    RMARITAL      RMARITAL. 
    EDUCAT        EDUCAT2F. 
    HIEDUC        HIEDUC2F. 
    RACE          RACE.     
    HISPANIC      HISPANIC. 
    HISPRACE      HISPRACE. 
    RCURPREG      YESNO.    
    PREGNUM       NUMPREGF. 
    PARITY        PARITY.   
    INSURANC      INSURANC. 
    PUBASSIS      PUBASSIS. 
    POVERTY       POVERTYF. 
    LABORFOR      LABOR2FR. 
    RELIGION      RELIGION. 
    METRO         METRO.    
    BRNOUT        TE_2F.    
    YRSTRUS       YEARFMT.  
    PRGLNGTH_I    IMPFLAG.  
    OUTCOME_I     IMPFLAG.  
    BIRTHORD_I    IMPFLAG.  
    DATEND_I      IMPFLAG.  
    AGEPREG_I     IMPFLAG.  
    DATECON_I     IMPFLAG.  
    AGECON_I      IMPFLAG.  
    FMAROUT5_I    IMPFLAG.  
    PMARPREG_I    IMPFLAG.  
    RMAROUT6_I    IMPFLAG.  
    FMARCON5_I    IMPFLAG.  
    LEARNPRG_I    IMPFLAG.  
    PNCAREWK_I    IMPFLAG.  
    PAYDELIV_I    IMPFLAG.  
    LBW1_I        IMPFLAG.  
    BFEEDWKS_I    IMPFLAG.  
    MATERNLV_I    IMPFLAG.  
    OLDWANTR_I    IMPFLAG.  
    OLDWANTP_I    IMPFLAG.  
    WANTRESP_I    IMPFLAG.  
    WANTPART_I    IMPFLAG.  
    AGER_I        IMPFLAG.  
    FMARITAL_I    IMPFLAG.  
    RMARITAL_I    IMPFLAG.  
    EDUCAT_I      IMPFLAG.  
    HIEDUC_I      IMPFLAG.  
    RACE_I        IMPFLAG.  
    HISPANIC_I    IMPFLAG.  
    HISPRACE_I    IMPFLAG.  
    RCURPREG_I    IMPFLAG.  
    PREGNUM_I     IMPFLAG.  
    PARITY_I      IMPFLAG.  
    INSURANC_I    IMPFLAG.  
    PUBASSIS_I    IMPFLAG.  
    POVERTY_I     IMPFLAG.  
    LABORFOR_I    IMPFLAG.  
    RELIGION_I    IMPFLAG.  
    METRO_I       IMPFLAG.  
    CMINTVW       CMINTVWF. 
 ;

RUN;


PROC SQL NOPRINT;
    CREATE TABLE NSFG.FemPregLabels_2002 AS
    SELECT *
    FROM dictionary.columns
    WHERE libname="NSFG" AND UPCASE(memname)="FEMPREGDATA_2002";
QUIT;
