---
title: "Overall Contraceptive Use Rate"
author: "Joshua Born"
output:
  html_document:
    code_folding: hide
    toc: true
    toc_depth: 5
---

```{r setup, include=FALSE}
library(data.table)
library(ggplot2)
library(here)
library(knitr)
library(survey)

i_am('EDA/006_overall_contraceptive_use_rate.Rmd')

source(here('R/NSFG_helpers.R'))
source(here('R/helpers/deprecated.R'))
source(here('R/general_helpers.R'))

opts_chunk$set(
  cache = TRUE,
  echo = TRUE,
  fig.height = 8,
  fig.width = 12,
  warning = FALSE
)
```

```{r fem-load-data}
fem_2017_2019 <- load_NSFG_data('2017_2019', 'FemResp')
fem_2017_2019_formats <- fem_2017_2019$Formats
```

```{r fem-process-data, dependson=c('fem-load-data')}
fem_2017_2019_data <- copy(fem_2017_2019$Data[, .(
  CASEID,
  CONSTAT1 = factorize(CONSTAT1, 'CONSTATF', fem_2017_2019_formats),
  LSEXPREG = factorize(LSEXPREG, 'Y1N2RECF', fem_2017_2019_formats),
  METH3M1,
  METH3M2,
  METH3M3,
  P1YRELP = factorize(P1YRELP, 'P1YRELP', fem_2017_2019_formats),
  POSIBLMN = factorize(POSIBLMN, 'Y1N5RDF', fem_2017_2019_formats),
  POSIBLPG = factorize(POSIBLPG, 'Y1N5RDF', fem_2017_2019_formats),
  PSURGSTR = factorize(PSURGSTR, 'Y1N5C', fem_2017_2019_formats),
  SECU,
  SEST,
  SEX3MO = factorize(SEX3MO, 'Y1N2RECF', fem_2017_2019_formats),
  TUBS = factorize(TUBS, 'Y1N5C', fem_2017_2019_formats),
  WGT2017_2019,
  WYNOLSTP = factorize(WYNOLSTP, 'Y1N5RDF', fem_2017_2019_formats),
  WYNOTUSE = factorize(WYNOTUSE, 'Y1N5RDF', fem_2017_2019_formats)
)])

# remove sterility not from contraceptive procedure from METH3M series
fem_2017_2019_data[
  METH3M3 %in% 20:21,
  `:=`(
    METH3M3 = NA
  )
]
fem_2017_2019_data[
  METH3M2 %in% 20:21,
  `:=`(
    METH3M2 = METH3M3,
    METH3M3 = NA
  )
]
fem_2017_2019_data[
  METH3M1 %in% 20:21,
  `:=`(
    METH3M1 = METH3M2,
    METH3M2 = METH3M3,
    METH3M3 = NA
  )
]

# make METH3M series variables into factors
fem_2017_2019_data[, `:=`(
  METH3M1 = factorize(METH3M1, 'METH3MF', fem_2017_2019_formats),
  METH3M2 = factorize(METH3M2, 'METH3MF', fem_2017_2019_formats),
  METH3M3 = factorize(METH3M3, 'METH3MF', fem_2017_2019_formats)
)]

# create boolean variables for whether each specific method is currently used
for (x in c(1:19, 22:24)) {
  set(
    fem_2017_2019_data,
    j = sprintf('using3m_meth%d', x),
    value = has_level(fem_2017_2019_data$METH3M1, x) |
      has_level(fem_2017_2019_data$METH3M2, x) |
      has_level(fem_2017_2019_data$METH3M3, x)
  )
}

# count any respondents who are sexually active and whose last intercourse was with husband or cohabitating partner who has an active vasectomy as using vasectomy as a contraceptive method
fem_2017_2019_data[, using3m_meth3 := fifelse(
  SEX3MO == 'YES' & PSURGSTR == 'YES' & (
    P1YRELP == 'Current husband or (current husband from whom she is separated)' |
    P1YRELP == 'Current cohabiting partner'
  ),
  TRUE,
  using3m_meth3
)]

# count any respondents with current tubal ligations who are sexually active as currently using tubal ligation as a contraceptive method
fem_2017_2019_data[, using3m_meth4 := fifelse(
  SEX3MO == 'YES' & TUBS == 'YES',
  TRUE,
  using3m_meth4
)]

# create variable counting number of current methods
fem_2017_2019_data[
  ,
  meth3m_count := rowSums(.SD),
  .SDcols = patterns('^using3m_meth')
]

# set master categorization for contraceptive use
fem_2017_2019_data[,
  curr_use := factor(fcase(
    meth3m_count > 0,
      'Used at least one contraceptive method at last intercourse',
    SEX3MO != 'YES',
      'Did not have sexual intercourse with male in past 3 months',
    LSEXPREG == 'YES',
      'Pregnant in month of last intercourse',
    CONSTAT1 == 'Postpartum',
      'Postpartum',
    (WYNOTUSE == 'Yes' | WYNOLSTP == 'Yes'),
      'Currently trying to conceive',
    POSIBLPG == 'No',
      'Physically unable to conceive',
    POSIBLMN == 'No' & (
      P1YRELP == 'Current cohabiting partner' |
      P1YRELP == 'Current husband or (current husband from whom she is separated)'
    ),
      'Last intercourse was with partner who is physically unable to conceive',
    default = 'Otherwise did not use contraception at last intercourse'
  ))
]

# create survey design object
fem_2017_2019_svy <- svydesign(
  ids = ~SECU,
  strata = ~SEST,
  data = fem_2017_2019_data,
  nest = TRUE,
  weights = ~WGT2017_2019
)
```


```{r male-load-data}
male_2017_2019 <- load_NSFG_data('2017_2019', 'Male')
male_2017_2019_formats <- male_2017_2019$Formats
```

```{r male-process-data, dependson=c('male-load-data')}
male_2017_2019_data <- copy(male_2017_2019$Data[, .(
  CWPPOSS = factorize(CWPPOSS, 'Y1N5RDF', male_2017_2019_formats),
  CWPPRGNW = factorize(CWPPRGNW, 'Y1N5RDF', male_2017_2019_formats),
  CWPTRYPG = factorize(CWPTRYPG, 'Y1N5RDF', male_2017_2019_formats),
  FATHPOSS = factorize(FATHPOSS, 'Y1N5RDF', male_2017_2019_formats),
  METH3M1 = factorize(METH3M1, 'METH3MF', male_2017_2019_formats),
  METH3M2 = factorize(METH3M2, 'METH3MF', male_2017_2019_formats),
  METH3M3 = factorize(METH3M3, 'METH3MF', male_2017_2019_formats),
  METH3M4 = factorize(METH3M4, 'METH3MF', male_2017_2019_formats),
  P1COHABIT = factorize(P1COHABIT, 'Y1N5RDF', male_2017_2019_formats),
  P1CURRWIFE = factorize(P1CURRWIFE, 'Y1N5RDF', male_2017_2019_formats),
  PSURGSTR = factorize(PSURGSTR, 'N0Y1CF', male_2017_2019_formats),
  PXCPREG = factorize(PXCPREG, 'Y1N5RDF', male_2017_2019_formats),
  PXTRYING = factorize(PXTRYING, 'Y1N5RDF', male_2017_2019_formats),
  RSURGSTR  = factorize(RSURGSTR, 'N0Y1RDF', male_2017_2019_formats),
  SECU,
  SEST,
  SEX3MO = factorize(SEX3MO, 'SEX3MO', male_2017_2019_formats),
  WGT2017_2019
)])

# create boolean variables for whether each specific method is currently used
for (x in 1:13) {
  set(
    male_2017_2019_data,
    j = sprintf('using3m_meth%d', x),
    value = has_level(male_2017_2019_data$METH3M1, x) |
      has_level(male_2017_2019_data$METH3M2, x) |
      has_level(male_2017_2019_data$METH3M3, x) |
      has_level(male_2017_2019_data$METH3M4, x)
  )
}

# count any respondents who are sexually active and who have an active vasectomy as using vasectomy as a contraceptive method
male_2017_2019_data[, using3m_meth3 := fifelse(
  SEX3MO == 'YES, HAD INTERCOURSE' & RSURGSTR == 'YES',
  TRUE,
  using3m_meth3
)]

# count any respondents who are sexually active and who are married or cohabitating and whose last intercourse was with wife or cohabitating partner who has active tubal ligation
male_2017_2019_data[, using3m_meth5 := fifelse(
  SEX3MO == 'YES, HAD INTERCOURSE' &
    (P1CURRWIFE == 'Yes' | P1COHABIT == 'Yes') &
    PSURGSTR == 'YES',
  TRUE,
  using3m_meth5
)]

# create variable counting number of current methods
male_2017_2019_data[
  ,
  meth3m_count := rowSums(.SD),
  .SDcols = patterns('^using3m_meth')
]

# set master categorization for contraceptive use
male_2017_2019_data[,
  curr_use := factor(fcase(
    meth3m_count > 0,
      'Used at least one contraceptive method at last intercourse',
    SEX3MO != 'YES, HAD INTERCOURSE',
      'Did not have sexual intercourse with female in past 3 months',
    PXCPREG == 'Yes' | ((P1CURRWIFE == 'Yes' | P1COHABIT == 'Yes') & CWPPRGNW == 'Yes'),
      'Last intercourse was with partner who is pregnant',
    PXTRYING == 'Yes' | ((P1CURRWIFE == 'Yes' | P1COHABIT == 'Yes') & CWPTRYPG == 'Yes'),
      'Last intercourse was with partner who is trying to conceive',
    FATHPOSS == 'No',
      'Physically unable to conceive',
    (P1CURRWIFE == 'Yes' | P1COHABIT == 'Yes') & CWPPOSS == 'No',
      'Last intercourse was with wife or cohabitating partner who is physically unable to concieve',
    default = 'Otherwise did not use contraception at last intercourse'
  ))
]

# create survey design object
male_2017_2019_svy <- svydesign(
  ids = ~SECU,
  strata = ~SEST,
  data = male_2017_2019_data,
  nest = TRUE,
  weights = ~WGT2017_2019
)
```

# Females

## Estimates

```{r, dependson=c('fem-process-data')}
collect_estimate(
  svyci(
    ~curr_use,
    fem_2017_2019_svy,
    svytotal
  ),
  type = 'total',
  domain = 'females aged 15-49 living in households in the United States',
  title = 'by current contraceptive status',
)[, .(level, estimate, se, `2.5 %`, `97.5 %`)] |> kable()
```


## Contraceptive Use Rate

```{r, dependson=c('fem-process-data')}
#svyratio(
#  ~I(curr_use == 'Used at least one contraceptive method at last intercourse'),
#  ~I(curr_use == 'Used at least one contraceptive method at last intercourse' | curr_use == 'Otherwise did not use contraception at last intercourse'),
#  fem_2017_2019_svy
#)

svyci(
  ~I(
    curr_use == 'Used at least one contraceptive method at last intercourse'
  ),
  subset(
    fem_2017_2019_svy,
    curr_use == 'Used at least one contraceptive method at last intercourse' | curr_use == 'Otherwise did not use contraception at last intercourse'
  ),
  svymean
) |> rounded() |> kable()
```

```{r, dependson=c('fem-process-data')}
svyci(
  ~I(
    curr_use == 'Used at least one contraceptive method at last intercourse'
  ),
  subset(
    fem_2017_2019_svy,
    curr_use == 'Used at least one contraceptive method at last intercourse' | curr_use == 'Otherwise did not use contraception at last intercourse'
  ),
  svytotal
) |> in_millions() |> kable()
```


# Males

```{r, dependson=c('male-process-data')}
collect_estimate(
  svyci(
    ~curr_use,
    male_2017_2019_svy,
    svytotal
  ),
  type = 'total',
  domain = 'males aged 15-49 living in households in the United States',
  title = 'by current contraceptive status',
)[, .(level, estimate, se, `2.5 %`, `97.5 %`)] |> kable()
```


## Contraceptive Use Rate

```{r, dependson=c('male-process-data')}
svyci(
  ~I(
    curr_use == 'Used at least one contraceptive method at last intercourse'
  ),
  subset(
    male_2017_2019_svy,
    curr_use == 'Used at least one contraceptive method at last intercourse' | curr_use == 'Otherwise did not use contraception at last intercourse'
  ),
  svymean
) |> rounded() |> kable()
```

```{r, dependson=c('male-process-data')}
svyci(
  ~I(
    curr_use == 'Used at least one contraceptive method at last intercourse'
  ),
  subset(
    male_2017_2019_svy,
    curr_use == 'Used at least one contraceptive method at last intercourse' | curr_use == 'Otherwise did not use contraception at last intercourse'
  ),
  svytotal
) |> in_millions() |> kable()
```
