---
title: "Persons Who Have Not Had Intercourse with Someone of the Opposite Sex in Previous 3 Months"
author: "Joshua Born"
output:
  html_document:
    code_folding: hide
    toc: true
    toc_depth: 5
---

```{r setup, include=FALSE}
library(data.table)
library(ggplot2)
library(here)
library(knitr)
library(survey)

i_am('EDA/008_not_sexually_active.Rmd')

source(here('R/NSFG_helpers.R'))
source(here('R/deprecated_helpers.R'))
source(here('R/general_helpers.R'))

opts_chunk$set(
  cache = TRUE,
  echo = TRUE,
  fig.height = 8,
  fig.width = 12,
  warning = FALSE
)
```

```{r fem-load-data}
fem_2017_2019 <- load_NSFG_data('2017_2019', 'FemResp')
fem_2017_2019_formats <- fem_2017_2019$Formats
```

```{r fem-process-data, dependson=c('fem-load-data')}
fem_2017_2019_data <- copy(fem_2017_2019$Data[, .(
  ATTRACT = factorize(ATTRACT, 'ATTRACT', fem_2017_2019_formats),
  CASEID,
  HADSEX = factorize(HADSEX, 'HADSEX', fem_2017_2019_formats),
  MFLASTP = factorize(MFLASTP, 'MALFEMNAF', fem_2017_2019_formats),
  SAMESEXANY = factorize(SAMESEXANY, 'Y1N5NAC', fem_2017_2019_formats),
  SECU,
  SEST,
  SEX3MO = factorize(SEX3MO, 'Y1N2RECF', fem_2017_2019_formats),
  WGT2017_2019,
  YNOSEX = factorize(YNOSEX, 'YNOSEX', fem_2017_2019_formats)
)])

# create two-level of SEX3MO
fem_2017_2019_data[, sex_active := factor(fifelse(
  SEX3MO == 'YES',
  'Had sexual intercourse with male in previous 3 months',
  'Did not have sexual intercourse with male in previous 3 months'
))]

# remove empty 'Not Applicable' level from ATTRACT
fem_2017_2019_data[, ATTRACT := factor(ATTRACT)]

# create survey design object
fem_2017_2019_svy <- svydesign(
  ids = ~SECU,
  strata = ~SEST,
  data = fem_2017_2019_data,
  nest = TRUE,
  weights = ~WGT2017_2019
)
```

```{r male-load-data}
male_2017_2019 <- load_NSFG_data('2017_2019', 'Male')
male_2017_2019_formats <- male_2017_2019$Formats
```

```{r male-process-data, dependson=c('male-load-data')}
male_2017_2019_data <- copy(male_2017_2019$Data[, .(
  ATTRACT = factorize(ATTRACT, 'ATTRACT', male_2017_2019_formats),
  CASEID,
  HADSEX = factorize(HADSEX, 'HADSEX', male_2017_2019_formats),
  MFLASTP = factorize(MFLASTP, 'MALFEMNAF', male_2017_2019_formats),
  SAMESEXANY = factorize(SAMESEXANY, 'Y1N5NAC', male_2017_2019_formats),
  SECU,
  SEST,
  SEX3MO = factorize(SEX3MO, 'SEX3MO', male_2017_2019_formats),
  WGT2017_2019,
  YNOSEX = factorize(YNOSEX, 'YNOSEX', male_2017_2019_formats)
)])

# create two-level of SEX3MO
male_2017_2019_data[, sex_active := factor(fifelse(
  SEX3MO == 'YES, HAD INTERCOURSE',
  'Had sexual intercourse with female in previous 3 months',
  'Did not have sexual intercourse with female in previous 3 months'
))]

# remove empty 'Not Applicable' level from ATTRACT
male_2017_2019_data[, ATTRACT := factor(ATTRACT)]

# create survey design object
male_2017_2019_svy <- svydesign(
  ids = ~SECU,
  strata = ~SEST,
  data = male_2017_2019_data,
  nest = TRUE,
  weights = ~WGT2017_2019
)
```


# Females

```{r, dependson=c('fem-process-data')}
collect_estimate(
  svyci(
    ~I(SEX3MO != 'YES'),
    fem_2017_2019_svy,
    svytotal
  ),
  type = 'total',
  domain = 'females aged 15-49 living in households in the United States',
  title = 'who did not have sexual intercourse with male in past 3 months'
) |> kable()
```


## Never Sexually Active

```{r, dependson=c('fem-process-data')}
collect_estimate(
  svyci(
    ~I(HADSEX == 'NO, R NEVER HAD INTERCOURSE'),
    subset(
      fem_2017_2019_svy,
      SEX3MO != 'YES'
    ),
    svytotal
  )[level == TRUE],
  type = 'total',
  domain = 'females who did not have sexual intercourse with male in past 3 months',
  title = 'who have never had sexual intercourse with male'
) |> kable()
```

```{r, dependson=c('fem-process-data')}
collect_estimate(
  svyci(
    ~I(HADSEX == 'NO, R NEVER HAD INTERCOURSE'),
    subset(
      fem_2017_2019_svy,
      SEX3MO != 'YES'
    ),
    svyciprop
  ),
  type = 'proportion',
  domain = 'females who did not have sexual intercourse with male in past 3 months',
  title = 'who have never had sexual intercourse with male'
) |> kable()
```

```{r, dependson=c('fem-process-data')}
collect_estimate(
  svyci(
    ~YNOSEX,
    subset(
      fem_2017_2019_svy,
      HADSEX == 'NO, R NEVER HAD INTERCOURSE'
    ),
    svytotal
  ),
  type = 'total',
  domain = 'females who have never had sexual intercourse with male',
  title = 'by reason for not having had sexual intercourse with male'
) |> kable()
```

```{r, dependson=c('fem-process-data')}
collect_estimate(
  svyci(
    ~YNOSEX,
    subset(
      fem_2017_2019_svy,
      HADSEX == 'NO, R NEVER HAD INTERCOURSE'
    ),
    svymean
  ),
  type = 'proportion',
  domain = 'females who have never had sexual intercourse with male',
  title = 'by reason for not having had sexual intercourse with male'
) |> kable()
```


## Attraction to Sexes

```{r, dependson=c('fem-process-data')}
collect_estimate(
  svyci(
    ~ATTRACT,
    subset(
      fem_2017_2019_svy,
      SEX3MO == 'YES'
    ),
    svymean,
    ordered = FALSE
  ),
  type = 'proportion',
  domain = 'females who have had intercourse with male in past 3 months',
  title = 'by strength of attraction to sexes'
) |> kable()
```

```{r, dependson=c('fem-process-data')}
collect_estimate(
  svyci(
    ~ATTRACT,
    subset(
      fem_2017_2019_svy,
      SEX3MO == 'NO'
    ),
    svymean,
    ordered = FALSE
  ),
  type = 'proportion',
  domain = 'females who have had sexual intercourse with male, but not in past 3 months',
  title = 'by strength of attraction to sexes'
) |> kable()
```

```{r, dependson=c('fem-process-data')}
collect_estimate(
  svyci(
    ~ATTRACT,
    subset(
      fem_2017_2019_svy,
      HADSEX == 'NO, R NEVER HAD INTERCOURSE'
    ),
    svymean,
    ordered = FALSE
  ),
  type = 'proportion',
  domain = 'females who have never had sexual intercourse with male',
  title = 'by strength of attraction to sexes'
) |> kable()
```

```{r, dependson=c('fem-process-data')}
collect_estimate(
  svyci(
    ~ATTRACT,
    subset(
      fem_2017_2019_svy,
      YNOSEX == 'Other'
    ),
    svymean,
    ordered = FALSE
  ),
  type = 'proportion',
  domain = 'females who have never had sexual intercourse with male for reason "Other"',
  title = 'by strength of attraction to sexes'
) |> kable()
```

```{r, dependson=c('fem-process-data')}
collect_estimate(
  svyci(
    ~ATTRACT,
    subset(
      fem_2017_2019_svy,
      YNOSEX == 'Other'
    ),
    svytotal,
    ordered = FALSE
  ),
  type = 'total',
  domain = 'females who have never had sexual intercourse with male for reason "Other"',
  title = 'by strength of attraction to sexes'
) |> kable()
```

```{r, dependson=c('fem-process-data')}
collect_estimate(
  svyci(
    ~ATTRACT,
    subset(
      fem_2017_2019_svy,
      SEX3MO != 'YES'
    ),
    svytotal,
    ordered = FALSE
  ),
  type = 'total',
  domain = 'females who have not had intercourse with a male in past 3 months',
  title = 'by strength of attraction to sexes'
) |> kable()
```

```{r, dependson=c('fem-process-data')}
collect_estimate(
  svyci(
    ~ATTRACT,
    subset(
      fem_2017_2019_svy,
      SEX3MO != 'YES'
    ),
    svymean,
    ordered = FALSE
  ),
  type = 'proportion',
  domain = 'females who have not had intercourse with a male in past 3 months',
  title = 'by strength of attraction to sexes'
) |> kable()
```

### Chi-squared Test

```{r, dependson=c('fem-process-data')}
svytable(~ATTRACT+sex_active, fem_2017_2019_svy) |> kable()
```

```{r, dependson=c('fem-process-data')}
env$estimates[
  type == 'proportion' &
    title == 'by strength of attraction to sexes' &
    (
      domain == 'females who have not had intercourse with a male in past 3 months' |
      domain == 'females who have had intercourse with male in past 3 months'
    ),
  .(
    domain, level, estimate, se, `2.5 %`, `97.5 %`
  )
] |> kable()
```

```{r, dependson=c('fem-process-data')}
svychisq(~ATTRACT+sex_active, fem_2017_2019_svy)
```



## Sexual Experience with Female Partner

```{r, dependson=c('fem-process-data')}
collect_estimate(
  svyci(
    ~SAMESEXANY,
    subset(
      fem_2017_2019_svy,
      HADSEX == 'NO, R NEVER HAD INTERCOURSE'
    ),
    svytotal
  ),
  type = 'total',
  domain = 'females who have never had sexual intercourse with male',
  title = 'by whether had sexual encounter with female'
) |> kable()
```

```{r, dependson=c('fem-process-data')}
collect_estimate(
  svyci(
    ~SAMESEXANY,
    subset(
      fem_2017_2019_svy,
      HADSEX == 'NO, R NEVER HAD INTERCOURSE'
    ),
    svymean
  ),
  type = 'proportion',
  domain = 'females who have never had sexual intercourse with male',
  title = 'by whether had sexual encounter with female'
) |> kable()
```

```{r, dependson=c('fem-process-data')}
collect_estimate(
  svyci(
    ~I(MFLASTP == 'Female'),
    subset(
      fem_2017_2019_svy,
      SEX3MO != 'YES'
    ),
    svytotal
  )[level == TRUE],
  type = 'total',
  domain = 'females who have not had intercourse with a male in past 3 months',
  title = 'by whether last sexual experience was with female partner'
) |> kable()
```

```{r, dependson=c('fem-process-data')}
collect_estimate(
  svyci(
    ~I(MFLASTP == 'Female'),
    subset(
      fem_2017_2019_svy,
      SEX3MO != 'YES'
    ),
    svyciprop
  ),
  type = 'proportion',
  domain = 'females who have not had intercourse with a male in past 3 months',
  title = 'by whether last sexual experience was with female partner'
) |> kable()
```



# Males

```{r, dependson=c('male-process-data')}
collect_estimate(
  svyci(
    ~I(SEX3MO != 'YES, HAD INTERCOURSE'),
    male_2017_2019_svy,
    svytotal
  ),
  type = 'total',
  domain = 'males aged 15-49 living in households in the United States',
  title = 'who did not have sexual intercourse with female in past 3 months'
) |> kable()
```


## Never Sexually Active

```{r, dependson=c('male-process-data')}
collect_estimate(
  svyci(
    ~I(HADSEX == 'NO, R NEVER HAD INTERCOURSE'),
    subset(
      male_2017_2019_svy,
      SEX3MO != 'YES, HAD INTERCOURSE'
    ),
    svytotal
  )[level == TRUE],
  type = 'total',
  domain = 'males who did not have sexual intercourse with female in past 3 months',
  title = 'who never had sexual intercourse with female'
) |> kable()
```

```{r, dependson=c('male-process-data')}
collect_estimate(
  svyci(
    ~I(HADSEX == 'NO, R NEVER HAD INTERCOURSE'),
    subset(
      male_2017_2019_svy,
      SEX3MO != 'YES, HAD INTERCOURSE'
    ),
    svyciprop
  ),
  type = 'proportion',
  domain = 'males who did not have sexual intercourse with female in past 3 months',
  title = 'who never had sexual intercourse with female'
) |> kable()
```

```{r, dependson=c('male-process-data')}
collect_estimate(
  svyci(
    ~YNOSEX,
    subset(
      male_2017_2019_svy,
      HADSEX == 'NO, R NEVER HAD INTERCOURSE'
    ),
    svytotal
  ),
  type = 'total',
  domain = 'males who have never had sexual intercourse with female',
  title = 'by reason for not having had sexual intercourse with female'
) |> kable()
```

```{r, dependson=c('male-process-data')}
collect_estimate(
  svyci(
    ~ATTRACT,
    subset(
      male_2017_2019_svy,
      YNOSEX == 'Other'
    ),
    svytotal,
    ordered = FALSE
  ),
  type = 'total',
  domain = 'males who have never had sexual intercourse with female for reason "Other"',
  title = 'by strength of attraction to sexes'
) |> kable()
```

```{r, dependson=c('male-process-data')}
collect_estimate(
  svyci(
    ~ATTRACT,
    subset(
      male_2017_2019_svy,
      YNOSEX == 'Other'
    ),
    svymean,
    ordered = FALSE
  ),
  type = 'proportion',
  domain = 'males who have never had sexual intercourse with female for reason "Other"',
  title = 'by strength of attraction to sexes'
) |> kable()
```


## Same-Sex Attraction

```{r, dependson=c('male-process-data')}
svytable(~ATTRACT+sex_active, male_2017_2019_svy) |> kable()
```

```{r, dependson=c('male-process-data')}
collect_estimate(
  svyci(
    ~ATTRACT,
    subset(
      male_2017_2019_svy,
      SEX3MO != 'YES, HAD INTERCOURSE'
    ),
    svymean,
    ordered = FALSE
  ),
  type = 'proportion',
  domain = 'males who did not have sexual intercourse with female in past 3 months',
  title = 'by strength of attraction to sexes'
) |> kable()
```

```{r, dependson=c('male-process-data')}
collect_estimate(
  svyci(
    ~ATTRACT,
    subset(
      male_2017_2019_svy,
      SEX3MO == 'YES, HAD INTERCOURSE'
    ),
    svymean,
    ordered = FALSE
  ),
  type = 'proportion',
  domain = 'males have had sexual intercourse with female in past 3 months',
  title = 'by strength of attraction to sexes'
) |> kable()
```

```{r, dependson=c('male-process-data')}
svychisq(~ATTRACT+sex_active, male_2017_2019_svy)
```

```{r, dependson=c('male-process-data')}
collect_estimate(
  svyci(
    ~ATTRACT,
    subset(
      male_2017_2019_svy,
      SEX3MO != 'YES, HAD INTERCOURSE'
    ),
    svytotal,
    ordered = FALSE
  ),
  type = 'total',
  domain = 'males who did not have sexual intercourse with female in past 3 months',
  title = 'by strength of attraction to sexes'
) |> kable()
```


## Sexual Experience with Male Partner

```{r, dependson=c('male-process-data')}
collect_estimate(
  svyci(
    ~SAMESEXANY,
    subset(
      male_2017_2019_svy,
      HADSEX == 'NO, R NEVER HAD INTERCOURSE'
    ),
    svytotal
  ),
  type = 'total',
  domain = 'males who have never had sexual intercourse with female',
  title = 'by whether had sexual encounter with male'
) |> kable()
```

```{r, dependson=c('male-process-data')}
collect_estimate(
  svyci(
    ~SAMESEXANY,
    subset(
      male_2017_2019_svy,
      HADSEX == 'NO, R NEVER HAD INTERCOURSE'
    ),
    svymean
  ),
  type = 'proportion',
  domain = 'males who have never had sexual intercourse with female',
  title = 'by whether had sexual encounter with male'
) |> kable()
```

```{r, dependson=c('male-process-data')}
collect_estimate(
  svyci(
    ~I(MFLASTP == 'Male'),
    subset(
      male_2017_2019_svy,
      SEX3MO != 'YES, HAD INTERCOURSE'
    ),
    svytotal
  )[level == TRUE],
  type = 'total',
  domain = 'males who have not had intercourse with a female in past 3 months',
  title = 'by whether last sexual experience was with male partner'
) |> kable()
```

```{r, dependson=c('male-process-data')}
collect_estimate(
  svyci(
    ~I(MFLASTP == 'Male'),
    subset(
      male_2017_2019_svy,
      SEX3MO != 'YES, HAD INTERCOURSE'
    ),
    svyciprop
  ),
  type = 'proportion',
  domain = 'males who have not had intercourse with a female in past 3 months',
  title = 'by whether last sexual experience was with male partner'
) |> kable()
```
