---
title: "Males Who Do Not Know Whether Partner Used Contraception"
author: "Joshua Born"
output:
  html_document:
    code_folding: hide
    toc: true
    toc_depth: 5
---

```{r setup, include=FALSE}
library(data.table)
library(here)
library(knitr)
library(survey)

i_am('EDA/010_males_who_do_not_know.Rmd')

source(here('R/helpers/NSFG/formats.R'))
source(here('R/helpers/NSFG/load.R'))
source(here('R/helpers/data_table.R'))
source(here('R/helpers/deprecated.R'))
source(here('R/helpers/general.R'))

opts_chunk$set(
  cache = TRUE,
  echo = TRUE,
  fig.height = 8,
  fig.width = 12,
  warning = FALSE
)
```


```{r male-load-data, depeondson='setup'}
male_2017_2019 <- load_NSFG_data('2017_2019', 'Male')
male_2017_2019_formats <- male_2017_2019$Formats
```

```{r male-process-data, dependson=c('male-load-data')}
male_2017_2019_data <- copy(male_2017_2019$Data[, .(
  CWPLMET201 = factorize(CWPLMET201, 'MTHDSV3F', male_2017_2019_formats),
  CWPLUSE2 = factorize(CWPLUSE2, 'Y1N5RDF', male_2017_2019_formats),
  CWPPOSS = factorize(CWPPOSS, 'Y1N5RDF', male_2017_2019_formats),
  CWPPRGNW = factorize(CWPPRGNW, 'Y1N5RDF', male_2017_2019_formats),
  CWPTRYPG = factorize(CWPTRYPG, 'Y1N5RDF', male_2017_2019_formats),
  FATHPOSS = factorize(FATHPOSS, 'Y1N5RDF', male_2017_2019_formats),
  METH3M1 = factorize(METH3M1, 'METH3MF', male_2017_2019_formats),
  METH3M2 = factorize(METH3M2, 'METH3MF', male_2017_2019_formats),
  METH3M3 = factorize(METH3M3, 'METH3MF', male_2017_2019_formats),
  METH3M4 = factorize(METH3M4, 'METH3MF', male_2017_2019_formats),
  P1COHABIT = factorize(P1COHABIT, 'Y1N5RDF', male_2017_2019_formats),
  P1CURRWIFE = factorize(P1CURRWIFE, 'Y1N5RDF', male_2017_2019_formats),
  PSURGSTR = factorize(PSURGSTR, 'N0Y1CF', male_2017_2019_formats),
  PXCPREG = factorize(PXCPREG, 'Y1N5RDF', male_2017_2019_formats),
  PXLPMETH01 = factorize(PXLPMETH01, 'MTHDSV3F', male_2017_2019_formats),
  PXLPUSE = factorize(PXLPUSE, 'Y1N5RDF', male_2017_2019_formats),
  PXLSXPRB = factorize(PXLSXPRB, 'Y1N5RDF', male_2017_2019_formats),
  PXTRYING = factorize(PXTRYING, 'Y1N5RDF', male_2017_2019_formats),
  RSURGSTR  = factorize(RSURGSTR, 'N0Y1RDF', male_2017_2019_formats),
  SECU,
  SEST,
  SEX3MO = factorize(SEX3MO, 'SEX3MO', male_2017_2019_formats),
  WGT2017_2019
)])

# create boolean variables for whether each specific method is currently used
for (x in 1:13) {
  set(
    male_2017_2019_data,
    j = sprintf('last3m_meth%d', x),
    value = has_level(male_2017_2019_data$METH3M1, x) |
      has_level(male_2017_2019_data$METH3M2, x) |
      has_level(male_2017_2019_data$METH3M3, x) |
      has_level(male_2017_2019_data$METH3M4, x)
  )
}

# count any respondents who are sexually active and who have an active vasectomy as using vasectomy as a contraceptive method
male_2017_2019_data[, last3m_meth3 := fifelse(
  SEX3MO == 'YES, HAD INTERCOURSE' & RSURGSTR == 'YES',
  TRUE,
  last3m_meth3
)]

# count any respondents who are sexually active and who are married or cohabitating and whose last intercourse was with wife or cohabitating partner who has active tubal ligation
male_2017_2019_data[, last3m_meth5 := fifelse(
  SEX3MO == 'YES, HAD INTERCOURSE' &
    (P1CURRWIFE == 'Yes' | P1COHABIT == 'Yes') &
    PSURGSTR == 'YES',
  TRUE,
  last3m_meth5
)]

# create variable counting number of current methods
male_2017_2019_data[
  ,
  meth3m_count := rowSums(.SD),
  .SDcols = patterns('^last3m_meth')
]

# create categorical variable for contraceptive use at last intercourse (in past 3 months)
male_2017_2019_data[,
  last_used_3m := factor(fcase(
    meth3m_count > 0,
      'Used at least one contraceptive method at last intercourse',
    SEX3MO != 'YES, HAD INTERCOURSE',
      'Did not have sexual intercourse with female in past 3 months',
    PXCPREG == 'Yes' | ((P1CURRWIFE == 'Yes' | P1COHABIT == 'Yes') & CWPPRGNW == 'Yes'),
      'Last intercourse was with partner who is pregnant',
    PXTRYING == 'Yes' | ((P1CURRWIFE == 'Yes' | P1COHABIT == 'Yes') & CWPTRYPG == 'Yes'),
      'Last intercourse was with partner who is trying to conceive',
    FATHPOSS == 'No',
      'Physically unable to conceive',
    (P1CURRWIFE == 'Yes' | P1COHABIT == 'Yes') & CWPPOSS == 'No',
      'Last intercourse was with wife or cohabitating partner who is physically unable to concieve',
    default = 'Otherwise did not use contraception at last intercourse'
  ))
]


# create categorical variable for whether don't know if partner used contraceptive at last intercourse
male_2017_2019_data[,
  do_not_know_last_used_3m := factor(fcase(
    meth3m_count > 0,
      'Used at least one contraceptive method at last intercourse',
    SEX3MO != 'YES, HAD INTERCOURSE',
      'Did not have sexual intercourse with female in past 3 months',
    CWPLUSE2 == "Don't know" |
      CWPLMET201 == "Don't know" |
      PXLPUSE == "Don't know" |
      PXLPMETH01 == "Don't know" |
      PXLSXPRB == 'Yes' |
      PXLSXPRB == "Don't know",
      "Don't know if partner used contraception at last intercourse",
    default = 'Did not use contraception at last intercourse'
  ))
]

# create categorical variable for contraceptive use at last intercourse (in past 3 months), taking account "don't know" cases
male_2017_2019_data[,
  last_used_3m_2 := factor(fcase(
    meth3m_count > 0,
      'Used at least one contraceptive method at last intercourse',
    SEX3MO != 'YES, HAD INTERCOURSE',
      'Did not have sexual intercourse with female in past 3 months',
    PXCPREG == 'Yes' | ((P1CURRWIFE == 'Yes' | P1COHABIT == 'Yes') & CWPPRGNW == 'Yes'),
      'Last intercourse was with partner who is pregnant',
    PXTRYING == 'Yes' | ((P1CURRWIFE == 'Yes' | P1COHABIT == 'Yes') & CWPTRYPG == 'Yes'),
      'Last intercourse was with partner who is trying to conceive',
    FATHPOSS == 'No',
      'Physically unable to conceive',
    (P1CURRWIFE == 'Yes' | P1COHABIT == 'Yes') & CWPPOSS == 'No',
      'Last intercourse was with wife or cohabitating partner who is physically unable to concieve',
    CWPLUSE2 == "Don't know" |
      CWPLMET201 == "Don't know" |
      PXLPUSE == "Don't know" |
      PXLPMETH01 == "Don't know" |
      PXLSXPRB == 'Yes' |
      PXLSXPRB == "Don't know",
      "Don't know if partner used contraception at last intercourse",
    default = 'Otherwise did not use contraception at last intercourse'
  ))
]


# create survey design object
male_2017_2019_svy <- svydesign(
  ids = ~SECU,
  strata = ~SEST,
  data = male_2017_2019_data,
  nest = TRUE,
  weights = ~WGT2017_2019
)
```


```{r, dependson='male-process-data'}
male_2017_2019_data[
  last_used_3m == 'Otherwise did not use contraception at last intercourse',
  .N
] |> kable()
```

```{r, dependson='male-process-data'}
male_2017_2019_data[
  last_used_3m == 'Otherwise did not use contraception at last intercourse',
  tablena(CWPLUSE2)
] |> kable()
```

```{r, dependson='male-process-data'}
male_2017_2019_data[
  last_used_3m == 'Otherwise did not use contraception at last intercourse',
  tablena(PXLPUSE)
] |> kable()
```

```{r, dependson='male-process-data'}
male_2017_2019_data[
  last_used_3m == 'Otherwise did not use contraception at last intercourse',
  tablena(PXLPMETH01)
] |> kable()
```

```{r, dependson='male-process-data'}
male_2017_2019_data[
  last_used_3m == 'Otherwise did not use contraception at last intercourse',
  tablena(PXLSXPRB)
] |> kable()
```


```{r, dependson='male-process-data'}
male_2017_2019_data[
  last_used_3m == 'Otherwise did not use contraception at last intercourse' &
    CWPLUSE2 == 'No answer provided' &
    CWPLMET201 == 'No answer provided' &
    PXLPUSE == 'No answer provided' &
    PXLPMETH01 == 'No answer provided' &
    PXLSXPRB == 'No answer provided',
  .N
]
```

Together these 5 variables cover all respondents who otherwise did not use contraception at last intercourse.

```{r, dependson=c('male-process-data')}
collect_estimate(
  svyci(
    ~factor(do_not_know_last_used_3m),
    subset(
      male_2017_2019_svy,
      last_used_3m == 'Otherwise did not use contraception at last intercourse'
    ),
    svytotal
  ),
  type = 'total',
  domain = 'males who had intercourse with a female in the past 3 months and did not report use of a contraceptive method, without a reason',
  title = 'by whether do not know if partner used contraception'
) |> kable()
```

```{r, dependson=c('male-process-data')}
collect_estimate(
  svyci(
    ~factor(do_not_know_last_used_3m),
    subset(
      male_2017_2019_svy,
      last_used_3m == 'Otherwise did not use contraception at last intercourse'
    ),
    svymean
  ),
  type = 'proportion',
  domain = 'males who had intercourse with a female in the past 3 months and did not report use of a contraceptive method, without a reason',
  title = 'by whether do not know if partner used contraception'
) |> kable()
```


```{r, dependson=c('male-process-data')}
collect_estimate(
  svyci(
    ~last_used_3m_2,
    male_2017_2019_svy,
    svytotal
  ),
  type = 'total',
  domain = 'males aged 15-49 living in households in the United States',
  title = 'by current contraceptive status, taking into account those who do not know',
)[, .(level, estimate, se, `2.5 %`, `97.5 %`)] |> kable()
```

```{r, dependson=c('male-process-data')}
collect_estimate(
  svyci(
    ~last_used_3m_2,
    male_2017_2019_svy,
    svymean
  ),
  type = 'proportion',
  domain = 'males aged 15-49 living in households in the United States',
  title = 'by current contraceptive status, taking into account those who do not know',
)[, .(level, estimate, se, `2.5 %`, `97.5 %`)] |> kable()
```

```{r, dependson=c('male-process-data')}
svyci(
  ~I(
    last_used_3m_2 == 'Used at least one contraceptive method at last intercourse'
  ),
  subset(
    male_2017_2019_svy,
    last_used_3m_2 == 'Used at least one contraceptive method at last intercourse' |
      last_used_3m_2 == 'Otherwise did not use contraception at last intercourse'
  ),
  svymean
) |> rounded() |> kable()
```
