---
title: "NSFG Estimates Compared with Census Counts"
author: "Joshua Born"
output:
  html_document:
    code_folding: show
    toc: true
    toc_depth: 5
---

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(gt)
library(gtExtras)
library(haven)
library(here)
library(readr)
library(srvyr)
library(tidyr)

knitr::opts_chunk$set(
  cache = TRUE,
  dpi=200,
  echo = FALSE,
  fig.align = 'center',
  fig.height=9.6,
  fig.retina=1.5,
  fig.width=9.6
)
```

```{r, load-data, message=FALSE}
guttmacher_raw <- read_csv(
  here('data/guttmacher/NationalAndStatePregnancy_PublicUse.csv')
)
vital_births <- read_csv(
  here('data/NCHS_-_Births_and_General_Fertility_Rates__United_States.csv'),
  name_repair = 'universal'
)
preg2017_2019 <- read_sas(
  here('data/d2017_2019fempreg.sas7bdat'),
  catalog_file = here('data/d2017_2019fempreg.sas7bcat')
)
preg2015_2017 <- read_sas(
  here('data/d2015_2017fempreg.sas7bdat'),
  catalog_file = here('data/d2015_2017fempreg.sas7bcat')
)
preg2013_2015 <- read_sas(
  here('data/d2013_2015fempreg.sas7bdat'),
  catalog_file = here('data/d2013_2015fempreg.sas7bcat')
)
preg2011_2013 <- read_sas(
  here('data/d2011_2013fempreg.sas7bdat'),
  catalog_file = here('data/d2011_2013fempreg.sas7bcat')
)
wgt2011_2019 <- read_sas(
  here('data/d2011_2019femwgt.sas7bdat')
)
```

```{r, calculate-census-counts-by-year, dependson="load-data"}
guttmacher_national <- guttmacher_raw |> 
  filter(state == 'US') |>
  select(-state, -notes) |>
  mutate(abortions_interpolated = year %in%
      c(1983, 1986, 1989, 1990, 1993, 1994, 1997, 1998, 2001, 2002, 2003, 2006,
        2009, 2012, 2015)
  )

census_counts <- bind_rows(
  guttmacher_national |>
    filter(!abortions_interpolated) |> 
    rename(Year = year, Total = abortionstotal) |>
    select(Year, Total) |>
    mutate(Outcome = 'Abortions'),
  vital_births |> 
    filter(Year >= 1973) |>
    rename(Total = Birth.Number) |>
    select(Year, Total) |>
    mutate(Outcome = 'Births')
)
```

```{r plot-census-counts-by-year, dependson="calculate-census-counts-by-year", include=FALSE}
ggplot(
  data = census_counts,
  mapping = aes(
    y = Total,
    x = Year,
    color = Outcome,
    shape = Outcome
  )
) +
  geom_point() +
  scale_y_continuous(
    breaks = \(x) seq(x[1], x[2], 5e5),
    expand = expansion(mult = c(0, 0.05)),
    labels = scales::unit_format(unit = "M", scale = 1e-6),
    limits = c(0, NA),
    minor_breaks = \(x) seq(x[1], x[2], 25e4)
  ) +
  scale_x_continuous(
    breaks = \(x) seq(x[1]+1, x[2], 4),
    expand = expansion(add = 1),
    minor_breaks = \(x) seq(x[1]+1, x[2], 2)
  ) + 
  theme_bw() +
  theme(
    legend.position = 'bottom',
    legend.title = element_blank(),
    axis.ticks.y = element_blank()
  )
```

```{r print-table-of-census-counts-by-year, dependson="calculate-census-counts-by-year", include=FALSE}
gt(census_counts) |>
  sub_missing(
    missing_text = ''
  ) |> 
  fmt_number(
    starts_with('Total'),
    drop_trailing_zeros = TRUE
  )
```

```{r define-plot-function}
plot_CIs_against_census_counts <- function(these_data, begin, end, outcome) {
  if (outcome == 'Births') {
    y_axis_label <- 'Live Births'
    title_string <- paste('Number of live births in the United States per year')
    subtitle_string <- paste('CIs estimated by the', paste(begin, end, sep = '-'), "NSFG (brackets) compared with the NVSS counts (X's)")
  }
  if (outcome == 'Abortions') {
    y_axis_label <- 'Induced Abortions'
    title_string <- paste('Number of induced abortions in the United States per year')
    subtitle_string <- paste('CIs estimated by the', paste(begin, end, sep = '-'), "NSFG (brackets) compared with the Guttmacher APC counts (X's)")
  }
  ggplot(
    data = filter(
      these_data,
      Begin == begin,
      End == end,
      Outcome == outcome
    )
  ) +
  geom_vline(
    aes(
      xintercept = Begin
    ),
    color = 'red',
    linetype = 2
  ) +
  geom_vline(
    aes(
      xintercept = End
    ),
    color = 'red',
    linetype = 2
  ) +
  geom_vline(
    aes(
      xintercept = Begin - 5
    ),
    color = 'darkgreen',
    linetype = 4
  ) +
  geom_segment(
    arrow = arrow(angle = 90, ends = 'both', length = unit(0.075, 'inches')),
    aes(
      x = Year,
      xend = Year,
      y = Estimate_low,
      yend = Estimate_upp
    ),
    color = 'darkblue',
    na.rm = TRUE
  ) +
  geom_point(
    aes(
      x = Year,
      y = Total
    ),
    color = 'darkorange',
    shape = 4,
    size = 4,
    stroke = 1,
    na.rm = TRUE
  ) +
  scale_y_continuous(
    expand = expansion(mult = c(0, 0.05)),
    labels = scales::unit_format(unit = "M", scale = 1e-6),
    limits = c(0, NA)
  ) +
  scale_x_continuous(
    breaks = \(x) seq(x[1], x[2], 2),
    expand = expansion(add = 1)
  ) +
  labs(
    title = title_string,
    subtitle = subtitle_string,
    y = y_axis_label
  ) +
  theme_bw() +
  theme(
    axis.text.x = element_text(
      angle = 45,
      color = 'black',
      hjust = 0.5,
      vjust = 0.65
    ),
    axis.ticks.y = element_blank(),
    legend.position = 'bottom',
    legend.title = element_blank()
  )
}
```

```{r create-survey-objects, dependson="load-data"}
cm_to_year <- function(x) {
  x_int <- as.integer(x)
  ifelse(
    x_int %in% c(NA, 9997, 9998, 9999),
    NA,
    floor((x_int - 1) / 12) + 1900
  )
}

nsfg2015_2019 <- bind_rows(
    select(preg2015_2017, SECU, SEST, CASEID, DATEND, OUTCOME),
    select(preg2017_2019, SECU, SEST, CASEID, DATEND, OUTCOME)
  ) |>
  left_join(
    wgt2011_2019,
    by = join_by(CASEID)
  ) |>
  mutate(
    OUTCOME = labelled(OUTCOME, c(
      "LIVE BIRTH" = 1,
      "INDUCED ABORTION" = 2,
      "STILLBIRTH" = 3,
      "MISCARRIAGE" = 4,
      "ECTOPIC PREGNANCY" = 5,
      "CURRENT PREGNANCY" = 6
    )),
    Abortions = if_else(OUTCOME == 2, 1, 0),
    Births = if_else(OUTCOME == 1, 1, 0),
    Year = DATEND
  ) |> 
  as_survey_design(
    strata = SEST,
    ids = SECU,
    weights = WGT2015_2019,
    nest = TRUE
  )


nsfg2011_2015 <- bind_rows(
  select(preg2011_2013, SECU, SEST, CASEID, DATEND, OUTCOME) |>
    mutate(
      DATEND = as.numeric(DATEND) + 3653
    ), # Not sure what happened here when the data was exported from SAS, but this adjustment seems to fix it.
  select(preg2013_2015, SECU, SEST, CASEID, DATEND, OUTCOME),
) |>
  left_join(
    wgt2011_2019,
    by = join_by(CASEID)
  ) |>
  mutate(
    OUTCOME = labelled(OUTCOME, c(
      "LIVE BIRTH" = 1,
      "INDUCED ABORTION" = 2,
      "STILLBIRTH" = 3,
      "MISCARRIAGE" = 4,
      "ECTOPIC PREGNANCY" = 5,
      "CURRENT PREGNANCY" = 6
    )),
    Abortions = if_else(OUTCOME == 2, 1, 0),
    Births = if_else(OUTCOME == 1, 1, 0),
    Year = cm_to_year(DATEND)
  ) |> 
  as_survey_design(
    strata = SEST,
    ids = SECU,
    weights = WGT2011_2015,
    nest = TRUE
  )

nsfg2011_2019 <- bind_rows(
    bind_rows(
      select(preg2011_2013, SECU, SEST, CASEID, DATEND, OUTCOME) |>
        mutate(
          DATEND = as.numeric(DATEND) + 3653
        ), # Not sure what happened here when the data was exported from SAS, but this adjustment seems to fix it.
      select(preg2013_2015, SECU, SEST, CASEID, DATEND, OUTCOME),
    ) |> mutate(
      Year = cm_to_year(DATEND)
    ),
    bind_rows(
      select(preg2015_2017, SECU, SEST, CASEID, DATEND, OUTCOME),
      select(preg2017_2019, SECU, SEST, CASEID, DATEND, OUTCOME)
    ) |>
      mutate(
        Year = DATEND
      )
  ) |>
  left_join(
    wgt2011_2019,
    by = join_by(CASEID)
  ) |>
  mutate(
    OUTCOME = labelled(OUTCOME, c(
      "LIVE BIRTH" = 1,
      "INDUCED ABORTION" = 2,
      "STILLBIRTH" = 3,
      "MISCARRIAGE" = 4,
      "ECTOPIC PREGNANCY" = 5,
      "CURRENT PREGNANCY" = 6
    )),
    Abortions = if_else(OUTCOME == 2, 1, 0),
    Births = if_else(OUTCOME == 1, 1, 0)
  ) |>
  filter(!is.na(WGT2011_2019)) |>
  as_survey_design(
    strata = SEST,
    ids = SECU,
    weights = WGT2011_2019,
    nest = TRUE
  )
```

```{r generate-estimates, dependson=c("create-survey-objects", "calculate-census-counts-by-year")}
estimate_births_and_abortions <- function(survey, begin, end, census_counts) {
  bind_rows(
    survey |>
      group_by(Year) |>
      summarize(
        Estimate = survey_total(Abortions, vartype = 'ci')
      ) |> 
      filter(!is.na(Year)) |>
      mutate(
        Begin = begin ,
        End = end ,
        Outcome = 'Abortions'
      ),
    survey |>
      group_by(Year) |> 
      summarize(
        Estimate = survey_total(Births, vartype = 'ci')
      ) |> 
      filter(!is.na(Year)) |>
      mutate(
        Begin = begin,
        End = end,
        Outcome = 'Births'
      )
  ) |>
    left_join(
      census_counts,
      by = c('Year', 'Outcome')
    )
}

estimates <- bind_rows(
  estimate_births_and_abortions(nsfg2015_2019, 2015, 2019, census_counts),
  estimate_births_and_abortions(nsfg2011_2015, 2011, 2015, census_counts),
  estimate_births_and_abortions(nsfg2011_2019, 2011, 2019, census_counts)
)
```

```{r births-2015-2019, dependson=c("define-plot-function", "generate-estimates")}
plot_CIs_against_census_counts(
  estimates,
  begin = 2015,
  end = 2019,
  outcome = 'Births'
)
```

```{r abortions-2015-2019, dependson=c("define-plot-function", "generate-estimates")}
plot_CIs_against_census_counts(
  estimates,
  begin = 2015,
  end = 2019,
  outcome = 'Abortions'
)
```

```{r births-2011-2015, dependson=c("define-plot-function", "generate-estimates")}
plot_CIs_against_census_counts(
  estimates,
  begin = 2011,
  end = 2015,
  outcome = 'Births'
)
```

```{r abortions-2011-2015, dependson=c("define-plot-function", "generate-estimates")}
plot_CIs_against_census_counts(
  estimates,
  begin = 2011,
  end = 2015,
  outcome = 'Abortions'
)
```

```{r births-2011-2019, dependson=c("define-plot-function", "generate-estimates")}
plot_CIs_against_census_counts(
  estimates,
  begin = 2011,
  end = 2019,
  outcome = 'Births'
)
```

```{r abortions-2011-2019, dependson=c("define-plot-function", "generate-estimates")}
plot_CIs_against_census_counts(
  estimates,
  begin = 2011,
  end = 2019,
  outcome = 'Abortions'
)
```