---
title: "Calibration of 2015-2019 National Survey of Family Growth (NSFG)"
author: "Joshua Born"
output:
  html_document:
    code_folding: show
    toc: true
    toc_depth: 5
    css: wide.css
---

```{r setup, include=FALSE}
library(dplyr)
library(gt)
library(haven)
library(here)
library(readr)
library(srvyr)
library(stringr)
library(tidyr)

knitr::opts_chunk$set(
  cache = TRUE,
  dpi=200,
  echo = FALSE,
  fig.align = 'center',
  fig.height=9.6,
  fig.retina=1.5,
  fig.width=9.6
)
```


## NVSS Live Births Test Harness

```{r create-NVSS-test-harness, message=FALSE}
NVSS_combined <- bind_rows(
  read_tsv(
      here('data/NVSS/2011-2014/age.txt'),
      name_repair = 'universal',
      show_col_types = FALSE
    ) |>
    filter(is.na(Notes)) |>
    mutate(Level = case_when(
      Age.of.Mother.9 %in% c(
        'Under 15 years',
        '15-19 years'
      ) ~ 'Under 20 years',
      Age.of.Mother.9 %in% c(
        '40-44 years',
        '45-49 years',
        '50 years and over'
      ) ~ '40 years and over',
      .default = Age.of.Mother.9
    )) |>
    select(Year, Level, Births) |>
    group_by(Year, Level) |>
    summarize(Births = sum(Births), .groups = 'drop') |>
    mutate(Variable = 'Age group', .after = Year),
  read_tsv(
      here('data/NVSS/2011-2014/marital_status.txt'),
      name_repair = 'universal',
      show_col_types = FALSE
    ) |>
    filter(is.na(Notes)) |>
    rename(Level = Marital.Status) |>
    select(Year, Level, Births) |>
    mutate(Variable = 'Marital status'),
  read_tsv(
      here('data/NVSS/2011-2014/race_ethnicity.txt'),
      name_repair = 'universal',
      show_col_types = FALSE
    ) |>
    rename(
      Hispanic.Origin = Mother.s.Hispanic.Origin,
      Race = Mother.s.Bridged.Race
    ) |>
    filter(
      (is.na(Notes) & Hispanic.Origin != 'Hispanic or Latino') |
        (Notes == 'Total' & Hispanic.Origin == 'Hispanic or Latino')
    ) |>
    select(Notes, Year, Hispanic.Origin, Race, Births) |>
    mutate(
      Level = case_when(
        Hispanic.Origin == 'Hispanic or Latino' ~ 'Hispanic',
        Race == 'White' ~ 'Non-Hispanic White',
        Race == 'Black or African American' ~ 'Non-Hispanic Black',
        .default = 'Non-Hispanic Other or Multiple Race'
      )
    ) |>
    group_by(Year, Level) |>
    summarize(Births = sum(Births), .groups = 'drop') |>
    mutate(Variable = 'Race and ethnicity')
) |>
  arrange(-Year, Variable)

NVSS_combined |>
  gt() |>
  fmt_number('Births', decimals = 0)
```


## 2014 Guttmacher APS Test Harness

```{r load-and-process-guttmacher-APC-data}
guttmacher_APC_national <- read_csv(
    here('data/Guttmacher/NationalAndStatePregnancy_PublicUse.csv'),
    show_col_types = FALSE
  ) |>
  filter(state == 'US') |>
  select(-state, -notes) |>
  mutate(interpolated = year %in%
      c(1983, 1986, 1989, 1990, 1993, 1994, 1997, 1998, 2001, 2002, 2003, 2006,
        2009, 2012, 2015)
  )

guttmacher_APC_2014 <- guttmacher_APC_national |>
  filter(year == 2014) |>
  select(starts_with('abortions'))

guttmacher_APC_2014_total <- pull(guttmacher_APC_2014, abortionstotal)

guttmacher_APC_2012 <- guttmacher_APC_national |>
  filter(year == 2012) |>
  select(starts_with('abortions'))

guttmacher_APC_2012_total <- pull(guttmacher_APC_2012, abortionstotal)

guttmacher_APC_2011 <- guttmacher_APC_national |>
  filter(year == 2011) |>
  select(starts_with('abortions'))

guttmacher_APC_2011_total <- pull(guttmacher_APC_2011, abortionstotal)
```

```{r create-guttmacher-test-harness, dependson="load-and-process-guttmacher-APC-data"}
guttmacher_APS_2014 <- bind_rows(
  tribble(
    ~name, ~Level, ~PctAPS2014,
    'abortionslt20',   'Under 20 years',     11.9,
    'abortions1517',   '15-17 years',     3.4,
    'abortions1819',   '18-19 years',     8.2,
    'abortions2024',   '20-24 years',     33.6,
    'abortions2529',   '25-29 years',     26.5,
    'abortions3034',   '30-34 years',     15.9,
    'abortions3539',   '35-39 years',     9.1,
    'abortions40plus', '40 years and over',   3.1
  ) |> mutate(
    Variable = 'Age group',
    .before = everything()
  ) |>
    left_join(
      pivot_longer(
        guttmacher_APC_2014,
        cols = everything(),
        values_to = 'TtlAPC2014'
      ),
      by = 'name'
    ) |>
    select(-name),
  tribble(
    ~Level, ~PctAPS2014,
    'Married            ',               14.3,
    'Cohabitating, not married',         31.0,
    'Never-married, not cohabiting',     45.9,
    'Previously married, not cohabiting', 8.8
  ) |>  mutate(
    Variable = 'Relationship status',
    .before = everything()
  ),
  tribble(
    ~Level, ~PctAPS2014,
    'White',    38.7,
    'Black',    27.6,
    'Hispanic', 24.8,
    'Asian/Pacific Islander', 5.5,
    'Other',    3.4
  ) |>  mutate(
    Variable = 'Race/ethnicity',
    .before = everything()
  ),
  tribble(
    ~Level, ~PctAPS2014,
    'U.S.-born',     83.9,
    'Foreign-born',  16.1
  ) |>  mutate(
    Variable = 'Nativity',
    .before = everything()
  ),
  tribble(
    ~Level, ~PctAPS2014,
    '<high school',                  8.9,
    'High school graduate/GED',      27.0,
    'Some college/associate degree', 40.9,
    'College graduate',              23.1
  ) |>  mutate(
    Variable = 'Educational attainment',
    .before = everything()
  ),
  tribble(
    ~Level, ~PctAPS2014,
    '0',   40.7,
    '1',   26.2,
    '>=2', 33.1
  ) |>  mutate(
    Variable = 'No. of prior births',
    .before = everything()
  ),
  tribble(
    ~Level, ~PctAPS2014,
    '>=1', 44.8
  ) |>  mutate(
    Variable = 'No. of previous induced abortions',
    .before = everything()
  ),
  tribble(
    ~Level, ~PctAPS2014,
    '<100',    49.3,
    '100-199', 25.7,
    '>=200',   25.0
  ) |>  mutate(
    Variable = 'Family income as % of poverty level',
    .before = everything()
  ),
  tribble(
    ~Level, ~PctAPS2014,
    'Mainline Protestant',    17.3,
    'Evangelical Protestant', 12.8,
    'Roman Catholic',         23.7,
    'Other',                  8.2,
    'None',                   38.0
  ) |>  mutate(
    Variable = 'Religious affiliation',
    .before = everything()
  ),
  tribble(
    ~Level, ~PctAPS2014,
    'Heterosexual/straight',    94.4,
    'Homosexual/gay/lesbian',   0.3,
    'Bisexual',                 4.2,
    'Something else',           1.1
  ) |>  mutate(
    Variable = 'Sexual orientation',
    .before = everything()
  ),
  tribble(
    ~Level, ~PctAPS2014,
    'Any method',  50.9,
    'Sterilization',  0.2,
    'Long-active reversible methods', 1.0,
    'Short-acting hormonal methods', 14.2,
    'Not using a method', 49.1,
    'IUD', 0.8,
    'Implant', 0.2,
    'Injectables', 1.6,
    'Ring', 1.4,
    'Pill', 12.6,
    'Patch', 0.2,
    'Condom', 24.2,
    'Withdrawal', 8.6,
    'Other', 1.1,
    'Not using, but ever used', 39.2,
    'Never used', 9.9
  ) |>  mutate(
    Variable = 'Contraceptive used in month pregnancy began',
    .before = everything()
  )
) |> mutate(
  Level = str_squish(Level),
  PctAPS2014 = PctAPS2014 / 100,
  TtlAPS2014 = as.integer(round(guttmacher_APC_2014_total * PctAPS2014)),
  .before = 'TtlAPC2014'
)

guttmacher_APS_2014 |>
  gt() |>
  fmt_percent(starts_with('Percent'), decimals = 1) |>
  fmt_number(starts_with('Ttl'), decimals = 0)
```


## CDC Abortion Surveillance Test Harnesses

### 2014

```{r create-CDC-2014-test-harness, dependson="load-and-process-guttmacher-APC-data"}
CDC_2014 <- bind_rows(
  tribble(
    ~name, ~Level, ~PctCDC,
    'abortionslt15',   'Under 15 years',   0.3,
    'abortions1519',   '15-19 years',   10.4,
    'abortions2024',   '20-24 years',   32.2,
    'abortions2529',   '25-29 years',   26.7,
    'abortions3034',   '30-34 years',   17.1,
    'abortions3539',   '35-39 years',   9.7,
    'abortions40plus', '40 years and over', 3.6
  ) |> mutate(
    Variable = 'Age group',
    .before = everything()
  ) |> left_join(
    pivot_longer(
      guttmacher_APC_2014,
      cols = everything(),
      values_to = 'TtlAPC'
    ),
    by = 'name'
  ) |> select(-name),
  tribble(
    ~Level, ~PctCDC,
    '<=8',   64.9,
    '9-13',  26.1,
    '14-15', 3.6,
    '16-17', 2.2,
    '18-20', 1.9,
    '>=21',  1.3
  ) |>  mutate(
    Variable = 'Gestational age',
    .before = everything()
  ),
  tribble(
    ~Level, ~PctCDC,
    'White',    38.0,
    'Black',    36.0,
    'Other (incl. Asian/Pacific Islander)',    7.7,
    'Hispanic', 18.3,
  ) |>  mutate(
    Variable = 'Race/ethnicity',
    .before = everything()
  ),
  tribble(
    ~Level, ~PctCDC,
    'Married',    14.5,
    'Unmarried',  85.5
  ) |>  mutate(
    Variable = 'Relationship status',
    .before = everything()
  ),
  tribble(
    ~Level, ~PctCDC,
    '0',   40.4,
    '1',   26.0,
    '2',   19.7,
    '3',   8.7,
    '>=4', 5.1
  ) |>  mutate(
    Variable = 'No. of prior births',
    .before = everything()
  ),
  tribble(
    ~Level, ~PctCDC,
    '0',   55.1,
    '1',   24.7,
    '2',   11.6,
    '>=3', 8.6
  ) |>  mutate(
    Variable = 'No. of previous induced abortions',
    .before = everything()
  )
) |> mutate(
  Level = str_squish(Level),
  PctCDC = PctCDC / 100,
  TtlCDC = as.integer(round(guttmacher_APC_2014_total * PctCDC)),
  .before = 'TtlAPC'
)

CDC_2014 |>
  gt() |>
  fmt_percent(starts_with('Percent'), decimals = 1) |>
  fmt_number(starts_with('Ttl'), decimals = 0)
```


### 2012

```{r create-CDC-2012-test-harness, dependson="load-and-process-guttmacher-APC-data"}
CDC_2012 <- bind_rows(
  tribble(
    ~name, ~Level, ~PctCDC,
    'abortionslt15',   'Under 15 years',   0.4,
    'abortions1519',   '15-19 years',   12.2,
    'abortions2024',   '20-24 years',   32.8,
    'abortions2529',   '25-29 years',   25.4,
    'abortions3034',   '30-34 years',   16.4,
    'abortions3539',   '35-39 years',   9.1,
    'abortions40plus', '40 years and over', 3.7
  ) |> mutate(
    Variable = 'Age group',
    .before = everything()
  ) |> left_join(
    pivot_longer(
      guttmacher_APC_2012,
      cols = everything(),
      values_to = 'TtlAPC'
    ),
    by = 'name'
  ) |> select(-name),
  tribble(
    ~Level, ~PctCDC,
    '<=8',   65.8,
    '9-13',  25.6,
    '14-15', 3.5,
    '16-17', 1.8,
    '18-20', 1.9,
    '>=21',  1.3
  ) |>  mutate(
    Variable = 'Gestational age',
    .before = everything()
  ),
  tribble(
    ~Level, ~PctCDC,
    'White',    37.6,
    'Black',    36.7,
    'Other (incl. Asian/Pacific Islander)',    7.0,
    'Hispanic', 18.7,
  ) |>  mutate(
    Variable = 'Race/ethnicity',
    .before = everything()
  ),
  tribble(
    ~Level, ~PctCDC,
    'Married',    14.7,
    'Unmarried',  85.3
  ) |>  mutate(
    Variable = 'Relationship status',
    .before = everything()
  ),
  tribble(
    ~Level, ~PctCDC,
    '0',   40.3,
    '1',   26.2,
    '2',   19.6,
    '3',   8.7,
    '>=4', 5.3
  ) |>  mutate(
    Variable = 'No. of prior births',
    .before = everything()
  ),
  tribble(
    ~Level, ~PctCDC,
    '0',   55.7,
    '1',   24.6,
    '2',   11.0,
    '>=3', 8.6
  ) |>  mutate(
    Variable = 'No. of previous induced abortions',
    .before = everything()
  )
) |> mutate(
  Level = str_squish(Level),
  PctCDC = PctCDC / 100,
  TtlCDC = as.integer(round(guttmacher_APC_2012_total * PctCDC)),
  .before = 'TtlAPC'
)

CDC_2012 |>
  gt() |>
  fmt_percent(starts_with('Percent'), decimals = 1) |>
  fmt_number(starts_with('Ttl'), decimals = 0)
```


### 2011

```{r create-CDC-2011-test-harness, dependson="load-and-process-guttmacher-APC-data"}
CDC_2011 <- bind_rows(
  tribble(
    ~name, ~Level, ~PctCDC,
    'abortionslt15',   'Under 15 years',   0.4,
    'abortions1519',   '15-19 years',   13.5,
    'abortions2024',   '20-24 years',   32.9,
    'abortions2529',   '25-29 years',   24.9,
    'abortions3034',   '30-34 years',   15.8,
    'abortions3539',   '35-39 years',   8.9,
    'abortions40plus', '40 years and over', 3.6
  ) |> mutate(
    Variable = 'Age group',
    .before = everything()
  ) |> left_join(
    pivot_longer(
      guttmacher_APC_2011,
      cols = everything(),
      values_to = 'TtlAPC'
    ),
    by = 'name'
  ) |> select(-name),
  tribble(
    ~Level, ~PctCDC,
    '<=8',   64.5,
    '9-13',  26.9,
    '14-15', 3.5,
    '16-17', 1.9,
    '18-20', 1.9,
    '>=21',  1.4
  ) |>  mutate(
    Variable = 'Gestational age',
    .before = everything()
  ),
  tribble(
    ~Level, ~PctCDC,
    'White',    37.2,
    'Black',    36.2,
    'Other (incl. Asian/Pacific Islander)',    7.0,
    'Hispanic', 19.7,
  ) |>  mutate(
    Variable = 'Race/ethnicity',
    .before = everything()
  ),
  tribble(
    ~Level, ~PctCDC,
    'Married',    14.5,
    'Unmarried',  85.5
  ) |>  mutate(
    Variable = 'Relationship status',
    .before = everything()
  ),
  tribble(
    ~Level, ~PctCDC,
    '0',   39.9,
    '1',   26.5,
    '2',   19.6,
    '3',   8.7,
    '>=4', 5.2
  ) |>  mutate(
    Variable = 'No. of prior births',
    .before = everything()
  ),
  tribble(
    ~Level, ~PctCDC,
    '0',   53.7,
    '1',   25.5,
    '2',   11.6,
    '>=3', 9.3
  ) |>  mutate(
    Variable = 'No. of previous induced abortions',
    .before = everything()
  )
) |> mutate(
  Level = str_squish(Level),
  PctCDC = PctCDC / 100,
  TtlCDC = as.integer(round(guttmacher_APC_2011_total * PctCDC)),
  .before = 'TtlAPC'
)

CDC_2011 |>
  gt() |>
  fmt_percent(starts_with('Percent'), decimals = 1) |>
  fmt_number(starts_with('Ttl'), decimals = 0)
```


### Comparison of CDC Abortion Test Harnesses

```{r compare-CDC-test-harnesses, dependson=c("create-CDC_2014-test-harness", "create-CDC_2012-test-harness", "create-CDC_2011-test-harness"), R.options=list(width = 3000)}
CDC_combined <- full_join(
  CDC_2011,
  CDC_2012,
  by = c('Variable', 'Level'),
  suffix = c('2011', '2012')
) |>
  full_join(
    rename_with(
      CDC_2014,
      ~paste0(.x, '2014'),
      starts_with(c('Pct', 'Ttl'))
    ),
    by = c('Variable', 'Level')
  ) |>
  select(-contains('APC'))

CDC_combined |>
  gt() |>
  fmt_percent(starts_with('Pct'), decimals = 1) |>
  fmt_number(starts_with('Ttl'), decimals = 0)
```


## Comparison of Abortion Test Harnesses

```{r compare-abortion-test-harnesses, dependson=c("create-CDC_2014-test-harness", "create-CDC_2012-test-harness", "create-CDC_2011-test-harness", "create-guttmacher-test-harness")}
combine_levels <- function(tbl, variable, levels, new_level, remove = TRUE) {
  new_row <- tbl |>
    filter(Variable == variable, Level %in% levels) |>
    group_by(Variable) |>
    summarize(across(c(-Level), sum)) |>
    mutate(Level = new_level, .after = Variable)

  if (remove) {
    add_row(tbl, new_row, .before = 1) |>
      filter(!is.element(Level, levels))
  } else {
    add_row(tbl, new_row, .before = 1)
  }
}

full_join(
  CDC_combined |>
    combine_levels(
      'No. of previous induced abortions',
      c('1', '2', '>=3'),
      '>=1',
      remove = FALSE
    ) |>
    combine_levels(
      'No. of prior births',
      c('2', '3', '>=4'),
      '>=2',
      remove = FALSE
    ),
  guttmacher_APS_2014 |>
    select(-TtlAPC2014) |>
    combine_levels(
      'Relationship status',
      c('Cohabitating, no married', 'Never-married, not cohabiting', 'Previously married, not cohabiting'),
      'Unmarried',
      remove = FALSE
    ),
  by = c('Variable', 'Level')
) |>
  arrange(Variable) |>
  gt() |>
  fmt_number(starts_with('Ttl'), decimals = 0) |>
  fmt_percent(starts_with('Pct'), decimals = 1)
```


## Uncalibrated NSFG Estimates

```{r load-NSFG-data}
NSFG_2017_2019_preg_raw <- read_sas(
  data_file = here('data/NSFG/d2017_2019fempreg.sas7bdat'),
  catalog_file = here('data/NSFG/d2017_2019fempreg.sas7bcat')
)
NSFG_2015_2017_preg_raw <- read_sas(
  data_file = here('data/NSFG/d2015_2017fempreg.sas7bdat'),
  catalog_file = here('data/NSFG/d2015_2017fempreg.sas7bcat')
)
NSFG_2011_2019_wgts <- read_sas(
  data_file = here('data/NSFG/d2011_2019femwgt.sas7bdat')
)
```

```{r select-NSFG-variables, dependson="load-NSFG-data"}
NSFG_2015_2019_preg_data <- bind_rows(
  select(
    NSFG_2015_2017_preg_raw,
    SECU, SEST, CASEID,
    DATEND,
    OUTCOME,
    AGEPREG,
    NBRNLV_S,
    FMAROUT5,
    HISPRACE2
  ),
  select(
    NSFG_2017_2019_preg_raw,
    SECU, SEST, CASEID,
    DATEND,
    OUTCOME,
    AGEPREG,
    NBRNLV_S,
    FMAROUT5,
    HISPRACE2
  )
) |>
left_join(
  select(NSFG_2011_2019_wgts, CASEID, WGT2015_2019),
  by = join_by(CASEID)
) |>
mutate(
  one = 1,
  OUTCOME = as_factor(labelled(OUTCOME, c(
    "LIVE BIRTH" = 1,
    "INDUCED ABORTION" = 2,
    "STILLBIRTH" = 3,
    "MISCARRIAGE" = 4,
    "ECTOPIC PREGNANCY" = 5,
    "CURRENT PREGNANCY" = 6
  ))),
  age_group = cut(
    AGEPREG,
    breaks = c(0, seq(20, 40, 5), Inf),
    right = FALSE,
    labels = c(
      "Under 20 years",
      "20-24 years",
      "25-29 years",
      "30-34 years",
      "35-39 years",
      "40 years and over"
    )
  ),
  FMAROUT5 = as_factor(labelled(FMAROUT5, c(
    "MARRIED" = 1,
    "DIVORCED" = 2,
    "WINDOWED" = 3,
    "SEPARATED" = 4,
    "NEVER MARRIED" = 5
  ))),
  marital_status = as.factor(if_else(
    FMAROUT5 == 'MARRIED',
    'Married',
    'Unmarried'
  )),
  HISPRACE2 = as_factor(labelled(HISPRACE2, c(
    'Hispanic' = 1,
    'Non-Hispanic White' = 2,
    'Non-Hispanic Black' = 3,
    'Non-Hispanic Other or Multiple Race' = 4
  )))
) |>
rename(
  Year = DATEND
)
```

```{r create-NSFG-survey-object, dependson="select-NSFG-variables"}
NSFG_2015_2019_preg_srv <- NSFG_2015_2019_preg_data |>
  as_survey_design(
    strata = SEST,
    ids = SECU,
    weights = WGT2015_2019,
    nest = TRUE
  )
```

```{r estimate-uncalibrated-pregnancies, dependson="create-NSFG-survey-object"}
NSFG_2015_2019_preg_srv |>
  group_by(Year, OUTCOME) |>
  summarize(
    Est_Pregnancies = survey_total(one, vartype = 'ci'),
    n = unweighted(sum(one))
  ) |>
  filter(Year %in% 2011:2014) |>
  gt() |>
  fmt_number(decimal = 0)
```


### Comparison of Uncalibrated Estimates with Births Test Harness

```{r estimate-uncalibrated-births, dependson="create-NSFG-survey-object"}
NSFG_2015_2019_est_unc_births <- bind_rows(
  NSFG_2015_2019_preg_srv |>
    group_by(Year, OUTCOME, age_group) |>
    summarize(
      Est_Births = survey_total(NBRNLV_S, vartype = 'ci'),
      n = unweighted(sum(one))
    ) |>
    ungroup() |>
    filter(
      Year %in% 2011:2014 & OUTCOME == 'LIVE BIRTH'
    ) |>
    select(-OUTCOME) |>
    rename(Level = age_group) |>
    mutate(Variable = 'Age group', .after = Year),
  NSFG_2015_2019_preg_srv |>
    group_by(Year, OUTCOME, marital_status) |>
    summarize(
      Est_Births = survey_total(NBRNLV_S, vartype = 'ci'),
      n = unweighted(sum(one))
    ) |>
    ungroup() |>
    filter(
      Year %in% 2011:2014 & OUTCOME == 'LIVE BIRTH'
    ) |>
    select(-OUTCOME) |>
    rename(Level = marital_status) |>
    mutate(Variable = 'Marital status', .after = Year),
  NSFG_2015_2019_preg_srv |>
    group_by(Year, OUTCOME, HISPRACE2) |>
    summarize(
      Est_Births = survey_total(NBRNLV_S, vartype = 'ci'),
      n = unweighted(sum(one))
    ) |>
    ungroup() |>
    filter(
      Year %in% 2011:2014 & OUTCOME == 'LIVE BIRTH'
    ) |>
    select(-OUTCOME) |>
    rename(Level = HISPRACE2) |>
    mutate(Variable = 'Race and ethnicity', .after = Year)
)
```

```{r compare-uncalibrated-estimates-with-NVSS, dependson=c("create-NVSS-test-harness", "estimate-uncalibrated-births")}
full_join(
  NVSS_combined,
  NSFG_2015_2019_est_unc_births,
  by = c('Year', 'Variable', 'Level')
) |>
  mutate(
    Bias = Est_Births - Births,
    Relative_Bias = Bias / Births,
    `Covers?` = Births <= Est_Births_upp & Births >= Est_Births_low
  ) |>
  gt() |>
  fmt_number(-Year, decimal = 0) |>
  fmt_percent(Relative_Bias, decimal = 1)
```


### Comparison of Uncalibrated Estimates with Abortion Test Harness

```{r create-combined-abortion-test-harness, dependson=c("create-CDC_2014-test-harness", "create-CDC_2012-test-harness", "create-CDC_2011-test-harness", "create-guttmacher-test-harness")}
combined_abortion_test_harness <- bind_rows(
  mutate(CDC_2014, Year = 2014, Source = 'CDC', .before = everything()),
  mutate(CDC_2012, Year = 2012, Source = 'CDC', .before = everything()),
  mutate(CDC_2011, Year = 2011, Source = 'CDC', .before = everything())
) |>
  select(-TtlAPC, -PctCDC) |>
  rename(Abortions = TtlCDC) |>
  bind_rows(
    guttmacher_APS_2014 |>
      select(-TtlAPC2014, -PctAPS2014) |>
      mutate(Year = 2014, Source = 'APS', .before = everything()) |>
      rename(Abortions = TtlAPS2014)
  ) |>
  arrange(-Year, Variable, Source)
```

```{r estimate-uncalibrated-abortions, dependson="create-NSFG-survey-object"}
NSFG_2015_2019_est_unc_abortions <- NSFG_2015_2019_preg_srv |>
    group_by(Year, OUTCOME, age_group) |>
    summarize(
      Est_Abortions = survey_total(one, vartype = 'ci'),
      n = unweighted(sum(one))
    ) |>
    ungroup() |>
    filter(
      Year %in% 2011:2014 & OUTCOME == 'INDUCED ABORTION'
    ) |>
    select(-OUTCOME) |>
    rename(Level = age_group) |>
    mutate(Variable = 'Age group', .after = Year)
```

```{r compare-uncalibrated-abortion-estimates, dependson=c("create-combined-abortion-test-harness", "estimate-uncalibrated-births")}
left_join(
  combined_abortion_test_harness,
  NSFG_2015_2019_est_unc_abortions,
  by = c('Year', 'Variable', 'Level')
) |>
  mutate(
    Bias = Est_Abortions - Abortions,
    Relative_Bias = Bias / Abortions,
    `Covers?` = Abortions <= Est_Abortions_upp & Abortions >= Est_Abortions_low
  ) |>
  gt() |>
  fmt_number(-Year, decimal = 0) |>
  fmt_percent(Relative_Bias, decimal = 1)
```