---
title: "Total Births and Births by Age of Mother in United States, 1940-2019"
author: "Joshua Born"
output:
  html_document:
    code_folding: hide
    toc: true
    toc_depth: 5
    css: wide.css
---


```{r setup, include=FALSE}
library(dplyr)
library(gt)
library(here)
library(readr)
library(tidyr)

knitr::opts_chunk$set(
  cache=TRUE,
  dpi=200,
  echo = TRUE,
  fig.align = 'center',
  fig.height=9.6,
  fig.retina=1.5,
  fig.width=9.6
)
```


```{r helper-functions}
load_natality_1968_2019 <- function(year) {
  if (year <= 1971) {
    these_data <- read_csv(
        here(paste0('data/NVSS/natality', year, 'us.csv')),
        col_select = c('mage8'),
        col_types = 'f'
      ) |>
      mutate(recwt = 2) |>
      rename(Age.Group = mage8)
  } else if (year >= 2006) {
    these_data <- read_csv(
        here(paste0('data/NVSS/natality', year, 'us.csv')),
        col_select = c('mager9'),
        col_types = 'f'
      ) |>
      mutate(recwt = 1) |>
      rename(Age.Group = mager9)
  } else if (year >= 2003) {
    these_data <- read_csv(
        here(paste0('data/NVSS/natality', year, 'us.csv')),
        col_select = c('mager9', 'recwt'),
        col_types = 'fn'
      ) |>
      rename(Age.Group = mager9)
  } else {
    these_data <- read_csv(
        here(paste0('data/NVSS/natality', year, 'us.csv')),
        col_select = c('mage8', 'recwt'),
        col_types = 'fn'
      ) |>
      rename(Age.Group = mage8)
  }
  these_data |>
    mutate(
      Age.Group = factor(
        Age.Group,
        levels = 1:9,
        labels = c(
          "[0,15]",
          "[15,19]",
          "[20,24]",
          "[25,29]",
          "[30,34]",
          "[35,39]",
          "[40,44]",
          "[45,49]",
          "[50,54]"
        ),
        ordered = TRUE
      ),
      Year = year
    ) |>
    group_by(Year, Age.Group) |>
    summarize(Births = sum(recwt), .groups = 'drop')
}
```


```{r processing-of-data-1968-2019, dependson="helper-functions"}
births_by_age_group_1968_2019 <- Map(load_natality_1968_2019, 1968:2019) |>
  bind_rows() |>
  filter(!is.na(Age.Group))

saveRDS(
  births_by_age_group_1968_2019,
  here('data/NVSS/births_by_age_group_1968-2019.Rds')
)
```


```{r processing-of-data-1909-1967, dependson="processing-of-data-1968-2019"}
births_1909_1967 <- read_csv(here(
  'data/NVSS/NCHS_-_Births_and_General_Fertility_Rates__United_States.csv'
  )) |>
  rename(Births = `Birth Number`) |>
  select(Year, Births)

births_by_age_group_1909_1967 <- read_csv(here(
  'data/NVSS/NCHS_-_Percent_Distribution_of_Births_for_Females_by_Age_Group__United_States.csv'
)) |>
  left_join(
    rename(births_1909_1967, Total.Births = Births),
    by = join_by(Year)
  ) |>
  mutate(
    Age.Group = factor(
      case_match(
        `Age Group`,
        'Less than 15 Years' ~ '[0,15]',
        '15-19 Years' ~ '[15,19]',
        '20-24 Years' ~ '[20,24]',
        '25-29 Years' ~ '[25,29]',
        '30-34 Years' ~ '[30,34]',
        '35-39 Years' ~ '[35,39]',
        '40-44 Years' ~ '[40,44]',
        '45+ Years' ~ '[45,Inf)'
      ),
      levels = c(levels(births_by_age_group_1968_2019$Age.Group)[1:7], '[45,Inf)'),
      ordered = TRUE
    ),
    Births = `Percentage of Births` * Total.Births
  ) |>
  select(Year, Age.Group, Births)
```


```{r combination-of-data-sets, dependson=c("processing-of-data-1968-2019", "processing-of-data-1909-1967")}
births_1909_2019 <- births_by_age_group_1968_2019 |>
  group_by(Year) |>
  summarize(Births = sum(Births), .groups = 'drop') |>
  bind_rows(
    filter(births_1909_1967, Year < 1968)
  ) |>
  arrange(Year)

saveRDS(
  births_1909_2019,
  here('data/NVSS/births_1909-2019.Rds')
)

births_by_age_group_1909_2019 <- births_by_age_group_1968_2019 |>
  mutate(
    Age.Group.Old = as.character(Age.Group),
    Age.Group = factor(
      if_else(
        Age.Group.Old %in% c('[40,44]', '[45,49]'),
        '[45,Inf)',
        Age.Group
      ),
      levels = levels(births_by_age_group_1909_1967$Age.Group),
      ordered = TRUE
    )
  ) |>
  group_by(Year, Age.Group) |>
  summarize(Births = sum(Births), .groups = 'drop') |>
  bind_rows(
    births_by_age_group_1909_1967 |>
      filter(Year < 1968)
  ) |>
  arrange(Year, Age.Group)

saveRDS(
  births_by_age_group_1909_2019,
  here('data/NVSS/births_by_age_group_1909-2019.Rds')
)
```
