---
title: "Estimates of Unintended Pregnancies after Raking"
author: "Joshua Born"
output:
  html_document:
    code_folding: hide
    toc: true
    toc_depth: 5
    css: wide.css
---

```{r setup, include=FALSE}
library(PracTools)
library(dplyr)
library(gt)
library(haven)
library(here)
library(readr)
library(srvyr)
library(survey)
library(svrep)
library(tidyr)

knitr::opts_chunk$set(
  cache = TRUE,
  dpi=200,
  echo = TRUE,
  fig.align = 'center',
  fig.height=9.6,
  fig.retina=1.5,
  fig.width=9.6
)
```


## Data Preparation

### Load Raw Data

```{r load-raw-data}
raw_preg_2017_2019 <- read_sas(
  data_file = here('data/NSFG/d2017_2019fempreg.sas7bdat'),
  catalog_file = here('data/NSFG/d2017_2019fempreg.sas7bcat')
)
raw_preg_2015_2017 <- read_sas(
  data_file = here('data/NSFG/d2015_2017fempreg.sas7bdat'),
  catalog_file = here('data/NSFG/d2015_2017fempreg.sas7bcat')
)
weights_2011_2019 <- read_sas(
  data_file = here('data/NSFG/d2011_2019femwgt.sas7bdat')
)
raw_fem_2017_2019 <- read_sas(
  data_file = here('data/NSFG/d2017_2019femresp.sas7bdat'),
  catalog_file = here('data/NSFG/d2017_2019femresp.sas7bcat')
)
raw_fem_2015_2017 <- read_sas(
  data_file = here('data/NSFG/d2015_2017femresp.sas7bdat'),
  catalog_file = here('data/NSFG/d2015_2017femresp.sas7bcat')
)
```


### Select Pregancies Data Variables

```{r select-pregnancies-variables, dependson="load-raw-data"}
data_preg <- bind_rows(
  select(
    raw_preg_2015_2017,
    SECU, SEST, CASEID,
    DATEND,
    OUTCOME,
    PREGORDR,
    FMAROUT5,
    AGEPREG,
    WANTRESP,
    DATECON
  ),
  select(
    raw_preg_2017_2019,
    SECU, SEST, CASEID,
    DATEND,
    OUTCOME,
    PREGORDR,
    FMAROUT5,
    AGEPREG,
    WANTRESP,
    DATECON
  )
) |>
  left_join(
    select(weights_2011_2019, CASEID, WGT2015_2019),
    by = join_by(CASEID)
  ) |>
  mutate(
    one = 1,
    OUTCOME = as_factor(labelled(OUTCOME, c(
      "LIVE BIRTH" = 1,
      "INDUCED ABORTION" = 2,
      "STILLBIRTH" = 3,
      "MISCARRIAGE" = 4,
      "ECTOPIC PREGNANCY" = 5,
      "CURRENT PREGNANCY" = 6
    ))),
    FMAROUT5 = as_factor(labelled(FMAROUT5, c(
      "MARRIED" = 1,
      "DIVORCED" = 2,
      "WINDOWED" = 3,
      "SEPARATED" = 4,
      "NEVER MARRIED" = 5
    ))),
    intent = as.factor(if_else(
      WANTRESP %in% 1:2,
      'Intended',
      'Unintended'
    )),
    WANTRESP = as_factor(labelled(WANTRESP, c(
      "Later, overdue" = 1,
      "Right time" = 2,
      "Too soon, mistimed" = 3,
      "Didn't care, indifferent" = 4,
      "Unwanted" = 5,
      "Don't know, not sure" = 6
    ))),
    marital_status = as.factor(if_else(
      FMAROUT5 == 'MARRIED',
      'Married',
      'Unmarried'
    ))
  ) |>
  rename(
    Year = DATEND
  ) |>
  arrange(
    CASEID, PREGORDR
  )
```


### Select Female Respondents Data Variables

```{r select-female-respondents-variables, dependson="load-raw-data"}
data_fem <- bind_rows(
  select(raw_fem_2017_2019, CASEID, SEST, SECU, AGER, HISPRACE2, ABORTION),
  select(raw_fem_2015_2017, CASEID, SEST, SECU, AGER, HISPRACE2, ABORTION)
) |>
  mutate(
    one = 1,
    age_group = cut(
      AGER,
      breaks = c(14, 19, 24, 29, 34, 39, 44, 50),
      labels = c('15-19', '20-24', '25-29', '30-34', '35-39', '40-44', '45-49')
    ),
    HISPRACE2 = as_factor(labelled(HISPRACE2, c(
      'Hispanic' = 1,
      'Non-Hispanic White' = 2,
      'Non-Hispanic Black' = 3,
      'Non-Hispanic Other' = 4
    ))),
    any_abortion = !is.na(ABORTION) & ABORTION > 0
  ) |>
  left_join(
    select(weights_2011_2019, CASEID, WGT2015_2019),
    by = join_by(CASEID)
  )
```


### Create Post-Stratification Targets

```{r create-post-stratification-targets}
census_pop_targets_2015_2019 <- readRDS(
  here('data/Census/prepared/census_for_2015_2019.Rds')
) |>
  filter(SEX_f == 'Female') |>
  mutate(
    poststrat_age_race = gsub(
      '[ -]',
      '_',
      paste0(
        gsub(' to | years', '_', AGEGROUP_f),
        race_ethn_f
      )
    )
  ) |>
  rename(Freq = pop) |>
  select(poststrat_age_race, Freq) |>
  as.data.frame()


census_pop_total_2015_2019 <- sum(census_pop_targets_2015_2019$Freq)


guttmacher_APC_national <- read_csv(
    here('data/Guttmacher/NationalAndStatePregnancy_PublicUse.csv'),
    show_col_types = FALSE
  ) |>
  filter(state == 'US') |>
  mutate(interpolated = year %in%
      c(1983, 1986, 1989, 1990, 1993, 1994, 1997, 1998, 2001, 2002, 2003, 2006,
        2009, 2012, 2015)
  ) |>
  select('year', 'interpolated', 'abortionslt20', 'abortions2024',
    'abortions2529', 'abortions3034', 'abortions3539', 'abortions40plus',
    'abortionstotal')


NVSS_age_2011_2014 <- read_tsv(
    here('data/NVSS/2011-2014/age.txt'),
    name_repair = 'universal',
    show_col_types = FALSE
  ) |>
  filter(!is.na(Year) | !is.na(Age.of.Mother.9)) |>
  mutate(
    Variable = paste0('birth_', Year, '_age'),
    Level = factor(
      case_when(
        Age.of.Mother.9.Code %in% c('15', '15-19') ~ 'Under 20 years',
        Age.of.Mother.9.Code %in% c('40-44', '45-49', '50+') ~ '40 years and over',
        is.na(Age.of.Mother.9.Code) ~ 'Other',
        .default = Age.of.Mother.9
      ),
      levels = c(
        'Under 20 years',
        '20-24 years',
        '25-29 years',
        '30-34 years',
        '35-39 years',
        '40 years and over',
        'Other'
      ),
      ordered = TRUE
    ),
    Freq = if_else(
      !is.na(Notes) & Notes == 'Total',
      census_pop_total_2015_2019 - Births,
      Births
    )
  ) |>
  group_by(Variable, Level) |>
  summarize(Freq = sum(Freq), .groups = 'drop') |>
  arrange(Variable, Level) |>
  group_by(Variable) |>
  group_split() |>
  lapply(function(tbl) {
    variable_name <- first(pull(tbl, Variable))
    tbl <- select(tbl, -Variable)
    names(tbl) <- c(variable_name, 'Freq')
    tbl
  })


NVSS_marital_status_2011_2014 <- read_tsv(
    here('data/NVSS/2011-2014/marital_status.txt'),
    name_repair = 'universal',
    show_col_types = FALSE
  ) |>
  filter(!is.na(Year) | !is.na(Marital.Status)) |>
  mutate(
    Variable = paste0('birth_', Year, '_marital_status'),
    Level = factor(
      if_else(
        !is.na(Marital.Status),
        Marital.Status,
        'Other'
      ),
      levels = c(
        'Married',
        'Unmarried',
        'Other'
      ),
      ordered = TRUE
    ),
    Freq = if_else(
      !is.na(Notes) & Notes == 'Total',
      census_pop_total_2015_2019 - Births,
      Births
    )
  ) |>
  select(Variable, Level, Freq) |>
  group_by(Variable) |>
  group_split() |>
  lapply(function(tbl) {
    variable_name <- first(pull(tbl, Variable))
    tbl <- select(tbl, -Variable)
    names(tbl) <- c(variable_name, 'Freq')
    tbl
  })
```


## Estimates after Raking using 5-level Abortion Post-Stratification Variable

```{r split-by-age, dependson=c("select-pregnancies-variables", "select-female-respondents-variables", "create-post-stratification-targets")}
derived_fem <- data_fem |>
  mutate(
    poststrat_age_race = factor(gsub(
      '[ -]',
      '_',
      paste(
        'Age',
        age_group,
        case_when(
          grepl('^Hispanic', HISPRACE2) ~ 'Hispanic',
          grepl('Black', HISPRACE2) ~ 'Non-Hispanic Black',
          .default = 'Non-Hispanic Non-Black'
        ),
        sep = '_'
      )
    ))
  ) |>
  left_join(
    data_preg |>
      group_by(CASEID) |>
      summarize(
        abortion_2011_2014_poststrat = case_when(
          any(OUTCOME == 'INDUCED ABORTION' & Year %in% 2011:2014 & AGEPREG < 20) ~ 'Under 20 years',
          any(OUTCOME == 'INDUCED ABORTION' & Year %in% 2011:2014 & AGEPREG <= 24) ~ '20-24 years',
          any(OUTCOME == 'INDUCED ABORTION' & Year %in% 2011:2014 & AGEPREG <= 29) ~ '25-29 years',
          any(OUTCOME == 'INDUCED ABORTION' & Year %in% 2011:2014 & AGEPREG <= 34) ~ '30-34 years',
          any(OUTCOME == 'INDUCED ABORTION' & Year %in% 2011:2014 & AGEPREG >= 35) ~ '35 years and over',
          .default = 'Other'
        ),
        abortion_2011plus_poststrat = case_when(
          any(OUTCOME == 'INDUCED ABORTION' & Year > 2011 & AGEPREG < 20) ~ 'Under 20 years',
          any(OUTCOME == 'INDUCED ABORTION' & Year > 2011 & AGEPREG <= 24) ~ '20-24 years',
          any(OUTCOME == 'INDUCED ABORTION' & Year > 2011 & AGEPREG <= 29) ~ '25-29 years',
          any(OUTCOME == 'INDUCED ABORTION' & Year > 2011 & AGEPREG <= 34) ~ '30-34 years',
          any(OUTCOME == 'INDUCED ABORTION' & Year > 2011 & AGEPREG >= 35) ~ '35 years and over',
          .default = 'Other'
        ),
        birth_2014_marital_status =  case_when(
          any(OUTCOME == 'LIVE BIRTH' & Year == 2014 & FMAROUT5 == 'MARRIED') ~ 'Married',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2014) ~ 'Unmarried',
          .default = 'Other'
        ),
        birth_2013_marital_status =  case_when(
          any(OUTCOME == 'LIVE BIRTH' & Year == 2013 & FMAROUT5 == 'MARRIED') ~ 'Married',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2013) ~ 'Unmarried',
          .default = 'Other'
        ),
        birth_2012_marital_status =  case_when(
          any(OUTCOME == 'LIVE BIRTH' & Year == 2012 & FMAROUT5 == 'MARRIED') ~ 'Married',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2012) ~ 'Unmarried',
          .default = 'Other'
        ),
        birth_2011_marital_status =  case_when(
          any(OUTCOME == 'LIVE BIRTH' & Year == 2011 & FMAROUT5 == 'MARRIED') ~ 'Married',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2011) ~ 'Unmarried',
          .default = 'Other'
        ),
        birth_2014_age = case_when(
          any(OUTCOME == 'LIVE BIRTH' & Year == 2014 & AGEPREG < 20) ~ 'Under 20 years',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2014 & AGEPREG <= 24) ~ '20-24 years',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2014 & AGEPREG <= 29) ~ '25-29 years',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2014 & AGEPREG <= 34) ~ '30-34 years',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2014 & AGEPREG <= 39) ~ '35-39 years',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2014 & AGEPREG >= 40) ~ '40 years and over',
          .default = 'Other'
        ),
        birth_2013_age =  case_when(
          any(OUTCOME == 'LIVE BIRTH' & Year == 2013 & AGEPREG < 20) ~ 'Under 20 years',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2013 & AGEPREG <= 24) ~ '20-24 years',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2013 & AGEPREG <= 29) ~ '25-29 years',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2013 & AGEPREG <= 34) ~ '30-34 years',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2013 & AGEPREG <= 39) ~ '35-39 years',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2013 & AGEPREG >= 40) ~ '40 years and over',
          .default = 'Other'
        ),
        birth_2012_age =  case_when(
          any(OUTCOME == 'LIVE BIRTH' & Year == 2012 & AGEPREG < 20) ~ 'Under 20 years',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2012 & AGEPREG <= 24) ~ '20-24 years',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2012 & AGEPREG <= 29) ~ '25-29 years',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2012 & AGEPREG <= 34) ~ '30-34 years',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2012 & AGEPREG <= 39) ~ '35-39 years',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2012 & AGEPREG >= 40) ~ '40 years and over',
          .default = 'Other'
        ),
        birth_2011_age =  case_when(
          any(OUTCOME == 'LIVE BIRTH' & Year == 2011 & AGEPREG < 20) ~ 'Under 20 years',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2011 & AGEPREG <= 24) ~ '20-24 years',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2011 & AGEPREG <= 29) ~ '25-29 years',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2011 & AGEPREG <= 34) ~ '30-34 years',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2011 & AGEPREG <= 39) ~ '35-39 years',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2011 & AGEPREG >= 40) ~ '40 years and over',
          .default = 'Other'
        )
      ),
    by = 'CASEID'
  ) |>
  mutate(
    across(
      ends_with('_poststrat'),
      function(x) {
        factor(
          coalesce(x, 'Other'),
          levels = c(
            'Under 20 years',
            '20-24 years',
            '25-29 years',
            '30-34 years',
            '35 years and over',
            'Other'
          )
        )
      }
    ),
    across(
      ends_with('_age'),
      function(x) {
        factor(
          coalesce(x, 'Other'),
          levels = c(
            'Under 20 years',
            '20-24 years',
            '25-29 years',
            '30-34 years',
            '35-39 years',
            '40 years and over',
            'Other'
          )
        )
      }
    ),
    across(
      ends_with('_marital_status'),
      function(x) {
        factor(
          coalesce(x, 'Other'),
          ordered = TRUE,
          levels = c(
            'Married',
            'Unmarried',
            'Other'
          )
        )
      }
    ),
    abortion_2011plus_poststrat = if_else(
      abortion_2011plus_poststrat != abortion_2011_2014_poststrat & abortion_2011_2014_poststrat != 'Other',
      abortion_2011_2014_poststrat,
      abortion_2011plus_poststrat
    )
  )

svy_fem <- as_survey_design(
    .data = derived_fem,
    strata = SEST,
    ids = SECU,
    weights = WGT2015_2019,
    nest = TRUE
  )

rep_fem <- as_survey_rep(
  .data = svy_fem,
  type = 'JKn'
)

rep_preg <- data_preg |>
  select(-WGT2015_2019) |>
  left_join(
    rep_fem |>
      as_data_frame_with_weights(
        full_wgt_name = "FULL_SAMPLE_WGT",
        rep_wgt_prefix = "REP_WGT_"
      ) |>
      select(CASEID, contains('_WGT')),
    by = join_by(CASEID)
  ) |>
  as_survey_rep(
    type = 'JKn',
    weights = FULL_SAMPLE_WGT,
    repweights = starts_with('REP_WGT_'),
    rscales = rep_fem$rscales
  )

guttmacher_APC_2011_2014_age <- guttmacher_APC_national |>
  filter(year %in% 2011:2014) |>
  rename(
    `Other` = abortionstotal,
    `Under 20 years` = abortionslt20,
    `20-24 years` = abortions2024,
    `25-29 years` = abortions2529,
    `30-34 years` = abortions3034
  ) |>
  mutate(
    `35 years and over` = abortions3539 + abortions40plus,
    .keep = 'unused'
  ) |>
  summarize(across(3:8, sum)) |>
  pivot_longer(
    cols = everything(),
    names_to = 'Levels',
    values_to = 'Freq'
  ) |>
  mutate(
    abortion_2011_2014_poststrat = factor(
      Levels,
      levels = c(
        'Under 20 years',
        '20-24 years',
        '25-29 years',
        '30-34 years',
        '35 years and over',
        'Other'
      ),
      ordered = TRUE
    ),
    Freq = if_else(
      abortion_2011_2014_poststrat == 'Other',
      census_pop_total_2015_2019 - Freq,
      Freq
    )
  ) |>
  arrange(abortion_2011_2014_poststrat) |>
  select(abortion_2011_2014_poststrat, Freq)

poststrat_targets_2015_2019 <- c(
  list(census_pop_targets_2015_2019),
  NVSS_age_2011_2014,
  NVSS_marital_status_2011_2014,
  list(guttmacher_APC_2011_2014_age)
)

source(here('R/rake2.R'))

post_fem <- rake2(
  rep_fem,
  sample.margins = lapply(
    poststrat_targets_2015_2019,
    \(x) as.formula(paste0('~', colnames(x)[1]))
  ),
  population.margins = poststrat_targets_2015_2019,
  weight_adj_strata = list(
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    ~abortion_2011plus_poststrat
  ),
  control=list(maxit=25, epsilon=1, verbose=TRUE)
)

post_preg <- data_preg |>
  select(-WGT2015_2019) |>
  left_join(
    post_fem |>
      as_data_frame_with_weights(
        full_wgt_name = "FULL_SAMPLE_WGT",
        rep_wgt_prefix = "REP_WGT_"
      ) |>
      select(CASEID, contains('_WGT')),
    by = join_by(CASEID)
  ) |>
  as_survey_rep(
    type = 'JKn',
    weights = FULL_SAMPLE_WGT,
    repweights = starts_with('REP_WGT_'),
    rscales = post_fem$rscales
  )

data.frame(
  survey = c('Original', 'Replicate Weights', 'Post-Stratified'),
  UWE = c(
    deffK(weights(svy_fem, 'sampling')),
    deffK(weights(rep_fem, 'sampling')),
    deffK(weights(post_fem, 'sampling'))
  )
) |> gt()

bind_rows(list(
  rep_preg |>
    group_by(DATECON, intent) |>
    summarize(
      n = n(),
      Freq = survey_total(one, vartype = 'se')
    ) |>
    mutate(
      RSE = Freq_se / Freq,
      post_strat = 'before'
    ) |>
    filter(DATECON %in% 2011:2014),
  post_preg |>
    group_by(DATECON, intent) |>
    summarize(
      n = n(),
      Freq = survey_total(one, vartype = 'se')
    ) |>
    mutate(
      RSE = Freq_se / Freq,
      post_strat = 'after'
    ) |>
    filter(DATECON %in% 2011:2014)
)) |> inner_join(
  bind_rows(list(
    rep_preg |>
      group_by(DATECON, intent) |>
      summarize(
        n = n(),
        Freq = survey_total(one, vartype = 'ci')
      ) |>
      mutate(
        Freq_CI_range = Freq_upp - Freq_low,
        Rel_CI = Freq_CI_range / Freq,
        post_strat = 'before'
      ) |>
      filter(DATECON %in% 2011:2014),
    post_preg |>
      group_by(DATECON, intent) |>
      summarize(
        n = n(),
        Freq = survey_total(one, vartype = 'ci')
      ) |>
      mutate(
        Freq_CI_range = Freq_upp - Freq_low,
        Rel_CI = Freq_CI_range / Freq,
        post_strat = 'after'
      ) |>
      filter(DATECON %in% 2011:2014)
  )),
  by = join_by(DATECON, intent, post_strat, Freq, n)
) |>
  select(DATECON, intent, post_strat, everything()) |>
  mutate(
    post_strat = factor(
      post_strat,
      levels = c('before', 'after'),
      ordered = TRUE
    )
  ) |>
  arrange(DATECON, intent, post_strat) |>
  gt() |>
  fmt_number(
    starts_with('Freq'),
    decimals = 0
  ) |>
  fmt_percent(
    c(RSE, Rel_CI)
  )
```



## Estimates after Raking using 6-level Abortion Post-Stratification Variable

```{r six-level, dependson=c("select-pregnancies-variables", "select-female-respondents-variables", "create-post-stratification-targets")}
derived_fem <- data_fem |>
  mutate(
    poststrat_age_race = factor(gsub(
      '[ -]',
      '_',
      paste(
        'Age',
        age_group,
        case_when(
          grepl('^Hispanic', HISPRACE2) ~ 'Hispanic',
          grepl('Black', HISPRACE2) ~ 'Non-Hispanic Black',
          .default = 'Non-Hispanic Non-Black'
        ),
        sep = '_'
      )
    ))
  ) |>
  left_join(
    data_preg |>
      group_by(CASEID) |>
      summarize(
        abortion_2011_2014_age = case_when(
          any(OUTCOME == 'INDUCED ABORTION' & Year %in% 2011:2014 & AGEPREG < 20) ~ 'Under 20 years',
          any(OUTCOME == 'INDUCED ABORTION' & Year %in% 2011:2014 & AGEPREG <= 24) ~ '20-24 years',
          any(OUTCOME == 'INDUCED ABORTION' & Year %in% 2011:2014 & AGEPREG <= 29) ~ '25-29 years',
          any(OUTCOME == 'INDUCED ABORTION' & Year %in% 2011:2014 & AGEPREG <= 34) ~ '30-34 years',
          any(OUTCOME == 'INDUCED ABORTION' & Year %in% 2011:2014 & AGEPREG <= 39) ~ '35-39 years',
          any(OUTCOME == 'INDUCED ABORTION' & Year %in% 2011:2014 & AGEPREG >= 40) ~ '40 years and over',
          .default = 'Other'
        ),
        abortion_2011plus_age = case_when(
          any(OUTCOME == 'INDUCED ABORTION' & Year > 2011 & AGEPREG < 20) ~ 'Under 20 years',
          any(OUTCOME == 'INDUCED ABORTION' & Year > 2011 & AGEPREG <= 24) ~ '20-24 years',
          any(OUTCOME == 'INDUCED ABORTION' & Year > 2011 & AGEPREG <= 29) ~ '25-29 years',
          any(OUTCOME == 'INDUCED ABORTION' & Year > 2011 & AGEPREG <= 34) ~ '30-34 years',
          any(OUTCOME == 'INDUCED ABORTION' & Year > 2011 & AGEPREG <= 39) ~ '35-39 years',
          any(OUTCOME == 'INDUCED ABORTION' & Year > 2011 & AGEPREG >= 40) ~ '40 years and over',
          .default = 'Other'
        ),
        birth_2014_marital_status =  case_when(
          any(OUTCOME == 'LIVE BIRTH' & Year == 2014 & FMAROUT5 == 'MARRIED') ~ 'Married',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2014) ~ 'Unmarried',
          .default = 'Other'
        ),
        birth_2013_marital_status =  case_when(
          any(OUTCOME == 'LIVE BIRTH' & Year == 2013 & FMAROUT5 == 'MARRIED') ~ 'Married',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2013) ~ 'Unmarried',
          .default = 'Other'
        ),
        birth_2012_marital_status =  case_when(
          any(OUTCOME == 'LIVE BIRTH' & Year == 2012 & FMAROUT5 == 'MARRIED') ~ 'Married',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2012) ~ 'Unmarried',
          .default = 'Other'
        ),
        birth_2011_marital_status =  case_when(
          any(OUTCOME == 'LIVE BIRTH' & Year == 2011 & FMAROUT5 == 'MARRIED') ~ 'Married',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2011) ~ 'Unmarried',
          .default = 'Other'
        ),
        birth_2014_age = case_when(
          any(OUTCOME == 'LIVE BIRTH' & Year == 2014 & AGEPREG < 20) ~ 'Under 20 years',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2014 & AGEPREG <= 24) ~ '20-24 years',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2014 & AGEPREG <= 29) ~ '25-29 years',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2014 & AGEPREG <= 34) ~ '30-34 years',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2014 & AGEPREG <= 39) ~ '35-39 years',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2014 & AGEPREG >= 40) ~ '40 years and over',
          .default = 'Other'
        ),
        birth_2013_age =  case_when(
          any(OUTCOME == 'LIVE BIRTH' & Year == 2013 & AGEPREG < 20) ~ 'Under 20 years',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2013 & AGEPREG <= 24) ~ '20-24 years',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2013 & AGEPREG <= 29) ~ '25-29 years',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2013 & AGEPREG <= 34) ~ '30-34 years',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2013 & AGEPREG <= 39) ~ '35-39 years',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2013 & AGEPREG >= 40) ~ '40 years and over',
          .default = 'Other'
        ),
        birth_2012_age =  case_when(
          any(OUTCOME == 'LIVE BIRTH' & Year == 2012 & AGEPREG < 20) ~ 'Under 20 years',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2012 & AGEPREG <= 24) ~ '20-24 years',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2012 & AGEPREG <= 29) ~ '25-29 years',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2012 & AGEPREG <= 34) ~ '30-34 years',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2012 & AGEPREG <= 39) ~ '35-39 years',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2012 & AGEPREG >= 40) ~ '40 years and over',
          .default = 'Other'
        ),
        birth_2011_age =  case_when(
          any(OUTCOME == 'LIVE BIRTH' & Year == 2011 & AGEPREG < 20) ~ 'Under 20 years',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2011 & AGEPREG <= 24) ~ '20-24 years',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2011 & AGEPREG <= 29) ~ '25-29 years',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2011 & AGEPREG <= 34) ~ '30-34 years',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2011 & AGEPREG <= 39) ~ '35-39 years',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2011 & AGEPREG >= 40) ~ '40 years and over',
          .default = 'Other'
        )
      ),
    by = 'CASEID'
  ) |>
  mutate(
    across(
      ends_with('_age'),
      function(x) {
        factor(
          coalesce(x, 'Other'),
          levels = c(
            'Under 20 years',
            '20-24 years',
            '25-29 years',
            '30-34 years',
            '35-39 years',
            '40 years and over',
            'Other'
          )
        )
      }
    ),
    across(
      ends_with('_marital_status'),
      function(x) {
        factor(
          coalesce(x, 'Other'),
          ordered = TRUE,
          levels = c(
            'Married',
            'Unmarried',
            'Other'
          )
        )
      }
    ),
    abortion_2011plus_age = if_else(
      abortion_2011plus_age != abortion_2011_2014_age & abortion_2011_2014_age != 'Other',
      abortion_2011_2014_age,
      abortion_2011plus_age
    )
  )

svy_fem <- as_survey_design(
    .data = derived_fem,
    strata = SEST,
    ids = SECU,
    weights = WGT2015_2019,
    nest = TRUE
  )

rep_fem <- as_survey_rep(
  .data = svy_fem,
  type = 'JKn'
)

rep_preg <- data_preg |>
  select(-WGT2015_2019) |>
  left_join(
    rep_fem |>
      as_data_frame_with_weights(
        full_wgt_name = "FULL_SAMPLE_WGT",
        rep_wgt_prefix = "REP_WGT_"
      ) |>
      select(CASEID, contains('_WGT')),
    by = join_by(CASEID)
  ) |>
  as_survey_rep(
    type = 'JKn',
    weights = FULL_SAMPLE_WGT,
    repweights = starts_with('REP_WGT_'),
    rscales = rep_fem$rscales
  )

guttmacher_APC_2011_2014_age <- guttmacher_APC_national |>
  filter(year %in% 2011:2014) |>
  rename(
    `Other` = abortionstotal,
    `Under 20 years` = abortionslt20,
    `20-24 years` = abortions2024,
    `25-29 years` = abortions2529,
    `30-34 years` = abortions3034,
    `35-39 years` = abortions3539,
    `40 years and over` = abortions40plus
  ) |>
  summarize(across(3:9, sum)) |>
  pivot_longer(
    cols = everything(),
    names_to = 'Levels',
    values_to = 'Freq'
  ) |>
  mutate(
    abortion_2011_2014_age = factor(
      Levels,
      levels = c(
        'Under 20 years',
        '20-24 years',
        '25-29 years',
        '30-34 years',
        '35-39 years',
        '40 years and over',
        'Other'
      ),
      ordered = TRUE
    ),
    Freq = if_else(
      abortion_2011_2014_age == 'Other',
      census_pop_total_2015_2019 - Freq,
      Freq
    )
  ) |>
  arrange(abortion_2011_2014_age) |>
  select(abortion_2011_2014_age, Freq)

poststrat_targets_2015_2019 <- c(
  list(census_pop_targets_2015_2019),
  NVSS_age_2011_2014,
  NVSS_marital_status_2011_2014,
  list(guttmacher_APC_2011_2014_age)
)

source(here('R/rake2.R'))

post_fem <- rake2(
  rep_fem,
  sample.margins = lapply(
    poststrat_targets_2015_2019,
    \(x) as.formula(paste0('~', colnames(x)[1]))
  ),
  population.margins = poststrat_targets_2015_2019,
  weight_adj_strata = list(
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    ~abortion_2011plus_age
  ),
  control=list(maxit=25, epsilon=1, verbose=TRUE)
)

post_preg <- data_preg |>
  select(-WGT2015_2019) |>
  left_join(
    post_fem |>
      as_data_frame_with_weights(
        full_wgt_name = "FULL_SAMPLE_WGT",
        rep_wgt_prefix = "REP_WGT_"
      ) |>
      select(CASEID, contains('_WGT')),
    by = join_by(CASEID)
  ) |>
  as_survey_rep(
    type = 'JKn',
    weights = FULL_SAMPLE_WGT,
    repweights = starts_with('REP_WGT_'),
    rscales = post_fem$rscales
  )

data.frame(
  survey = c('Original', 'Replicate Weights', 'Post-Stratified'),
  UWE = c(
    deffK(weights(svy_fem, 'sampling')),
    deffK(weights(rep_fem, 'sampling')),
    deffK(weights(post_fem, 'sampling'))
  )
) |> gt()

bind_rows(list(
  rep_preg |>
    group_by(DATECON, intent) |>
    summarize(
      n = n(),
      Freq = survey_total(one, vartype = 'se')
    ) |>
    mutate(
      RSE = Freq_se / Freq,
      post_strat = 'before'
    ) |>
    filter(DATECON %in% 2011:2014),
  post_preg |>
    group_by(DATECON, intent) |>
    summarize(
      n = n(),
      Freq = survey_total(one, vartype = 'se')
    ) |>
    mutate(
      RSE = Freq_se / Freq,
      post_strat = 'after'
    ) |>
    filter(DATECON %in% 2011:2014)
)) |> inner_join(
  bind_rows(list(
    rep_preg |>
      group_by(DATECON, intent) |>
      summarize(
        n = n(),
        Freq = survey_total(one, vartype = 'ci')
      ) |>
      mutate(
        Freq_CI_range = Freq_upp - Freq_low,
        Rel_CI = Freq_CI_range / Freq,
        post_strat = 'before'
      ) |>
      filter(DATECON %in% 2011:2014),
    post_preg |>
      group_by(DATECON, intent) |>
      summarize(
        n = n(),
        Freq = survey_total(one, vartype = 'ci')
      ) |>
      mutate(
        Freq_CI_range = Freq_upp - Freq_low,
        Rel_CI = Freq_CI_range / Freq,
        post_strat = 'after'
      ) |>
      filter(DATECON %in% 2011:2014)
  )),
  by = join_by(DATECON, intent, post_strat, Freq, n)
) |>
  select(DATECON, intent, post_strat, everything()) |>
  mutate(
    post_strat = factor(
      post_strat,
      levels = c('before', 'after'),
      ordered = TRUE
    )
  ) |>
  arrange(DATECON, intent, post_strat) |>
  gt() |>
  fmt_number(
    starts_with('Freq'),
    decimals = 0
  ) |>
  fmt_percent(
    c(RSE, Rel_CI)
  )
```
