---
title: "Weight Adjustment for 2011-2015 NSFG"
author: "Joshua Born"
output:
  html_document:
    code_folding: hide
    toc: true
    toc_depth: 5
    css: wide.css
---

```{r setup, include=FALSE}
library(PracTools)
library(dplyr)
library(gt)
library(haven)
library(here)
library(lubridate)
library(readr)
library(srvyr)
library(stringr)
library(survey)
library(svrep)
library(tidyr)

knitr::opts_chunk$set(
  cache = TRUE,
  dpi=200,
  echo = TRUE,
  fig.align = 'center',
  fig.height=9.6,
  fig.retina=1.5,
  fig.width=9.6
)
```


## Weight Preparation

### Loading of Raw Data

```{r load-raw-data}
raw_preg_2013_2015 <- read_sas(
  data_file = here('data/NSFG/d2013_2015fempreg.sas7bdat'),
  catalog_file = here('data/NSFG/d2013_2015fempreg.sas7bcat')
)
raw_preg_2011_2013 <- read_sas(
  data_file = here('data/NSFG/d2011_2013fempreg.sas7bdat'),
  catalog_file = here('data/NSFG/d2011_2013fempreg.sas7bcat')
)
weights_2011_2019 <- read_sas(
  data_file = here('data/NSFG/d2011_2019femwgt.sas7bdat')
)
raw_fem_2013_2015 <- read_sas(
  data_file = here('data/NSFG/d2013_2015femresp.sas7bdat'),
  catalog_file = here('data/NSFG/d2013_2015femresp.sas7bcat')
)
raw_fem_2011_2013 <- read_sas(
  data_file = here('data/NSFG/d2011_2013femresp.sas7bdat'),
  catalog_file = here('data/NSFG/d2011_2013femresp.sas7bcat')
)
```


### Data Preparation

```{r data-preparation, dependson="load-raw-data"}
cm_to_date <- function(x) {
  x_int <- as.integer(x)
  if_else(
    is.na(x_int) | x_int > 9000 | x_int == 0,
    NA,
    ym(paste0(
      floor((x_int - 1) / 12) + 1900,
      factor(
        x_int %% 12,
        levels = 0:11,
        labels = c('Dec', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov')
      )
    ))
  )
}

data_preg <- bind_rows(
  select(
    raw_preg_2011_2013,
    CASEID, SECU, SEST,
    
    # Variables used in post-stratification
    AGEPREG,
    DATEND,
    FMAROUT5,
    OUTCOME,
    
    #BRNOUT,
    #DATECON,
    #HIEDUC,
    #HISPRACE2,
    #NBRNLV_S,
    #POVERTY,
    #PREGORDR,
    #PRGLNGTH,
    #RELIGION,
    #RMAROUT6,
    #WANTRESP
  ),
  select(
    raw_preg_2013_2015,
    CASEID, SECU, SEST,
    
    # Variables used in post-stratification
    AGEPREG,
    DATEND,
    FMAROUT5,
    OUTCOME,
    
    #BRNOUT,
    #DATECON,
    #GEST_OTHR,
    #HIEDUC,
    #HISPRACE2,
    #NBRNLV_S,
    #POVERTY,
    #PREGORDR,
    #RELIGION,
    #RMAROUT6,
    #WANTRESP
  )
) |>
  left_join(
    select(weights_2011_2019, CASEID, WGT2011_2015),
    by = join_by(CASEID)
  ) |>
  mutate(

    # Variables used in post-stratification
    FMAROUT5 = as_factor(labelled(FMAROUT5, c(
      "MARRIED" = 1,
      "DIVORCED" = 2,
      "WINDOWED" = 3,
      "SEPARATED" = 4,
      "NEVER MARRIED" = 5
    ))),
    OUTCOME = as_factor(labelled(OUTCOME, c(
      "LIVE BIRTH" = 1,
      "INDUCED ABORTION" = 2,
      "STILLBIRTH" = 3,
      "MISCARRIAGE" = 4,
      "ECTOPIC PREGNANCY" = 5,
      "CURRENT PREGNANCY" = 6
    ))),
    Year = year(cm_to_date(DATEND)),
    AgeAtEndOfPregnancy = as.integer(AGEPREG / 100)
    
    #Variables used in...
    #one = 1,
    #HISPRACE2 = as_factor(labelled(HISPRACE2, c(
    #  'Hispanic' = 1,
    #  'Non-Hispanic White' = 2,
    #  'Non-Hispanic Black' = 3,
    #  'Non-Hispanic Other' = 4
    #))),
    #age_group = cut(
    #  AGEPREG,
    #  breaks = c(0, seq(20, 40, 5), Inf),
    #  right = FALSE,
    #  labels = c(
    #    "Under 20 years",
    #    "20-24 years",
    #    "25-29 years",
    #    "30-34 years",
    #    "35-39 years",
    #    "40 years and over"
    #  )
    #),
    #educational_attainment = case_when(
    #  HIEDUC %in% 5:8 ~ '<high school',
    #  HIEDUC == 9 ~ 'High school graduate/GED',
    #  HIEDUC %in% 10:11 ~ 'Some college/associate degree',
    #  HIEDUC %in% 12:15 ~ 'College graduate',
    #),
    #gestational_age = case_when(
    #  GEST_OTHR == 1 | PRGLNGTH %in% 0:13 ~ '1st trimester (13 or less weeks)',
    #  GEST_OTHR %in% 2:3 | PRGLNGTH %in% 14:95 ~ '2nd or 3rd trimester (14 or more weeks)'
    #),
    #intent = as.factor(if_else(
    #  WANTRESP %in% 1:2,
    #  'Intended',
    #  'Unintended'
    #)),
    #marital_status = as.factor(if_else(
    #  FMAROUT5 == 'MARRIED',
    #  'Married',
    #  'Unmarried'
    #)),
    #nativity = case_when(
    #  BRNOUT == 1 ~ 'Foreign-born',
    #  BRNOUT == 5 ~ 'U.S.-born',
    #  !is.element(BRNOUT, c(1, 5)) ~ 'Unknown'
    #),
    #poverty_level = cut(
    #  POVERTY,
    #  breaks = c(0, 99, 199, Inf),
    #  include.lowest = TRUE,
    #  labels = c('<100', '100-199', '>=200')
    #),
    #relationship_status = case_when(
    #  RMAROUT6 == 1 ~ 'Married',
    #  RMAROUT6 == 5 ~ 'Cohabitating, not married',
    #  RMAROUT6 == 6 ~ 'Never-married, not cohabiting',
    #  RMAROUT6 %in% 2:4 ~ 'Previously married, not cohabiting'
    #),
    #religious_affiliation = case_when(
    #  RELIGION == 1 ~ 'None',
    #  RELIGION == 2 ~ 'Roman Catholic',
    #  RELIGION == 3 ~ 'Protestant',
    #  RELIGION == 4 ~ 'Other'
    #),
    #birth = if_else(
    #  OUTCOME == 'LIVE BIRTH',
    #  1,
    #  0
    #),
    #abortion = if_else(
    #  OUTCOME == 'INDUCED ABORTION',
    #  1,
    #  0
    #)
  )
  #arrange(
  #  CASEID, PREGORDR
  #) |>
  #group_by(
  #  CASEID
  #) |>
  #mutate(
  #  births = cumsum(birth),
  #  previous_births = lag(births, default = 0),
  #  previous_births_topcoded4 = factor(if_else(
  #    previous_births >= 4,
  #    '>=4',
  #    as.character(previous_births)
  #  )),
  #  previous_births_topcoded2 = factor(if_else(
  #    previous_births >= 2,
  #    '>=2',
  #    as.character(previous_births)
  #  )),
  #  abortions = cumsum(abortion),
  #  previous_abortions = lag(abortions, default = 0),
  #  previous_abortions_topcoded3 = factor(if_else(
  #    previous_abortions >= 3,
  #    '>=3',
  #    as.character(previous_abortions)
  #  )),
  #  any_previous_abortions = factor(if_else(
  #    previous_abortions >= 1,
  #    '>=1',
  #    'None'
  #  ))
  #) |>
  #ungroup()

data_fem <- bind_rows(
  select(
    raw_fem_2013_2015,
    CASEID, SEST, SECU,
    AGER,
    HISPRACE2
  ),
  select(
    raw_fem_2011_2013,
    CASEID, SEST, SECU,
    AGER,
    HISPRACE2
  )
) |>
  mutate(
    one = 1,
    age_group = cut(
      AGER,
      breaks = c(14, 19, 24, 29, 34, 39, 45),
      labels = c('15-19', '20-24', '25-29', '30-34', '35-39', '40-44')
    ),
    HISPRACE2 = as_factor(labelled(HISPRACE2, c(
      'Hispanic' = 1,
      'Non-Hispanic White' = 2,
      'Non-Hispanic Black' = 3,
      'Non-Hispanic Other' = 4
    )))
  ) |>
  left_join(
    select(weights_2011_2019, CASEID, WGT2011_2015),
    by = join_by(CASEID)
  ) |>
  mutate(
    poststrat_age_race = factor(gsub(
      '[ -]',
      '_',
      paste(
        'Age',
        age_group,
        case_when(
          grepl('^Hispanic', HISPRACE2) ~ 'Hispanic',
          grepl('Black', HISPRACE2) ~ 'Non-Hispanic Black',
          .default = 'Non-Hispanic Non-Black'
        ),
        sep = '_'
      )
    ))
  ) |>
  left_join(
    data_preg |>
      group_by(CASEID) |>
      summarize(
        abortion_2006_2010_age = case_when(
          any(OUTCOME == 'INDUCED ABORTION' & Year %in% 2006:2010 & AgeAtEndOfPregnancy < 20) ~ 'Under 20 years',
          any(OUTCOME == 'INDUCED ABORTION' & Year %in% 2006:2010 & AgeAtEndOfPregnancy <= 24) ~ '20-24 years',
          any(OUTCOME == 'INDUCED ABORTION' & Year %in% 2006:2010 & AgeAtEndOfPregnancy <= 29) ~ '25-29 years',
          any(OUTCOME == 'INDUCED ABORTION' & Year %in% 2006:2010 & AgeAtEndOfPregnancy <= 34) ~ '30-34 years',
          any(OUTCOME == 'INDUCED ABORTION' & Year %in% 2006:2010 & AgeAtEndOfPregnancy >= 35) ~ '35 years and over',
          .default = 'Other'
        ),
        abortion_2006plus_age = case_when(
          any(OUTCOME == 'INDUCED ABORTION' & Year > 2006 & AgeAtEndOfPregnancy < 20) ~ 'Under 20 years',
          any(OUTCOME == 'INDUCED ABORTION' & Year > 2006 & AgeAtEndOfPregnancy <= 24) ~ '20-24 years',
          any(OUTCOME == 'INDUCED ABORTION' & Year > 2006 & AgeAtEndOfPregnancy <= 29) ~ '25-29 years',
          any(OUTCOME == 'INDUCED ABORTION' & Year > 2006 & AgeAtEndOfPregnancy <= 34) ~ '30-34 years',
          any(OUTCOME == 'INDUCED ABORTION' & Year > 2006 & AgeAtEndOfPregnancy >= 35) ~ '35 years and over',
          .default = 'Other'
        ),
        birth_2006_marital_status =  case_when(
          any(OUTCOME == 'LIVE BIRTH' & Year == 2006 & FMAROUT5 == 'MARRIED') ~ 'Married',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2006) ~ 'Unmarried',
          .default = 'Other'
        ),
        birth_2007_marital_status =  case_when(
          any(OUTCOME == 'LIVE BIRTH' & Year == 2007 & FMAROUT5 == 'MARRIED') ~ 'Married',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2007) ~ 'Unmarried',
          .default = 'Other'
        ),
        birth_2008_marital_status =  case_when(
          any(OUTCOME == 'LIVE BIRTH' & Year == 2008 & FMAROUT5 == 'MARRIED') ~ 'Married',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2008) ~ 'Unmarried',
          .default = 'Other'
        ),
        birth_2009_marital_status =  case_when(
          any(OUTCOME == 'LIVE BIRTH' & Year == 2009 & FMAROUT5 == 'MARRIED') ~ 'Married',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2009) ~ 'Unmarried',
          .default = 'Other'
        ),
        birth_2010_marital_status =  case_when(
          any(OUTCOME == 'LIVE BIRTH' & Year == 2010 & FMAROUT5 == 'MARRIED') ~ 'Married',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2010) ~ 'Unmarried',
          .default = 'Other'
        ),
        birth_2006_age = case_when(
          any(OUTCOME == 'LIVE BIRTH' & Year == 2006 & AgeAtEndOfPregnancy < 20) ~ 'Under 20 years',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2006 & AgeAtEndOfPregnancy <= 24) ~ '20-24 years',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2006 & AgeAtEndOfPregnancy <= 29) ~ '25-29 years',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2006 & AgeAtEndOfPregnancy <= 34) ~ '30-34 years',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2006 & AgeAtEndOfPregnancy >= 35) ~ '35 years and over',
          .default = 'Other'
        ),
        birth_2007_age =  case_when(
          any(OUTCOME == 'LIVE BIRTH' & Year == 2007 & AgeAtEndOfPregnancy < 20) ~ 'Under 20 years',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2007 & AgeAtEndOfPregnancy <= 24) ~ '20-24 years',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2007 & AgeAtEndOfPregnancy <= 29) ~ '25-29 years',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2007 & AgeAtEndOfPregnancy <= 34) ~ '30-34 years',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2007 & AgeAtEndOfPregnancy >= 35) ~ '35 years and over',
          .default = 'Other'
        ),
        birth_2008_age =  case_when(
          any(OUTCOME == 'LIVE BIRTH' & Year == 2008 & AgeAtEndOfPregnancy < 20) ~ 'Under 20 years',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2008 & AgeAtEndOfPregnancy <= 24) ~ '20-24 years',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2008 & AgeAtEndOfPregnancy <= 29) ~ '25-29 years',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2008 & AgeAtEndOfPregnancy <= 34) ~ '30-34 years',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2008 & AgeAtEndOfPregnancy >= 35) ~ '35 years and over',
          .default = 'Other'
        ),
        birth_2009_age =  case_when(
          any(OUTCOME == 'LIVE BIRTH' & Year == 2009 & AgeAtEndOfPregnancy < 20) ~ 'Under 20 years',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2009 & AgeAtEndOfPregnancy <= 24) ~ '20-24 years',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2009 & AgeAtEndOfPregnancy <= 29) ~ '25-29 years',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2009 & AgeAtEndOfPregnancy <= 34) ~ '30-34 years',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2009 & AgeAtEndOfPregnancy >= 35) ~ '35 years and over',
          .default = 'Other'
        ),
        birth_2010_age =  case_when(
          any(OUTCOME == 'LIVE BIRTH' & Year == 2010 & AgeAtEndOfPregnancy < 20) ~ 'Under 20 years',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2010 & AgeAtEndOfPregnancy <= 24) ~ '20-24 years',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2010 & AgeAtEndOfPregnancy <= 29) ~ '25-29 years',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2010 & AgeAtEndOfPregnancy <= 34) ~ '30-34 years',
          any(OUTCOME == 'LIVE BIRTH' & Year == 2010 & AgeAtEndOfPregnancy >= 35) ~ '35 years and over',
          .default = 'Other'
        )
      ),
    by = 'CASEID'
  ) |>
  mutate(
    across(
      ends_with('_age'),
      function(x) {
        factor(
          coalesce(x, 'Other'),
          levels = c(
            'Under 20 years',
            '20-24 years',
            '25-29 years',
            '30-34 years',
            '35 years and over',
            'Other'
          ),
          order = TRUE
        )
      }
    ),
    across(
      ends_with('_marital_status'),
      function(x) {
        factor(
          coalesce(x, 'Other'),
          ordered = TRUE,
          levels = c(
            'Married',
            'Unmarried',
            'Other'
          )
        )
      }
    ),
    abortion_2006plus_age = if_else(
      abortion_2006plus_age != abortion_2006_2010_age & abortion_2006_2010_age != 'Other',
      abortion_2006_2010_age,
      abortion_2006plus_age
    )
  )

before_fem <- data_fem |>
  as_survey_design(
    strata = SEST,
    ids = SECU,
    weights = WGT2011_2015,
    nest = TRUE
  ) |>
  as_survey_rep(
    type = 'JKn'
  )
```


### Creation of Post-Stratification Targets

```{r create-post-stratification-targets}
census_pop_targets <- readRDS(
  here('data/Census/prepared/census_for_2011_2015.Rds')
) |>
  filter(SEX_f == 'Female') |>
  mutate(
    poststrat_age_race = gsub(
      '[ -]',
      '_',
      paste0(
        gsub(' to | years', '_', AGEGROUP_f),
        race_ethn_f
      )
    )
  ) |>
  rename(Freq = pop) |>
  select(poststrat_age_race, Freq) |>
  filter(!grepl('45_49', poststrat_age_race)) |>
  as.data.frame()


census_pop_total <- sum(census_pop_targets$Freq)


guttmacher_APC_national <- read_csv(
    here('data/Guttmacher/NationalAndStatePregnancy_PublicUse.csv'),
    show_col_types = FALSE
  ) |>
  filter(state == 'US') |>
  mutate(interpolated = year %in%
      c(1983, 1986, 1989, 1990, 1993, 1994, 1997, 1998, 2001, 2002, 2003, 2006,
        2009, 2012, 2015)
  ) |>
  select('year', 'interpolated', 'abortionslt20', 'abortions2024',
    'abortions2529', 'abortions3034', 'abortions3539', 'abortions40plus',
    'abortionstotal')

guttmacher_APC_age <- guttmacher_APC_national |>
  filter(year %in% 2006:2010) |>
  rename(
    `Other` = abortionstotal,
    `Under 20 years` = abortionslt20,
    `20-24 years` = abortions2024,
    `25-29 years` = abortions2529,
    `30-34 years` = abortions3034
  ) |>
  mutate(
    `35 years and over` = abortions3539 + abortions40plus,
    .keep = 'unused'
  ) |>
  summarize(across(3:8, sum)) |>
  pivot_longer(
    cols = everything(),
    names_to = 'Levels',
    values_to = 'Freq'
  ) |>
  mutate(
    abortion_2006_2010_age = factor(
      Levels,
      levels = c(
        'Under 20 years',
        '20-24 years',
        '25-29 years',
        '30-34 years',
        '35 years and over',
        'Other'
      ),
      ordered = TRUE
    ),
    Freq = if_else(
      abortion_2006_2010_age == 'Other',
      census_pop_total - Freq,
      Freq
    )
  ) |>
  arrange(abortion_2006_2010_age) |>
  select(abortion_2006_2010_age, Freq)


NVSS_age <- bind_rows(
  read_tsv(
    here('data/NVSS/2006-2010/age.txt'),
    name_repair = 'universal',
    show_col_types = FALSE
  ),
  read_tsv(
    here('data/NVSS/2006-2010/age_2006.txt'),
    name_repair = 'universal',
    show_col_types = FALSE
  )
) |>
  filter(!is.na(Year) | !is.na(Age.of.Mother.9)) |>
  mutate(
    Variable = paste0('birth_', Year, '_age'),
    Level = factor(
      case_when(
        Age.of.Mother.9.Code %in% c('15', '15-19') ~ 'Under 20 years',
        Age.of.Mother.9.Code %in% c('35-39', '40-44', '45-49', '50+') ~ '35 years and over',
        is.na(Age.of.Mother.9.Code) ~ 'Other',
        .default = Age.of.Mother.9
      ),
      levels = c(
        'Under 20 years',
        '20-24 years',
        '25-29 years',
        '30-34 years',
        '35 years and over',
        'Other'
      ),
      ordered = TRUE
    ),
    Freq = if_else(
      !is.na(Notes) & Notes == 'Total',
      census_pop_total - Births,
      Births
    )
  ) |>
  group_by(Variable, Level) |>
  summarize(Freq = sum(Freq), .groups = 'drop') |>
  arrange(Variable, Level) |>
  group_by(Variable) |>
  group_split() |>
  lapply(function(tbl) {
    variable_name <- first(pull(tbl, Variable))
    tbl <- select(tbl, -Variable)
    names(tbl) <- c(variable_name, 'Freq')
    tbl
  })


NVSS_marital_status <- bind_rows(
    read_tsv(
      here('data/NVSS/2006-2010/marital_status.txt'),
      name_repair = 'universal',
      show_col_types = FALSE
    ),
    read_tsv(
      here('data/NVSS/2006-2010/marital_status_2006.txt'),
      name_repair = 'universal',
      show_col_types = FALSE
    )
  ) |>
  filter(!is.na(Year) | !is.na(Marital.Status)) |>
  mutate(
    Variable = paste0('birth_', Year, '_marital_status'),
    Level = factor(
      if_else(
        !is.na(Marital.Status),
        Marital.Status,
        'Other'
      ),
      levels = c(
        'Married',
        'Unmarried',
        'Other'
      ),
      ordered = TRUE
    ),
    Freq = if_else(
      !is.na(Notes) & Notes == 'Total',
      census_pop_total - Births,
      Births
    )
  ) |>
  select(Variable, Level, Freq) |>
  group_by(Variable) |>
  group_split() |>
  lapply(function(tbl) {
    variable_name <- first(pull(tbl, Variable))
    tbl <- select(tbl, -Variable)
    names(tbl) <- c(variable_name, 'Freq')
    tbl
  })


poststrat_targets <- c(
  list(census_pop_targets),
  NVSS_age,
  NVSS_marital_status,
  list(guttmacher_APC_age)
)
```


### Post-Stratifications

```{r rake-post-stratifications, dependson=c("data-preparation", "create-post-stratification-targets")}
source(here('R/rake2.R'))

weight_adj_strata <- list()
weight_adj_strata[[12]] <- ~abortion_2006plus_age

post_fem <- rake2(
  before_fem,
  sample.margins = lapply(
    poststrat_targets,
    \(x) as.formula(paste0('~', colnames(x)[1]))
  ),
  population.margins = poststrat_targets,
  weight_adj_strata = weight_adj_strata,
  control=list(maxit=25, epsilon=1, verbose=TRUE)
)
```


### Saving of Adjusted Weights

```{r save-adjusted-weights, dependson="rake-post-stratifications"}
post_fem |>
  as_data_frame_with_weights(
    full_wgt_name = "FULL_SAMPLE_WGT",
    rep_wgt_prefix = "REP_WGT_"
  ) |>
  select(CASEID, contains('_WGT')) |>
  arrange(CASEID) |>
  saveRDS(here('data/NSFG/adjusted_2011_2015_weights.Rds'))

saveRDS(
  post_fem$rscales,
  here('data/NSFG/adjusted_2011_2015_rscales.Rds')
)
```


## Examination of Results of Weight Adjustment

### Creation of Survey Objects

```{r create-survey-objects, dependson=c("save-adjusted-weights")}
after_fem <- data_fem |>
  select(-WGT2011_2015) |>
  left_join(
    readRDS(here('data/NSFG/adjusted_2011_2015_weights.Rds')),
    by = join_by(CASEID)
  ) |>
  as_survey_rep(
    type = 'JKn',
    weights = FULL_SAMPLE_WGT,
    repweights = starts_with('REP_WGT_'),
    rscales = readRDS(here('data/NSFG/adjusted_2011_2015_rscales.Rds'))
  )

before_preg <- data_preg |>
  select(-WGT2011_2015) |>
  left_join(
    before_fem |>
      as_data_frame_with_weights(
        full_wgt_name = "FULL_SAMPLE_WGT",
        rep_wgt_prefix = "REP_WGT_"
      ) |>
      select(CASEID, contains('_WGT')),
    by = join_by(CASEID)
  ) |>
  as_survey_rep(
    type = 'JKn',
    weights = FULL_SAMPLE_WGT,
    repweights = starts_with('REP_WGT_'),
    rscales = before_fem$rscales
  )

after_preg <- data_preg |>
  select(-WGT2011_2015) |>
  left_join(
    readRDS(here('data/NSFG/adjusted_2011_2015_weights.Rds')),
    by = join_by(CASEID)
  ) |>
  as_survey_rep(
    type = 'JKn',
    weights = FULL_SAMPLE_WGT,
    repweights = starts_with('REP_WGT_'),
    rscales = readRDS(here('data/NSFG/adjusted_2011_2015_rscales.Rds'))
  )
```


### UWE

```{r uwe, dependson="create-survey-objects"}
data.frame(
  when = rep(c('Before Raking', 'After Raking'), 2),
  table = rep(c('Female Respondents', 'Pregnancies'), each = 2),
  UWE = c(
    deffK(weights(before_fem, 'sampling')),
    deffK(weights(after_fem, 'sampling')),
    deffK(weights(before_preg, 'sampling')),
    deffK(weights(after_preg, 'sampling'))
  )
) |>
  gt() |>
  fmt_number()
```


### Observations with Extreme Weights

#### By Entropy

```{r extreme-entropy, dependson="create-survey-objects"}
entropy_extreme_before <- before_fem$variables |>
  select(CASEID, WGT2011_2015) |>
  filter(
    WGT2011_2015^2 > 10 * mean(WGT2011_2015^2)
  )

entropy_extreme_after <-  after_fem$variables |>
  select(CASEID, FULL_SAMPLE_WGT) |>
  filter(
    FULL_SAMPLE_WGT^2 > 10 * mean(FULL_SAMPLE_WGT^2)
  )

data.frame(
  Label = c(
    'Total Observations',
    'Extreme Weights Before',
    'Extreme Weights After',
    'Difference'
  ),
  Count = c(
    nrow(after_fem),
    nrow(entropy_extreme_before),
    nrow(entropy_extreme_after),
    nrow(entropy_extreme_after) - nrow(entropy_extreme_before)
  )
) |>
  gt() |>
  fmt_number(decimal = 0)

entropy_extreme_after |>
  anti_join(
    entropy_extreme_before,
    by = join_by(CASEID)
  ) |>
  left_join(
    before_fem$variables |>
      select(
        CASEID,
        WGT2011_2015,
        abortion_2006_2010_age,
        abortion_2006plus_age,
        poststrat_age_race,
        birth_2010_marital_status,
        birth_2009_marital_status,
        birth_2008_marital_status,
        birth_2007_marital_status,
        birth_2006_marital_status,
        birth_2010_age,
        birth_2009_age,
        birth_2008_age,
        birth_2007_age,
        birth_2006_age
      ),
    by = join_by(CASEID)
  ) |> 
  gt() |>
  fmt_number(contains('WGT'), decimal = 0)
```


#### By Inter-Quartile Range (IQR)

```{r extreme-iqr, dependson="create-survey-objects"}
iqr_extreme_after <- after_fem$variables |>
  select(CASEID, FULL_SAMPLE_WGT) |>
  filter(
    FULL_SAMPLE_WGT > 5 * IQR(FULL_SAMPLE_WGT) + median(FULL_SAMPLE_WGT)
  )

iqr_extreme_before <- before_fem$variables |>
  select(CASEID, WGT2011_2015) |>
  filter(
    WGT2011_2015 > 5 * IQR(WGT2011_2015) + median(WGT2011_2015)
  )

data.frame(
  Label = c(
    'Total Observations',
    'Extreme Weights Before',
    'Extreme Weights After',
    'Difference'
  ),
  Count = c(
    nrow(after_fem),
    nrow(iqr_extreme_before),
    nrow(iqr_extreme_after),
    nrow(iqr_extreme_after) - nrow(iqr_extreme_before)
  )
) |>
  gt() |>
  fmt_number(decimal = 0)

iqr_extreme_after |>
  anti_join(
    iqr_extreme_before,
    by = join_by(CASEID)
  ) |>
  left_join(
    before_fem$variables |>
      select(
        CASEID,
        WGT2011_2015,
        abortion_2006_2010_age,
        abortion_2006plus_age,
        poststrat_age_race,
        birth_2010_marital_status,
        birth_2009_marital_status,
        birth_2008_marital_status,
        birth_2007_marital_status,
        birth_2006_marital_status,
        birth_2010_age,
        birth_2009_age,
        birth_2008_age,
        birth_2007_age,
        birth_2006_age
      ),
    by = join_by(CASEID)
  ) |>
  gt() |>
  fmt_number(contains('WGT'), decimal = 0)
```


### Post-Stratification Targets

```{r verify-post-stratification, dependson="create-survey-objects"}
after_fem |>
  group_by(poststrat_age_race) |>
  summarize(
    Est = survey_total(one)
  ) |>
  full_join(
    poststrat_targets[[1]],
    by = join_by(poststrat_age_race)
  ) |>
  mutate(
    Diff = Est - Freq
  ) |>
  gt() |>
  fmt_number(c(Est, Freq), decimal = 0) |>
  fmt_number(c(Est_se, Diff), decimal = 2)

after_fem |>
  group_by(birth_2006_age) |>
  summarize(
    Count = n(),
    Est = survey_total(one)
  ) |>
  full_join(
    poststrat_targets[[2]],
    by = join_by(birth_2006_age)
  ) |>
  mutate(
    Diff = Est - Freq
  ) |>
  gt() |>
  fmt_number(c(Est, Freq), decimal = 0) |>
  fmt_number(c(Est_se, Diff), decimal = 2)

after_fem |>
  group_by(birth_2007_age) |>
  summarize(
    Count = n(),
    Est = survey_total(one)
  ) |>
  full_join(
    poststrat_targets[[3]],
    by = join_by(birth_2007_age)
  ) |>
  mutate(
    Diff = Est - Freq
  ) |>
  gt() |>
  fmt_number(c(Est, Freq), decimal = 0) |>
  fmt_number(c(Est_se, Diff), decimal = 2)

after_fem |>
  group_by(birth_2008_age) |>
  summarize(
    Count = n(),
    Est = survey_total(one)
  ) |>
  full_join(
    poststrat_targets[[4]],
    by = join_by(birth_2008_age)
  ) |>
  mutate(
    Diff = Est - Freq
  ) |>
  gt() |>
  fmt_number(c(Est, Freq), decimal = 0) |>
  fmt_number(c(Est_se, Diff), decimal = 2)

after_fem |>
  group_by(birth_2009_age) |>
  summarize(
    Count = n(),
    Est = survey_total(one)
  ) |>
  full_join(
    poststrat_targets[[5]],
    by = join_by(birth_2009_age)
  ) |>
  mutate(
    Diff = Est - Freq
  ) |>
  gt() |>
  fmt_number(c(Est, Freq), decimal = 0) |>
  fmt_number(c(Est_se, Diff), decimal = 2)

after_fem |>
  group_by(birth_2010_age) |>
  summarize(
    Count = n(),
    Est = survey_total(one)
  ) |>
  full_join(
    poststrat_targets[[6]],
    by = join_by(birth_2010_age)
  ) |>
  mutate(
    Diff = Est - Freq
  ) |>
  gt() |>
  fmt_number(c(Est, Freq), decimal = 0) |>
  fmt_number(c(Est_se, Diff), decimal = 2)

after_fem |>
  group_by(birth_2006_marital_status) |>
  summarize(
    Count = n(),
    Est = survey_total(one)
  ) |>
  full_join(
    poststrat_targets[[7]],
    by = join_by(birth_2006_marital_status)
  ) |>
  mutate(
    Diff = Est - Freq
  ) |>
  gt() |>
  fmt_number(c(Est, Freq), decimal = 0) |>
  fmt_number(c(Est_se, Diff), decimal = 2)

after_fem |>
  group_by(birth_2007_marital_status) |>
  summarize(
    Count = n(),
    Est = survey_total(one)
  ) |>
  full_join(
    poststrat_targets[[8]],
    by = join_by(birth_2007_marital_status)
  ) |>
  mutate(
    Diff = Est - Freq
  ) |>
  gt() |>
  fmt_number(c(Est, Freq), decimal = 0) |>
  fmt_number(c(Est_se, Diff), decimal = 2)

after_fem |>
  group_by(birth_2008_marital_status) |>
  summarize(
    Count = n(),
    Est = survey_total(one)
  ) |>
  full_join(
    poststrat_targets[[9]],
    by = join_by(birth_2008_marital_status)
  ) |>
  mutate(
    Diff = Est - Freq
  ) |>
  gt() |>
  fmt_number(c(Est, Freq), decimal = 0) |>
  fmt_number(c(Est_se, Diff), decimal = 2)

after_fem |>
  group_by(birth_2009_marital_status) |>
  summarize(
    Count = n(),
    Est = survey_total(one)
  ) |>
  full_join(
    poststrat_targets[[10]],
    by = join_by(birth_2009_marital_status)
  ) |>
  mutate(
    Diff = Est - Freq
  ) |>
  gt() |>
  fmt_number(c(Est, Freq), decimal = 0) |>
  fmt_number(c(Est_se, Diff), decimal = 2)

after_fem |>
  group_by(birth_2010_marital_status) |>
  summarize(
    Count = n(),
    Est = survey_total(one)
  ) |>
  full_join(
    poststrat_targets[[11]],
    by = join_by(birth_2010_marital_status)
  ) |>
  mutate(
    Diff = Est - Freq
  ) |>
  gt() |>
  fmt_number(c(Est, Freq), decimal = 0) |>
  fmt_number(c(Est_se, Diff), decimal = 2)

after_fem |>
  group_by(abortion_2006_2010_age) |>
  summarize(
    Count = n(),
    Est = survey_total(one)
  ) |>
  full_join(
    poststrat_targets[[12]],
    by = join_by(abortion_2006_2010_age)
  ) |>
  mutate(
    Diff = Est - Freq
  ) |>
  gt() |>
  fmt_number(c(Est, Freq), decimal = 0) |>
  fmt_number(c(Est_se, Diff), decimal = 2)
```


### Abortion Adjustments

```{r find-average-abortion-adjustment, dependson="create-survey-objects"}
before_fem |>
  group_by(abortion_2006_2010_age) |>
  summarize(
    Count = n(),
    Before = survey_total(one)
  ) |>
  full_join(
    after_fem |>
      group_by(abortion_2006_2010_age) |>
      summarize(
        After = survey_total(one)
      ),
    by = join_by(abortion_2006_2010_age)
  ) |>
  mutate(
    Factor = After / Before
  ) |>
  gt() |>
  fmt_number(decimal = 0) |>
  fmt_number(Factor, decimal = 2)

before_fem |>
  group_by(abortion_2006plus_age) |>
  summarize(
    Count = n(),
    Before = survey_total(one)
  ) |>
  full_join(
    after_fem |>
      group_by(abortion_2006plus_age) |>
      summarize(
        After = survey_total(one)
      ),
    by = join_by(abortion_2006plus_age)
  ) |>
  mutate(
    Factor = After / Before
  ) |>
  gt() |>
  fmt_number(decimal = 0) |>
  fmt_number(Factor, decimal = 2)
```
