---
title: "Total Pregnancies and Pregnancies by Age of Mother in United States, 1974-2014"
author: "Joshua Born"
output:
  html_document:
    code_folding: hide
    toc: true
    toc_depth: 5
    css: wide.css
---


```{r setup, include=FALSE}
library(dplyr)
library(gt)
library(haven)
library(here)
library(lubridate)
library(srvyr)
library(tidyr)

knitr::opts_chunk$set(
  cache=TRUE,
  dpi=200,
  echo = TRUE,
  fig.align = 'center',
  fig.height=9.6,
  fig.retina=1.5,
  fig.width=9.6
)
```


```{r process-1982-1983}
raw_preg_1982_1983 <- read_sas(
  data_file = here('data/NSFG/d1982_1983fempreg.sas7bdat'),
  catalog_file = here('data/NSFG/d1982_1983fempreg.sas7bcat')
)

weights_1982_1983 <- readRDS(here('data/NSFG/adjusted_cycle_3_weights.Rds'))

preg_1982_1983 <- raw_preg_1982_1983 |> select(
    CASEID,
    AGEPREG,
    YRPREG
  ) |>
  mutate(
    Year = if_else(
      !is.na(YRPREG) & YRPREG != 99,
      1900 + YRPREG,
      NA
    ),
    YRPREG = as_factor(labelled(YRPREG, c(
      "CURRENT PREGNANCY" = NA,
      "BEFORE 1970" = 60,
      "YEAR NOT ASCERTAINED" = 99
    ))),
    Age = as.integer(AGEPREG / 100),
    AgeGroup = cut(
      Age,
      breaks = c(0, seq(15, 40, 5), Inf),
      right = FALSE,
      labels = c(
        "Under 15 years",
        "15-19 years",
        "20-24 years",
        "25-29 years",
        "30-34 years",
        "35-39 years",
        "40 years and over"
      )
    )
  ) |>
  left_join(
    weights_1982_1983,
    by = join_by(CASEID)
  )

svy_preg_1982_1983 <- as_survey_rep(
  preg_1982_1983,
  weights = FULL_SAMPLE_WGT,
  repweights = starts_with('REP_WGT_'),
  type = 'BRR'
)

analysis_years_1982_1983 <- 1974:1979

total_pregnancies_1982_1983 <- svy_preg_1982_1983 |>
  group_by(Year) |>
  summarize(
    total_pregnancies = survey_total(vartype = 'ci')
  ) |>
  filter(Year %in% analysis_years_1982_1983)

pregnancies_by_age_1982_1983 <- svy_preg_1982_1983 |>
  group_by(Year, AgeGroup) |>
  summarize(
    total_pregnancies = survey_total(vartype = 'ci')
  ) |>
  filter(Year %in% analysis_years_1982_1983)
```


```{r century-month-helper}
cm_to_date <- function(x) {
  x_int <- as.integer(x)
  if_else(
    is.na(x_int) | x_int > 9000 | x_int == 0,
    NA,
    ym(paste0(
      floor((x_int - 1) / 12) + 1900,
      factor(
        x_int %% 12,
        levels = 0:11,
        labels = c('Dec', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov')
      )
    ))
  )
}
```


```{r process-1985-1987, warning=FALSE, dependson="century-month-helper"}
raw_preg_1985_1987 <- read_sas(
  data_file = here('data/NSFG/d1985_1987fempreg.sas7bdat'),
  catalog_file = here('data/NSFG/d1985_1987fempreg.sas7bcat')
)

weights_1985_1987 <- readRDS(here('data/NSFG/adjusted_cycle_4_weights.Rds')) |>
  rename(SEQNUM = caseid)

preg_1985_1987 <- raw_preg_1985_1987 |> select(
    AGEPREG,
    B14MO,
    SEQNUM
  ) |>
  mutate(
    Year = year(cm_to_date(B14MO)),
    Age = as.integer(AGEPREG / 100),
    AgeGroup = cut(
      Age,
      breaks = c(0, seq(15, 40, 5), Inf),
      right = FALSE,
      labels = c(
        "Under 15 years",
        "15-19 years",
        "20-24 years",
        "25-29 years",
        "30-34 years",
        "35-39 years",
        "40 years and over"
      )
    )
  ) |>
  left_join(
    weights_1985_1987,
    by = join_by(SEQNUM)
  )

svy_preg_1985_1987 <- as_survey_rep(
  preg_1985_1987,
  weights = FULL_SAMPLE_WGT,
  repweights = starts_with('REP_WGT_'),
  type = 'BRR'
)

analysis_years_1985_1987 <- 1980:1985

total_pregnancies_1985_1987 <- svy_preg_1985_1987 |>
  group_by(Year) |>
  summarize(
    total_pregnancies = survey_total(vartype = 'ci')
  ) |>
  filter(Year %in% analysis_years_1985_1987)

pregnancies_by_age_1985_1987 <- svy_preg_1985_1987 |>
  group_by(Year, AgeGroup) |>
  summarize(
    total_pregnancies = survey_total(vartype = 'ci')
  ) |>
  filter(Year %in% analysis_years_1985_1987)
```


```{r process-1995-1995, warning=FALSE, dependson="century-month-helper"}
raw_preg_1995_1995 <- read_sas(
  data_file = here('data/NSFG/d1995_1995fempreg.sas7bdat'),
  catalog_file = here('data/NSFG/d1995_1995fempreg.sas7bcat')
)

weights_1995_1995 <- readRDS(here('data/NSFG/adjusted_cycle_5_weights.Rds'))

preg_1995_1995 <- raw_preg_1995_1995 |> select(
    CASEID,
    AGEPREG,
    DATEND
  ) |>
  mutate(
    Year = year(cm_to_date(DATEND)),
    Age = as.integer(AGEPREG / 100),
    AgeGroup = cut(
      Age,
      breaks = c(0, seq(15, 40, 5), Inf),
      right = FALSE,
      labels = c(
        "Under 15 years",
        "15-19 years",
        "20-24 years",
        "25-29 years",
        "30-34 years",
        "35-39 years",
        "40 years and over"
      )
    )
  ) |>
  left_join(
    weights_1995_1995,
    by = join_by(CASEID)
  )

jkcoefs_1995_1995 <- readRDS(here('data/NSFG/adjusted_cycle_5_rscales.Rds'))

svy_preg_1995_1995 <- as_survey_rep(
  preg_1995_1995,
  weights = FULL_SAMPLE_WGT,
  repweights = starts_with('REP_WGT_'),
  type = 'JKn',
  rscales = jkcoefs_1995_1995
)

analysis_years_1995_1995 <- 1986:1994

total_pregnancies_1995_1995 <- svy_preg_1995_1995 |>
  group_by(Year) |>
  summarize(
    total_pregnancies = survey_total(vartype = 'ci')
  ) |>
  filter(Year %in% analysis_years_1995_1995)

pregnancies_by_age_1995_1995 <- svy_preg_1995_1995 |>
  group_by(Year, AgeGroup) |>
  summarize(
    total_pregnancies = survey_total(vartype = 'ci')
  ) |>
  filter(Year %in% analysis_years_1995_1995)
```


```{r process-2002-2003, warning=FALSE, dependson="century-month-helper"}
raw_preg_2002_2003 <- read_sas(
  data_file = here('data/NSFG/d2002_2003fempreg.sas7bdat'),
  catalog_file = here('data/NSFG/d2002_2003fempreg.sas7bcat')
)

weights_2002_2003 <- readRDS(here('data/NSFG/adjusted_cycle_6_weights.Rds'))

preg_2002_2003 <- raw_preg_2002_2003 |> select(
    CASEID,
    AGEPREG,
    DATEND
  ) |>
  mutate(
    Year = year(cm_to_date(DATEND)),
    Age = as.integer(AGEPREG / 100),
    AgeGroup = cut(
      Age,
      breaks = c(0, seq(15, 40, 5), Inf),
      right = FALSE,
      labels = c(
        "Under 15 years",
        "15-19 years",
        "20-24 years",
        "25-29 years",
        "30-34 years",
        "35-39 years",
        "40 years and over"
      )
    )
  ) |>
  left_join(
    weights_2002_2003,
    by = join_by(CASEID)
  )

svy_preg_2002_2003 <- as_survey_rep(
  preg_2002_2003,
  weights = FULL_SAMPLE_WGT,
  repweights = starts_with('REP_WGT_'),
  type = 'BRR'
)

analysis_years_2002_2003 <- 1995:2001

total_pregnancies_2002_2003 <- svy_preg_2002_2003 |>
  group_by(Year) |>
  summarize(
    total_pregnancies = survey_total(vartype = 'ci')
  ) |>
  filter(Year %in% analysis_years_2002_2003)

pregnancies_by_age_2002_2003 <- svy_preg_2002_2003 |>
  group_by(Year, AgeGroup) |>
  summarize(
    total_pregnancies = survey_total(vartype = 'ci')
  ) |>
  filter(Year %in% analysis_years_2002_2003)
```


## Average Pregnancies per Year

```{r average-pregnancies, dependson=c("process-1982-1983", "process-1985-1987", "process-1995-1995", "process-2002-2003")}
process_average_pregnancies <- function(estimates, analysis_years) {
  estimates |>
    filter(Year %in% analysis_years) |>
    select(-Year) |>
    summarize(across(everything(), sum)) |>
    mutate(
      across(everything(), \(x) x / length(analysis_years)),
      Years = paste0(analysis_years[1], '-', tail(analysis_years, 1)),
      .before = everything()
    )
}

bind_rows(
  process_average_pregnancies(
    total_pregnancies_1982_1983,
    analysis_years_1982_1983
  ),
  process_average_pregnancies(
    total_pregnancies_1985_1987,
    analysis_years_1985_1987
  ),
  process_average_pregnancies(
    total_pregnancies_1995_1995,
    1986:1990
  ),
  process_average_pregnancies(
    total_pregnancies_1995_1995,
    1991:1994
  ),
  process_average_pregnancies(
    total_pregnancies_2002_2003,
    analysis_years_2002_2003
  )
) |>
  gt() |>
  fmt_integer()
```


## Pregnancies in Each Year

```{r pregnancies-each-year, dependson=c("process-1982-1983", "process-1985-1987", "process-1995-1995", "process-2002-2003")}
bind_rows(
  total_pregnancies_1982_1983,
  total_pregnancies_1985_1987,
  total_pregnancies_1995_1995,
  total_pregnancies_2002_2003
) |>
  gt() |>
  fmt_integer(-Year)
```


## Average Pregnancies per Year by Age Group

```{r average-pregnancies-by-age, dependson=c("process-1982-1983", "process-1985-1987", "process-1995-1995", "process-2002-2003")}
process_average_pregnancies_by_age <- function(estimates, analysis_years) {
  estimates |>
    ungroup() |>
    filter(Year %in% analysis_years) |>
    select(-Year) |>
    group_by(AgeGroup) |>
    summarize(across(everything(), sum)) |>
    mutate(
      across(-AgeGroup, \(x) x / length(analysis_years)),
      Years = paste0(analysis_years[1], '-', tail(analysis_years, 1)),
      .before = everything()
    )
}

bind_rows(
  process_average_pregnancies_by_age(
    pregnancies_by_age_1982_1983,
    analysis_years_1982_1983
  ),
  process_average_pregnancies_by_age(
    pregnancies_by_age_1985_1987,
    analysis_years_1985_1987
  ),
  process_average_pregnancies_by_age(
    pregnancies_by_age_1995_1995,
    1986:1990
  ),
  process_average_pregnancies_by_age(
    pregnancies_by_age_1995_1995,
    1991:1994
  ),
  process_average_pregnancies_by_age(
    pregnancies_by_age_2002_2003,
    analysis_years_2002_2003
  )
) |>
  group_by(Years) |>
  gt() |>
  fmt_integer()
```


## Pregnancies by Age Group in Each Year

```{r pregnancies-each-year-by-age, dependson=c("process-1982-1983", "process-1985-1987", "process-1995-1995", "process-2002-2003")}
bind_rows(
  pregnancies_by_age_1982_1983,
  pregnancies_by_age_1985_1987,
  pregnancies_by_age_1995_1995,
  pregnancies_by_age_2002_2003
) |>
  gt() |>
  fmt_integer(-Year)
```


## Pregnancies by Age Group in Each Year -- Wide Table

```{r wide-pregnancies-each-year-by-age, dependson=c("process-1982-1983", "process-1985-1987", "process-1995-1995", "process-2002-2003")}
process_pregnancies_by_age_wide <- function(estimates) {
  estimates |>
    ungroup() |>
    pivot_wider(
      id_cols = AgeGroup,
      names_from = Year,
      names_prefix = 'pregnancies_',
      values_from = total_pregnancies
    )
}

full_join(
  process_pregnancies_by_age_wide(pregnancies_by_age_1982_1983),
  process_pregnancies_by_age_wide(pregnancies_by_age_1985_1987),
  by = join_by(AgeGroup)
) |>
full_join(
  process_pregnancies_by_age_wide(pregnancies_by_age_1995_1995),
  by = join_by(AgeGroup)
) |>
full_join(
  process_pregnancies_by_age_wide(pregnancies_by_age_2002_2003),
  by = join_by(AgeGroup)
) |>
  gt() |>
  fmt_integer()
```
