---
title: "Preparation of NVSS Natality Data"
author: "Joshua Born"
output:
  html_document:
    code_folding: hide
    toc: true
    toc_depth: 5
    css: wide.css
---


```{r setup, include=FALSE}
library(dplyr)
library(gt)
library(here)
library(readr)

knitr::opts_chunk$set(
  cache = FALSE,
  dpi=200,
  echo = TRUE,
  fig.align = 'center',
  fig.height=9.6,
  fig.retina=1.5,
  fig.width=9.6
)
```


```{r helper-functions}
explore_NVSS_data <- function(year) {
  read_csv(
    here(paste0('data/NVSS/natality', year, 'us.csv')),
    n_max = 100
  )
}

process_NVSS_data_94 <- function(year) {
  read_csv(
    here(paste0('data/NVSS/natality', year, 'us.csv')),
    col_select = c('datayear', 'stsubocc', 'mage8', 'mrace', 'ormoth')
  ) |>
  mutate(
    demographic_category = factor(
      case_when(
        ormoth %in% 1:5 ~ 'Hispanic',
        mrace == 2 ~ 'Non-Hispanic Black',
        .default = 'Non-Hispanic Non-Black'
      )
    ),
    mage8 = factor(
      mage8,
      levels = 1:8,
      labels = c(
        "Under 15 years",
        "15-19 years",
        "20-24 years",
        "25-29 years",
        "30-34 years",
        "35-39 years",
        "40-44 years",
        "45-49 years"
      )
    ),
    ormoth = factor(
      ormoth,
      levels = c(0:5, 9),
      labels = c(
        "Non-Hispanic",
        "Mexican",
        "Puerto Rican",
        "Cuban",
        "Central or South American",
        "Other or unknown Hispanic",
        "Origin unknown or not stated"
      )
    ),
    mrace = factor(
      mrace,
      levels = c(1:7, seq(18, 78, by = 10)),
      labels = c(
        "White",
        "Black",
        "American Indian",
        "Chinese",
        "Japanese",
        "Hawaiian",
        "Filipino",
        "Asian Indian",
        "Korean",
        "Samoan",
        "Vietnamese",
        "Guamanian",
        "Other Asian or Pacific Islander",
        "Combined other Asian or Pacific Islander"
      )
    )
  )
}

process_NVSS_data_91 <- function(year) {
  read_csv(
    here(paste0('data/NVSS/natality', year, 'us.csv')),
    col_select = c('datayear', 'stsubocc', 'mage8', 'mrace', 'ormoth')
  ) |>
  mutate(
    mage8 = factor(
      mage8,
      levels = 1:8,
      labels = c(
        "Under 15 years",
        "15-19 years",
        "20-24 years",
        "25-29 years",
        "30-34 years",
        "35-39 years",
        "40-44 years",
        "45-49 years"
      )
    ),
    mrace = factor(
      mrace,
      levels = 1:9,
      labels = c(
        "White",
        "Black",
        "American Indian",
        "Chinese",
        "Japanese",
        "Hawaiian",
        "Filipino",
        "Other Asian or Pacific Islander",
        "All other races"
      )
    )
  )
}

process_NVSS_data_88 <- function(year) {
  read_csv(
    here(paste0('data/NVSS/natality', year, 'us.csv')),
    col_select = c('datayear', 'stsubocc', 'mage8', 'mrace')
  ) |>
  mutate(
    mage8 = factor(
      mage8,
      levels = 1:8,
      labels = c(
        "Under 15 years",
        "15-19 years",
        "20-24 years",
        "25-29 years",
        "30-34 years",
        "35-39 years",
        "40-44 years",
        "45-49 years"
      )
    ),
    mrace = factor(
      mrace,
      levels = 0:9,
      labels = c(
        "Other Asian or Pacific Islander",
        "White",
        "Black",
        "American Indian",
        "Chinese",
        "Japanese",
        "Hawaiian",
        "Other nonwhite",
        "Filipino",
        "Not stated"
      )
    )
  )
}

count_levels <- function(tbl, year, variable_name) {
  tbl |>
    group_by(get(variable_name)) |>
    count() |>
    ungroup() |>
    mutate(Year = year, Variable = variable_name, .before = everything()) |>
    rename(Level = `get(variable_name)`)
}

summarize_natality_year <- function(tbl, year) {
  bind_rows(
    count_levels('datayear'),
    count_levels('stsubocc'),
    count_levels('mage8'),
    count_levels('mrace3'),
    count_levels('ormoth'),
    count_levels('demographic_category')
  )
}

crosstabulate_natality_year <- function(tbl, year) {
  tbl |>
    group_by(demographic_category, mage8) |>
    count() |>
    ungroup()
}

process_natality_year <- function(year) {
  tbl <- load_NVSS_data(year)
  list(
    summary = summarize_natality_year(tbl, year),
    crosstab = crosstabulate_natality_year(tbl, year)
  )
}
```

```{r}
years <- 1994:1974

NVSS_1994 <- process_NVSS_data_94(1994)
NVSS_1993 <- process_NVSS_data_94(1993)
NVSS_1992 <- process_NVSS_data_94(1992)

NVSS_1991 <- process_NVSS_data_91(1991)
NVSS_1990 <- process_NVSS_data_91(1990)
NVSS_1989 <- process_NVSS_data_91(1989)

NVSS_1988 <- process_NVSS_data_88(1988)
```


```{r}
#saveRDS(NVSS_1992_cross, here('data/NVSS/natality1992us_crosstabs.Rds'))
```

