---
title: "Contraceptive Use and Nonuse in the United States: Based on the 2017-2019 National Survey of Family Growth"
author: "Joshua Born"
output:
  html_document:
    code_folding: hide
    toc: true
    toc_depth: 5
---

```{r setup, include=FALSE}
library(here)

i_am('reports/contraceptive_use_and_nonuse_in_the_united_states_2017-2019.Rmd')
```


# Outline

* Those currently (at last intercourse with opposite sex in past 3 months) using contraception versus not using contraception
* During last intercourse
    * By number of methods used
    * By method(s) used
    * By method, among those using only one method
    * By method, proportion also using another method
    * By other method(s) used, among those using methods commonly used with other methods
* Past 12 months
    * Number of methods
    * By method(s) used
    * By method, among those using only one method
* Consistency
    * Did not use at last intercourse, but used at least one method in past 12 months
    * Did not use at last intercourse, but ever used contraception (females)
    * Frequency of any method use in past 12 months
    * Frequency of condom use in past 12 months
    * Frequency of condom use in past 12 months, among exclusive condom users
    * Frequency of condom use in past 4 weeks (females)
    * Number of missed pills in past 4 weeks (females)
* Ever (females)
    * By method(s)
    * By method(s) among those who have had intercourse with opposite sex
    * Ever discontinued due to dissatisfaction
    * Reason for dissatisfaction with pill
    * Reason for dissatisfaction with condoms
    * Reason for dissatisfaction with IUDs
* Not currently using contraception, overview by category
* Not sexually active currently
    * Never
        * Reason for never
    * Same-sex attractedness
* Physically infertile category (females)
    * By reason in domain
    * By reason generally
    * Partner infertile generally
* Why not using contraception (females)
    * By reason(s)
    * By main or exclusive reason
    * Reasons(s) for those who believe themselves infertile to think themselves infertile
* Overall contraception rate
* Use for reasons other than contraception
    * Condom, pill, IUD, and tubal ligation among females
    * Condom among males



# Things to Do

* Collect estimates into coherent report
* Review situations in which universes do not match specifications in codebooks and follow up with NSFG administrators
* Compare own report with published reports
* Look into what it takes to publish in an academic journal
* Replicate analysis in SAS
    * Attempt single-factor categorical data analysis, e.g., whether totals of otherwise not using contraception and currently trying to conceive are different
