---
author: "Joshua Born"
bibliography: "../../bibliographies/responses-to-comments-about-abortion.bib"
csl: "../../bibliographies/chicago-author-date.csl"
date: 2022-05-10
#tags: ["first-person"]
title: "Responses to Comments about Abortion"
output:
  blogdown::html_page:
    number_sections: false
    toc: true
    toc_depth: 5
include-before: |
  <!--more-->
  ## Table of Contents
---

```{r setup, include=FALSE}
library(here)

i_am('content/noindex/responses-to-comments-about-abortion.Rmd')

knitr::opts_chunk$set(
  echo = FALSE
)
```

## Introduction

Writing about the topic of induced abortion of pregnancy -- henceforth just "abortion" -- I encounter a lot of comments that are, to put it politely, uninformative. Indeed, if you are a person inclined to nuanced critical thinking, you might encounter a lot of these comments even just going about your everyday life and notice that the standards of discourse around abortion are quite poor. Rather than respond to the same sorts of comments over and over again, this page is intended to be a summary of all of my responses to all of these comments.

## Reasons for Poor Standards of Discourse

Before getting into the specific responses, I would like to provide a rough outline of why I believe standards of discourse about abortion are so poor:

1. Many if not most people are very poor at articulating their own feelings and therefore lack self-awareness about their own value judgments. A pure moral disagreement _per se_ occurs when two or more people have the same understanding of the facts of the matter, but have different value judgments. Therefore, those with poor self-awareness about their own value judgments are poor at understanding and discussing moral conflicts. This is not unique to abortion, but is true for all kinds of moral disagreement. I have written about this at length in my article on [moral skepticism](/moral-skepticism.html).
1. Moral psychology is an area rife for motivated reasoning. As such, there is much _post hoc_ rationalization invented to ornament moral sentiments. However, since these _post hoc_ rationalizations are invented after the fact, they are not the real reasons why any given person acquired a moral sentiment. They therefore are quite literally self-delusional stories that people tell themselves, with no informational content. Again, this is not unique to abortion, but is true for thinking about morality with regard to many different topics. The phenomenon of _post hoc_ rationalization in moral psychology has been popularly discussed by Jonathan Haidt and colleagues. [@haidt_emotional_2001; @haidt_righteous_2012]
1. Because there are several factions who have established orthodoxies on abortion, and there are many people whose viewpoints are informed by allegiance to a faction, oftentimes discourse about abortion is used as an opportunity to proclaim slogans and rhetoric designed to express affiliation with a political or religious group, instead of an opportunity for genuine discourse. This is true for any factional issue, not just abortion. I have previously written about how [slogans and political rhetoric are bad for critical thinking](/political-rhetoric-as-shibboleths.html).

While many issues similarly have aspects of moral disagreement, and many issues similarly have factional aspects, in the United States, abortion might very well be the issue with the greatest intersection of these phenomena and hence the greatest poverty in standards of discourse.

### Moral Compunction about Act Itself or About Other Consequences

...


## Responses to Comments


## "Choice" Rhetoric

If you have moral compunction about killing fetuses as a method of fertility control, then you are liable to encounter comments appealing to a rhetoric that revolves around "choice." You might be called "anti-choice" or be accused of denying people their "reproductive autonomy" or the like.

First of all, I do not want anyone who does not want to have children to be forced to have children. I just want people to exercise control of their own reproductive systems with non-violent means. Because I feel moral compunction at the killing of human fetuses of a similar level as the compunction I feel at killing human infants, I have the value judgement that killing fetuses is violence.

Secondly, my sentiments are not new. They were expressed at the [beginning of the birth control movement in the United States](/margaret-sanger-on-abortion-in-her-own-words.html). The very "choice" rhetoric used against me was invented not as part of the movement to legalize abortion, but decades earlier as part of the the early birth control movement. Indeed, Margaret Sanger both wrote that

> No woman can call herself free who does not own and control her body. No woman can call herself free until she can choose consciously whether she will or will not be a mother. [@sanger_woman_1920, 94]

and described abortion as a method of fertility control, a practice she was trying to eliminate, as "the murder of unborn children." [@sanger_better_1923]

Thirdly, an analogy might be in order, especially in response to those who have comments such as "who do you think should choose whether or not have an abortion, the government or women?" Supposedly, in classical Greece the Spartans had a counsel of elders that would examine a neonate and decide whether or not the newborn would be kept or thrown off a cliff, but in more "progressive" Athens the patriarch of a household would decide whether or not children born in the household would be kept or killed. In this way, Athenian law protected their citizens' "reproductive rights."

I'm not sure if this story is true, but let's assume it for the sake of a thought experiment. My reaction to the laws of Sparta versus Athens in this thought experiment is _I don't care._ If I were transported with my values intact back to ancient Greece, I would literally just want people to stop kill infants. The details of habits and customs and laws around the practice are largely irrelevant to me.

Infanticide as a method of fertility control has been so pushed to the margins of post-industrialized society today that no one is talking about who gets to choose to kill the infants. No one is "pro-choice" on infanticide today. This is the goal I am working toward with my studies, but for abortion in addition to infanticide.

My aim is that social progress -- whether that is behavioral, technological, economic, etc -- makes killing fetuses as a method of fertility control so outside the norms of society that no one even thinks about it as a choice, because the prospect of doing it is so horrendous to the mainstream of society.

This may seem far-fetched, but this is precisely what has happened to infanticide as a method of fertility control; it has gone from a mainstream practice to very far outside the mainstream. Granted it took many centuries for this moral transition to occur for infanticide. Sadly, I suspect we are in the earliest of stages of a similar moral transition on abortion, so I will never live to see my moral sentiments become mainstream.

Just because I will never live to see my moral sentiments become mainstream does not make me abandon them. It does, however, make me realize that the target audience for my research and writings is posterity as much as it is my contemporaries, if not more so.


### Fallacy of Externalization

Your value judgments -- i.e., your assessments of goodness or badness, rightness or wrongness -- are features of your own mind that are not true-or-false descriptions the world outside of your mind. In my article on moral skepticism, I describe a "[fallacy of externalization](/moral-skepticism.html#the-fallacy-of-externalization)" as a phenomenon in which people discuss their own value judgments very indirectly by pretending to describe things external to their own minds. There are many, many instances of the fallacy of externalization in comments about abortion.


#### Moral Fictions Such as "Rights" or "Social Contracts"

Rights are abstractions that do not describe anything in the physical world external to someone's mind. They are fictions that might very indirectly describe someone's value judgments, such as when hearing someone say "gun rights" is a hint they might like guns, but that is it. There is no knowledge about rights, because there are no truths about rights. There is no (direct) informational content in statements about rights.

There are some vocations, such as practicing law, in which you might talk about rights a lot. These are the same vocations that discuss a corporation, which is literally a fictitious person. Rights are no less fictions just because laws are written about them.

Some people find rights to be useful fictions. I do not. I also have the same attitude toward social contracts or any other moral fiction invented by lawyers, philosophers, etc.

Fictions do not affect my understanding of the world, which is something informed by empirical inquiry. Furthermore, fictions also do not affect my value judgments because fictions do not determine how I feel about reality.

Therefore, discussing rights or social contracts or any other abstraction that does not describe the world external to someone's mind is something that I think is a waste of time. Indeed, thinking about these things is worse than just wasting time to me, because doing so can give you the false impression of having knowledge when you do not have knowledge.


#### Appeals to "Science"

Some people claim their lack of moral compunction at killing fetuses as a method of fertility control is due to their understanding of science. Some people react to others' compunction at killing fetuses as a method of fertility control by claiming, "You don't understand science!"

**If you think your morality derives from science, you understand neither science nor morality.**

Science, popularly understood, comprises methods for understanding factual, true-or-false questions by investigating empirical evidence. There are many different ways this can be specifically formulated. They typically involve formulating and testing hypotheses or modeling observable phenomenon with some theory, typically mathematical.

While science can tell you about the facts of the matter, whether you judge something to be good or bad is up to you; your value judgments are not science. Furthermore, your moral sentiments _always_ and _necessarily_ involve something that is not derived from science, that is, these value judgments.

In short, science can tell you what is the case, but not how to feel about it. This is a restatement of what is called the "is-ought problem" or "naturalistic fallacy" in moral philosophy: just because things _are_ a given way does not imply that they _should_ be that way.

I value learning through scientific inquiry, both of my own and others'. I have gone to great lengths to change careers so that I can be part of the process of science. Any moral disagreement on abortion we might have is not because you "understand science" and I do not.

### "Progressive" versus "Conservative"

There is a genre of comments that take as their premise the binary factionalism between left-wing and right-wing that is a feature of partisan politics in the United States. The political right is interpreted as being opposed to abortion as a method of fertility control and is called "conservative," the political left is interpreted as being in favor of abortion as a method of fertility control and is called "progressive."

First of all, calling your own faction "progressive" is one of the most facile pieces of self-righteous labeling one can imagine.

Nonetheless, for those whose thinking is heavily influenced by this false dichotomy, it is a natural leap to think that moral compunction about abortion is a "conservative" position. Indeed, I have seen glib comments to the effect of "abort the backwardness of your conservative views on abortion!"

The issue I take with these comments is threefold:

1. If you strip away the stupidity of partisanship, you fill find a diversity of opinions about abortion -- or indeed anything else -- among populations large enough to consist of millions people, even among populations categorized as left-wing or right-wing. Therefore, framing disagreement about abortion in a partisan way is simpleminded.
1. Whether or not one viewpoint is relatively "newer" than another is not necessarily tantamount to that viewpoint being _better_ than another.
1. That being said, **defense of abortion as a method of fertility control is the conservative -- in the sense of maintaining a long-standing _status quo_ -- viewpoint on the matter.**

Elaborating on point #3, the only way you can construe advocacy of abortion as fertility control as a "newer" viewpoint is to ignore most of human existence and to think that the history of politics in the United States from the 1950s to present is the history of all time, everywhere. This is an extremely short-sighted.

People have been killing fetuses -- and indeed infants -- as a method of fertility control for most of human existence back to prehistory. This has been true in large societies, in small societies, and places all over the Earth. Indeed, for most of human history, this has been a legal and mainstream practice. The Roman Catholic Church, which has been prominent in moral condemnation of abortion, did not start doing so until the 17th or 18th centuries. European countries did not even start attempting to make _infanticide_ illegal until the late medieval, early modern periods, let alone abortion. Countries like Great Britain were still grappling with anti-infanticide laws into the 20th century. [@kilday_history_2013]

It is up to you whether you have the value judgement that killing fetuses as a method of fertility control is fine, but you do not get to rewrite history. Moral compunction about killing fetuses -- or even infants, for that matter -- as a method of fertility control has been a minority position throughout human existence and has only come to any prominence in the past few centuries. Those are the facts of the matter. If any position is conservative, it is that killing fetuses as a method of fertility control is acceptable.

This is something that [Margaret Sanger spoke about at length](/margaret-sanger-on-abortion-in-her-own-words.html) discussed at length when she founded the birth control movement in the United States.


## Citations

::: {#refs}
:::


## Footnotes
