baseURL = "https://borninquisitive.com/"
languageCode = "en-us"
title = "Born Inquisitive"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", ".md$"]
uglyURLS = true
disableKinds = ["taxonomyTerm"]


[permalinks]
  post = "/:slug/"

[Taxonomies]
  tags = "tags"

[params]
  subtitle = "A blog of independent thinking and evidence-based inquiry"
  description = "A blog containing independent thinking, criticism of fallacies, and evidence-based inquiry into reproductive responsibility."
  author = "Joshua Born"

[mediaTypes]
[mediaTypes."application/atom+xml"]
  suffixes = ["xml"]

[outputFormats.Atom]
  mediaType = "application/atom+xml"
  baseName = "feed"
  isPlainText = false

[outputs]
  home = ["HTML", "Atom"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
